CREATE OR REPLACE PROCEDURE DBA.SP_INSERT_PEDIDO_COMPRA_PROD (
    AI_IDSUBPRODUTO             INTEGER,
    AI_IDCLIFOR                 INTEGER,
    AI_IDPEDIDO                 INTEGER,
    AI_IDEMPRESA                INTEGER,
    ADE_PERDESCONTO1            DECIMAL(10, 6),
    ADE_PERDESCONTO2            DECIMAL(10, 6),
    ADE_PERDESCONTO3            DECIMAL(10, 6),
    ADE_PERDESCONTO4            DECIMAL(10, 6),
    ADE_PERIPI                  DECIMAL(10, 6),
    ADE_PERMARGEMLUCRO          DECIMAL(10, 6),
    ADE_QTDSOLICITADA           DECIMAL(12, 3),
    ADE_VALUNITARIO             DECIMAL(15, 6),
    ADE_PERICM                  DECIMAL(10, 6),
    ADE_VALTOTBRUTO             DECIMAL(15, 6),
    ADE_PERBONIFICACAO          DECIMAL(10, 6),
    ADE_VALTOTLIQUIDO           DECIMAL(15, 6),
    ADE_VALICMSUBST             DECIMAL(15, 6),
    ADE_PERFRETE                DECIMAL(10, 6),
    ADE_PERADICIONAL            DECIMAL(10, 6),
    ADE_PERIPIFRETE             DECIMAL(10, 6),
    ADE_VALDESCONTOICMS         DECIMAL(15, 6),
    ADE_PERIPIADICIONAL         DECIMAL(10, 6),
    ADE_VALIPI                  DECIMAL(15, 6),
    AC_FLAGSITUACAOATUAL        CHAR(1),
    ADE_PERACESSORIOS           DECIMAL(10, 6),
    ADE_PERIPIACESSORIOS        DECIMAL(10, 6),
    ADE_VALDESCONTOPISCOFINS    DECIMAL(15, 6),
    ADE_PERINFLACAO             DECIMAL(15, 6),
    ADE_PESOBRUTO               DECIMAL(12, 3),
    ADE_QTDTRANSFERIDA          DECIMAL(12, 3),
    AC_FLAGSALDOZERADO          CHAR(1),
    AD_DTENTREGA                DATE,
    AS_OBSPRODUTO               VARCHAR(400),
    ADE_QTDSUGERIDATRANSF       DECIMAL(12, 3),
    ADE_QTDSUGESTAOCOMPRA       DECIMAL(15, 3),
    AC_FLAGCALCULAST            CHAR(1),
    AC_OPERACAO                 CHAR(1),
    AI_IDLOCALRESERVA           INTEGER
)
BEGIN
    DECLARE AC_TIPOSITTRIB CHAR(1);
    DECLARE AI_IDCENARIOFISCAL BIGINT;
    DECLARE LS_UTILIZACENARIO CHAR(1);
    DECLARE CEN_UFORIGEM CHAR(2);
    DECLARE CEN_UFDESTINO CHAR(2);
    DECLARE CEN_TPTRIBORIGEM CHAR(1);
    DECLARE CEN_TPTRIBDESTINO CHAR(1);
    DECLARE CEN_ATVORIGEM INTEGER;
    DECLARE CEN_ATVDESTINO INTEGER;
    DECLARE LI_IDPRODUTO INTEGER;
    DECLARE AI_IDSUGESTAO INTEGER;
    DECLARE AD_DTENTREGA DATE;
    DECLARE LI_IDLOCALRESERVA INTEGER DEFAULT NULL;
	DECLARE CEN_TIPOOPERACAO INTEGER;
	DECLARE LD_VALUNITLIQUIDO DECIMAL(15,6);
	DECLARE LI_IDCENARIOFORNECEDOR INTEGER;
	DECLARE LD_VALLISTAFORNECEDOR, LD_VALFINALFORNECEDOR, LD_VALICMSSTFORNECEDOR, LD_VALIPIFORNECEDOR DECIMAL(15,6);
    DECLARE CEN_ORIPROD             INTEGER;

    SET AI_IDSUGESTAO = NULL;
    SET AC_TIPOSITTRIB = NULL;
    SET AI_IDCENARIOFISCAL = NULL;
    SET LS_UTILIZACENARIO = (SELECT COALESCE(DBA.UF_UTILIZACENARIOFISCAL(),'F') AS UTILIZACENARIO FROM DBA.DUMMY);
    SET LI_IDCENARIOFORNECEDOR = COALESCE((SELECT IDCENARIOFISCAL FROM DBA.PRODUTO_FORNECEDOR WHERE IDCLIFOR = AI_IDCLIFOR AND IDSUBPRODUTO = AI_IDSUBPRODUTO),0);
    SET AI_IDCENARIOFISCAL = LI_IDCENARIOFORNECEDOR;
    
    SET (LD_VALLISTAFORNECEDOR, LD_VALICMSSTFORNECEDOR, LD_VALIPIFORNECEDOR, LD_VALFINALFORNECEDOR)  = (
    	SELECT
			VALLISTAFORNECEDOR,
			VALICMSST,
			VALIPI,
			CASE 
				WHEN VLRFINALFORNECEDOR <> 0 THEN 
					CAST(VLRFINALFORNECEDOR AS CHAR(20)) 
				ELSE
					TRIM(CAST(CAST(COALESCE(VALLISTAFORNECEDOR,0)+COALESCE(PRODUTO_FORNECEDOR.VALICMSST,0)+COALESCE(PRODUTO_FORNECEDOR.VALIPI,0) AS DECIMAL(15, 6)) AS CHAR(20))) 
			END AS VALOR
		FROM
			PRODUTO_FORNECEDOR
		WHERE
			IDCLIFOR = AI_IDCLIFOR AND
			IDSUBPRODUTO = AI_IDSUBPRODUTO
    	);
    
    SET ADE_VALICMSUBST = COALESCE(LD_VALICMSSTFORNECEDOR,0);
    SET ADE_VALIPI = COALESCE(LD_VALIPIFORNECEDOR,0);
    
    /*BLOCO PARA AJUSTAR OS VALORES DO NOSSO LADO, VALIDAR A QUESTAO FINANCEIRA SE PASSAR A VIR O PARCELAMENTO DO LADO DO GEFOX, DEVERIA VIR OS VALORES CORRETOS JA PARA NAO DAR DIVERGENCIA EM PARCELAS*/
    SET ADE_VALUNITARIO = COALESCE(LD_VALLISTAFORNECEDOR,0);
    SET ADE_VALTOTBRUTO = COALESCE(LD_VALLISTAFORNECEDOR,0)*ADE_QTDSOLICITADA;
    SET ADE_VALTOTLIQUIDO = COALESCE(COALESCE(LD_VALFINALFORNECEDOR,LD_VALLISTAFORNECEDOR),0)*ADE_QTDSOLICITADA;
	SET LD_VALUNITLIQUIDO = COALESCE(COALESCE(LD_VALFINALFORNECEDOR,LD_VALLISTAFORNECEDOR),0);
    /*FIM BLOCO VALORES*/

    SET LI_IDPRODUTO = (
        SELECT
            IDPRODUTO
        FROM
            DBA.PRODUTO_GRADE
        WHERE
            IDSUBPRODUTO = AI_IDSUBPRODUTO
    );

    SET AD_DTENTREGA = NULL;

    IF LS_UTILIZACENARIO = 'T' AND AI_IDCLIFOR IS NOT NULL AND LI_IDCENARIOFORNECEDOR = 0 THEN
	
		SET CEN_TIPOOPERACAO = (
			SELECT 
				IDTIPOOPERACAO 
			FROM 
				DBA.TIPO_OPERACAO_INTERNA TOI 
			WHERE 
				IDOPERACAO = (
					SELECT	
						IDOPERACAO
					FROM	
						DBA.PEDIDO_COMPRA PC 
					WHERE
						PC.IDPEDIDO = AI_IDPEDIDO AND
						PC.IDEMPRESA = AI_IDEMPRESA
					FETCH FIRST 1 ROWS ONLY
					) AND
				FLAGPADRAO = 'T'
			);
	
        SET (
            CEN_UFORIGEM,
            CEN_UFDESTINO,
            CEN_TPTRIBORIGEM,
            CEN_TPTRIBDESTINO,
            CEN_ATVORIGEM,
            CEN_ATVDESTINO
        ) = (
            SELECT
                CLI.UFCLIFOR AS UFORIGEM,
                EMP.UF AS UFDESTINO,
                CLI.TIPOREGIMETRIBFEDERAL AS TPTRIBORIGEM,
                EMP.TIPOREGIMETRIBFEDERAL AS TPTRIBDESTINO,
                TPATVCLI.IDTIPOATIVIDADE AS ATVORIGEM,
                TPATVEMP.IDTIPOATIVIDADE AS ATVDESTINO
            FROM
                DBA.EMPRESA EMP
            LEFT JOIN
                DBA.CLIENTE_FORNECEDOR CLI ON
                    CLI.IDCLIFOR = AI_IDCLIFOR
            LEFT JOIN
                DBA.ATIVIDADE_TIPO_ATIVIDADE TPATVCLI ON
                    TPATVCLI.FLAGPADRAO = 'T' AND
                    TPATVCLI.IDATIVIDADE = CLI.IDATIVIDADE
            LEFT JOIN
                DBA.ATIVIDADE_TIPO_ATIVIDADE TPATVEMP ON
                    TPATVEMP.FLAGPADRAO = 'T' AND
                    TPATVEMP.IDATIVIDADE = EMP.IDATIVIDADE
            WHERE
                EMP.IDEMPRESA = AI_IDEMPRESA
        );
        
        SET CEN_ORIPROD = (
            SELECT
                CFPC.IDORIGEMPRODUTO
            FROM
                DBA.CENARIO_FISCAL_PADRAO_PRODUTO_EMPRESA CFPPE
            JOIN
                DBA.CENARIO_FISCAL_PADRAO_COMPOSICAO CFPC ON
                    CFPC.IDCENARIOPADRAO = CFPPE.IDCENARIOPADRAO
            WHERE
                CFPPE.IDEMPRESA = AI_IDEMPRESA AND
                CFPPE.IDPRODUTO = LI_IDPRODUTO AND
                CFPPE.IDSUBPRODUTO = AI_IDSUBPRODUTO AND
                CFPC.OPERACAO = 'E'
            FETCH FIRST 1 ROW ONLY
        );

        IF CEN_ORIPROD IS NULL THEN
            SET CEN_ORIPROD = (
                SELECT
                    CFPC.IDORIGEMPRODUTO
                FROM
                    DBA.PRODUTO_GRADE PG
                JOIN
                    DBA.CENARIO_FISCAL_GRUPO CFG ON
                        CFG.IDGRUPO = PG.IDGRUPOCENARIOFISCAL
                JOIN
                    DBA.CENARIO_FISCAL_PADRAO_PRODUTO_EMPRESA CFPPE ON
                        CFPPE.IDPRODUTO = CFG.IDPRODUTOMESTRE AND
                        CFPPE.IDSUBPRODUTO = CFG.IDSUBPRODUTOMESTRE
                JOIN
                    DBA.CENARIO_FISCAL_PADRAO_COMPOSICAO CFPC ON
                        CFPC.IDCENARIOPADRAO = CFPPE.IDCENARIOPADRAO
                WHERE
                    PG.IDPRODUTO = LI_IDPRODUTO AND
                    PG.IDSUBPRODUTO = AI_IDSUBPRODUTO AND
                    PG.IDGRUPOCENARIOFISCAL IS NOT NULL AND
                    CFPPE.IDEMPRESA = AI_IDEMPRESA AND
                    CFPC.OPERACAO = 'E'
                FETCH FIRST 1 ROW ONLY
            );
        END IF;

        SET AI_IDCENARIOFISCAL = (
            SELECT
                CF.IDCENARIOFISCAL
            FROM
                DBA.CENARIO_FISCAL_DADOS_VW CF
            WHERE
                CF.IDTIPOOPERACAO = CEN_TIPOOPERACAO AND
                CF.IDORIGEMPRODUTO = CEN_ORIPROD AND
                CF.FLAGINATIVO = 'F' AND
                CF.IDPRODUTO = LI_IDPRODUTO AND
                CF.IDSUBPRODUTO = AI_IDSUBPRODUTO AND
                CF.UFORIGEM = CEN_UFORIGEM AND
                CF.UFDESTINO = CEN_UFDESTINO AND
                CF.TIPOREGIMETRIBFEDERALORIGEM = CEN_TPTRIBORIGEM AND
                CF.TIPOREGIMETRIBFEDERALDESTINO = CEN_TPTRIBDESTINO AND
                CF.IDTIPOATIVIDADEORIGEM = CEN_ATVORIGEM AND
                CF.IDTIPOATIVIDADEDESTINO = CEN_ATVDESTINO
        );
    END IF;

    IF AI_IDLOCALRESERVA <> 0 THEN
        SET LI_IDLOCALRESERVA = AI_IDLOCALRESERVA;
    END IF;

    IF AC_OPERACAO = 'D' THEN
        DELETE FROM
            DBA.PEDIDO_COMPRA_EMPRESA_TRANSFERENCIA
        WHERE
            IDEMPRESAGERADO = AI_IDEMPRESA AND
            IDPEDIDOGERADO = AI_IDPEDIDO AND
            IDCLIFORGERADO = AI_IDCLIFOR AND
            IDPRODUTO = LI_IDPRODUTO AND
            IDSUBPRODUTO = AI_IDSUBPRODUTO;

        DELETE FROM
            DBA.PEDIDO_COMPRA_PROD
        WHERE
            IDEMPRESA = AI_IDEMPRESA AND
            IDPEDIDO = AI_IDPEDIDO AND
            IDCLIFOR = AI_IDCLIFOR AND
            IDPRODUTO = LI_IDPRODUTO AND
            IDSUBPRODUTO = AI_IDSUBPRODUTO;
    ELSE
        IF NOT EXISTS (
            SELECT
                1
            FROM
                DBA.PEDIDO_COMPRA_PROD
            WHERE
                IDEMPRESA = AI_IDEMPRESA AND
                IDCLIFOR = AI_IDCLIFOR AND
                IDPEDIDO = AI_IDPEDIDO AND
                IDPRODUTO = LI_IDPRODUTO AND
                IDSUBPRODUTO = AI_IDSUBPRODUTO
        ) THEN
            INSERT INTO DBA.PEDIDO_COMPRA_PROD (
                IDPRODUTO,
                IDSUBPRODUTO,
                IDCLIFOR,
                IDPEDIDO,
                IDEMPRESA,
                IDSUGESTAO,
                PERDESCONTO1,
                PERDESCONTO2,
                PERDESCONTO3,
                PERDESCONTO4,
                PERIPI,
                PERMARGEMLUCRO,
                QTDSOLICITADA,
                QTDATENDIDA,
                VALUNITARIO,
                PERICM,
                VALTOTBRUTO,
                PERBONIFICACAO,
                VALTOTLIQUIDO,
                VALICMSUBST,
                PERFRETE,
                PERADICIONAL,
                PERIPIFRETE,
                VALDESCONTOICMS,
                TIPOSITTRIB,
                PERIPIADICIONAL,
                VALIPI,
                FLAGSITUACAOATUAL,
                PERACESSORIOS,
                PERIPIACESSORIOS,
                VALDESCONTOPISCOFINS,
                PERINFLACAO,
                PESOBRUTO,
                QTDTRANSFERIDA,
                FLAGSALDOZERADO,
                DTENTREGA,
                OBSPRODUTO,
                QTDSUGERIDATRANSF,
                FLAGATENDIDO,
                QTDSUGESTAOCOMPRA,
                FLAGCALCULAST,
                IDCENARIOFISCAL,
                IDLOCALESTOQUERESERVA,
				VALUNITLIQUIDO
            )
            VALUES (
                LI_IDPRODUTO,
                AI_IDSUBPRODUTO,
                AI_IDCLIFOR,
                AI_IDPEDIDO,
                AI_IDEMPRESA,
                AI_IDSUGESTAO,
                ADE_PERDESCONTO1,
                ADE_PERDESCONTO2,
                ADE_PERDESCONTO3,
                ADE_PERDESCONTO4,
                ADE_PERIPI,
                ADE_PERMARGEMLUCRO,
                ADE_QTDSOLICITADA,
                0,
                ADE_VALUNITARIO,
                ADE_PERICM,
                ADE_VALTOTBRUTO,
                ADE_PERBONIFICACAO,
                ADE_VALTOTLIQUIDO,
                ADE_VALICMSUBST,
                ADE_PERFRETE,
                ADE_PERADICIONAL,
                ADE_PERIPIFRETE,
                ADE_VALDESCONTOICMS,
                AC_TIPOSITTRIB,
                ADE_PERIPIADICIONAL,
                ADE_VALIPI,
                AC_FLAGSITUACAOATUAL,
                ADE_PERACESSORIOS,
                ADE_PERIPIACESSORIOS,
                ADE_VALDESCONTOPISCOFINS,
                ADE_PERINFLACAO,
                ADE_PESOBRUTO,
                ADE_QTDTRANSFERIDA,
                AC_FLAGSALDOZERADO,
                AD_DTENTREGA,
                AS_OBSPRODUTO,
                ADE_QTDSUGERIDATRANSF,
                'F',
                ADE_QTDSUGESTAOCOMPRA,
                AC_FLAGCALCULAST,
                AI_IDCENARIOFISCAL,
                LI_IDLOCALRESERVA,
				LD_VALUNITLIQUIDO
            );
        ELSE
            UPDATE
                DBA.PEDIDO_COMPRA_PROD
            SET
                IDSUGESTAO = AI_IDSUGESTAO,
                PERDESCONTO1 = ADE_PERDESCONTO1,
                PERDESCONTO2 = ADE_PERDESCONTO2,
                PERDESCONTO3 = ADE_PERDESCONTO3,
                PERDESCONTO4 = ADE_PERDESCONTO4,
                PERIPI = ADE_PERIPI,
                PERMARGEMLUCRO = ADE_PERMARGEMLUCRO,
                QTDSOLICITADA = ADE_QTDSOLICITADA,
                VALUNITARIO = ADE_VALUNITARIO,
                PERICM = ADE_PERICM,
                VALTOTBRUTO = ADE_VALTOTBRUTO,
                PERBONIFICACAO = ADE_PERBONIFICACAO,
                VALTOTLIQUIDO = ADE_VALTOTLIQUIDO,
                VALICMSUBST = ADE_VALICMSUBST,
                PERFRETE = ADE_PERFRETE,
                PERADICIONAL = ADE_PERADICIONAL,
                PERIPIFRETE = ADE_PERIPIFRETE,
                VALDESCONTOICMS = ADE_VALDESCONTOICMS,
                TIPOSITTRIB = AC_TIPOSITTRIB,
                PERIPIADICIONAL = ADE_PERIPIADICIONAL,
                VALIPI = ADE_VALIPI,
                FLAGSITUACAOATUAL = AC_FLAGSITUACAOATUAL,
                PERACESSORIOS = ADE_PERACESSORIOS,
                PERIPIACESSORIOS = ADE_PERIPIACESSORIOS,
                VALDESCONTOPISCOFINS = ADE_VALDESCONTOPISCOFINS,
                PERINFLACAO = ADE_PERINFLACAO,
                PESOBRUTO = ADE_PESOBRUTO,
                QTDTRANSFERIDA = ADE_QTDTRANSFERIDA,
                FLAGSALDOZERADO = AC_FLAGSALDOZERADO,
                DTENTREGA = AD_DTENTREGA,
                OBSPRODUTO = AS_OBSPRODUTO,
                QTDSUGERIDATRANSF = ADE_QTDSUGERIDATRANSF,
                QTDSUGESTAOCOMPRA = ADE_QTDSUGESTAOCOMPRA,
                FLAGCALCULAST = AC_FLAGCALCULAST,
                IDCENARIOFISCAL = AI_IDCENARIOFISCAL,
                IDLOCALESTOQUERESERVA = LI_IDLOCALRESERVA,
				VALUNITLIQUIDO = LD_VALUNITLIQUIDO
            WHERE
                IDEMPRESA = AI_IDEMPRESA AND
                IDCLIFOR = AI_IDCLIFOR AND
                IDPEDIDO = AI_IDPEDIDO AND
                IDPRODUTO = LI_IDPRODUTO AND
                IDSUBPRODUTO = AI_IDSUBPRODUTO;
        END IF;
    END IF;
END
