CREATE OR REPLACE VIEW DBA.VW_GEA_PEDIDO_COMPRA_ALTERADO AS
SELECT
    PC.IDEMPRESA,
    PC.IDPEDIDO,
    PC.IDCLIFOR,
    PC.DTMOVIMENTO,
    PC.DTALTERACAO,
    DBA.SOMA_DIAS(PC.DTMOVIMENTO, PC.DIASENTREGA) AS DTPREVENTREGA,
    0 AS ACRESCIMO,
    PC.IDPAGAMENTO,
    0 AS DESCFORMA,
    0 AS PERACRESVENDA,
    'F' AS PRECOFIRME,
    CASE
        WHEN PC.FLAGFRETECIF = 'T' THEN
            'C'
        ELSE
            'F'
    END AS CIFFOB,
    PC.OBSGERAL,
    'F' AS ENCOMENDA,
    'F' AS ABASTECIMENTO,
    /*(
        SELECT
            CASE
                WHEN SUM(PCP.QTDSUGESTAOCOMPRA) = SUM(PCP.QTDCANCELADA) OR
                    SUM(PCP.QTDSOLICITADA) <= SUM(PCP.QTDCANCELADA) THEN
                    'T'
                ELSE
                    PC.FLAGCANCELADO
            END AS CANCELADO
        FROM
            DBA.PEDIDO_COMPRA_PROD AS PCP
        WHERE
            PCP.IDEMPRESA = PC.IDEMPRESA AND
            PCP.IDPEDIDO = PC.IDPEDIDO AND
            PCP.IDCLIFOR = PC.IDCLIFOR
    )*/PC.FLAGCANCELADO AS FLAGCANCELADO,
    (
        SELECT
            SUBSTR(
                XMLSERIALIZE(
                    XMLAGG(
                        XMLTEXT(
                            CONCAT(
                                ';',
                                DBA.DIF_DIAS(
                                    PC.DTMOVIMENTO,
                                    PEDIDO_COMPRA_VCTO.DTVENCIMENTO
                                )
                            )
                        )
                    ) AS VARCHAR(32000)
                ),
                2
            )
        FROM
            DBA.PEDIDO_COMPRA_VCTO AS PEDIDO_COMPRA_VCTO
        WHERE
            PEDIDO_COMPRA_VCTO.IDEMPRESA = PC.IDEMPRESA AND
            PEDIDO_COMPRA_VCTO.IDPEDIDO = PC.IDPEDIDO
    ) AS CONDICAO,
    PC.TIPOCATEGORIA,
    PC.TIPOITEMCATEGORIA,
    PCET.IDEMPRESA AS IDEMPRESAORIGEM,
    PCET.IDPEDIDO AS IDPEDIDOORIGEM,
    PCET.IDCLIFOR AS IDCLIFORORIGEM
FROM
    DBA.PEDIDO_COMPRA AS PC
LEFT JOIN
    (
        SELECT
            PCET.IDEMPRESA,
            PCET.IDPEDIDO,
            PCET.IDCLIFOR,
            PCET.IDEMPRESAGERADO,
            PCET.IDPEDIDOGERADO,
            PCET.IDCLIFORGERADO,
            ROW_NUMBER() OVER (
                PARTITION BY
                    PCET.IDEMPRESA,
                    PCET.IDPEDIDO,
                    PCET.IDCLIFOR
            ) AS LINHA
        FROM
            DBA.PEDIDO_COMPRA_EMPRESA_TRANSFERENCIA AS PCET
    ) AS PCET ON
        PC.IDEMPRESA = PCET.IDEMPRESAGERADO AND
        PC.IDPEDIDO = PCET.IDPEDIDOGERADO AND
        PC.IDCLIFOR = PCET.IDCLIFORGERADO AND
        PCET.LINHA = 1
WHERE
    PC.DTALTERACAO >= CURRENT DATE - 5 DAYS AND
    PC.TIPOCATEGORIA <> 'T' AND
    PC.ORIGEMPEDIDO <> 'T' AND
    PC.DTMOVIMENTO IS NOT NULL

UNION

SELECT DISTINCT
    PEDIDO_COMPRA.IDEMPRESA,
    PEDIDO_COMPRA.IDPEDIDO,
    PEDIDO_COMPRA.IDCLIFOR,
    PEDIDO_COMPRA.DTMOVIMENTO,
    PEDIDO_COMPRA.DTALTERACAO,
    DBA.SOMA_DIAS(PEDIDO_COMPRA.DTMOVIMENTO, DIASENTREGA) AS DTPREVENTREGA,
    0 AS ACRESCIMO,
    PEDIDO_COMPRA.IDPAGAMENTO,
    0 AS DESCFORMA,
    0 AS PERACRESVENDA,
    'F' AS PRECOFIRME,
    CASE
        WHEN FLAGFRETECIF = 'T' THEN
            'C'
        ELSE
            'F'
    END AS CIFFOB,
    OBSGERAL,
    'F' AS ENCOMENDA,
    'F' AS ABASTECIMENTO,
    /*(
        SELECT
            CASE
                WHEN SUM(PCP.QTDSUGESTAOCOMPRA) = SUM(PCP.QTDCANCELADA) OR
                    SUM(PCP.QTDSOLICITADA) <= SUM(PCP.QTDCANCELADA) THEN
                    'T'
                ELSE
                    PEDIDO_COMPRA.FLAGCANCELADO
            END AS CANCELADO
        FROM
            DBA.PEDIDO_COMPRA_PROD AS PCP
        WHERE
            PCP.IDEMPRESA = PEDIDO_COMPRA.IDEMPRESA AND
            PCP.IDPEDIDO = PEDIDO_COMPRA.IDPEDIDO AND
            PCP.IDCLIFOR = PEDIDO_COMPRA.IDCLIFOR
    )*/ PEDIDO_COMPRA.FLAGCANCELADO AS FLAGCANCELADO,
    (
        SELECT
            SUBSTR(
                XMLSERIALIZE(
                    XMLAGG(
                        XMLTEXT(
                            CONCAT(
                                ';',
                                DBA.DIF_DIAS(
                                    PEDIDO_COMPRA.DTMOVIMENTO,
                                    PEDIDO_COMPRA_VCTO.DTVENCIMENTO
                                )
                            )
                        )
                    ) AS VARCHAR(32000)
                ),
                2
            )
        FROM
            DBA.PEDIDO_COMPRA_VCTO AS PEDIDO_COMPRA_VCTO
        WHERE
            PEDIDO_COMPRA_VCTO.IDEMPRESA = PEDIDO_COMPRA.IDEMPRESA AND
            PEDIDO_COMPRA_VCTO.IDPEDIDO = PEDIDO_COMPRA.IDPEDIDO
    ) AS CONDICAO,
    PEDIDO_COMPRA.TIPOCATEGORIA,
    PEDIDO_COMPRA.TIPOITEMCATEGORIA,
    PCET.IDEMPRESA AS IDEMPRESAORIGEM,
    PCET.IDPEDIDO AS IDPEDIDOORIGEM,
    PCET.IDCLIFOR AS IDCLIFORORIGEM
FROM
    DBA.PEDIDO_COMPRA
JOIN
    DBA.CONFERE_PEDIDO ON
        PEDIDO_COMPRA.IDPEDIDO = CONFERE_PEDIDO.IDPEDIDO AND
        PEDIDO_COMPRA.IDEMPRESA = CONFERE_PEDIDO.IDEMPRESA AND
        PEDIDO_COMPRA.IDCLIFOR = CONFERE_PEDIDO.IDCLIFOR
JOIN
    DBA.NOTAS ON
        NOTAS.NUMNOTA = CONFERE_PEDIDO.NUMNOTA AND
        NOTAS.SERIENOTA = CONFERE_PEDIDO.SERIENOTA AND
        NOTAS.IDEMPRESA = CONFERE_PEDIDO.IDEMPRESA AND
        NOTAS.IDCLIFOR = CONFERE_PEDIDO.IDCLIFOR
LEFT JOIN
    (
        SELECT
            PCET.IDEMPRESA,
            PCET.IDPEDIDO,
            PCET.IDCLIFOR,
            PCET.IDEMPRESAGERADO,
            PCET.IDPEDIDOGERADO,
            PCET.IDCLIFORGERADO,
            ROW_NUMBER() OVER (
                PARTITION BY
                    PCET.IDEMPRESA,
                    PCET.IDPEDIDO,
                    PCET.IDCLIFOR
            ) AS LINHA
        FROM
            DBA.PEDIDO_COMPRA_EMPRESA_TRANSFERENCIA AS PCET
    ) AS PCET ON
        PEDIDO_COMPRA.IDEMPRESA = PCET.IDEMPRESAGERADO AND
        PEDIDO_COMPRA.IDPEDIDO = PCET.IDPEDIDOGERADO AND
        PEDIDO_COMPRA.IDCLIFOR = PCET.IDCLIFORGERADO AND
        PCET.LINHA = 1
WHERE
    NOTAS.DTMOVIMENTO >= CURRENT DATE - 5 DAYS AND
    NOTAS.TIPONOTAFISCAL = 'E' AND
    PEDIDO_COMPRA.TIPOCATEGORIA <> 'T' AND
    PEDIDO_COMPRA.ORIGEMPEDIDO <> 'T' AND
    PEDIDO_COMPRA.DTMOVIMENTO IS NOT NULL