CONNECT TO NOP48 USER dba USING "a9d9p8.E10"
~

ALTER TABLE TMP.LOG_REPROCESSA_DTFIM
    ADD COLUMN DT_INICIO_PROCESSO TIMESTAMP
~

ALTER TABLE TMP.LOG_REPROCESSA_DTFIM
    ADD COLUMN DURACAO_ULTIMO_CICLO_SEGUNDOS INTEGER
~

COMMIT
~

CONNECT RESET
~
