CONNECT TO NOPONTO USER dba USING "a9d9p8.E10"
~

SELECT CURRENT TIMESTAMP AS VALIDATION_TS, CURRENT SERVER AS DBNAME
FROM SYSIBM.SYSDUMMY1
~

SELECT TABNAME, COLNAME, TYPENAME, NULLS
FROM SYSCAT.COLUMNS
WHERE TABSCHEMA = 'DBA'
  AND TABNAME IN ('ESTOQUE_SINTETICO','CONTABIL_SALDO','PRODUTO_CUSTO','MOVIMENTO_CUSTO')
  AND COLNAME = 'DTFIM'
ORDER BY TABNAME
~

SELECT 'ESTOQUE_SINTETICO' AS TABNAME, COUNT(*) AS NULL_DTFIM
FROM DBA.ESTOQUE_SINTETICO
WHERE DTFIM IS NULL
~
SELECT 'CONTABIL_SALDO' AS TABNAME, COUNT(*) AS NULL_DTFIM
FROM DBA.CONTABIL_SALDO
WHERE DTFIM IS NULL
~
SELECT 'MOVIMENTO_CUSTO' AS TABNAME, COUNT(*) AS NULL_DTFIM
FROM DBA.MOVIMENTO_CUSTO
WHERE DTFIM IS NULL
~
SELECT 'PRODUTO_CUSTO' AS TABNAME, COUNT(*) AS NULL_DTFIM
FROM DBA.PRODUTO_CUSTO
WHERE DTFIM IS NULL
~

SELECT TABNAME, INDNAME, UNIQUERULE, COLNAMES
FROM SYSCAT.INDEXES
WHERE TABSCHEMA = 'DBA'
  AND INDNAME IN ('IE_ESTSIN_DTFIM','IE_CONSAL_DTFIM','IE_PROCUS_DTFIM','IE_MOVCUS_DTFIM')
ORDER BY TABNAME, INDNAME
~

SELECT ROUTINENAME, ROUTINETYPE, VALID
FROM SYSCAT.ROUTINES
WHERE ROUTINESCHEMA = 'DBA'
  AND ROUTINENAME LIKE '%DTFIM%'
ORDER BY ROUTINENAME
~

SELECT TRIGNAME, TABNAME, VALID
FROM SYSCAT.TRIGGERS
WHERE TRIGSCHEMA = 'DBA'
  AND TRIGNAME LIKE 'TR_DTFIM_%'
ORDER BY TABNAME, TRIGNAME
~

CONNECT RESET
~
