CONNECT TO NOPONTO USER dba USING "a9d9p8.E10"
~

ALTER TABLE DBA.ESTOQUE_SINTETICO ADD DTFIM DATE NULL
~
ALTER TABLE DBA.CONTABIL_SALDO ADD DTFIM DATE NULL
~
ALTER TABLE DBA.PRODUTO_CUSTO ADD DTFIM TIMESTAMP NULL
~
ALTER TABLE DBA.MOVIMENTO_CUSTO ADD DTFIM TIMESTAMP NULL
~
COMMIT
~

CONNECT RESET
~
