CONNECT TO NOPONTO USER dba USING "a9d9p8.E10"
~

ALTER TABLE DBA.ESTOQUE_SINTETICO ALTER COLUMN DTFIM SET NOT NULL
~
ALTER TABLE DBA.CONTABIL_SALDO ALTER COLUMN DTFIM SET NOT NULL
~
ALTER TABLE DBA.PRODUTO_CUSTO ALTER COLUMN DTFIM SET NOT NULL
~
ALTER TABLE DBA.MOVIMENTO_CUSTO ALTER COLUMN DTFIM SET NOT NULL
~
COMMIT
~

CONNECT RESET
~
