CONNECT TO NOPONTO USER dba USING "a9d9p8.E10"
~

SELECT COLNAME
FROM SYSCAT.COLUMNS
WHERE TABSCHEMA = 'SYSCAT'
  AND TABNAME = 'TRIGGERS'
ORDER BY COLNO
~

SELECT TRIGSCHEMA, TRIGNAME, TABSCHEMA, TABNAME, VALID
FROM SYSCAT.TRIGGERS
WHERE UPPER(TEXT) LIKE '%SP_ATUALIZA_CUSTOS_POLIT%'
   OR UPPER(TEXT) LIKE '%TR_DEL_PROCU%'
   OR TRIGNAME LIKE '%PROCU%'
ORDER BY TABNAME, TRIGNAME
~

SELECT TRIGSCHEMA, TRIGNAME, TABSCHEMA, TABNAME, VALID
FROM SYSCAT.TRIGGERS
WHERE TABSCHEMA = 'DBA'
  AND TABNAME IN ('MOVIMENTO_CUSTO','PRODUTO_CUSTO')
ORDER BY TABNAME, TRIGNAME
~

CONNECT RESET
~
