CONNECT TO NOPONTO USER dba USING "a9d9p8.E10"
~

SELECT CURRENT TIMESTAMP AS PRECHECK_TS, CURRENT SERVER AS DBNAME
FROM SYSIBM.SYSDUMMY1
~

SELECT TABSCHEMA, TABNAME, CARD, STATS_TIME
FROM SYSCAT.TABLES
WHERE TABSCHEMA = 'DBA'
  AND TABNAME IN ('ESTOQUE_SINTETICO','CONTABIL_SALDO','PRODUTO_CUSTO','MOVIMENTO_CUSTO')
ORDER BY TABNAME
~

SELECT TABNAME, COLNAME, TYPENAME, NULLS
FROM SYSCAT.COLUMNS
WHERE TABSCHEMA = 'DBA'
  AND TABNAME IN ('ESTOQUE_SINTETICO','CONTABIL_SALDO','PRODUTO_CUSTO','MOVIMENTO_CUSTO')
  AND COLNAME IN ('DTFIM','DTMOVIMENTO')
ORDER BY TABNAME, COLNO
~

SELECT TABNAME, INDNAME, UNIQUERULE, COLNAMES
FROM SYSCAT.INDEXES
WHERE TABSCHEMA = 'DBA'
  AND TABNAME IN ('ESTOQUE_SINTETICO','CONTABIL_SALDO','PRODUTO_CUSTO','MOVIMENTO_CUSTO')
  AND INDNAME IN ('IE_ESTSIN_DTFIM','IE_CONSAL_DTFIM','IE_PROCUS_DTFIM','IE_MOVCUS_DTFIM')
ORDER BY TABNAME, INDNAME
~

SELECT ROUTINENAME, ROUTINETYPE, VALID
FROM SYSCAT.ROUTINES
WHERE ROUTINESCHEMA = 'DBA'
  AND ROUTINENAME IN (
    'UF_MAX_DTFIM',
    'SP_REPROCESSA_DTFIM_ESTSIN','SP_REPROCESSA_DTFIM_CONSAL',
    'SP_REPROCESSA_DTFIM_MOVCUS','SP_REPROCESSA_DTFIM_PROCUS',
    'SP_PROCESSA_DTFIM_ESTSIN','SP_PROCESSA_DTFIM_CONSAL',
    'SP_PROCESSA_DTFIM_MOVCUS','SP_PROCESSA_DTFIM_PROCUS'
  )
ORDER BY ROUTINENAME
~

SELECT TRIGNAME, TABNAME, VALID
FROM SYSCAT.TRIGGERS
WHERE TRIGSCHEMA = 'DBA'
  AND TRIGNAME LIKE 'TR_DTFIM_%'
ORDER BY TABNAME, TRIGNAME
~

CONNECT RESET
~
