CONNECT TO NOP48 USER dba USING "a9d9p8.E10"
~

SELECT
    t.TABSCHEMA,
    t.TABNAME,
    t.TBSPACEID,
    t.TABLEID
FROM
    SYSCAT.TABLES t
WHERE
    t.TABSCHEMA = 'TMP'
AND t.TABNAME = 'LOG_REPROCESSA_DTFIM'
~

SELECT
    l.APPLICATION_HANDLE,
    l.LOCK_MODE,
    l.LOCK_CURRENT_MODE,
    l.LOCK_OBJECT_TYPE,
    l.LOCK_STATUS,
    l.LOCK_COUNT,
    a.APPL_NAME,
    a.AUTHID,
    a.APPL_STATUS,
    a.STATUS_CHANGE_TIME,
    a.CLIENT_NNAME
FROM
    TABLE(MON_GET_LOCKS(NULL, -2)) AS l
JOIN
    SYSCAT.TABLES t
ON
    t.TBSPACEID = l.TBSP_ID
AND t.TABLEID = l.TAB_FILE_ID
LEFT JOIN
    SYSIBMADM.APPLICATIONS a
ON
    a.AGENT_ID = l.APPLICATION_HANDLE
WHERE
    t.TABSCHEMA = 'TMP'
AND t.TABNAME = 'LOG_REPROCESSA_DTFIM'
ORDER BY
    l.LOCK_STATUS,
    l.APPLICATION_HANDLE
~

CONNECT RESET
~
