CONNECT TO NOP48 USER dba USING "a9d9p8.E10"
~

SELECT
    APPLICATION_HANDLE,
    LOCK_MODE,
    LOCK_OBJECT_TYPE,
    TABSCHEMA,
    TABNAME,
    LOCK_STATUS
FROM
    TABLE(MON_GET_LOCKS(NULL, -2)) AS L
WHERE
    TABSCHEMA = 'TMP'
AND TABNAME = 'LOG_REPROCESSA_DTFIM'
ORDER BY
    LOCK_STATUS,
    APPLICATION_HANDLE
~

SELECT
    AGENT_ID,
    APPLICATION_HANDLE,
    APPLICATION_NAME,
    AUTHID,
    CLIENT_WRKSTNNAME,
    APPL_STATUS,
    STATUS_CHANGE_TIME
FROM
    SYSIBMADM.APPLICATIONS
WHERE
    APPLICATION_HANDLE IN (
        SELECT
            APPLICATION_HANDLE
        FROM
            TABLE(MON_GET_LOCKS(NULL, -2)) AS L
        WHERE
            TABSCHEMA = 'TMP'
        AND TABNAME = 'LOG_REPROCESSA_DTFIM'
    )
ORDER BY
    APPLICATION_HANDLE
~

CONNECT RESET
~
