CONNECT TO NOP48 USER dba USING "a9d9p8.E10"
~
EXPORT TO _tmp_routines.del OF DEL MODIFIED BY NOCHARDEL
    SELECT
        ROUTINENAME,
        TEXT
    FROM
        SYSCAT.ROUTINES
    WHERE
        ROUTINESCHEMA = 'DBA'
    AND ROUTINENAME IN (
        'SP_REPROCESSA_DTFIM_ESTSIN',
        'SP_REPROCESSA_DTFIM_CONSAL',
        'SP_REPROCESSA_DTFIM_MOVCUS',
        'SP_REPROCESSA_DTFIM_PROCUS'
    )
    ORDER BY
        ROUTINENAME
~
CONNECT RESET
~
