CONNECT TO NOPONTO USER dba USING "a9d9p8.E10"
~
SELECT
    COUNT(*) AS TOTAL_ROWS,
    SUM(CASE WHEN DTFIM IS NOT NULL THEN 1 ELSE 0 END) AS FILLED_ROWS,
    SUM(CASE WHEN DTFIM IS NULL THEN 1 ELSE 0 END) AS NULL_ROWS
FROM DBA.MOVIMENTO_CUSTO WITH UR
~
CONNECT RESET
~
