CONNECT TO NOPONTO USER dba USING "a9d9p8.E10"
~

SELECT TRIGNAME, TABNAME, EVENT, TIME, VALID
FROM SYSCAT.TRIGGERS
WHERE TRIGSCHEMA = 'DBA'
  AND (
       TABNAME IN ('MOVIMENTO_CUSTO','PRODUTO_CUSTO')
    OR TRIGNAME = 'TR_DEL_PROCU'
  )
ORDER BY TABNAME, TRIGNAME
~

SELECT TRIGNAME, TEXT
FROM SYSCAT.TRIGGERS
WHERE TRIGSCHEMA = 'DBA'
  AND TRIGNAME IN ('TR_DEL_PROCU','TR_ATCMC_FILA_AU','TR_DTFIM_MOVCUS_AU')
ORDER BY TRIGNAME
~

SELECT ROUTINENAME, ROUTINETYPE, VALID
FROM SYSCAT.ROUTINES
WHERE ROUTINESCHEMA = 'DBA'
  AND ROUTINENAME = 'SP_ATUALIZA_CUSTOS_POLIT'
~

CONNECT RESET
~
