CONNECT TO NOPONTO USER dba USING "a9d9p8.E10"
~

SELECT TRIGNAME, TABNAME, TRIGTIME, TRIGEVENT, EVENTUPDATE, ENABLED, VALID
FROM SYSCAT.TRIGGERS
WHERE TABSCHEMA = 'DBA'
  AND TABNAME IN ('MOVIMENTO_CUSTO','PRODUTO_CUSTO')
ORDER BY TABNAME, TRIGNAME
~

SELECT TRIGNAME, SUBSTR(TEXT, 1, 3500) AS TEXT_PART
FROM SYSCAT.TRIGGERS
WHERE TRIGSCHEMA = 'DBA'
  AND TABNAME = 'MOVIMENTO_CUSTO'
  AND EVENTUPDATE = 'Y'
ORDER BY TRIGNAME
~

CONNECT RESET
~
