CONNECT TO NOP48 USER dba USING "a9d9p8.E10"
~

SELECT
    r.ROUTINENAME,
    r.SPECIFICNAME,
    r.PARM_COUNT,
    r.VALID,
    p.ORDINAL,
    p.PARMNAME,
    p.TYPENAME,
    p.ROWTYPE
FROM
    SYSCAT.ROUTINES r
LEFT JOIN
    SYSCAT.ROUTINEPARMS p
ON
    p.ROUTINESCHEMA = r.ROUTINESCHEMA
AND p.SPECIFICNAME = r.SPECIFICNAME
WHERE
    r.ROUTINESCHEMA = 'DBA'
AND r.ROUTINENAME IN (
    'SP_REPROCESSA_DTFIM_ESTSIN_TMP',
    'SP_REPROCESSA_DTFIM_CONSAL_TMP',
    'SP_REPROCESSA_DTFIM_MOVCUS_TMP',
    'SP_REPROCESSA_DTFIM_PROCUS_TMP'
)
ORDER BY
    r.ROUTINENAME,
    p.ORDINAL
~

CONNECT RESET
~
