WITH TOTAIS_CLIENTE AS (
    SELECT
        CR.IDCLIFOR,
        SUM(COALESCE(CR.VALTITULO, 0)) AS TOTAL_TITULO,
        SUM(
            CASE
                WHEN CR.FLAGBAIXADA = 'F'
                    THEN COALESCE(CR.VALSALDOTITULO, 0)
                ELSE 0
            END
        ) AS TOTAL_ATIVO,
        SUM(
            CASE
                WHEN CR.FLAGBAIXADA = 'F'
                 AND CR.DTVENCIMENTO >= CURRENT_DATE
                    THEN COALESCE(CR.VALSALDOTITULO, 0)
                ELSE 0
            END
        ) AS TOTAL_TITULOS_NAO_VENCIDOS,
        SUM(
            CASE
                WHEN CR.FLAGBAIXADA = 'F'
                 AND CR.DTVENCIMENTO < CURRENT_DATE
                    THEN COALESCE(CR.VALSALDOTITULO, 0)
                ELSE 0
            END
        ) AS TOTAL_TITULOS_VENCIDOS,
        SUM(COALESCE(CR.SUMVALPAGAMENTOTITULO, 0)) AS TOTAL_PAGO,
        SUM(
            CASE
                WHEN CR.DTULTIMOPAGAMENTO IS NOT NULL
                 AND CR.DTULTIMOPAGAMENTO > CR.DTVENCIMENTO + 3 DAYS
                    THEN COALESCE(CR.SUMVALPAGAMENTOTITULO, 0)
                ELSE 0
            END
        ) AS TOTAL_PAGO_ATRASO_SUP_3_DIAS
    FROM
        DBA.CONTAS_RECEBER_SALDOS_VIEW CR
    GROUP BY
        CR.IDCLIFOR
)
SELECT
    CF.IDCLIFOR,
    CF.CNPJCPF,
    TS.DESCRSITUACAO AS SITUACAO_CLIENTE,
    CF.SCORESPCSERASA AS SCORE_SERASA,
    CF.DTCADASTRO AS DATA_CADASTRO,
    CF.DTALTERACAO AS DATA_ULTIMA_ALTERACAO,
    CF.VALLIMITECREDITO AS VALOR_LIMITE_CREDITO,
    TC.TOTAL_TITULO,
    TC.TOTAL_ATIVO,
    TC.TOTAL_TITULOS_NAO_VENCIDOS,
    TC.TOTAL_TITULOS_VENCIDOS,
    TC.TOTAL_PAGO,
    TC.TOTAL_PAGO_ATRASO_SUP_3_DIAS
FROM
    TOTAIS_CLIENTE TC
    INNER JOIN DBA.CLIENTE_FORNECEDOR CF ON (
        CF.IDCLIFOR = TC.IDCLIFOR
    )
    LEFT JOIN DBA.TABELA_SITUACAO TS ON (
        TS.IDSITUACAO = CF.IDSITUACAO
    )
ORDER BY
    CF.IDCLIFOR;
