WITH NOTAS_COMPRA AS (
    SELECT
        N.IDCLIFOR
    FROM
        DBA.NOTAS N
    JOIN
        DBA.NOTAS_ENTRADA_SAIDA NES ON
            NES.IDEMPRESA = N.IDEMPRESA AND
            NES.IDPLANILHA = N.IDPLANILHA
    JOIN
        DBA.OPERACAO_INTERNA OI ON
            OI.IDOPERACAO = NES.IDOPERACAO
    WHERE
        N.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM AND
        OI.TIPOMOVIMENTO = 'C'
),
TOTAL_NOTAS AS (
    SELECT
        COUNT(*) AS QTD_TOTAL_NOTAS
    FROM
        NOTAS_COMPRA
),
FORNECEDORES AS (
    SELECT
        NC.IDCLIFOR,
        COUNT(*) AS QTD_NOTAS
    FROM
        NOTAS_COMPRA NC
    GROUP BY
        NC.IDCLIFOR
)
SELECT
    F.IDCLIFOR,
    CF.NOME AS NOME_FORNECEDOR,
    F.QTD_NOTAS AS QUANTIDADE_NOTAS,
    DECIMAL(
        CASE
            WHEN TN.QTD_TOTAL_NOTAS = 0 THEN
                0
            ELSE
                (F.QTD_NOTAS * 100.00) / TN.QTD_TOTAL_NOTAS
        END,
        15,
        2
    ) AS PERCENTUAL_REPRESENTATIVIDADE,
    CF.UFCLIFOR AS ESTADO_FORNECEDOR,
    CASE CF.REGIMETRIBUTARIO
        WHEN 'R' THEN 'Regime Regular'
        WHEN 'H' THEN 'Regime Hibrido'
        WHEN 'E' THEN 'Tributacao Especifica'
        ELSE CF.REGIMETRIBUTARIO
    END AS REGIME_FORNECEDOR,
    ATIV.DESCRATIVIDADE AS RAMO_ATIVIDADE_FORNECEDOR
FROM
    FORNECEDORES F
CROSS JOIN
    TOTAL_NOTAS TN
JOIN
    DBA.CLIENTE_FORNECEDOR CF ON
        CF.IDCLIFOR = F.IDCLIFOR
LEFT JOIN
    DBA.ATIVIDADE ATIV ON
        ATIV.IDATIVIDADE = CF.IDATIVIDADE
ORDER BY
    F.QTD_NOTAS DESC,
    CF.NOME
FETCH FIRST 10 ROWS ONLY;
