select '##DIVISAO_TESTE' from sysibm.sysdummy1@
select min(IDDIVISAO) from DBA.DIVISAO@

insert into DBA.ESTRUTURA_MERCADOLOGICA
  (IDESTRUTURA, DESCRESTRUTURA, IDESTRUTURAPAI)
values
  (900000001, 'TESTE MANUAL - DIVISAO', null)@

insert into DBA.ESTRUTURA_MERCADOLOGICA_NIVEIS
  (IDNIVELESTRUTURA, IDESTRUTURA)
values
  (4, 900000001)@

insert into DBA.ESTRUTURA_MERCADOLOGICA
  (IDESTRUTURA, DESCRESTRUTURA, IDESTRUTURAPAI)
values
  (900000002, 'TESTE MANUAL - SECAO', 900000001)@

insert into DBA.ESTRUTURA_MERCADOLOGICA_NIVEIS
  (IDNIVELESTRUTURA, IDESTRUTURA)
values
  (3, 900000002)@

insert into DBA.ESTRUTURA_MERCADOLOGICA
  (IDESTRUTURA, DESCRESTRUTURA, IDESTRUTURAPAI)
values
  (900000003, 'TESTE MANUAL - GRUPO', 900000002)@

insert into DBA.ESTRUTURA_MERCADOLOGICA_NIVEIS
  (IDNIVELESTRUTURA, IDESTRUTURA)
values
  (2, 900000003)@

insert into DBA.ESTRUTURA_MERCADOLOGICA
  (IDESTRUTURA, DESCRESTRUTURA, IDESTRUTURAPAI)
values
  (900000004, 'TESTE MANUAL - SUB-GRUPO', 900000003)@

insert into DBA.ESTRUTURA_MERCADOLOGICA_NIVEIS
  (IDNIVELESTRUTURA, IDESTRUTURA)
values
  (1, 900000004)@

update DBA.DIVISAO
set IDNIVELESTRUTURA = 4,
    IDESTRUTURAPAI = 900000001
where IDDIVISAO = (select min(IDDIVISAO) from DBA.DIVISAO)@

select '##ARVORE_TESTE' from sysibm.sysdummy1@
select
  e.IDESTRUTURA,
  e.DESCRESTRUTURA,
  e.IDESTRUTURAPAI,
  n.IDNIVELESTRUTURA,
  c.DESCRNIVEL
from DBA.ESTRUTURA_MERCADOLOGICA e
join DBA.ESTRUTURA_MERCADOLOGICA_NIVEIS n
  on n.IDESTRUTURA = e.IDESTRUTURA
join DBA.CONFIG_NIVEIS_ESTRUTURA_MERCADOLOGICA c
  on c.IDNIVELESTRUTURA = n.IDNIVELESTRUTURA
where e.IDESTRUTURA between 900000001 and 900000004
order by e.IDESTRUTURA@

select '##DIVISAO_LINK_TESTE' from sysibm.sysdummy1@
select
  d.IDDIVISAO,
  d.DESCRDIVISAO,
  d.IDNIVELESTRUTURA,
  d.IDESTRUTURAPAI,
  e.DESCRESTRUTURA
from DBA.DIVISAO d
left join DBA.ESTRUTURA_MERCADOLOGICA e
  on e.IDESTRUTURA = d.IDESTRUTURAPAI
where d.IDDIVISAO = (select min(IDDIVISAO) from DBA.DIVISAO)@

rollback@
