WITH BAIXAS AS (
    SELECT
        IDPLANILHA,
        COUNT(*) AS QT_BAIXAS,
        SUM(VALPAGAMENTOTITULO) AS VAL_BAIXAS
    FROM
        DBA.CONTAS_RECEBER_BAIXAS
    WHERE
        ORIGEMMOVIMENTO IN ('SIT', 'TES')
    GROUP BY
        IDPLANILHA
),
CONTABIL AS (
    SELECT
        IDPLANILHA,
        COUNT(*) AS QT_CONTABIL_C,
        SUM(VALLANCAMENTO) AS VAL_CONTABIL_C
    FROM
        DBA.CONTABIL_MOVIMENTO
    WHERE
        TIPONATUREZALCTO = 'C'
    GROUP BY
        IDPLANILHA
)
SELECT
    B.IDPLANILHA,
    B.QT_BAIXAS,
    B.VAL_BAIXAS,
    COALESCE(C.QT_CONTABIL_C, 0) AS QT_CONTABIL_C,
    COALESCE(C.VAL_CONTABIL_C, 0) AS VAL_CONTABIL_C,
    B.VAL_BAIXAS - COALESCE(C.VAL_CONTABIL_C, 0) AS DIFERENCA
FROM
    BAIXAS B
    LEFT JOIN CONTABIL C ON (
        C.IDPLANILHA = B.IDPLANILHA
    )
WHERE
    B.VAL_BAIXAS <> COALESCE(C.VAL_CONTABIL_C, 0)
ORDER BY
    ABS(B.VAL_BAIXAS - COALESCE(C.VAL_CONTABIL_C, 0)) DESC,
    B.IDPLANILHA;
