CREATE OR REPLACE FUNCTION DBA.UF_GET_COI_PEDIDO_COMPRA_LIBERADO (
	AI_IDEMPRESA INTEGER,
	AI_IDCLIFOR INTEGER
)
RETURNS INTEGER
LANGUAGE SQL
READS SQL DATA
BEGIN ATOMIC
	DECLARE LI_IDOPERACAO INTEGER;

	SET LI_IDOPERACAO = (
		SELECT
			CF.IDOPERACAOPADRAO
		FROM
			DBA.CLIENTE_FORNECEDOR CF
		JOIN
			DBA.OPERACAO_INTERNA OI ON
				OI.IDOPERACAO = CF.IDOPERACAOPADRAO
		WHERE
			CF.IDCLIFOR = AI_IDCLIFOR AND
			OI.TIPOCATEGORIA = 'C' AND
			OI.TIPOITEMCATEGORIA = 'C1' AND
			NOT EXISTS (
				SELECT
					1
				FROM
					DBA.EMPRESA_BLOQUEIO_COI EBC
				WHERE
					EBC.IDEMPRESA = AI_IDEMPRESA AND
					EBC.IDOPERACAO = OI.IDOPERACAO
			)
		FETCH FIRST 1 ROW ONLY
	);

	IF LI_IDOPERACAO IS NOT NULL THEN
		RETURN LI_IDOPERACAO;
	END IF;

	SET LI_IDOPERACAO = (
		SELECT
			CC.IDCOIPADRAOPEDIDOCOMPRA
		FROM
			DBA.CONFIG_COMPRAS CC
		JOIN
			DBA.OPERACAO_INTERNA OI ON
				OI.IDOPERACAO = CC.IDCOIPADRAOPEDIDOCOMPRA
		WHERE
			OI.TIPOCATEGORIA = 'C' AND
			OI.TIPOITEMCATEGORIA = 'C1' AND
			NOT EXISTS (
				SELECT
					1
				FROM
					DBA.EMPRESA_BLOQUEIO_COI EBC
				WHERE
					EBC.IDEMPRESA = AI_IDEMPRESA AND
					EBC.IDOPERACAO = OI.IDOPERACAO
			)
		FETCH FIRST 1 ROW ONLY
	);

	IF LI_IDOPERACAO IS NOT NULL THEN
		RETURN LI_IDOPERACAO;
	END IF;

	SET LI_IDOPERACAO = (
		SELECT
			MIN(OI.IDOPERACAO)
		FROM
			DBA.OPERACAO_INTERNA OI
		WHERE
			OI.TIPOCATEGORIA = 'C' AND
			OI.TIPOITEMCATEGORIA = 'C1' AND
			NOT EXISTS (
				SELECT
					1
				FROM
					DBA.EMPRESA_BLOQUEIO_COI EBC
				WHERE
					EBC.IDEMPRESA = AI_IDEMPRESA AND
					EBC.IDOPERACAO = OI.IDOPERACAO
			)
	);

	RETURN LI_IDOPERACAO;
END
GO
GRANT EXECUTE ON FUNCTION DBA.UF_GET_COI_PEDIDO_COMPRA_LIBERADO TO USER GEA
GO
DROP PROCEDURE DBA.SP_INSERT_PEDIDO_COMPRA
GO
CREATE OR REPLACE PROCEDURE DBA.SP_INSERT_PEDIDO_COMPRA (
	AI_IDEMPRESA INTEGER,
	AI_IDCLIFOR INTEGER,
	AI_IDPEDIDO INTEGER,
	AI_IDPAGAMENTO INTEGER,
	AI_IDEMPRESAEMITENTE INTEGER,
	AI_IDUSUARIO INTEGER,
	AD_DTMOVIMENTO DATE,
	ADE_PERDESCGERAL DECIMAL(10,6),
	AI_DIASENTREGA INTEGER,
	AC_FLAGVCTOFIXO CHAR(1),
	ADE_VALFRETE DECIMAL(15,6),
	AS_OBSGERAL VARCHAR(300),
	AC_FLAGPEDIDOBLOQUEADO CHAR(1),
	AC_FLAGFRETECIF CHAR(1),
	AC_TIPOEMBALAGEMGRAVADA CHAR(1),
	AC_FLAGCANCELADO CHAR(1),
	AC_TIPORATEIOFRETE CHAR(1),
	AC_TIPONATUREZAFRETE CHAR(1),
	AC_TIPODOCUMENTOFRETE CHAR(1),
	ADE_VALFRETEPAGO DECIMAL(15,6),
	AC_FLAGEXPORTADO CHAR(1),
	AC_TIPOCATEGORIA CHAR(1),
	AC_ORIGEMPEDIDO CHAR(1)
)
BEGIN
	DECLARE AI_IDCTACONTABIL INTEGER;
	DECLARE AI_IDASSOCIADO INTEGER;
	DECLARE AI_IDTRANSPORTADOR INTEGER;
	DECLARE AI_IDCOTACAO INTEGER;
	DECLARE AS_ENDERECOTRANSPORTADOR VARCHAR(80);
	DECLARE AS_FONETRANSPORTADOR VARCHAR(20);
	DECLARE AD_DTVALIDADEPEDIDO DATE;
	DECLARE AI_IDPREPEDIDOIMP INTEGER;
	DECLARE AC_TIPOPEDIDO CHAR(2);
	DECLARE AI_IDPLANILHA INTEGER;
	DECLARE AI_TIPOCATEGORIA CHAR(1);
	DECLARE AI_TIPOITEMCATEGORIA CHAR(1);
	DECLARE AI_OPERACAOINTERNA INTEGER;

	SET AI_IDPLANILHA = DBA.UF_GET_IDPLANILHA();
	SET AI_IDCTACONTABIL = NULL;
	SET AI_IDASSOCIADO = NULL;
	SET AI_IDTRANSPORTADOR = NULL;
	SET AI_IDCOTACAO = NULL;
	SET AS_ENDERECOTRANSPORTADOR = NULL;
	SET AS_FONETRANSPORTADOR = NULL;
	SET AD_DTVALIDADEPEDIDO = CASE WHEN COALESCE((SELECT NUMDIASPADRAOVALIDADEPEDIDO FROM DBA.CONFIG_COMPRAS),0) = 0 THEN NULL ELSE AD_DTMOVIMENTO + COALESCE((SELECT NUMDIASPADRAOVALIDADEPEDIDO FROM DBA.CONFIG_COMPRAS),0) DAYS END;
	SET AI_IDPREPEDIDOIMP = NULL;
	SET AC_TIPOPEDIDO = NULL;
	SET AI_OPERACAOINTERNA = DBA.UF_GET_COI_PEDIDO_COMPRA_LIBERADO(AI_IDEMPRESA, AI_IDCLIFOR);
	
	IF AC_TIPOCATEGORIA = 'K' THEN
		SET AI_TIPOCATEGORIA = 'C';
		SET AI_TIPOITEMCATEGORIA = 'K';
	ELSE
		SET AI_TIPOCATEGORIA = AC_TIPOCATEGORIA;
		SET AI_TIPOITEMCATEGORIA = 'C';
	END IF;

	IF NOT EXISTS ( SELECT 1 FROM DBA.PEDIDO_COMPRA WHERE IDEMPRESA = AI_IDEMPRESA AND IDCLIFOR = AI_IDCLIFOR AND IDPEDIDO = AI_IDPEDIDO ) THEN

	INSERT INTO DBA.PEDIDO_COMPRA (
		IDEMPRESA,
		IDCLIFOR,
		IDPEDIDO,
		IDOPERACAO,
		IDPAGAMENTO,
		IDCTACONTABIL,
		IDEMPRESAEMITENTE,
		IDUSUARIO,
		IDASSOCIADO,
		IDTRANSPORTADOR,
		DTMOVIMENTO,
		PERDESCGERAL,
		IDPLANILHA,
		DIASENTREGA,
		FLAGVCTOFIXO,
		VALFRETE,
		OBSGERAL,
		FLAGPEDIDOBLOQUEADO,
		FLAGFRETECIF,
		IDCOTACAO,
		TIPOEMBALAGEMGRAVADA,
		FLAGCANCELADO,
		TIPORATEIOFRETE,
		TIPONATUREZAFRETE,
		TIPODOCUMENTOFRETE,
		VALFRETEPAGO,
		FLAGEXPORTADO,
		ENDERECOTRANSPORTADOR,
		FONETRANSPORTADOR,
		TIPOCATEGORIA,
		DTVALIDADEPEDIDO,
		ORIGEMPEDIDO,
		IDPREPEDIDOIMP,
		TIPOPEDIDO,
		TIPOITEMCATEGORIA
	) VALUES (
		AI_IDEMPRESA,
		AI_IDCLIFOR,
		AI_IDPEDIDO,
		AI_OPERACAOINTERNA,
		AI_IDPAGAMENTO,
		AI_IDCTACONTABIL,
		AI_IDEMPRESAEMITENTE,
		AI_IDUSUARIO,
		AI_IDASSOCIADO,
		AI_IDTRANSPORTADOR,
		AD_DTMOVIMENTO,
		ADE_PERDESCGERAL,
		AI_IDPLANILHA,
		AI_DIASENTREGA,
		AC_FLAGVCTOFIXO,
		ADE_VALFRETE,
		AS_OBSGERAL,
		AC_FLAGPEDIDOBLOQUEADO,
		AC_FLAGFRETECIF,
		AI_IDCOTACAO,
		AC_TIPOEMBALAGEMGRAVADA,
		AC_FLAGCANCELADO,
		AC_TIPORATEIOFRETE,
		AC_TIPONATUREZAFRETE,
		AC_TIPODOCUMENTOFRETE,
		ADE_VALFRETEPAGO,
		AC_FLAGEXPORTADO,
		AS_ENDERECOTRANSPORTADOR,
		AS_FONETRANSPORTADOR,
		AI_TIPOCATEGORIA,
		AD_DTVALIDADEPEDIDO,
		AC_ORIGEMPEDIDO,
		AI_IDPREPEDIDOIMP,
		AC_TIPOPEDIDO,
		AI_TIPOITEMCATEGORIA
	);

	ELSE

	UPDATE
		DBA.PEDIDO_COMPRA
	SET
		IDEMPRESA = AI_IDEMPRESA,
		IDCLIFOR = AI_IDCLIFOR,
		IDPEDIDO = AI_IDPEDIDO,
		IDOPERACAO = AI_OPERACAOINTERNA,
		IDPAGAMENTO = AI_IDPAGAMENTO,
		IDCTACONTABIL = AI_IDCTACONTABIL,
		IDEMPRESAEMITENTE = AI_IDEMPRESAEMITENTE,
		IDUSUARIO = AI_IDUSUARIO,
		IDASSOCIADO = AI_IDASSOCIADO,
		IDTRANSPORTADOR = AI_IDTRANSPORTADOR,
		DTMOVIMENTO = AD_DTMOVIMENTO,
		PERDESCGERAL = ADE_PERDESCGERAL,
		IDPLANILHA = AI_IDPLANILHA,
		DIASENTREGA = AI_DIASENTREGA,
		FLAGVCTOFIXO = AC_FLAGVCTOFIXO,
		VALFRETE = ADE_VALFRETE,
		OBSGERAL = AS_OBSGERAL,
		FLAGPEDIDOBLOQUEADO = AC_FLAGPEDIDOBLOQUEADO,
		FLAGFRETECIF = AC_FLAGFRETECIF,
		IDCOTACAO = AI_IDCOTACAO,
		TIPOEMBALAGEMGRAVADA = AC_TIPOEMBALAGEMGRAVADA,
		FLAGCANCELADO = AC_FLAGCANCELADO,
		TIPORATEIOFRETE = AC_TIPORATEIOFRETE,
		TIPONATUREZAFRETE = AC_TIPONATUREZAFRETE,
		TIPODOCUMENTOFRETE = AC_TIPODOCUMENTOFRETE,
		VALFRETEPAGO = ADE_VALFRETEPAGO,
		FLAGEXPORTADO = AC_FLAGEXPORTADO,
		ENDERECOTRANSPORTADOR = AS_ENDERECOTRANSPORTADOR,
		FONETRANSPORTADOR = AS_FONETRANSPORTADOR,
		TIPOCATEGORIA = AI_TIPOCATEGORIA,
		DTVALIDADEPEDIDO = AD_DTVALIDADEPEDIDO,
		ORIGEMPEDIDO = AC_ORIGEMPEDIDO,
		IDPREPEDIDOIMP = AI_IDPREPEDIDOIMP,
		TIPOPEDIDO = AC_TIPOPEDIDO,
		TIPOITEMCATEGORIA = AI_TIPOITEMCATEGORIA
	WHERE
		IDEMPRESA = AI_IDEMPRESA AND
		IDCLIFOR = AI_IDCLIFOR AND
		IDPEDIDO = AI_IDPEDIDO;

	END IF;

END
GO
GRANT EXECUTE ON PROCEDURE DBA.SP_INSERT_PEDIDO_COMPRA TO USER GEA
GO
COMMIT
GO
