DROP TRIGGER DBA.TR_VAL_POL_PRECO_PROD_OFF_INS
@

DROP TRIGGER DBA.TR_VAL_POL_PRECO_PROD_OFF_UPD
@

CREATE OR REPLACE TRIGGER DBA.TR_DEL_POL_PRECO_PROD_OFF_INS
AFTER INSERT ON DBA.POLITICA_PRECO_PRODUTO_OFF
REFERENCING NEW AS N
FOR EACH ROW
WHEN (N.VALPRECOVAREJO IS NULL OR N.VALPRECOVAREJO = 0)
BEGIN ATOMIC
    DELETE FROM DBA.POLITICA_PRECO_PRODUTO_OFF
    WHERE IDEMPRESA = N.IDEMPRESA
      AND IDPRODUTO = N.IDPRODUTO
      AND IDSUBPRODUTO = N.IDSUBPRODUTO
      AND DTVIGENCIA = N.DTVIGENCIA;
END
@

