-- CLASSIFICACAO POR FORNECEDOR, COM TOTAIS DE NOTAS MONOTIPO POR TIPO.
-- Execute PREPARACAO e depois a consulta desejada na mesma sessao DB2.
-- Parametros: :RA_DTINI e :RA_DTFIM.
--
-- A classificacao (1 a 16) considera o conjunto de tipos do FORNECEDOR no
-- periodo. QTDNOTASTIPO conta somente notas cuja tributacao inteira e o TIPO
-- exibido, exatamente na granularidade do resumo-base.

DECLARE GLOBAL TEMPORARY TABLE SESSION.MAPEAMENTO_FORNECEDOR_MONOTIPO (
    CONSULTA SMALLINT, IDCLIFOR INTEGER, IDATIVIDADE INTEGER,
    ATIVIDADE VARCHAR(60), PRODUTOR CHAR(1), TIPO VARCHAR(20),
    QTDNOTASTIPO BIGINT, XML BIGINT, CAD BIGINT
) ON COMMIT PRESERVE ROWS NOT LOGGED WITH REPLACE;

INSERT INTO SESSION.MAPEAMENTO_FORNECEDOR_MONOTIPO
WITH
NOTAS_MOVIMENTO AS (
    SELECT EA.IDEMPRESA, EA.IDPLANILHA, N.IDCLIFOR
    FROM DBA.ESTOQUE_ANALITICO EA
    INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
    INNER JOIN DBA.NOTAS N ON N.IDEMPRESA = EA.IDEMPRESA AND N.IDPLANILHA = EA.IDPLANILHA
    WHERE EA.IDOPERACAO < 1000 AND OI.TIPOMOVIMENTO = 'C'
      AND OI.FLAGMOVSALDOPRO = 'T' AND N.FLAGMOVFISCAL = 'T' AND N.FLAGNOTACANCEL = 'F'
      AND EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
    GROUP BY EA.IDEMPRESA, EA.IDPLANILHA, N.IDCLIFOR
),
ITENS AS (
    SELECT NM.IDEMPRESA, NM.IDPLANILHA, NM.IDCLIFOR,
           CASE WHEN EAF.FLAGTRIBUTACAOXML = 'T' THEN 'XML' ELSE 'CAD' END AS FONTE,
           CASE
               WHEN MOD(EA.IDSITTRIB,100) = 40 THEN 'ISENTO-40'
               WHEN MOD(EA.IDSITTRIB,100) = 41 THEN 'NAOTRIBUTADO-41'
               WHEN MOD(EA.IDSITTRIB,100) = 50 THEN 'SUSPENSO-50'
               WHEN MOD(EA.IDSITTRIB,100) = 90 THEN 'OUTROS-90'
               WHEN MOD(EA.IDSITTRIB,100) = 0 THEN 'TRIBUTADO-00'
               WHEN MOD(EA.IDSITTRIB,100) = 20 THEN 'REDUCAO-20'
               WHEN MOD(EA.IDSITTRIB,100) = 51 THEN 'DIFERIDO-51'
               WHEN EA.TIPOSITTRIB = 'F' AND MOD(EA.IDSITTRIB,100) = 60 THEN 'STNORMAL-60'
               WHEN EA.TIPOSITTRIB = 'A' AND MOD(EA.IDSITTRIB,100) = 60 THEN 'STFRONTEIRA-60'
               ELSE 'OUTRO'
           END AS TIPO
    FROM NOTAS_MOVIMENTO NM
    INNER JOIN DBA.ESTOQUE_ANALITICO EA ON EA.IDEMPRESA = NM.IDEMPRESA AND EA.IDPLANILHA = NM.IDPLANILHA
    INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
    LEFT JOIN DBA.ESTOQUE_ANALITICO_FISCAL EAF ON EAF.IDEMPRESA = EA.IDEMPRESA AND EAF.IDPLANILHA = EA.IDPLANILHA AND EAF.NUMSEQUENCIA = EA.NUMSEQUENCIA
    WHERE OI.FLAGMOVSALDOPRO = 'T' AND EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
),
NOTA_RESUMO AS (
    SELECT IDEMPRESA, IDPLANILHA, IDCLIFOR, MAX(TIPO) AS TIPO,
           COUNT(DISTINCT TIPO) AS QTDTIPOS,
           MAX(CASE WHEN FONTE='XML' THEN 1 ELSE 0 END) AS TEM_XML,
           MAX(CASE WHEN FONTE='CAD' THEN 1 ELSE 0 END) AS TEM_CAD
    FROM ITENS
    GROUP BY IDEMPRESA, IDPLANILHA, IDCLIFOR
),
NOTAS_MONOTIPO AS (
    SELECT * FROM NOTA_RESUMO WHERE QTDTIPOS = 1
),
FORNECEDOR_RESUMO AS (
    SELECT IDCLIFOR, COUNT(DISTINCT TIPO) AS QTDTIPOS,
           MAX(TEM_XML) AS TEM_XML, MAX(TEM_CAD) AS TEM_CAD,
           MAX(CASE WHEN TIPO IN ('ISENTO-40','NAOTRIBUTADO-41','SUSPENSO-50','OUTROS-90') THEN 1 ELSE 0 END) AS TEM_GRUPO_A,
           MAX(CASE WHEN TIPO NOT IN ('ISENTO-40','NAOTRIBUTADO-41','SUSPENSO-50','OUTROS-90') THEN 1 ELSE 0 END) AS TEM_FORA_GRUPO_A,
           MAX(CASE WHEN TIPO IN ('TRIBUTADO-00','REDUCAO-20','DIFERIDO-51') THEN 1 ELSE 0 END) AS TEM_GRUPO_B,
           MAX(CASE WHEN TIPO NOT IN ('TRIBUTADO-00','REDUCAO-20','DIFERIDO-51') THEN 1 ELSE 0 END) AS TEM_FORA_GRUPO_B
    FROM NOTAS_MONOTIPO
    GROUP BY IDCLIFOR
),
FORNECEDOR_TIPO AS (
    SELECT IDCLIFOR, TIPO, COUNT(*) AS QTDNOTASTIPO,
           SUM(TEM_XML) AS XML, SUM(TEM_CAD) AS CAD
    FROM NOTAS_MONOTIPO
    GROUP BY IDCLIFOR, TIPO
),
FORNECEDORES AS (
    SELECT FR.*, CF.IDATIVIDADE, TA.DESCRTIPOATIVIDADE AS ATIVIDADE,
           COALESCE(ATV.FLAGPRODUTORRURAL,'F') AS PRODUTOR,
           CASE WHEN CF.TIPOREGIMETRIBFEDERAL='S' THEN 'S' ELSE 'N' END AS SIMPLESNACIONAL
    FROM FORNECEDOR_RESUMO FR
    INNER JOIN DBA.CLIENTE_FORNECEDOR CF ON CF.IDCLIFOR = FR.IDCLIFOR
    LEFT JOIN DBA.ATIVIDADE ATV ON ATV.IDATIVIDADE = CF.IDATIVIDADE
    LEFT JOIN DBA.ATIVIDADE_TIPO_ATIVIDADE ATA ON ATA.IDATIVIDADE = CF.IDATIVIDADE AND ATA.FLAGPADRAO='T'
    LEFT JOIN DBA.TIPO_ATIVIDADE TA ON TA.IDTIPOATIVIDADE = ATA.IDTIPOATIVIDADE
),
CLASSIFICACAO AS (
    SELECT 1 AS CONSULTA, * FROM FORNECEDORES WHERE PRODUTOR='T' AND TEM_CAD=1 AND TEM_XML=0 AND QTDTIPOS=1 AND TEM_GRUPO_A=1 AND TEM_FORA_GRUPO_A=0
    UNION ALL SELECT 2,* FROM FORNECEDORES WHERE PRODUTOR='T' AND TEM_CAD=1 AND TEM_XML=0 AND QTDTIPOS>1 AND TEM_GRUPO_A=1 AND TEM_FORA_GRUPO_A=0
    UNION ALL SELECT 3,* FROM FORNECEDORES WHERE PRODUTOR<>'T' AND TEM_CAD=1 AND TEM_XML=0 AND QTDTIPOS=1 AND TEM_GRUPO_A=1 AND TEM_FORA_GRUPO_A=0
    UNION ALL SELECT 4,* FROM FORNECEDORES WHERE PRODUTOR<>'T' AND TEM_CAD=1 AND TEM_XML=0 AND QTDTIPOS>1 AND TEM_GRUPO_A=1 AND TEM_FORA_GRUPO_A=0
    UNION ALL SELECT 5,* FROM FORNECEDORES WHERE TEM_CAD=1 AND TEM_XML=0 AND QTDTIPOS=1 AND TEM_FORA_GRUPO_A=1
    UNION ALL SELECT 6,* FROM FORNECEDORES WHERE TEM_CAD=1 AND TEM_XML=0 AND QTDTIPOS>1 AND NOT (TEM_GRUPO_A=1 AND TEM_FORA_GRUPO_A=0)
    UNION ALL SELECT 7,* FROM FORNECEDORES WHERE TEM_XML=1 AND TEM_CAD=0 AND QTDTIPOS=1 AND TEM_GRUPO_A=1 AND TEM_FORA_GRUPO_A=0
    UNION ALL SELECT 8,* FROM FORNECEDORES WHERE TEM_XML=1 AND TEM_CAD=0 AND QTDTIPOS>1 AND TEM_GRUPO_A=1 AND TEM_FORA_GRUPO_A=0
    UNION ALL SELECT 9,* FROM FORNECEDORES WHERE TEM_XML=1 AND TEM_CAD=0 AND QTDTIPOS=1 AND TEM_FORA_GRUPO_A=1
    UNION ALL SELECT 10,* FROM FORNECEDORES WHERE TEM_XML=1 AND TEM_CAD=0 AND QTDTIPOS>1 AND NOT (TEM_GRUPO_A=1 AND TEM_FORA_GRUPO_A=0)
    UNION ALL SELECT 11,* FROM FORNECEDORES WHERE TEM_XML=1 AND TEM_CAD=1 AND QTDTIPOS=1
    UNION ALL SELECT 12,* FROM FORNECEDORES WHERE TEM_XML=1 AND TEM_CAD=1 AND QTDTIPOS>1
    UNION ALL SELECT 13,* FROM FORNECEDORES WHERE SIMPLESNACIONAL='S' AND TEM_CAD=1 AND TEM_XML=0 AND QTDTIPOS=1 AND TEM_GRUPO_B=1 AND TEM_FORA_GRUPO_B=0
    UNION ALL SELECT 14,* FROM FORNECEDORES WHERE SIMPLESNACIONAL='S' AND TEM_CAD=1 AND TEM_XML=0 AND QTDTIPOS>1 AND TEM_GRUPO_B=1 AND TEM_FORA_GRUPO_B=0
    UNION ALL SELECT 15,* FROM FORNECEDORES WHERE SIMPLESNACIONAL='N' AND TEM_CAD=1 AND TEM_XML=0 AND QTDTIPOS=1 AND TEM_GRUPO_B=1 AND TEM_FORA_GRUPO_B=0
    UNION ALL SELECT 16,* FROM FORNECEDORES WHERE SIMPLESNACIONAL='N' AND TEM_CAD=1 AND TEM_XML=0 AND QTDTIPOS>1 AND TEM_GRUPO_B=1 AND TEM_FORA_GRUPO_B=0
)
SELECT C.CONSULTA, C.IDCLIFOR, C.IDATIVIDADE, C.ATIVIDADE, C.PRODUTOR,
       FT.TIPO, FT.QTDNOTASTIPO, FT.XML, FT.CAD
FROM CLASSIFICACAO C
INNER JOIN FORNECEDOR_TIPO FT ON FT.IDCLIFOR=C.IDCLIFOR;

-- Cada bloco abaixo apresenta as colunas solicitadas para a consulta numerada.
-- Execute somente o bloco desejado depois da PREPARACAO.
SELECT IDCLIFOR,IDATIVIDADE,ATIVIDADE,PRODUTOR,TIPO,QTDNOTASTIPO,XML,CAD,DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD" FROM SESSION.MAPEAMENTO_FORNECEDOR_MONOTIPO WHERE CONSULTA=1 ORDER BY IDCLIFOR,TIPO;
SELECT IDCLIFOR,IDATIVIDADE,ATIVIDADE,PRODUTOR,TIPO,QTDNOTASTIPO,XML,CAD,DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD" FROM SESSION.MAPEAMENTO_FORNECEDOR_MONOTIPO WHERE CONSULTA=2 ORDER BY IDCLIFOR,TIPO;
SELECT IDCLIFOR,IDATIVIDADE,ATIVIDADE,PRODUTOR,TIPO,QTDNOTASTIPO,XML,CAD,DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD" FROM SESSION.MAPEAMENTO_FORNECEDOR_MONOTIPO WHERE CONSULTA=3 ORDER BY IDCLIFOR,TIPO;
SELECT IDCLIFOR,IDATIVIDADE,ATIVIDADE,PRODUTOR,TIPO,QTDNOTASTIPO,XML,CAD,DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD" FROM SESSION.MAPEAMENTO_FORNECEDOR_MONOTIPO WHERE CONSULTA=4 ORDER BY IDCLIFOR,TIPO;
SELECT IDCLIFOR,IDATIVIDADE,ATIVIDADE,PRODUTOR,TIPO,QTDNOTASTIPO,XML,CAD,DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD" FROM SESSION.MAPEAMENTO_FORNECEDOR_MONOTIPO WHERE CONSULTA=5 ORDER BY IDCLIFOR,TIPO;
SELECT IDCLIFOR,IDATIVIDADE,ATIVIDADE,PRODUTOR,TIPO,QTDNOTASTIPO,XML,CAD,DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD" FROM SESSION.MAPEAMENTO_FORNECEDOR_MONOTIPO WHERE CONSULTA=6 ORDER BY IDCLIFOR,TIPO;
SELECT IDCLIFOR,IDATIVIDADE,ATIVIDADE,PRODUTOR,TIPO,QTDNOTASTIPO,XML,CAD,DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD" FROM SESSION.MAPEAMENTO_FORNECEDOR_MONOTIPO WHERE CONSULTA=7 ORDER BY IDCLIFOR,TIPO;
SELECT IDCLIFOR,IDATIVIDADE,ATIVIDADE,PRODUTOR,TIPO,QTDNOTASTIPO,XML,CAD,DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD" FROM SESSION.MAPEAMENTO_FORNECEDOR_MONOTIPO WHERE CONSULTA=8 ORDER BY IDCLIFOR,TIPO;
SELECT IDCLIFOR,IDATIVIDADE,ATIVIDADE,PRODUTOR,TIPO,QTDNOTASTIPO,XML,CAD,DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD" FROM SESSION.MAPEAMENTO_FORNECEDOR_MONOTIPO WHERE CONSULTA=9 ORDER BY IDCLIFOR,TIPO;
SELECT IDCLIFOR,IDATIVIDADE,ATIVIDADE,PRODUTOR,TIPO,QTDNOTASTIPO,XML,CAD,DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD" FROM SESSION.MAPEAMENTO_FORNECEDOR_MONOTIPO WHERE CONSULTA=10 ORDER BY IDCLIFOR,TIPO;
SELECT IDCLIFOR,IDATIVIDADE,ATIVIDADE,PRODUTOR,TIPO,QTDNOTASTIPO,XML,CAD,DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD" FROM SESSION.MAPEAMENTO_FORNECEDOR_MONOTIPO WHERE CONSULTA=11 ORDER BY IDCLIFOR,TIPO;
SELECT IDCLIFOR,IDATIVIDADE,ATIVIDADE,PRODUTOR,TIPO,QTDNOTASTIPO,XML,CAD,DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD" FROM SESSION.MAPEAMENTO_FORNECEDOR_MONOTIPO WHERE CONSULTA=12 ORDER BY IDCLIFOR,TIPO;
SELECT IDCLIFOR,IDATIVIDADE,ATIVIDADE,PRODUTOR,TIPO,QTDNOTASTIPO,XML,CAD,DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD" FROM SESSION.MAPEAMENTO_FORNECEDOR_MONOTIPO WHERE CONSULTA=13 ORDER BY IDCLIFOR,TIPO;
SELECT IDCLIFOR,IDATIVIDADE,ATIVIDADE,PRODUTOR,TIPO,QTDNOTASTIPO,XML,CAD,DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD" FROM SESSION.MAPEAMENTO_FORNECEDOR_MONOTIPO WHERE CONSULTA=14 ORDER BY IDCLIFOR,TIPO;
SELECT IDCLIFOR,IDATIVIDADE,ATIVIDADE,PRODUTOR,TIPO,QTDNOTASTIPO,XML,CAD,DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD" FROM SESSION.MAPEAMENTO_FORNECEDOR_MONOTIPO WHERE CONSULTA=15 ORDER BY IDCLIFOR,TIPO;
SELECT IDCLIFOR,IDATIVIDADE,ATIVIDADE,PRODUTOR,TIPO,QTDNOTASTIPO,XML,CAD,DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD" FROM SESSION.MAPEAMENTO_FORNECEDOR_MONOTIPO WHERE CONSULTA=16 ORDER BY IDCLIFOR,TIPO;
