-- DETALHAMENTO POR NOTA DAS CONSULTAS APROVADAS.
-- Execute primeiro a PREPARACAO de:
-- CONSULTAS_01_A_16_POR_FORNECEDOR_NOTAS_MONOTIPO.sql
-- e depois esta SQL, na mesma sessao DB2 e com os mesmos parametros.

WITH
NOTAS_MOVIMENTO AS (
    SELECT EA.IDEMPRESA, EA.IDPLANILHA, N.IDCLIFOR
    FROM DBA.ESTOQUE_ANALITICO EA
    INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO=EA.IDOPERACAO
    INNER JOIN DBA.NOTAS N ON N.IDEMPRESA=EA.IDEMPRESA AND N.IDPLANILHA=EA.IDPLANILHA
    WHERE EA.IDOPERACAO<1000 AND OI.TIPOMOVIMENTO='C' AND OI.FLAGMOVSALDOPRO='T'
      AND N.FLAGMOVFISCAL='T' AND N.FLAGNOTACANCEL='F'
      AND EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
    GROUP BY EA.IDEMPRESA, EA.IDPLANILHA, N.IDCLIFOR
),
ITENS_TIPO AS (
    SELECT NM.IDEMPRESA,NM.IDPLANILHA,NM.IDCLIFOR,
           CASE
             WHEN MOD(EA.IDSITTRIB,100)=40 THEN 'ISENTO-40'
             WHEN MOD(EA.IDSITTRIB,100)=41 THEN 'NAOTRIBUTADO-41'
             WHEN MOD(EA.IDSITTRIB,100)=50 THEN 'SUSPENSO-50'
             WHEN MOD(EA.IDSITTRIB,100)=90 THEN 'OUTROS-90'
             WHEN MOD(EA.IDSITTRIB,100)=0 THEN 'TRIBUTADO-00'
             WHEN MOD(EA.IDSITTRIB,100)=20 THEN 'REDUCAO-20'
             WHEN MOD(EA.IDSITTRIB,100)=51 THEN 'DIFERIDO-51'
             WHEN EA.TIPOSITTRIB='F' AND MOD(EA.IDSITTRIB,100)=60 THEN 'STNORMAL-60'
             WHEN EA.TIPOSITTRIB='A' AND MOD(EA.IDSITTRIB,100)=60 THEN 'STFRONTEIRA-60'
             ELSE 'OUTRO' END AS TIPO
    FROM NOTAS_MOVIMENTO NM
    INNER JOIN DBA.ESTOQUE_ANALITICO EA ON EA.IDEMPRESA=NM.IDEMPRESA AND EA.IDPLANILHA=NM.IDPLANILHA
    INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO=EA.IDOPERACAO
    WHERE OI.FLAGMOVSALDOPRO='T' AND EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
),
NOTAS_MONOTIPO AS (
    SELECT IDEMPRESA,IDPLANILHA,IDCLIFOR,MAX(TIPO) AS TIPO
    FROM ITENS_TIPO GROUP BY IDEMPRESA,IDPLANILHA,IDCLIFOR
    HAVING COUNT(DISTINCT TIPO)=1
),
VALORES_NOTA AS (
    SELECT NM.IDEMPRESA,NM.IDPLANILHA,NM.IDCLIFOR,DATE(N.DTMOVIMENTO) AS DATA,N.NUMNOTA,N.SERIENOTA,
           LISTAGG(DISTINCT VARCHAR(EA.IDCSTPISCOFINS), ', ') WITHIN GROUP(ORDER BY VARCHAR(EA.IDCSTPISCOFINS)) AS IDCSTPISCOFINS,
           SUM(COALESCE(EA.VALIPI,0)) AS VALIPI,SUM(COALESCE(EA.VALIPIFRETE,0)) AS VALIPIFRETE,
           SUM(COALESCE(EA.VALIPIACESSORIOS,0)) AS VALIPIACESSORIOS,SUM(COALESCE(EA.VALIPIEMBALAGEM,0)) AS VALIPIEMBALAGEM,
           SUM(COALESCE(EA.VALADICIONAIS,0)) AS VALADICIONAIS,SUM(COALESCE(EA.VALFRETE,0)) AS VALFRETE,
           SUM(COALESCE(EA.VALACESSORIOS,0)) AS VALACESSORIOS,SUM(COALESCE(EA.VALDESCONTOPRO,0)) AS VALDESCONTOPRO,
           SUM(COALESCE(EA.VALDESCONTOFINANCEIRO,0)) AS VALDESCONTOFINANCEIRO,
           SUM(COALESCE(EA.VALACRESCIMOFINANCEIRO,0)) AS VALACRESCIMOFINANCEIRO,
           SUM(COALESCE(EA.VALACRESCIMOPRO,0)) AS VALACRESCIMOPRO
    FROM NOTAS_MOVIMENTO NM
    INNER JOIN DBA.NOTAS N ON N.IDEMPRESA=NM.IDEMPRESA AND N.IDPLANILHA=NM.IDPLANILHA
    INNER JOIN DBA.ESTOQUE_ANALITICO EA ON EA.IDEMPRESA=NM.IDEMPRESA AND EA.IDPLANILHA=NM.IDPLANILHA
    INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO=EA.IDOPERACAO
    WHERE OI.FLAGMOVSALDOPRO='T' AND EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
    GROUP BY NM.IDEMPRESA,NM.IDPLANILHA,NM.IDCLIFOR,DATE(N.DTMOVIMENTO),N.NUMNOTA,N.SERIENOTA
),
VALORES_XML AS (
    SELECT NFET.IDEMPRESA,NFET.IDPLANILHA,SUM(COALESCE(XP.VDESC,0)) AS XML_VDESC,
           SUM(COALESCE(XP.VFRETE,0)) AS XML_VFRETE,SUM(COALESCE(XP.VSEG,0)) AS XML_VSEG,
           SUM(COALESCE(XP.VOUTRO,0)) AS XML_VOUTRO,SUM(COALESCE(XPI.VIPI,0)) AS XML_VIPI,
           SUM(COALESCE(XICMS.VICMSST,0)) AS XML_VICMSST,
           LISTAGG(DISTINCT VARCHAR(XICMS.PMVAST), ', ') WITHIN GROUP(ORDER BY VARCHAR(XICMS.PMVAST)) AS PMVAST
    FROM NOTAS_MOVIMENTO NM
    INNER JOIN DBA.NOTA_FISCAL_ELETRONICA_TERCEIROS NFET ON NFET.IDEMPRESA=NM.IDEMPRESA AND NFET.IDPLANILHA=NM.IDPLANILHA
    INNER JOIN NFE.XML_IDENTIFICACAO XI ON XI.CHNFE=NFET.CHAVENFE
    LEFT JOIN NFE.XML_PRODUTO XP ON XP.IDNFE=XI.IDNFE
    LEFT JOIN NFE.XML_PRODUTO_IPI XPI ON XPI.IDPRODUTONFE=XP.IDPRODUTONFE
    LEFT JOIN NFE.XML_PRODUTO_ICMS XICMS ON XICMS.IDPRODUTONFE=XP.IDPRODUTONFE
    GROUP BY NFET.IDEMPRESA,NFET.IDPLANILHA
)
SELECT M.CONSULTA,VN.DATA,VN.IDEMPRESA,VN.IDPLANILHA,VN.IDCLIFOR,VN.NUMNOTA,VN.SERIENOTA,VN.IDCSTPISCOFINS,
       M.IDATIVIDADE,M.ATIVIDADE,M.PRODUTOR,
       CASE WHEN CF.TIPOREGIMETRIBFEDERAL='S' THEN 'S' ELSE 'N' END AS SIMPLESNACIONAL,M.TIPO,
       VN.VALIPI,VN.VALIPIFRETE,VN.VALIPIACESSORIOS,VN.VALIPIEMBALAGEM,VN.VALADICIONAIS,VN.VALFRETE,
       VN.VALACESSORIOS,VN.VALDESCONTOPRO,VN.VALDESCONTOFINANCEIRO,VN.VALACRESCIMOFINANCEIRO,VN.VALACRESCIMOPRO,
       COALESCE(VX.XML_VDESC,0) AS XML_VDESC,COALESCE(VX.XML_VFRETE,0) AS XML_VFRETE,
       COALESCE(VX.XML_VSEG,0) AS XML_VSEG,COALESCE(VX.XML_VOUTRO,0) AS XML_VOUTRO,
       COALESCE(VX.XML_VIPI,0) AS XML_VIPI,COALESCE(VX.XML_VICMSST,0) AS XML_VICMSST,COALESCE(VX.PMVAST,'') AS PMVAST
FROM NOTAS_MONOTIPO NM
INNER JOIN SESSION.MAPEAMENTO_FORNECEDOR_MONOTIPO M ON M.IDCLIFOR=NM.IDCLIFOR AND M.TIPO=NM.TIPO
INNER JOIN VALORES_NOTA VN ON VN.IDEMPRESA=NM.IDEMPRESA AND VN.IDPLANILHA=NM.IDPLANILHA
INNER JOIN DBA.CLIENTE_FORNECEDOR CF ON CF.IDCLIFOR=M.IDCLIFOR
LEFT JOIN VALORES_XML VX ON VX.IDEMPRESA=VN.IDEMPRESA AND VX.IDPLANILHA=VN.IDPLANILHA
ORDER BY M.CONSULTA,VN.DATA,VN.IDEMPRESA,VN.IDPLANILHA,M.IDCLIFOR,M.TIPO;

-- Para ver somente uma consulta, acrescente antes do ORDER BY:
-- WHERE M.CONSULTA = 1
