-- RESUMO - NOTAS COM APENAS UM TIPO DE TRIBUTACAO NA NOTA TODA, SEM AGRUPAMENTOS
WITH TIPOS AS (
        SELECT 'ISENTO-40' AS TIPO FROM SYSIBM.SYSDUMMY1
        UNION ALL SELECT 'NAOTRIBUTADO-41' FROM SYSIBM.SYSDUMMY1
        UNION ALL SELECT 'OUTROS-90' FROM SYSIBM.SYSDUMMY1
        UNION ALL SELECT 'REDUCAO-20' FROM SYSIBM.SYSDUMMY1
        UNION ALL SELECT 'STNORMAL-60' FROM SYSIBM.SYSDUMMY1
        UNION ALL SELECT 'STFRONTEIRA-60' FROM SYSIBM.SYSDUMMY1
        UNION ALL SELECT 'SUSPENSO-50' FROM SYSIBM.SYSDUMMY1
        UNION ALL SELECT 'DIFERIDO-51' FROM SYSIBM.SYSDUMMY1
        UNION ALL SELECT 'TRIBUTADO-00' FROM SYSIBM.SYSDUMMY1
),
NOTAS_MOVIMENTO AS (
        SELECT EA.IDEMPRESA, EA.IDPLANILHA
        FROM DBA.ESTOQUE_ANALITICO EA
        INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
        INNER JOIN DBA.NOTAS N ON N.IDEMPRESA = EA.IDEMPRESA AND N.IDPLANILHA = EA.IDPLANILHA
        WHERE EA.IDOPERACAO < 1000
                AND OI.TIPOMOVIMENTO = 'C'
                AND OI.FLAGMOVSALDOPRO = 'T'
                AND N.FLAGMOVFISCAL = 'T'
                AND N.FLAGNOTACANCEL = 'F'
                AND EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
        GROUP BY EA.IDEMPRESA, EA.IDPLANILHA
),
ITENS_TRIBUTACAO AS (
        SELECT NM.IDEMPRESA, NM.IDPLANILHA,
                CASE
                        WHEN EA.IDSITTRIB IN (40,140,240,340,440,540,640,740,840) THEN 'ISENTO-40'
                        WHEN EA.IDSITTRIB IN (41,141,241,341,441,541,641,741,841) THEN 'NAOTRIBUTADO-41'
                        WHEN EA.IDSITTRIB IN (50,150,250,350,450,550,650,750,850) THEN 'SUSPENSO-50'
                        WHEN EA.IDSITTRIB IN (90,190,290,390,490,590,690,790,890) THEN 'OUTROS-90'
                        WHEN EA.IDSITTRIB IN (0,100,200,300,400,500,600,700,800) THEN 'TRIBUTADO-00'
                        WHEN EA.IDSITTRIB IN (20,120,220,320,420,520,620,720,820) THEN 'REDUCAO-20'
                        WHEN EA.IDSITTRIB IN (51,151,251,351,451,551,651,751,851) THEN 'DIFERIDO-51'
                        WHEN EA.TIPOSITTRIB = 'F' AND EA.IDSITTRIB IN (60,160,260,360,460,560,660,760,860) THEN 'STNORMAL-60'
                        WHEN EA.TIPOSITTRIB = 'A' AND EA.IDSITTRIB IN (60,160,260,360,460,560,660,760,860) THEN 'STFRONTEIRA-60'
                END AS TIPO
        FROM NOTAS_MOVIMENTO NM
        INNER JOIN DBA.ESTOQUE_ANALITICO EA ON EA.IDEMPRESA = NM.IDEMPRESA AND EA.IDPLANILHA = NM.IDPLANILHA
        INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
        WHERE OI.FLAGMOVSALDOPRO = 'T'
                AND EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
),
TIPO_NOTA AS (
        SELECT IDEMPRESA, IDPLANILHA, MAX(TIPO) AS TIPO
        FROM ITENS_TRIBUTACAO
        GROUP BY IDEMPRESA, IDPLANILHA
        HAVING COUNT(DISTINCT COALESCE(TIPO, 'OUTRO')) = 1
                AND MAX(TIPO) IS NOT NULL
),
APURACAO AS (
        SELECT TIPO, COUNT(*) AS QTDTIPO
        FROM TIPO_NOTA
        GROUP BY TIPO
),
TOTAL_TIPO AS (
        SELECT COUNT(*) AS QTDTOTALTIPO
        FROM TIPO_NOTA
),
NOTAS_TOTAL AS (
        SELECT N.IDEMPRESA, N.IDPLANILHA
        FROM DBA.NOTAS N
        INNER JOIN DBA.NOTAS_ENTRADA_SAIDA NES ON NES.IDEMPRESA = N.IDEMPRESA AND NES.IDPLANILHA = N.IDPLANILHA
        INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = NES.IDOPERACAO
        WHERE NES.IDOPERACAO < 1000
                AND OI.TIPOMOVIMENTO = 'C'
                AND OI.FLAGMOVSALDOPRO = 'T'
                AND N.FLAGMOVFISCAL = 'T'
                AND N.FLAGNOTACANCEL = 'F'
                AND N.DTMOVIMENTO BETWEEN DBA.DTINI(:RA_DTINI) AND DBA.DTFIM(:RA_DTFIM)
        GROUP BY N.IDEMPRESA, N.IDPLANILHA
),
TOTAL_NOTAS AS (
        SELECT COUNT(*) AS QTDTOTAL
        FROM NOTAS_TOTAL
)
SELECT
        T.TIPO,
        COALESCE(A.QTDTIPO, 0) AS QTDTIPO,
        TT.QTDTOTALTIPO,
        DECIMAL((CAST(COALESCE(A.QTDTIPO, 0) AS DECIMAL(15,6)) / NULLIF(CAST(TT.QTDTOTALTIPO AS DECIMAL(15,6)), 0)) * 100, 15, 2) AS "% TIPO",
        TN.QTDTOTAL,
        DECIMAL((CAST(COALESCE(A.QTDTIPO, 0) AS DECIMAL(15,6)) / NULLIF(CAST(TN.QTDTOTAL AS DECIMAL(15,6)), 0)) * 100, 15, 2) AS "% TOTAL"
FROM TIPOS T
LEFT JOIN APURACAO A ON A.TIPO = T.TIPO
CROSS JOIN TOTAL_TIPO TT
CROSS JOIN TOTAL_NOTAS TN
ORDER BY
        CASE T.TIPO
                WHEN 'ISENTO-40' THEN 1
                WHEN 'NAOTRIBUTADO-41' THEN 2
                WHEN 'OUTROS-90' THEN 3
                WHEN 'REDUCAO-20' THEN 4
                WHEN 'STNORMAL-60' THEN 5
                WHEN 'STFRONTEIRA-60' THEN 6
                WHEN 'SUSPENSO-50' THEN 7
                WHEN 'DIFERIDO-51' THEN 8
                WHEN 'TRIBUTADO-00' THEN 9
        END;