-- CISS-183841 | Rollback. Executar somente se o deploy precisar ser revertido.
-- Nao restaura valores anteriores de DTALTERACAO, pois a coluna e removida.
-- Executar com: db2 -td@ -vf 03_rollback_cmv_dtalteracao.sql
CONNECT TO NOPNEW01 USER dba USING "a9d9p8.E10"@
DROP TRIGGER DBA.TR_ESTSIN_CMV_AD@
DROP TRIGGER DBA.TR_ESTSIN_DTALTERACAO_BU@
DROP TRIGGER DBA.TR_ESTSIN_DTALTERACAO_BI@
DROP INDEX DBA.IX_ESTSIN_DTALT_EMP_DT@
ALTER TABLE DBA.ESTOQUE_SINTETICO DROP COLUMN DTALTERACAO@
RUNSTATS ON TABLE DBA.ESTOQUE_SINTETICO AND INDEXES ALL@
CONNECT RESET@
