SELECT OPERATOR_ID,
       PREDICATE_ID,
       HOW_APPLIED,
       WHEN_EVALUATED,
       RELOP_TYPE,
       DECIMAL(FILTER_FACTOR, 18, 12) AS FILTER_FACTOR,
       SUBSTR(PREDICATE_TEXT, 1, 500) AS PREDICATE_TEXT
FROM DBA.EXPLAIN_PREDICATE
WHERE EXPLAIN_TIME = TIMESTAMP('2026-08-18-13.37.50.588654')
  AND SOURCE_NAME = 'SQLC2O27'
  AND STMTNO = 1
  AND SECTNO = 201
ORDER BY OPERATOR_ID, PREDICATE_ID
@
