SELECT EXPLAIN_TIME, SOURCE_NAME, EXPLAIN_LEVEL, STMTNO, SECTNO, TOTAL_COST,
       SUBSTR(STATEMENT_TEXT, 1, 120) AS SQL_INICIO
FROM DBA.EXPLAIN_STATEMENT
WHERE STATEMENT_TEXT LIKE 'SELECT TMP.IDEMPRESA%'
ORDER BY EXPLAIN_TIME DESC
FETCH FIRST 3 ROWS ONLY
@

SELECT COLNO, COLNAME, TYPENAME, LENGTH
FROM SYSCAT.COLUMNS
WHERE TABSCHEMA = 'DBA'
  AND TABNAME = 'EXPLAIN_OPERATOR'
ORDER BY COLNO
@

SELECT COLNO, COLNAME, TYPENAME, LENGTH
FROM SYSCAT.COLUMNS
WHERE TABSCHEMA = 'DBA'
  AND TABNAME = 'EXPLAIN_OBJECT'
ORDER BY COLNO
@

SELECT COLNO, COLNAME, TYPENAME, LENGTH
FROM SYSCAT.COLUMNS
WHERE TABSCHEMA = 'DBA'
  AND TABNAME = 'EXPLAIN_STREAM'
ORDER BY COLNO
@
