CREATE TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES (
	IDEMPRESA                               INTEGER NOT NULL,
	FLAGMOSTRALIMITE                        CHAR(1) DEFAULT NULL,
	FLAGMOSTRAVALORACUMULADO                CHAR(1) DEFAULT NULL,
	FLAGMOSTRASALDODISPONIVEL               CHAR(1) DEFAULT NULL,
	FLAGIMPRESCHQVISTA                      CHAR(1) DEFAULT 'F',
	FLAGIMPRIMECOMPROVPROMOCAO              CHAR(1) DEFAULT 'F',
	FLAGIMPRIMEPEDIDO                       CHAR(1) DEFAULT 'F',
	FLAGIMPNOMEOPERADOR                     CHAR(1) DEFAULT NULL,
	FLAGIMPDADOSCLI                         CHAR(1) DEFAULT NULL,
	FLAGIMPRIMERELATORIOCANCELAMENTOS       CHAR(1) DEFAULT NULL,
	IMPRESSAOVALORPRODUTO                   VARCHAR(5) DEFAULT 'VLA',
	FLAGIMPRIMIRNOMEFANTASIA                CHAR(1) DEFAULT 'F',
	FLAGIMPRIMELIMITECREDITO                CHAR(1) DEFAULT 'F',
	FLAGIMPRIMELIMITEPRAZO                  CHAR(1) DEFAULT 'F',
	FLAGIMPRIMEPONTOSCLIENTE                CHAR(1) DEFAULT 'F',
	FLAGIMPRIMIRVALORLIQUIDO                CHAR(1) DEFAULT 'F',
	FLAGIMPRIMIRUMAVIA                      CHAR(1) DEFAULT 'F',
	FLAGDANFEIMPRIMECOMPROVANTETEF          CHAR(1) DEFAULT 'F',
	FLAGIMPCONVENIOREL                      CHAR(1) DEFAULT 'F',
	FLAGIMPRIMIRVIAUNICATEF                 CHAR(1) DEFAULT 'F',
	FLAGIMPRIMIRPRODUTIVIDADEFECHTO         CHAR(1) DEFAULT 'F',
	FLAGIMPRIMEOBSCLIENTENFE                CHAR(1) DEFAULT 'F',
	FLAGIMPRIMEQRCODEENTREGADOMICILIO       CHAR(1) DEFAULT 'F',
	FLAGIMPRIMIRBRUTOEDESCONTO              CHAR(1) DEFAULT NULL,
	FLAGIMPRIMEINFOCLIRESCOMPPRAZO          CHAR(1) DEFAULT 'F',
	FLAGIMPRIMIRNOMEFANTASIACLIENTE         CHAR(1) DEFAULT NULL,
	FLAGIMPRIMESALDOCREDITOAPROPRIACAO      CHAR(1) DEFAULT NULL,
	FLAGIMPRIMECLIENTENOTANAOIDENTIFICADA   CHAR(1) DEFAULT 'F',
	FLAGIMPRESSAODESCONTONIVELITEM          CHAR(1) DEFAULT 'T',
	FLAGMASCARACPF                          CHAR(1) DEFAULT 'F',
	FLAGIMPRIMIRASSINATURAOPERSUPERSUPSAN   CHAR(1) DEFAULT 'F',
	FLAGIMPRIMIRCONFERENCIAPRODUTO          CHAR(1) DEFAULT 'F',
	FLAGIMPRIMIRDESCONTOAGRUPADO            CHAR(1) DEFAULT 'F',
	FLAGIMPRIMIRCUPOMPOS                    CHAR(1) DEFAULT 'F',
	FLAGIMPRESSAODETALHADAAPROPRIACAO       CHAR(1) DEFAULT 'F',
	FLAGIMPRNOMECPFCOMPROVANTES             CHAR(1) DEFAULT 'F',
	FLAGIMPRDADOSCONVENIOSEMTESTARLIMITE    CHAR(1) DEFAULT 'F',
	FLAGIMPRIMIRVALORBOLETOSAGRUPADO        CHAR(1) DEFAULT 'F',
	DTALTERACAO                             TIMESTAMP
);
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT PK_CONFIGFRCAIXAIMPRESSOES PRIMARY KEY (IDEMPRESA)
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT FK_CONFIGFRCAIXAIMPRESSOES_EMP FOREIGN KEY (IDEMPRESA) REFERENCES DBA.EMPRESA (IDEMPRESA)
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGMOSTRALIMITE CHECK (FLAGMOSTRALIMITE IS NULL OR FLAGMOSTRALIMITE IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGMOSTRAVALORACUMULADO CHECK (FLAGMOSTRAVALORACUMULADO IS NULL OR FLAGMOSTRAVALORACUMULADO IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGMOSTRASALDODISPONIVEL CHECK (FLAGMOSTRASALDODISPONIVEL IS NULL OR FLAGMOSTRASALDODISPONIVEL IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPRESCHQVISTA CHECK (FLAGIMPRESCHQVISTA IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPRIMECOMPROVPROMOCAO CHECK (FLAGIMPRIMECOMPROVPROMOCAO IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPRIMEPEDIDO CHECK (FLAGIMPRIMEPEDIDO IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPNOMEOPERADOR CHECK (FLAGIMPNOMEOPERADOR IS NULL OR FLAGIMPNOMEOPERADOR IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPDADOSCLI CHECK (FLAGIMPDADOSCLI IS NULL OR FLAGIMPDADOSCLI IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPRELATORIOCANCELAMENTOS CHECK (FLAGIMPRIMERELATORIOCANCELAMENTOS IS NULL OR FLAGIMPRIMERELATORIOCANCELAMENTOS IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPRIMIRNOMEFANTASIA CHECK (FLAGIMPRIMIRNOMEFANTASIA IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPRIMELIMITECREDITO CHECK (FLAGIMPRIMELIMITECREDITO IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPRIMELIMITEPRAZO CHECK (FLAGIMPRIMELIMITEPRAZO IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPRIMEPONTOSCLIENTE CHECK (FLAGIMPRIMEPONTOSCLIENTE IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPRIMIRVALORLIQUIDO CHECK (FLAGIMPRIMIRVALORLIQUIDO IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPRIMIRUMAVIA CHECK (FLAGIMPRIMIRUMAVIA IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGDANFEIMPRIMECOMPROVTEF CHECK (FLAGDANFEIMPRIMECOMPROVANTETEF IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPCONVENIOREL CHECK (FLAGIMPCONVENIOREL IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPRIMIRVIAUNICATEF CHECK (FLAGIMPRIMIRVIAUNICATEF IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPRPRODUTIVIDADEFECHTO CHECK (FLAGIMPRIMIRPRODUTIVIDADEFECHTO IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPRIMEOBSCLIENTENFE CHECK (FLAGIMPRIMEOBSCLIENTENFE IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPQRCODEENTREGADOM CHECK (FLAGIMPRIMEQRCODEENTREGADOMICILIO IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPRIMIRBRUTOEDESCONTO CHECK (FLAGIMPRIMIRBRUTOEDESCONTO IS NULL OR FLAGIMPRIMIRBRUTOEDESCONTO IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPRINFOCLIRESCOMPPRAZO CHECK (FLAGIMPRIMEINFOCLIRESCOMPPRAZO IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPRNOMEFANTASIACLI CHECK (FLAGIMPRIMIRNOMEFANTASIACLIENTE IS NULL OR FLAGIMPRIMIRNOMEFANTASIACLIENTE IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPRSALDOCREDAPROP CHECK (FLAGIMPRIMESALDOCREDITOAPROPRIACAO IS NULL OR FLAGIMPRIMESALDOCREDITOAPROPRIACAO IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPRCLINOTANAOIDENT CHECK (FLAGIMPRIMECLIENTENOTANAOIDENTIFICADA IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPRDESCNIVELITEM CHECK (FLAGIMPRESSAODESCONTONIVELITEM IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGMASCARACPF CHECK (FLAGMASCARACPF IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPRASSINATURAOPERSUP CHECK (FLAGIMPRIMIRASSINATURAOPERSUPERSUPSAN IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPRCONFERENCIAPROD CHECK (FLAGIMPRIMIRCONFERENCIAPRODUTO IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPRDESCONTOAGRUPADO CHECK (FLAGIMPRIMIRDESCONTOAGRUPADO IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPRIMIRCUPOMPOS CHECK (FLAGIMPRIMIRCUPOMPOS IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPRDETALLADAPROP CHECK (FLAGIMPRESSAODETALHADAAPROPRIACAO IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPRNOMECPFCOMPROV CHECK (FLAGIMPRNOMECPFCOMPROVANTES IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPRDADOSCONVSEMTESTE CHECK (FLAGIMPRDADOSCONVENIOSEMTESTARLIMITE IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES ADD CONSTRAINT CKT_FLAGIMPRVALBOLETOSAGRUP CHECK (FLAGIMPRIMIRVALORBOLETOSAGRUPADO IN ('T','F'))
GO
COMMENT ON TABLE DBA.CONFIG_FRCAIXA_IMPRESSOES IS 'Armazena as configuracoes de impressoes para o frente de caixa'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.IDEMPRESA IS 'Codigo da empresa.'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGMOSTRALIMITE IS 'Indica se deve mostrar limite do cliente na impressao. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGMOSTRAVALORACUMULADO IS 'Indica se deve mostrar o valor acumulado na impressao. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGMOSTRASALDODISPONIVEL IS 'Indica se deve mostrar o saldo disponivel na impressao. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPRESCHQVISTA IS 'Indica se deve imprimir cheque a vista. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPRIMECOMPROVPROMOCAO IS 'Indica se imprime comprovante de promocao. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPRIMEPEDIDO IS 'Indica se imprime o pedido. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPNOMEOPERADOR IS 'Indica se imprime o nome do operador. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPDADOSCLI IS 'Indica se imprime os dados do cliente. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPRIMERELATORIOCANCELAMENTOS IS 'Indica se imprime relatorio de cancelamentos. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.IMPRESSAOVALORPRODUTO IS 'Definicao da forma de impressao do valor do produto.'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPRIMIRNOMEFANTASIA IS 'Indica se imprime o nome fantasia. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPRIMELIMITECREDITO IS 'Indica se imprime limite de credito. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPRIMELIMITEPRAZO IS 'Indica se imprime limite a prazo. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPRIMEPONTOSCLIENTE IS 'Indica se imprime pontos do cliente. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPRIMIRVALORLIQUIDO IS 'Indica se imprime o valor liquido. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPRIMIRUMAVIA IS 'Indica se imprime somente uma via. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGDANFEIMPRIMECOMPROVANTETEF IS 'Indica se o DANFE imprime o comprovante TEF. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPCONVENIOREL IS 'Indica se imprime relatorio de convenio. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPRIMIRVIAUNICATEF IS 'Indica se imprime via unica do TEF. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPRIMIRPRODUTIVIDADEFECHTO IS 'Indica se imprime relatorio de produtividade no fechamento. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPRIMEOBSCLIENTENFE IS 'Indica se imprime a observacao do cliente na NFe. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPRIMEQRCODEENTREGADOMICILIO IS 'Indica se imprime QR Code de entrega em domicilio. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPRIMIRBRUTOEDESCONTO IS 'Indica se imprime valor bruto e desconto. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPRIMEINFOCLIRESCOMPPRAZO IS 'Indica se imprime informacoes do cliente no resumo de compra a prazo. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPRIMIRNOMEFANTASIACLIENTE IS 'Indica se imprime o nome fantasia do cliente. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPRIMESALDOCREDITOAPROPRIACAO IS 'Indica se imprime saldo de credito de apropriacao. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPRIMECLIENTENOTANAOIDENTIFICADA IS 'Indica se imprime dados do cliente em nota nao identificada. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPRESSAODESCONTONIVELITEM IS 'Indica se imprime desconto ao nivel de item. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGMASCARACPF IS 'Indica se aplica mascara no CPF impresso. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPRIMIRASSINATURAOPERSUPERSUPSAN IS 'Indica se imprime campo de assinatura de operador e supervisor em sangrias/suprimentos. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPRIMIRCONFERENCIAPRODUTO IS 'Indica se imprime conferencia de produto. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPRIMIRDESCONTOAGRUPADO IS 'Indica se imprime os descontos de forma agrupada. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPRIMIRCUPOMPOS IS 'Indica se imprime cupom no POS. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPRESSAODETALHADAAPROPRIACAO IS 'Indica se realiza impressao detalhada de apropriacao. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPRNOMECPFCOMPROVANTES IS 'Indica se imprime nome e CPF nos comprovantes. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPRDADOSCONVENIOSEMTESTARLIMITE IS 'Indica se imprime dados do convenio sem testar limite. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.FLAGIMPRIMIRVALORBOLETOSAGRUPADO IS 'Indica se imprime valor de boletos de forma agrupada. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FRCAIXA_IMPRESSOES.DTALTERACAO IS 'Data da ultima alteracao feita no registro de configuracoes de impressao da empresa.'
GO
CALL DBA.SP_PREP_TAB_COM('CONFIG_FRCAIXA_IMPRESSOES')
