ALTER TABLE DBA.AGRUPAMENTO_TIPO DROP CONSTRAINT CKT_SIGLATIPO
GO
ALTER TABLE DBA.AGRUPAMENTO_TIPO ADD CONSTRAINT CKT_SIGLATIPO CHECK (SIGLATIPO IN ('GEN', 'PSEM', 'GCOM', 'PAST'))
GO
INSERT INTO AGRUPAMENTO_TIPO (
    DESCRTIPOAGRUPAMENTO,
    SIGLATIPO
) SELECT
    'Pasta Produto do Fornecedor',
    'PAST'
FROM
    SYSIBM.SYSDUMMY1
WHERE
    NOT EXISTS (
        SELECT
            1
        FROM
            AGRUPAMENTO_TIPO
        WHERE
            SIGLATIPO = 'PAST'
    )
GO
ALTER TABLE DBA.AGRUPAMENTO_USUARIO DROP CONSTRAINT FK_AGRUPAMENTO_USUARIO_USUARIO
GO
ALTER TABLE DBA.AGRUPAMENTO_USUARIO DROP CONSTRAINT FK_AGRUPAMENTO_USUARIO_AGRUPAMENTO
GO
ALTER TABLE DBA.AGRUPAMENTO_USUARIO DROP PRIMARY KEY
GO
CREATE TABLE DBA.AGRUPAMENTO_USUARIO (
    IDAGRUPAMENTOUSUARIO    INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    IDUSUARIO               INTEGER NOT NULL,
    TIPOUSUARIO             VARCHAR(4),
    IDAGRUPAMENTO           INTEGER NOT NULL,
    DTALTERACAO             TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FLAGINATIVO             CHAR(1) DEFAULT 'F'
)
GO
ALTER TABLE DBA.AGRUPAMENTO_USUARIO ADD CONSTRAINT PK_AGRUPAMENTO_USUARIO PRIMARY KEY (IDAGRUPAMENTOUSUARIO)
GO
ALTER TABLE DBA.AGRUPAMENTO_USUARIO ADD CONSTRAINT FK_AGRUPAMENTO_USUARIO_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES DBA.USUARIO (IDUSUARIO)
GO
ALTER TABLE DBA.AGRUPAMENTO_USUARIO ADD CONSTRAINT FK_AGRUPAMENTO_USUARIO_AGRUPAMENTO FOREIGN KEY (IDAGRUPAMENTO) REFERENCES DBA.AGRUPAMENTO (IDAGRUPAMENTO)
GO
ALTER TABLE DBA.AGRUPAMENTO_USUARIO ADD CONSTRAINT CKT_TIPOUSUARIO CHECK (TIPOUSUARIO IN ('COMP', 'REPR'))
GO
ALTER TABLE DBA.AGRUPAMENTO_USUARIO ADD CONSTRAINT CKT_AGRUPAMENTO_USUARIO_FLAGINATIVO CHECK (FLAGINATIVO IN ('F', 'T'))
GO
COMMENT ON COLUMN DBA.AGRUPAMENTO_USUARIO.IDAGRUPAMENTOUSUARIO IS 'Chave primaria.'
GO
COMMENT ON COLUMN DBA.AGRUPAMENTO_USUARIO.IDUSUARIO IS 'Apresenta qual foi o usuario que fez a alteracao.'
GO
COMMENT ON COLUMN DBA.AGRUPAMENTO_USUARIO.TIPOUSUARIO IS 'Indica a que tipo de usuario o registro pertence COMP - Comprador / REPR - Representante.'
GO
COMMENT ON COLUMN DBA.AGRUPAMENTO_USUARIO.IDAGRUPAMENTO IS 'Indica o ID do Agrupamento ao qual o registro pertence.'
GO
COMMENT ON COLUMN DBA.AGRUPAMENTO_USUARIO.DTALTERACAO IS 'Indica data e horario que o registro sofreu a ultima alteracao.'
GO
COMMENT ON COLUMN DBA.AGRUPAMENTO_USUARIO.FLAGINATIVO IS 'Indica se o registro esta ativo ou nao.'
GO
ALTER TABLE DBA.AGRUPAMENTO_CLIENTE_FORNECEDOR DROP CONSTRAINT FK_AGRUPAMENTO_CLIENTE_FORNECEDOR_AGRUPAMENTO
GO
ALTER TABLE DBA.AGRUPAMENTO_CLIENTE_FORNECEDOR DROP CONSTRAINT FK_AGRUPAMENTO_CLIENTE_FORNECEDOR_CLIENTE_FORNECEDOR
GO
ALTER TABLE DBA.AGRUPAMENTO_CLIENTE_FORNECEDOR DROP PRIMARY KEY
GO
CREATE TABLE DBA.AGRUPAMENTO_CLIENTE_FORNECEDOR (
    IDAGRUPAMENTOCLIFOR    INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    IDAGRUPAMENTO          INTEGER NOT NULL,
    IDCLIFOR               INTEGER NOT NULL,
    DTALTERACAO            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FLAGINATIVO            CHAR(1) DEFAULT 'F'
)
GO
ALTER TABLE DBA.AGRUPAMENTO_CLIENTE_FORNECEDOR ADD CONSTRAINT PK_AGRUPAMENTO_CLIENTE_FORNECEDOR PRIMARY KEY (IDAGRUPAMENTOCLIFOR)
GO
ALTER TABLE DBA.AGRUPAMENTO_CLIENTE_FORNECEDOR ADD CONSTRAINT FK_AGRUPAMENTO_CLIENTE_FORNECEDOR_AGRUPAMENTO FOREIGN KEY (IDAGRUPAMENTO) REFERENCES DBA.AGRUPAMENTO (IDAGRUPAMENTO)
GO
ALTER TABLE DBA.AGRUPAMENTO_CLIENTE_FORNECEDOR ADD CONSTRAINT FK_AGRUPAMENTO_CLIENTE_FORNECEDOR_CLIENTE_FORNECEDOR FOREIGN KEY (IDCLIFOR) REFERENCES DBA.CLIENTE_FORNECEDOR (IDCLIFOR)
GO
ALTER TABLE DBA.AGRUPAMENTO_CLIENTE_FORNECEDOR ADD CONSTRAINT CKT_AGRUPAMENTO_CLIENTE_FORNECEDOR_FLAGINATIVO CHECK (FLAGINATIVO IN ('F', 'T'))
GO
COMMENT ON COLUMN DBA.AGRUPAMENTO_CLIENTE_FORNECEDOR.IDAGRUPAMENTOCLIFOR IS 'Chave primaria.'
GO
COMMENT ON COLUMN DBA.AGRUPAMENTO_CLIENTE_FORNECEDOR.IDCLIFOR IS 'Indica a qual fornecedor o registro pertence.'
GO
COMMENT ON COLUMN DBA.AGRUPAMENTO_CLIENTE_FORNECEDOR.IDAGRUPAMENTO IS 'Indica o ID do Agrupamento ao qual o registro pertence.'
GO
COMMENT ON COLUMN DBA.AGRUPAMENTO_CLIENTE_FORNECEDOR.DTALTERACAO IS 'Indica data e horario que o registro sofreu a ultima alteracao.'
GO
COMMENT ON COLUMN DBA.AGRUPAMENTO_CLIENTE_FORNECEDOR.FLAGINATIVO IS 'Indica se o registro esta ativo ou nao.'
GO
ALTER TABLE DBA.PRODUTO_FORNECEDOR DROP CONSTRAINT FK_PRODUTO_FORNECEDOR_AGRUPAMENTO_CLIENTE_FORNECEDOR
GO
ALTER TABLE DBA.PRODUTO_FORNECEDOR ADD COLUMN IDPASTAFORNECEDOR INTEGER
GO
ALTER TABLE DBA.PRODUTO_FORNECEDOR ADD CONSTRAINT FK_PRODUTO_FORNECEDOR_AGRUPAMENTO_CLIENTE_FORNECEDOR FOREIGN KEY (IDPASTAFORNECEDOR) REFERENCES DBA.AGRUPAMENTO_CLIENTE_FORNECEDOR (IDAGRUPAMENTOCLIFOR)
GO
