SELECT OPERATOR_ID || ' | ' ||
       PREDICATE_ID || ' | ' ||
       TRIM(HOW_APPLIED) || ' | ff=' ||
       CHAR(DECIMAL(FILTER_FACTOR, 18, 12)) || ' | ' ||
       TRIM(CAST(SUBSTR(PREDICATE_TEXT, 1, 500) AS VARCHAR(500))) AS PREDICATE_LINE
FROM DBA.EXPLAIN_PREDICATE
WHERE EXPLAIN_TIME = TIMESTAMP('2026-08-18-13.37.50.588654')
  AND SOURCE_NAME = 'SQLC2O27'
  AND STMTNO = 1
  AND SECTNO = 201
  AND (
      PREDICATE_TEXT LIKE '%IDEMPRESA%'
      OR PREDICATE_TEXT LIKE '%IDPLANILHA%'
      OR PREDICATE_TEXT LIKE '%DTEMISSAO%'
      OR PREDICATE_TEXT LIKE '%TIPOCATEGORIA%'
      OR PREDICATE_TEXT LIKE '%MODELO%'
      OR PREDICATE_TEXT LIKE '%PERPIS%'
      OR PREDICATE_TEXT LIKE '%PERCOFINS%'
      OR PREDICATE_TEXT LIKE '%VALBASEPISCOFINS%'
      OR PREDICATE_TEXT LIKE '%NUMSEQUENCIA%'
      OR PREDICATE_TEXT LIKE '%IDPRODUTO%'
      OR PREDICATE_TEXT LIKE '%IDSUBPRODUTO%'
  )
ORDER BY OPERATOR_ID, PREDICATE_ID
@
