ALTER TABLE DBA.REMESSA_PAG_BANCARIO DROP CONSTRAINT FK_REM_PAG_BANC_BANCO
GO
ALTER TABLE DBA.REMESSA_PAG_BANCARIO DROP CONSTRAINT FK_REM_PAG_BANC_FORPAGREC
GO
ALTER TABLE DBA.REMESSA_PAG_BANCARIO DROP PRIMARY KEY
GO
CREATE TABLE DBA.REMESSA_PAG_BANCARIO (
    IDREMESSA          INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NOMEARQUIVO        VARCHAR(100) NOT NULL,
    IDBANCO            INTEGER NOT NULL,
    IDRECEBIMENTO      INTEGER NOT NULL,
    DTENVIO            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PATHFILESTORAGE    VARCHAR(500),
    IDUSUARIO          INTEGER NOT NULL
)
GO
ALTER TABLE DBA.REMESSA_PAG_BANCARIO ADD CONSTRAINT PK_REMESSA_PAG_BANCARIO PRIMARY KEY (IDREMESSA)
GO
ALTER TABLE DBA.REMESSA_PAG_BANCARIO ADD CONSTRAINT FK_REM_PAG_BANC_BANCO FOREIGN KEY (IDBANCO) REFERENCES DBA.BANCO (IDBANCO)
GO
ALTER TABLE DBA.REMESSA_PAG_BANCARIO ADD CONSTRAINT FK_REM_PAG_BANC_FORPAGREC FOREIGN KEY (IDRECEBIMENTO) REFERENCES DBA.FORMA_PAGREC (IDRECEBIMENTO)
GO
COMMENT ON TABLE DBA.REMESSA_PAG_BANCARIO 					IS 'Arquivos de remessa de pagamento bancario enviados para a Nexxera'
GO
COMMENT ON COLUMN DBA.REMESSA_PAG_BANCARIO.IDREMESSA 		IS 'Identificador da remessa'
GO
COMMENT ON COLUMN DBA.REMESSA_PAG_BANCARIO.NOMEARQUIVO 		IS 'Nome do arquivo de remessa gerado pelo CISSPoder'
GO
COMMENT ON COLUMN DBA.REMESSA_PAG_BANCARIO.IDBANCO 			IS 'Codigo da instituicao bancaria'
GO
COMMENT ON COLUMN DBA.REMESSA_PAG_BANCARIO.IDRECEBIMENTO	IS 'Identificador da forma de pagamento'
GO
COMMENT ON COLUMN DBA.REMESSA_PAG_BANCARIO.DTENVIO 			IS 'Data em que o arquivo foi enviado para a Nexxera'
GO
COMMENT ON COLUMN DBA.REMESSA_PAG_BANCARIO.PATHFILESTORAGE 	IS 'Diretorio do arquivo no repositorio de arquivos da CISS'
GO
COMMENT ON COLUMN DBA.REMESSA_PAG_BANCARIO.IDUSUARIO 		IS 'Identificador do usuario que gerou a remessa'
GO
CALL SP_PREP_TAB_COM('REMESSA_PAG_BANCARIO')
GO
ALTER TABLE DBA.RETORNO_PAG_BANCARIO DROP CONSTRAINT FK_RET_PAG_BANC_BANCO
GO
ALTER TABLE DBA.RETORNO_PAG_BANCARIO DROP CONSTRAINT FK_RET_PAG_BANC_CTABANC
GO
ALTER TABLE DBA.RETORNO_PAG_BANCARIO DROP CONSTRAINT CKT_FLAGPROCESSADO
GO
ALTER TABLE DBA.RETORNO_PAG_BANCARIO DROP CONSTRAINT CKT_FLAGDDA
GO
ALTER TABLE DBA.RETORNO_PAG_BANCARIO DROP PRIMARY KEY
GO
CREATE TABLE DBA.RETORNO_PAG_BANCARIO (
    IDRETORNO          INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NOMEARQUIVO        VARCHAR(100) NOT NULL,
    IDBANCO            INTEGER NOT NULL,
    IDCTABANCARIA      INTEGER NOT NULL,
    DTPROCESSAMENTO    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PATHFILESTORAGE    VARCHAR(500),
    FLAGPROCESSADO     CHAR(1) NOT NULL DEFAULT 'F',
    FLAGDDA            CHAR(1) NOT NULL DEFAULT 'F'
)
GO
ALTER TABLE DBA.RETORNO_PAG_BANCARIO ADD CONSTRAINT PK_RETORNO_PAG_BANCARIO PRIMARY KEY (IDRETORNO)
GO
ALTER TABLE DBA.RETORNO_PAG_BANCARIO ADD CONSTRAINT FK_RET_PAG_BANC_BANCO FOREIGN KEY (IDBANCO) REFERENCES DBA.BANCO (IDBANCO)
GO
ALTER TABLE DBA.RETORNO_PAG_BANCARIO ADD CONSTRAINT FK_RET_PAG_BANC_CTABANC FOREIGN KEY (IDCTABANCARIA) REFERENCES DBA.CONTA_BANCARIA (IDCTABANCARIA)
GO
ALTER TABLE DBA.RETORNO_PAG_BANCARIO ADD CONSTRAINT CKT_FLAGPROCESSADO CHECK (FLAGPROCESSADO IN ('T', 'F'))
GO
ALTER TABLE DBA.RETORNO_PAG_BANCARIO ADD CONSTRAINT CKT_FLAGDDA CHECK (FLAGDDA IN ('T', 'F'))
GO
COMMENT ON TABLE DBA.RETORNO_PAG_BANCARIO 					IS 'Arquivos de retorno de pagamento bancario e DDA importados da Nexxera'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO.IDRETORNO 		IS 'Identificador do arquivo de retorno'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO.NOMEARQUIVO 		IS 'Nome do arquivo de retorno'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO.IDBANCO 			IS 'Codigo da instituicao bancaria'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO.IDCTABANCARIA 	IS 'Identificador da conta bancaria'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO.DTPROCESSAMENTO	IS 'Data do processamento do arquivo'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO.PATHFILESTORAGE 	IS 'Diretorio do arquivo no repositorio de arquivos da CISS'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO.FLAGPROCESSADO 	IS 'Indica se o arquivo foi processado com sucesso'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO.FLAGDDA 			IS 'Indica se trata de um retorno de DDA'
GO
CALL SP_PREP_TAB_COM('RETORNO_PAG_BANCARIO')
GO
ALTER TABLE DBA.RETORNO_PAG_BANCARIO_TITULO DROP CONSTRAINT FK_RET_TITULO_RET_PAG
GO
ALTER TABLE DBA.RETORNO_PAG_BANCARIO_TITULO DROP CONSTRAINT CKT_STATUS
GO
ALTER TABLE DBA.RETORNO_PAG_BANCARIO_TITULO DROP CONSTRAINT CKT_STATUSRELACAOTITULO
GO
ALTER TABLE DBA.RETORNO_PAG_BANCARIO_TITULO DROP PRIMARY KEY
GO
CREATE TABLE DBA.RETORNO_PAG_BANCARIO_TITULO (
    IDRETORNOITEM         INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    IDRETORNO             INTEGER NOT NULL,
    NUMSEQUENCIA          INTEGER NOT NULL,
    IDEMPRESA             INTEGER,
    IDCLIFOR              INTEGER,
    IDTITULO              INTEGER,
    DIGITOTITULO          VARCHAR(3),
    SERIENOTA             VARCHAR(3),
    CODIGOBARRAS          VARCHAR(60),
    SEGMENTO              VARCHAR(20),
    NRODOCATRIBUIDO       VARCHAR(20),
    VALTITULO             DECIMAL(15, 2),
    VALDESCONTO           DECIMAL(15, 2),
    VALJUROS              DECIMAL(15, 2),
    DTPAGAMENTO           DATE,
    DTEMISSAO             DATE,
    DTVENCIMENTO          DATE,
    DTGERACAO             DATE,
    IDEMPRESAIMPORTACAO   INTEGER,
    STATUS                SMALLINT,
    STATUSRELACAOTITULO   SMALLINT,
    OCORRENCIA            VARCHAR(3),
    IDPLANILHABAIXA       INTEGER,
    CNPJ                  VARCHAR(14),
    CNPJCEDENTE           VARCHAR(14),
    CNPJSACADOR           VARCHAR(14),
    OBSPROCESSAMENTO      VARCHAR(700)
)
GO
ALTER TABLE DBA.RETORNO_PAG_BANCARIO_TITULO ADD CONSTRAINT PK_RET_PAG_BANC_TITULO PRIMARY KEY (IDRETORNOITEM)
GO
ALTER TABLE DBA.RETORNO_PAG_BANCARIO_TITULO ADD CONSTRAINT FK_RET_TITULO_RET_PAG FOREIGN KEY (IDRETORNO) REFERENCES DBA.RETORNO_PAG_BANCARIO (IDRETORNO)
GO
ALTER TABLE DBA.RETORNO_PAG_BANCARIO_TITULO ADD CONSTRAINT CKT_STATUS CHECK (STATUS IN (0, 1, 2, 3))
GO
ALTER TABLE DBA.RETORNO_PAG_BANCARIO_TITULO ADD CONSTRAINT CKT_STATUSRELACAOTITULO CHECK (STATUSRELACAOTITULO IN (0, 1, 2, 3, 4, 5))
GO
COMMENT ON TABLE DBA.RETORNO_PAG_BANCARIO_TITULO 						IS 'Dados das linhas do arquivo de retorno de pagamentos ou DDA importado da Nexxera'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO_TITULO.IDRETORNOITEM 		IS 'Identificador da linha importada'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO_TITULO.IDRETORNO 			IS 'Chave estrangeira da tabela do arquivo importado'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO_TITULO.NUMSEQUENCIA 			IS 'Sequencia da linha no arquivo'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO_TITULO.IDEMPRESA 			IS 'Codigo da empresa da conta a pagar'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO_TITULO.IDCLIFOR 				IS 'Codigo do fornecedor da conta a pagar'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO_TITULO.IDTITULO 				IS 'Codigo do titulo da conta a pagar'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO_TITULO.DIGITOTITULO 			IS 'Digito do titulo da conta a pagar'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO_TITULO.SERIENOTA 			IS 'Serie da nota da conta a pagar'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO_TITULO.CODIGOBARRAS 			IS 'Codigo de barras'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO_TITULO.SEGMENTO 				IS 'Segmento da linha'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO_TITULO.NRODOCATRIBUIDO 		IS 'Numero do documento atribuido'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO_TITULO.VALTITULO 			IS 'Valor do titulo'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO_TITULO.VALDESCONTO 			IS 'Valor de descontos'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO_TITULO.VALJUROS 				IS 'Valor de juros'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO_TITULO.DTPAGAMENTO 			IS 'Data do pagamento'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO_TITULO.DTEMISSAO 			IS 'Data de emissao'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO_TITULO.DTVENCIMENTO 			IS 'Data de vencimento'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO_TITULO.DTGERACAO 			IS 'Data de geracao (DDA)'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO_TITULO.IDEMPRESAIMPORTACAO 	IS 'Codigo da empresa referente ao CNPJ do cabecalho do arquivo'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO_TITULO.STATUS 				IS 'Status do processamento da linha (0 = BAIXADO, 1 = SEM_BAIXA, 2 = ERRO_BAIXA, 3 = DDA_IMPORTADO)'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO_TITULO.STATUSRELACAOTITULO	IS 'Relacionamento com o contas a pagar (0 = RELACIONADO, 1 = NAO ENCONTRADO, 2 = MULTIPLOS ENCONTRADOS, 3 = ENCONTRADO RADAR XML, 4 = PENDENTE RADAR XML, 5 = NFE PENDENTE PODER)'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO_TITULO.OCORRENCIA 			IS 'Codigo de ocorrencia da linha'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO_TITULO.IDPLANILHABAIXA 		IS 'Identificador da planilha referente a baixa realizada no processamento automatico'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO_TITULO.CNPJ 					IS 'CNPJ da empresa no cabecalho do lote do arquivo'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO_TITULO.CNPJCEDENTE 			IS 'CNPJ cedente do pagamento'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO_TITULO.CNPJSACADOR 			IS 'CNPJ sacador do pagamento'
GO
COMMENT ON COLUMN DBA.RETORNO_PAG_BANCARIO_TITULO.OBSPROCESSAMENTO 		IS 'Observacao do processamento da linha do arquivo'