-- CISS-183652 - Rollback
--
-- Reverte exclusivamente as baixas registradas previamente em
-- TMP.CONTAS_PAGAR_BAIXAS_CISS183652 pela procedure da demanda.
-- O registro da TMP e mantido como historico e marcado como revertido.
-- Baixas anteriores a implantacao da tabela de controle nao sao selecionadas.

CREATE OR REPLACE PROCEDURE DBA.SP_CISS_183652_REVERTE_BAIXAS()
LANGUAGE SQL
MODIFIES SQL DATA
BEGIN
    DECLARE V_QTD_LOTE INTEGER DEFAULT 0;
    DECLARE V_QTD_EXCLUIDA INTEGER DEFAULT 0;
    DECLARE V_QTD_ATUALIZADA INTEGER DEFAULT 0;
    DECLARE V_QTD_TMP INTEGER DEFAULT 0;

    FOR LOOPQUERY AS LQUERY CURSOR WITH HOLD FOR
        SELECT
            TMPBX.IDEMPRESA AS V_IDEMPRESA,
            TMPBX.IDCLIFOR AS V_IDCLIFOR,
            TMPBX.IDTITULO AS V_IDTITULO,
            TMPBX.DIGITOTITULO AS V_DIGITOTITULO,
            TMPBX.SERIENOTA AS V_SERIENOTA,
            TMPBX.IDPLANILHA AS V_IDPLANILHA,
            TMPBX.ORIGEMMOVIMENTO AS V_ORIGEMMOVIMENTO,
            TMPBX.DTPAGAMENTO AS V_DTPAGAMENTO,
            TMPBX.VALPAGAMENTOTITULO AS V_VALPAGAMENTO,
            TMPBX.VALDESCCONCEDIDOTITULO AS V_VALDESCONTO
        FROM
            TMP.CONTAS_PAGAR_BAIXAS_CISS183652 AS TMPBX
            JOIN DBA.CONTAS_PAGAR_BAIXAS AS BX ON
                BX.IDEMPRESA = TMPBX.IDEMPRESA AND
                BX.IDCLIFOR = TMPBX.IDCLIFOR AND
                BX.IDTITULO = TMPBX.IDTITULO AND
                BX.DIGITOTITULO = TMPBX.DIGITOTITULO AND
                BX.SERIENOTA = TMPBX.SERIENOTA AND
                BX.IDPLANILHA = TMPBX.IDPLANILHA AND
                BX.ORIGEMMOVIMENTO = TMPBX.ORIGEMMOVIMENTO AND
                BX.DTPAGAMENTO = TMPBX.DTPAGAMENTO AND
                BX.VALPAGAMENTOTITULO = TMPBX.VALPAGAMENTOTITULO AND
                BX.VALDESCCONCEDIDOTITULO = TMPBX.VALDESCCONCEDIDOTITULO
            JOIN DBA.CONTAS_PAGAR AS CP ON
                CP.IDEMPRESA = TMPBX.IDEMPRESA AND
                CP.IDCLIFOR = TMPBX.IDCLIFOR AND
                CP.IDTITULO = TMPBX.IDTITULO AND
                CP.DIGITOTITULO = TMPBX.DIGITOTITULO AND
                CP.SERIENOTA = TMPBX.SERIENOTA AND
                CP.IDPLANILHA = TMPBX.IDPLANILHA
        WHERE
            TMPBX.FLAGREVERTIDA = 'F'
        ORDER BY
            TMPBX.DTEXECUCAO,
            TMPBX.NUMLOTE,
            TMPBX.IDEMPRESA,
            TMPBX.IDCLIFOR,
            TMPBX.IDTITULO,
            TMPBX.DIGITOTITULO,
            TMPBX.SERIENOTA
    DO
        DELETE FROM
            DBA.CONTAS_PAGAR_BAIXAS AS BX
        WHERE
            BX.IDEMPRESA = V_IDEMPRESA AND
            BX.IDCLIFOR = V_IDCLIFOR AND
            BX.IDTITULO = V_IDTITULO AND
            BX.DIGITOTITULO = V_DIGITOTITULO AND
            BX.SERIENOTA = V_SERIENOTA AND
            BX.IDPLANILHA = V_IDPLANILHA AND
            BX.ORIGEMMOVIMENTO = V_ORIGEMMOVIMENTO AND
            BX.DTPAGAMENTO = V_DTPAGAMENTO AND
            BX.VALPAGAMENTOTITULO = V_VALPAGAMENTO AND
            BX.VALDESCCONCEDIDOTITULO = V_VALDESCONTO;

        GET DIAGNOSTICS V_QTD_EXCLUIDA = ROW_COUNT;

        IF V_QTD_EXCLUIDA = 1 THEN
            UPDATE
                DBA.CONTAS_PAGAR AS CP
            SET
                CP.SUMVALDESCCONCEDIDOTITULO = V_VALDESCONTO
            WHERE
                CP.IDEMPRESA = V_IDEMPRESA AND
                CP.IDCLIFOR = V_IDCLIFOR AND
                CP.IDTITULO = V_IDTITULO AND
                CP.DIGITOTITULO = V_DIGITOTITULO AND
                CP.SERIENOTA = V_SERIENOTA AND
                CP.IDPLANILHA = V_IDPLANILHA;

            GET DIAGNOSTICS V_QTD_ATUALIZADA = ROW_COUNT;

            IF V_QTD_ATUALIZADA <> 1 THEN
                SIGNAL SQLSTATE '75001'
                    SET MESSAGE_TEXT = 'CISS-183652: titulo da baixa excluida nao foi atualizado.';
            END IF;

            UPDATE
                TMP.CONTAS_PAGAR_BAIXAS_CISS183652 AS TMPBX
            SET
                TMPBX.FLAGREVERTIDA = 'T',
                TMPBX.DTREVERSAO = CURRENT TIMESTAMP,
                TMPBX.DTALTERACAO = CURRENT TIMESTAMP
            WHERE
                TMPBX.IDEMPRESA = V_IDEMPRESA AND
                TMPBX.IDCLIFOR = V_IDCLIFOR AND
                TMPBX.IDTITULO = V_IDTITULO AND
                TMPBX.DIGITOTITULO = V_DIGITOTITULO AND
                TMPBX.SERIENOTA = V_SERIENOTA AND
                TMPBX.IDPLANILHA = V_IDPLANILHA AND
                TMPBX.FLAGREVERTIDA = 'F';

            GET DIAGNOSTICS V_QTD_TMP = ROW_COUNT;

            IF V_QTD_TMP <> 1 THEN
                SIGNAL SQLSTATE '75002'
                    SET MESSAGE_TEXT = 'CISS-183652: registro da TMP nao foi marcado como revertido.';
            END IF;

            SET V_QTD_LOTE = V_QTD_LOTE + 1;

            IF MOD(V_QTD_LOTE, 1000) = 0 THEN
                COMMIT;
            END IF;
        END IF;
    END FOR;

    COMMIT;
END
GO

-- Quantidade e valor registrados pela procedure e ainda nao revertidos.
SELECT
    COUNT(*) AS QTD_BAIXAS_A_REVERTER,
    SUM(TMPBX.VALDESCCONCEDIDOTITULO) AS VALDESCONTO_A_RESTAURAR
FROM
    TMP.CONTAS_PAGAR_BAIXAS_CISS183652 AS TMPBX
    JOIN DBA.CONTAS_PAGAR_BAIXAS AS BX ON
        BX.IDEMPRESA = TMPBX.IDEMPRESA AND
        BX.IDCLIFOR = TMPBX.IDCLIFOR AND
        BX.IDTITULO = TMPBX.IDTITULO AND
        BX.DIGITOTITULO = TMPBX.DIGITOTITULO AND
        BX.SERIENOTA = TMPBX.SERIENOTA AND
        BX.IDPLANILHA = TMPBX.IDPLANILHA AND
        BX.ORIGEMMOVIMENTO = TMPBX.ORIGEMMOVIMENTO AND
        BX.DTPAGAMENTO = TMPBX.DTPAGAMENTO AND
        BX.VALPAGAMENTOTITULO = TMPBX.VALPAGAMENTOTITULO AND
        BX.VALDESCCONCEDIDOTITULO = TMPBX.VALDESCCONCEDIDOTITULO
WHERE
    TMPBX.FLAGREVERTIDA = 'F'
GO

CALL DBA.SP_CISS_183652_REVERTE_BAIXAS()
GO

-- Apos a execucao, esta consulta deve retornar zero.
SELECT
    COUNT(*) AS QTD_BAIXAS_NAO_REVERTIDAS
FROM
    TMP.CONTAS_PAGAR_BAIXAS_CISS183652 AS TMPBX
    JOIN DBA.CONTAS_PAGAR_BAIXAS AS BX ON
        BX.IDEMPRESA = TMPBX.IDEMPRESA AND
        BX.IDCLIFOR = TMPBX.IDCLIFOR AND
        BX.IDTITULO = TMPBX.IDTITULO AND
        BX.DIGITOTITULO = TMPBX.DIGITOTITULO AND
        BX.SERIENOTA = TMPBX.SERIENOTA AND
        BX.IDPLANILHA = TMPBX.IDPLANILHA
WHERE
    TMPBX.FLAGREVERTIDA = 'F'
GO
