SELECT TRIM(I.TABNAME) || ' | ' ||
       TRIM(I.INDNAME) || ' | ' ||
       I.UNIQUERULE || ' | cols=' || I.COLCOUNT || ' | fullkey=' ||
       COALESCE(CHAR(I.FULLKEYCARD), '-') || ' | ' ||
       LISTAGG(TRIM(C.COLNAME) || ' ' || C.COLORDER, ', ')
           WITHIN GROUP (ORDER BY C.COLSEQ) AS INDEX_LINE
FROM SYSCAT.INDEXES I
JOIN SYSCAT.INDEXCOLUSE C
  ON C.INDSCHEMA = I.INDSCHEMA
 AND C.INDNAME = I.INDNAME
WHERE I.TABSCHEMA = 'DBA'
  AND I.TABNAME IN (
      'PISCOFINS_MOVIMENTO',
      'NOTAS_ENTRADA_SAIDA',
      'NOTAS',
      'NOTAS_DEVOLUCAO',
      'NOTA_FISCAL_ELETRONICA',
      'NOTA_FISCAL_CONSUMIDOR_ELETRONICA',
      'CONFIG_ALIQUOTA_ZERO_PRODUTOS',
      'CONFIG_ALIQUOTA_ZERO_COI',
      'CONFIG_SPED_ALIQUOTA_ZERO',
      'CONFIG_CONTABIL'
  )
GROUP BY I.TABNAME, I.INDNAME, I.UNIQUERULE, I.COLCOUNT, I.FULLKEYCARD
ORDER BY I.TABNAME, I.INDNAME
@
