ALTER TABLE DBA.CONFERE_OBSERVACAO DROP CONSTRAINT FK_CONFEREOBS_CLIFOR
GO
ALTER TABLE DBA.CONFERE_OBSERVACAO DROP CONSTRAINT FK_CONFEREOBS_EMPRESA
GO
ALTER TABLE DBA.CONFERE_OBSERVACAO DROP CONSTRAINT FK_CONFEREOBS_CONFAUT
GO
ALTER TABLE DBA.CONFERE_OBSERVACAO DROP CONSTRAINT FK_CONFEREOBS_PRODUTO
GO
ALTER TABLE DBA.CONFERE_OBSERVACAO DROP PRIMARY KEY
GO
CREATE TABLE DBA.CONFERE_OBSERVACAO (
    IDCTDOBSERVACAO   INTEGER     NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    IDEMPRESA         INTEGER     NOT NULL,
    IDAUTORIZACAO     INTEGER     NOT NULL,
    IDCLIFOR          INTEGER     NOT NULL,
    NUMNOTA           INTEGER     NOT NULL,
    SERIENOTA         VARCHAR(3)  NOT NULL,
    IDPRODUTO         INTEGER     NOT NULL,
    IDSUBPRODUTO      INTEGER     NOT NULL,
    TIPO              VARCHAR(1)  NOT NULL DEFAULT 'L',
    IDUSUARIO         INTEGER     NOT NULL,
    OBSERVACAO        LONG VARCHAR,
    DTALTERACAO       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
GO
ALTER TABLE DBA.CONFERE_OBSERVACAO ADD CONSTRAINT PK_CONFERE_OBS PRIMARY KEY(IDCTDOBSERVACAO)
GO
ALTER TABLE DBA.CONFERE_OBSERVACAO ADD CONSTRAINT FK_CONFEREOBS_CLIFOR FOREIGN KEY(IDCLIFOR) REFERENCES DBA.CLIENTE_FORNECEDOR(IDCLIFOR)
GO
ALTER TABLE DBA.CONFERE_OBSERVACAO ADD CONSTRAINT FK_CONFEREOBS_EMPRESA FOREIGN KEY(IDEMPRESA) REFERENCES DBA.EMPRESA(IDEMPRESA)
GO
ALTER TABLE DBA.CONFERE_OBSERVACAO ADD CONSTRAINT FK_CONFEREOBS_CONFAUT FOREIGN KEY(IDCLIFOR, IDAUTORIZACAO, SERIENOTA, NUMNOTA, IDEMPRESA) REFERENCES DBA.CONFERE_AUTORIZA(IDCLIFOR, IDAUTORIZACAO, SERIENOTA, NUMNOTA, IDEMPRESA)
GO
ALTER TABLE DBA.CONFERE_OBSERVACAO ADD CONSTRAINT FK_CONFEREOBS_PRODUTO FOREIGN KEY(IDPRODUTO, IDSUBPRODUTO) REFERENCES DBA.PRODUTO_GRADE(IDPRODUTO, IDSUBPRODUTO)
GO
ALTER TABLE DBA.CONFERE_OBSERVACAO ADD CONSTRAINT CKT_TIPOLCTOCONFOBS CHECK ( TIPO IN ('L', 'D') )
GO
COMMENT ON TABLE DBA.CONFERE_OBSERVACAO IS 'Esta tabela sera usada para gravar as observacoes dos produtos da autorizacao'
GO
COMMENT ON COLUMN DBA.CONFERE_OBSERVACAO.IDCTDOBSERVACAO IS 'Chave primaria'
GO
COMMENT ON COLUMN DBA.CONFERE_OBSERVACAO.IDEMPRESA IS 'Codigo da empresa para onde sera autorizada a nota'
GO
COMMENT ON COLUMN DBA.CONFERE_OBSERVACAO.IDAUTORIZACAO IS 'Codigo da autorizacao de recepcao'
GO
COMMENT ON COLUMN DBA.CONFERE_OBSERVACAO.IDPRODUTO IS 'Codigo do produto'
GO
COMMENT ON COLUMN DBA.CONFERE_OBSERVACAO.IDSUBPRODUTO IS 'Codigo do sub produto'
GO
COMMENT ON COLUMN DBA.CONFERE_OBSERVACAO.IDCLIFOR IS 'Codigo interno do fornecedor da nota'
GO
COMMENT ON COLUMN DBA.CONFERE_OBSERVACAO.NUMNOTA IS 'Numero da NF-e'
GO
COMMENT ON COLUMN DBA.CONFERE_OBSERVACAO.SERIENOTA IS 'Serie da NF-e'
GO
COMMENT ON COLUMN DBA.CONFERE_OBSERVACAO.TIPO IS 'Tipo de lancamento L - Lancamento - D - Devolucao'
GO
COMMENT ON COLUMN DBA.CONFERE_OBSERVACAO.IDUSUARIO IS 'Usuario'
GO
COMMENT ON COLUMN DBA.CONFERE_OBSERVACAO.OBSERVACAO IS 'Obsrevacao'
GO
COMMENT ON COLUMN DBA.CONFERE_OBSERVACAO.DTALTERACAO IS 'Data de alteracao'
GO
INSERT INTO DBA.CONFIG_CISSCONTROL_DETALHES (IDCONFIGCISSCONTROLDETALHE, IDCONFIGCISSCONTROL, DESCRCONFIG, VALORPADRAO)
SELECT
    TMP.IDCONFIGCISSCONTROLDETALHE,
    TMP.IDCONFIGCISSCONTROL,
    TMP.DESCRCONFIG,
    TMP.VALORPADRAO
FROM
    TABLE (
        VALUES
            (50, 1, 'Exibe observação da conferência de recepção', 'F')
    ) AS TMP (IDCONFIGCISSCONTROLDETALHE, IDCONFIGCISSCONTROL, DESCRCONFIG, VALORPADRAO)
WHERE
    NOT EXISTS (SELECT
                    0
                FROM
                    DBA.CONFIG_CISSCONTROL_DETALHES TEMP
                WHERE
                    TEMP.IDCONFIGCISSCONTROLDETALHE = TMP.IDCONFIGCISSCONTROLDETALHE)