SELECT TABNAME, CARD, NPAGES, FPAGES, STATS_TIME
FROM SYSCAT.TABLES
WHERE TABSCHEMA = 'DBA'
  AND TABNAME IN (
      'PISCOFINS_MOVIMENTO',
      'NOTAS_ENTRADA_SAIDA',
      'NOTAS',
      'NOTAS_DEVOLUCAO',
      'NOTA_FISCAL_ELETRONICA',
      'NOTA_FISCAL_CONSUMIDOR_ELETRONICA'
  )
ORDER BY TABNAME
@

SELECT TABNAME, INDNAME, STATS_TIME, FULLKEYCARD, FIRSTKEYCARD, FIRST2KEYCARD, FIRST3KEYCARD, FIRST4KEYCARD, NLEAF, NLEVELS
FROM SYSCAT.INDEXES
WHERE TABSCHEMA = 'DBA'
  AND TABNAME IN ('PISCOFINS_MOVIMENTO', 'NOTAS_ENTRADA_SAIDA', 'NOTAS_DEVOLUCAO')
ORDER BY TABNAME, INDNAME
@
