SELECT OPERATOR_ID,
       OPERATOR_TYPE,
       DECIMAL(TOTAL_COST, 18, 2) AS TOTAL_COST,
       DECIMAL(IO_COST, 18, 2) AS IO_COST,
       DECIMAL(CPU_COST, 18, 2) AS CPU_COST,
       DECIMAL(FIRST_ROW_COST, 18, 2) AS FIRST_ROW_COST
FROM DBA.EXPLAIN_OPERATOR
WHERE EXPLAIN_TIME = TIMESTAMP('2026-08-18-13.37.50.588654')
  AND SOURCE_NAME = 'SQLC2O27'
  AND STMTNO = 1
  AND SECTNO = 201
ORDER BY OPERATOR_ID
@

SELECT STREAM_ID, SOURCE_TYPE, SOURCE_ID, TARGET_TYPE, TARGET_ID,
       OBJECT_SCHEMA, OBJECT_NAME,
       DECIMAL(STREAM_COUNT, 18, 2) AS STREAM_COUNT,
       COLUMN_COUNT,
       PREDICATE_ID
FROM DBA.EXPLAIN_STREAM
WHERE EXPLAIN_TIME = TIMESTAMP('2026-08-18-13.37.50.588654')
  AND SOURCE_NAME = 'SQLC2O27'
  AND STMTNO = 1
  AND SECTNO = 201
ORDER BY STREAM_ID
@

SELECT OBJECT_SCHEMA, OBJECT_NAME, OBJECT_TYPE,
       ROW_COUNT, PAGES, NLEAF, NLEVELS, FULLKEYCARD,
       FIRSTKEYCARD, FIRST2KEYCARD, FIRST3KEYCARD, FIRST4KEYCARD
FROM DBA.EXPLAIN_OBJECT
WHERE EXPLAIN_TIME = TIMESTAMP('2026-08-18-13.37.50.588654')
  AND SOURCE_NAME = 'SQLC2O27'
  AND STMTNO = 1
  AND SECTNO = 201
ORDER BY OBJECT_SCHEMA, OBJECT_NAME, OBJECT_TYPE
@

SELECT OPERATOR_ID, ARGUMENT_TYPE, ARGUMENT_VALUE
FROM DBA.EXPLAIN_ARGUMENT
WHERE EXPLAIN_TIME = TIMESTAMP('2026-08-18-13.37.50.588654')
  AND SOURCE_NAME = 'SQLC2O27'
  AND STMTNO = 1
  AND SECTNO = 201
  AND ARGUMENT_TYPE IN ('UNIQUE', 'JOIN_TYPE', 'ISCAN_TYPE', 'PREFETCH', 'SORTC_SHRHEAP_TOP')
ORDER BY OPERATOR_ID, ARGUMENT_TYPE
@
