SELECT TABSCHEMA, TABNAME
FROM SYSCAT.TABLES
WHERE TABNAME LIKE 'EXPLAIN%'
ORDER BY TABSCHEMA, TABNAME
@

SELECT EXPLAIN_TIME, SOURCE_NAME, EXPLAIN_LEVEL, STMTNO, SECTNO, TOTAL_COST, STATEMENT_TEXT
FROM EXPLAIN_STATEMENT
ORDER BY EXPLAIN_TIME DESC
FETCH FIRST 5 ROWS ONLY
@
