ALTER TABLE DBA.CONFIG_FECHAMENTO_VENDA DROP CONSTRAINT FK_CONFIGFECHAMENTOVENDA_EMP
GO
ALTER TABLE DBA.CONFIG_FECHAMENTO_VENDA DROP CONSTRAINT CKT_DESCONTOCOMBOCUPOM
GO
ALTER TABLE DBA.CONFIG_FECHAMENTO_VENDA DROP CONSTRAINT CKT_PROMOCAOAVANCADA
GO
ALTER TABLE DBA.CONFIG_FECHAMENTO_VENDA DROP CONSTRAINT CKT_APLICARDESCVALORLIQUIDO
GO
ALTER TABLE DBA.CONFIG_FECHAMENTO_VENDA DROP CONSTRAINT CKT_AVANCADACLIENTEFECHAMENTO
GO
ALTER TABLE DBA.CONFIG_FECHAMENTO_VENDA DROP CONSTRAINT CKT_IMPRIMEBOLETOSERVIDOR
GO
ALTER TABLE DBA.CONFIG_FECHAMENTO_VENDA DROP CONSTRAINT CKT_PERMITEALTERARVALFORMAPGTO
GO
ALTER TABLE DBA.CONFIG_FECHAMENTO_VENDA DROP CONSTRAINT CKT_VENDERITEMVALORBRUTO
GO
ALTER TABLE DBA.CONFIG_FECHAMENTO_VENDA DROP CONSTRAINT CKT_VENDERBRINDEVALORZERADO
GO
ALTER TABLE DBA.CONFIG_FECHAMENTO_VENDA DROP CONSTRAINT CKT_PERMITEVENDAOPERADOR
GO
ALTER TABLE DBA.CONFIG_FECHAMENTO_VENDA DROP PRIMARY KEY
GO
CREATE TABLE DBA.CONFIG_FECHAMENTO_VENDA (
IDEMPRESA                           INTEGER NOT NULL,
IDFORMAPAGTOTROCO                   INTEGER,
IDRECEBIMENTOCONTRAVALE             INTEGER,
VALMINIMPCONTRA                     DECIMAL(14,2),
DIASLIMITEPREDATAMENTOCHEQUE        INTEGER,
TIPOTESTELIMITECHEQUE               CHAR(1),
TIPOCOMPROVCONV                     CHAR(1) NOT NULL DEFAULT 'R',
TIPOCONSISTECUPOM                   CHAR(1),
IDFORMAPAGTOREFORCO                 INTEGER,
QTDMAXVENDASPENDENTES               INTEGER,
MSGFINALCUPOM1                      VARCHAR(40),
MSGFINALCUPOM2                      VARCHAR(40),
FLAGDESCONTOCOMBOCUPOM             CHAR(1) NOT NULL DEFAULT 'F',
MSGLINHA1PINPAD                     VARCHAR(20),
MSGLINHA2PINPAD                     VARCHAR(20),
OPCAOIGNORARDESCONTOPAGTOPARCIAL    CHAR(1),
OPCAOSOCIOTORCEDOR                  INTEGER,
IDFORMAPAGTODOTZ                    INTEGER,
PRIORIDADEAPLICPROMOCOES            CHAR(1),
FLAGAPLICARDESCVALORLIQUIDO        CHAR(1) NOT NULL DEFAULT 'F',
FLAGAVANCADACLIENTEFECHAMENTO      CHAR(1) NOT NULL DEFAULT 'F',
FLAGIMPRIMEBOLETOSERVIDORIMPRESSAO CHAR(1) NOT NULL DEFAULT 'F',
FLAGPERMITEALTERARVALFORMAPGTO     CHAR(1) NOT NULL DEFAULT 'F',
FLAGVENDERITEMVALORBRUTO           CHAR(1) NOT NULL DEFAULT 'F',
TROCODIGITAL                        CHAR(2),
FLAGVENDERBRINDEVALORZERADO        CHAR(1) NOT NULL DEFAULT 'F',
FLAGPERMITEVENDAOPERADOR           CHAR(1) NOT NULL DEFAULT 'F',
DTALTERACAO                         TIMESTAMP
);
GO
ALTER TABLE DBA.CONFIG_FECHAMENTO_VENDA ADD CONSTRAINT PK_CONFIGFECHAMENTOVENDA PRIMARY KEY (IDEMPRESA)
GO
ALTER TABLE DBA.CONFIG_FECHAMENTO_VENDA ADD CONSTRAINT FK_CONFIGFECHAMENTOVENDA_EMP FOREIGN KEY (IDEMPRESA) REFERENCES DBA.EMPRESA (IDEMPRESA)
GO
ALTER TABLE DBA.CONFIG_FECHAMENTO_VENDA ADD CONSTRAINT CKT_DESCONTOCOMBOCUPOM CHECK (FLAGDESCONTOCOMBOCUPOM IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FECHAMENTO_VENDA ADD CONSTRAINT CKT_APLICARDESCVALORLIQUIDO CHECK (FLAGAPLICARDESCVALORLIQUIDO IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FECHAMENTO_VENDA ADD CONSTRAINT CKT_AVANCADACLIENTEFECHAMENTO CHECK (FLAGAVANCADACLIENTEFECHAMENTO IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FECHAMENTO_VENDA ADD CONSTRAINT CKT_IMPRIMEBOLETOSERVIDOR CHECK (FLAGIMPRIMEBOLETOSERVIDORIMPRESSAO IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FECHAMENTO_VENDA ADD CONSTRAINT CKT_PERMITEALTERARVALFORMAPGTO CHECK (FLAGPERMITEALTERARVALFORMAPGTO IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FECHAMENTO_VENDA ADD CONSTRAINT CKT_VENDERITEMVALORBRUTO CHECK (FLAGVENDERITEMVALORBRUTO IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FECHAMENTO_VENDA ADD CONSTRAINT CKT_VENDERBRINDEVALORZERADO CHECK (FLAGVENDERBRINDEVALORZERADO IN ('T','F'))
GO
ALTER TABLE DBA.CONFIG_FECHAMENTO_VENDA ADD CONSTRAINT CKT_PERMITEVENDAOPERADOR CHECK (FLAGPERMITEVENDAOPERADOR IN ('T','F'))
GO
COMMENT ON TABLE DBA.CONFIG_FECHAMENTO_VENDA IS 'Armazena as configuracoes de fechamento de venda'
GO
COMMENT ON COLUMN DBA.CONFIG_FECHAMENTO_VENDA.IDEMPRESA IS 'Codigo da empresa.'
GO
COMMENT ON COLUMN DBA.CONFIG_FECHAMENTO_VENDA.IDFORMAPAGTOTROCO IS 'Codigo de identificacao da forma de pagamento de troco, este codigo se refere a uma forma de pagamento da tabela config_forma_pagto.'
GO
COMMENT ON COLUMN DBA.CONFIG_FECHAMENTO_VENDA.IDRECEBIMENTOCONTRAVALE IS 'Codigo de identificacao da forma de pagamento do contra-vale, este codigo se refere ao codigo da forma de pagamento do ERP.'
GO
COMMENT ON COLUMN DBA.CONFIG_FECHAMENTO_VENDA.VALMINIMPCONTRA IS 'Valor minimo de troco para que seja impresso um contra-vale para formas de pagamento que utilizam emissao de contra-vale. Abaixo do valor configurado neste campo sera retornado troco em dinheiro.'
GO
COMMENT ON COLUMN DBA.CONFIG_FECHAMENTO_VENDA.DIASLIMITEPREDATAMENTOCHEQUE IS 'Numero maximo de dias para pre-datamento do cheque.'
GO
COMMENT ON COLUMN DBA.CONFIG_FECHAMENTO_VENDA.TIPOTESTELIMITECHEQUE IS 'Tipo de teste do CNPJ/CPF para venda em cheque, definindo se deve ser testado pelo CNPJ/CPF do emitente, do portador ou de ambos. Sendo A para ambos, E somente por emitente e P somente por portador.'
GO
COMMENT ON COLUMN DBA.CONFIG_FECHAMENTO_VENDA.TIPOCOMPROVCONV IS 'Tipo de comprovante utilizado nas vendas com convenio. Sendo C para chequinho e R para recibo.'
GO
COMMENT ON COLUMN DBA.CONFIG_FECHAMENTO_VENDA.TIPOCONSISTECUPOM IS 'Tipo de teste de consistencia de cupom que sera realizado ao abrir a frente de caixa com um cupom aberto ou no fechamento de venda, sendo A cobrar acrescimo ou conceder desconto, D conceder desconto e B bloquear venda.'
GO
COMMENT ON COLUMN DBA.CONFIG_FECHAMENTO_VENDA.IDFORMAPAGTOREFORCO IS 'Codigo da forma de pagamento, na qual sera aplicado o reforco/fundo de troco.'
GO
COMMENT ON COLUMN DBA.CONFIG_FECHAMENTO_VENDA.QTDMAXVENDASPENDENTES IS 'Define a quantidade maxima de vendas pendentes no PDV sem replicar para exibir uma mensagem para o operador.'
GO
COMMENT ON COLUMN DBA.CONFIG_FECHAMENTO_VENDA.MSGFINALCUPOM1 IS 'Texto para a primeira linha de mensagem do cupom fiscal, impressa no fechamento do mesmo.'
GO
COMMENT ON COLUMN DBA.CONFIG_FECHAMENTO_VENDA.MSGFINALCUPOM2 IS 'Texto para a segunda linha de mensagem do cupom fiscal, impressa no fechamento do mesmo.'
GO
COMMENT ON COLUMN DBA.CONFIG_FECHAMENTO_VENDA.FLAGDESCONTOCOMBOCUPOM IS 'Define se o rateio dos itens em promocao sera no cupom.'
GO
COMMENT ON COLUMN DBA.CONFIG_FECHAMENTO_VENDA.MSGLINHA1PINPAD IS 'Primeira linha exibida no pinpad.'
GO
COMMENT ON COLUMN DBA.CONFIG_FECHAMENTO_VENDA.MSGLINHA2PINPAD IS 'Segunda linha exibida no pinpad.'
GO
COMMENT ON COLUMN DBA.CONFIG_FECHAMENTO_VENDA.OPCAOIGNORARDESCONTOPAGTOPARCIAL IS 'Define o comportamento para descontos em pagamentos parciais.'
GO
COMMENT ON COLUMN DBA.CONFIG_FECHAMENTO_VENDA.OPCAOSOCIOTORCEDOR IS 'Configuracao utilizada para programa socio torcedor.'
GO
COMMENT ON COLUMN DBA.CONFIG_FECHAMENTO_VENDA.IDFORMAPAGTODOTZ IS 'Forma de pagamento utilizada para integracao DOTZ.'
GO
COMMENT ON COLUMN DBA.CONFIG_FECHAMENTO_VENDA.PRIORIDADEAPLICPROMOCOES IS 'Define a prioridade de aplicacao das promocoes.'
GO
COMMENT ON COLUMN DBA.CONFIG_FECHAMENTO_VENDA.FLAGAPLICARDESCVALORLIQUIDO IS 'Indica se o desconto deve ser aplicado sobre o valor liquido. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FECHAMENTO_VENDA.FLAGAVANCADACLIENTEFECHAMENTO IS 'Indica se utiliza identificacao avancada do cliente no fechamento. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FECHAMENTO_VENDA.FLAGIMPRIMEBOLETOSERVIDORIMPRESSAO IS 'Indica se o boleto sera impresso pelo servidor de impressao. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FECHAMENTO_VENDA.FLAGPERMITEALTERARVALFORMAPGTO IS 'Permite alterar o valor informado na forma de pagamento. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FECHAMENTO_VENDA.FLAGVENDERITEMVALORBRUTO IS 'Permite vender item considerando valor bruto. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FECHAMENTO_VENDA.TROCODIGITAL IS 'Tipo de troco digital utilizado (S = Troco Solidario / T = Trocados).'
GO
COMMENT ON COLUMN DBA.CONFIG_FECHAMENTO_VENDA.FLAGVENDERBRINDEVALORZERADO IS 'Permite vender brindes com valor zerado. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FECHAMENTO_VENDA.FLAGPERMITEVENDAOPERADOR IS 'Permite realizar venda utilizando operador. (T/F)'
GO
COMMENT ON COLUMN DBA.CONFIG_FECHAMENTO_VENDA.DTALTERACAO IS 'Data da ultima alteracao feita no registro de configuracoes da empresa.'
GO
CALL DBA.SP_PREP_TAB_COM('CONFIG_FECHAMENTO_VENDA')
