SELECT TABNAME, COLNO, COLNAME
FROM SYSCAT.COLUMNS
WHERE TABSCHEMA = 'DBA'
  AND TABNAME IN ('EXPLAIN_OPERATOR', 'EXPLAIN_OBJECT', 'EXPLAIN_STREAM', 'EXPLAIN_PREDICATE', 'EXPLAIN_ARGUMENT')
  AND (
      COLNAME LIKE '%COST%'
      OR COLNAME LIKE '%CARD%'
      OR COLNAME LIKE '%COUNT%'
      OR COLNAME LIKE '%TYPE%'
      OR COLNAME LIKE '%ID'
      OR COLNAME IN ('OBJECT_SCHEMA', 'OBJECT_NAME', 'OBJECT_TYPE', 'ROW_COUNT', 'PAGES', 'NLEAF', 'NLEVELS',
                     'FULLKEYCARD', 'FIRSTKEYCARD', 'FIRST2KEYCARD', 'FIRST3KEYCARD', 'FIRST4KEYCARD',
                     'ARGUMENT_TYPE', 'ARGUMENT_VALUE', 'HOW_APPLIED')
  )
ORDER BY TABNAME, COLNO
@
