SET CURRENT EXPLAIN MODE EXPLAIN@

SELECT
    TMP.IDEMPRESA,
    TMP.TIPOAJUSTE,
    TMP.IDPLANILHANOTA,
    TMP.NUMNOTA,
    TMP.SERIENOTA,
    TMP.IDCLIFOR,
    TMP.DTEMISSAO,
    TMP.CHAVENFE,
    TMP.IDCSTPISCOFINS,
    TMP.PERPIS,
    TMP.PERCOFINS,
    TMP.IDCTADEBPISSAIDA,
    TMP.IDCTADEBCOFINSSAIDA,
    SUM(TMP.VALBASEPISCOFINS) AS VALBASEPISCOFINS
FROM
    (
        SELECT
            N.IDEMPRESA AS IDEMPRESA,
            1 AS TIPOAJUSTE,
            N.IDPLANILHA AS IDPLANILHANOTA,
            N.NUMNOTA AS NUMNOTA,
            N.SERIENOTA AS SERIENOTA,
            N.IDCLIFOR AS IDCLIFOR,
            NES.DTEMISSAO AS DTEMISSAO,
            COALESCE(NFE.CHAVENFE, NFCE.CHAVENFCE) AS CHAVENFE,
            PM.IDCSTPISCOFINS AS IDCSTPISCOFINS,
            CSAZ.PERPIS AS PERPIS,
            CSAZ.PERCOFINS AS PERCOFINS,
            CC.IDCTADEBPISSAIDA AS IDCTADEBPISSAIDA,
            CC.IDCTADEBCOFINSSAIDA AS IDCTADEBCOFINSSAIDA,
            CASE
                WHEN 'F' = 'T' THEN ROUND(PM.VALBASEPISCOFINS, 2)
                ELSE PM.VALBASEPISCOFINS
            END AS VALBASEPISCOFINS
        FROM
            DBA.NOTAS AS N
        JOIN
            DBA.PISCOFINS_MOVIMENTO AS PM ON
                PM.IDPLANILHA = N.IDPLANILHA AND
                PM.IDEMPRESA = N.IDEMPRESA
        JOIN
            DBA.NOTAS_ENTRADA_SAIDA AS NES ON
                NES.IDEMPRESA = N.IDEMPRESA AND
                NES.IDPLANILHA = N.IDPLANILHA
        JOIN
            DBA.CONFIG_SPED_ALIQUOTA_ZERO AS CSAZ ON
                CSAZ.IDEMPRESA = N.IDEMPRESA
        JOIN
            DBA.CONFIG_ALIQUOTA_ZERO_COI AS CAZC ON
                CAZC.IDEMPRESA = CSAZ.IDEMPRESA AND
                CAZC.IDOPERACAO = NES.IDOPERACAO
        JOIN
            DBA.CONFIG_ALIQUOTA_ZERO_PRODUTOS AS CAZP ON
                CAZP.IDEMPRESA = CSAZ.IDEMPRESA AND
                CAZP.IDPRODUTO = PM.IDPRODUTO AND
                CAZP.IDSUBPRODUTO = PM.IDSUBPRODUTO
        LEFT JOIN
            DBA.CONFIG_CONTABIL AS CC ON
                CC.IDEMPRESA = N.IDEMPRESA
        LEFT JOIN
            DBA.NOTA_FISCAL_ELETRONICA AS NFE ON
                NFE.IDEMPRESA = N.IDEMPRESA AND
                NFE.IDPLANILHA = N.IDPLANILHA
        LEFT JOIN
            DBA.NOTA_FISCAL_CONSUMIDOR_ELETRONICA AS NFCE ON
                NFCE.IDEMPRESA = N.IDEMPRESA AND
                NFCE.IDPLANILHA = N.IDPLANILHA
        WHERE
            N.IDEMPRESA = 3 AND
            NES.DTEMISSAO BETWEEN '2026-07-01' AND '2026-07-31' AND
            N.MODELO <> '65' AND
            NES.DTEMISSAO >= CSAZ.DTVIGENCIA AND
            NES.TIPOCATEGORIA <> 'D' AND
            PM.PERPIS = 0 AND
            PM.PERCOFINS = 0 AND
            PM.VALBASEPISCOFINS > 0
        UNION
        ALL
        SELECT
            N.IDEMPRESA AS IDEMPRESA,
            0 AS TIPOAJUSTE,
            N.IDPLANILHA AS IDPLANILHANOTA,
            N.NUMNOTA AS NUMNOTA,
            N.SERIENOTA AS SERIENOTA,
            N.IDCLIFOR AS IDCLIFOR,
            NES.DTEMISSAO AS DTEMISSAO,
            COALESCE(NFE.CHAVENFE, NFCE.CHAVENFCE) AS CHAVENFE,
            PM.IDCSTPISCOFINS AS IDCSTPISCOFINS,
            CSAZ.PERPIS AS PERPIS,
            CSAZ.PERCOFINS AS PERCOFINS,
            CC.IDCTADEBPISSAIDA AS IDCTADEBPISSAIDA,
            CC.IDCTADEBCOFINSSAIDA AS IDCTADEBCOFINSSAIDA,
            CASE
                WHEN 'F' = 'T' THEN ROUND(PM.VALBASEPISCOFINS, 2)
                ELSE PM.VALBASEPISCOFINS
            END AS VALBASEPISCOFINS
        FROM
            DBA.NOTAS AS N
        JOIN
            DBA.PISCOFINS_MOVIMENTO AS PM ON
                PM.IDPLANILHA = N.IDPLANILHA AND
                PM.IDEMPRESA = N.IDEMPRESA
        JOIN
            DBA.NOTAS_DEVOLUCAO AS ND ON
                ND.IDCLIFOR = N.IDCLIFOR AND
                ND.IDEMPRESA = PM.IDEMPRESA AND
                ND.IDPLANILHA = N.IDPLANILHA AND
                ND.NUMSEQUENCIADEVOLUCAO = PM.NUMSEQUENCIA AND
                ND.IDPRODUTO = PM.IDPRODUTO AND
                ND.IDSUBPRODUTO = PM.IDSUBPRODUTO
        JOIN
            DBA.PISCOFINS_MOVIMENTO AS PM_ORIGEM ON
                PM_ORIGEM.IDEMPRESA = ND.IDEMPRESA AND
                PM_ORIGEM.IDPLANILHA = ND.IDPLANILHADEVOLUCAO AND
                PM_ORIGEM.NUMSEQUENCIA = ND.NUMSEQUENCIAORIGEM AND
                PM_ORIGEM.IDPRODUTO = ND.IDPRODUTO AND
                PM_ORIGEM.IDSUBPRODUTO = ND.IDSUBPRODUTO
        JOIN
            DBA.NOTAS_ENTRADA_SAIDA AS NES ON
                NES.IDEMPRESA = N.IDEMPRESA AND
                NES.IDPLANILHA = N.IDPLANILHA
        JOIN
            DBA.NOTAS_ENTRADA_SAIDA AS NES_ORIGEM ON
                NES_ORIGEM.IDEMPRESA = ND.IDEMPRESA AND
                NES_ORIGEM.IDPLANILHA = ND.IDPLANILHADEVOLUCAO
        JOIN
            DBA.CONFIG_SPED_ALIQUOTA_ZERO AS CSAZ ON
                CSAZ.IDEMPRESA = N.IDEMPRESA
        JOIN
            DBA.CONFIG_ALIQUOTA_ZERO_COI AS CAZC ON
                CAZC.IDEMPRESA = CSAZ.IDEMPRESA AND
                CAZC.IDOPERACAO = NES_ORIGEM.IDOPERACAO
        JOIN
            DBA.CONFIG_ALIQUOTA_ZERO_PRODUTOS AS CAZP ON
                CAZP.IDEMPRESA = CSAZ.IDEMPRESA AND
                CAZP.IDPRODUTO = PM.IDPRODUTO AND
                CAZP.IDSUBPRODUTO = PM.IDSUBPRODUTO
        LEFT JOIN
            DBA.CONFIG_CONTABIL AS CC ON
                CC.IDEMPRESA = N.IDEMPRESA
        LEFT JOIN
            DBA.NOTA_FISCAL_ELETRONICA AS NFE ON
                NFE.IDEMPRESA = N.IDEMPRESA AND
                NFE.IDPLANILHA = N.IDPLANILHA
        LEFT JOIN
            DBA.NOTA_FISCAL_CONSUMIDOR_ELETRONICA AS NFCE ON
                NFCE.IDEMPRESA = N.IDEMPRESA AND
                NFCE.IDPLANILHA = N.IDPLANILHA
        WHERE
            N.IDEMPRESA = 3 AND
            NES.DTEMISSAO BETWEEN '2026-07-01' AND '2026-07-31' AND
            N.MODELO <> '65' AND
            NES.DTEMISSAO >= CSAZ.DTVIGENCIA AND
            NES.TIPOCATEGORIA = 'D' AND
            PM_ORIGEM.PERPIS = 0 AND
            PM_ORIGEM.PERCOFINS = 0 AND
            PM_ORIGEM.VALBASEPISCOFINS > 0 AND
            PM.PERPIS = 0 AND
            PM.PERCOFINS = 0 AND
            PM.VALBASEPISCOFINS > 0
    ) AS TMP
GROUP BY
    TMP.IDEMPRESA,
    TMP.TIPOAJUSTE,
    TMP.IDPLANILHANOTA,
    TMP.NUMNOTA,
    TMP.SERIENOTA,
    TMP.IDCLIFOR,
    TMP.DTEMISSAO,
    TMP.CHAVENFE,
    TMP.IDCSTPISCOFINS,
    TMP.PERPIS,
    TMP.PERCOFINS,
    TMP.IDCTADEBPISSAIDA,
    TMP.IDCTADEBCOFINSSAIDA
FOR READ ONLY@

SET CURRENT EXPLAIN MODE NO@
