SELECT
    PG.IDPRODUTO,
    PG.IDSUBPRODUTO
FROM
    DBA.PROMOCAO_GESTAO PROMO
INNER JOIN 
	DBA.PROMOCAO_GESTAO_PRODUTO PGP ON 
		PROMO.IDPROMOCAO = PGP.IDPROMOCAO
INNER JOIN 
	DBA.PROMOCAO_GESTAO_EMPRESA PGE_EMPR ON 
		PGE_EMPR.IDPROMOCAO = PROMO.IDPROMOCAO
INNER JOIN 
	DBA.PRODUTO_GRADE PG ON 
		PGP.IDPRODUTO = PG.IDPRODUTO AND 
		PGP.IDSUBPRODUTO = PG.IDSUBPRODUTO
INNER JOIN 
	DELIVERY.IFOOD_CONFIG_SYNC ICS ON 
		ICS.IDEMPRESA = PGE_EMPR.IDEMPRESA
INNER JOIN 
	DBA.PRODUTO_GRADE_ECOMMERCE PGE_ECOMM ON 
		PGE_ECOMM.IDPRODUTO = PG.IDPRODUTO AND 
		PGE_ECOMM.IDSUBPRODUTO = PG.IDSUBPRODUTO AND 
		PGE_ECOMM.IDCONFIGECOMMERCE = :id_propriedade_ecommerce
WHERE
    PG.FLAGINATIVO = 'F' AND
    ICS.IDCONFIGSYNC = :id_config_sync AND
    (PROMO.DTFIMPROMOCAO BETWEEN :dh_sync AND CURRENT TIMESTAMP)
GROUP BY
    PG.IDPRODUTO,
    PG.IDSUBPRODUTO    
UNION      
SELECT
    PG.IDPRODUTO,
    PG.IDSUBPRODUTO
FROM
    DBA.POLITICA_PRECO_PRODUTO PPP
INNER JOIN 
	DBA.PRODUTO_GRADE PG ON 
		PPP.IDPRODUTO = PG.IDPRODUTO AND 
		PPP.IDSUBPRODUTO = PG.IDSUBPRODUTO
INNER JOIN 
	DELIVERY.IFOOD_CONFIG_SYNC ICS ON 
		ICS.IDEMPRESA = PPP.IDEMPRESA
INNER JOIN 
	DBA.PRODUTO_GRADE_ECOMMERCE PGE_ECOMM ON 
		PGE_ECOMM.IDPRODUTO = PG.IDPRODUTO AND 
		PGE_ECOMM.IDSUBPRODUTO = PG.IDSUBPRODUTO AND 
		PGE_ECOMM.IDCONFIGECOMMERCE = :id_propriedade_ecommerce
WHERE
    PG.FLAGINATIVO = 'F' AND
    ICS.IDCONFIGSYNC = :id_config_sync AND
    (
        DBA.DTFIM(PPP.DTFIMPROMOCAOVAR) BETWEEN :dh_sync AND CURRENT TIMESTAMP OR
        DBA.DTFIM(PPP.DTFIMPROMOCAOATAC) BETWEEN :dh_sync AND CURRENT TIMESTAMP OR
        PPP.DTALTERACAOPROMOVAR >= :dh_sync OR
        PPP.DTALTERACAOPROMOATAC >= :dh_sync
    )
GROUP BY
    PG.IDPRODUTO,
    PG.IDSUBPRODUTO