CREATE OR REPLACE FUNCTION DBA.PROC_FIDC_PROCESSA_CONTRATOS (
	IN RA_DTINICIOFIDC DATE
)
RETURNS TABLE (
	RA_IDEXECUCAO INTEGER
)
LANGUAGE SQL
MODIFIES SQL DATA
BEGIN ATOMIC
	DECLARE RA_IDEXECUCAO INTEGER;
	DECLARE LDE_VALORSALDOCONTRATO DECIMAL(15,6);
	DECLARE LS_SQL_BACKUP VARCHAR(1000);
	DECLARE LS_PREFIXO_BACKUP VARCHAR(60);
	DECLARE LS_SUFIXO_BACKUP VARCHAR(80);
	DECLARE LI_PROX_SEQ SMALLINT DEFAULT 1;

	-- Qualquer erro em qualquer statement abaixo cai aqui
	-- e repassa o erro original para quem chamou.
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		RESIGNAL;
	END;

	-- DTINICIOFIDC é obrigatório — não existe valor padrão.
	-- Se não for informado (ou vier NULL), interrompe a execução aqui,
	-- antes de mexer em qualquer dado.
	IF RA_DTINICIOFIDC IS NULL THEN
		SIGNAL SQLSTATE '75001' SET MESSAGE_TEXT = 'DTINICIOFIDC e obrigatorio. Informe a data ao chamar a function, ex: SELECT * FROM TABLE(DBA.PROC_FIDC_PROCESSA_CONTRATOS(''2026-10-01''))';
	END IF;

	-- Gera o novo IDEXECUCAO e atribui às linhas recém-inseridas
	-- na planilha (as que ainda estão com IDEXECUCAO NULL).
	SET RA_IDEXECUCAO = NEXT VALUE FOR DBA.SEQ_FIDC_IDEXECUCAO;

	UPDATE TMP.FIDC_PLANILHA
	SET IDEXECUCAO = RA_IDEXECUCAO
	WHERE IDEXECUCAO IS NULL;

	-- -----------------------------------------------------------------
	-- INSERE OS CONTRATOS COM BASE NA PLANILHA
	-- -----------------------------------------------------------------
	INSERT INTO TMP.FIDC_CONTRATO
	SELECT
	    TMP2.IDGRUPOECONOMICO,
	    TMP2.NUMCONTRATO,
	    TMP2.NUMPARCELAS,
	    TMP2.VALOR,
	    RA_IDEXECUCAO AS IDEXECUCAO,
	    TMP2.CNPJSACADO
	FROM
	    (
	        SELECT
	            CF.IDGRUPOECONOMICO,
	            TMP.VALOR,
	            TMP.NUMCONTRATO,
	            TMP.NUMPARCELAS,
	            TMP.CHAVE,
	            TMP.CNPJSACADO
	        FROM
	            (
	                SELECT
	                    FIDC.VALOR,
	                    CAST(LEFT(FIDC.CHAVE, LENGTH(FIDC.CHAVE) - 2) AS INTEGER) AS NUMCONTRATO,
	                    CAST(RIGHT(FIDC.CHAVE, 2) AS INTEGER) AS NUMPARCELAS,
	                    FIDC.CHAVE,
	                    FIDC.CNPJSACADO
	                FROM
	                    TMP.FIDC_PLANILHA AS FIDC
	                WHERE
	                    FIDC.IDEXECUCAO = RA_IDEXECUCAO
	            ) AS TMP
	            LEFT JOIN DBA.PEDIDO_SISTEMA AS PS ON
	                PS.IDPEDIDOSISTEMA = TMP.NUMCONTRATO AND
	                PS.IDEMPRESA = 1
	            LEFT JOIN DBA.CLIENTE_FORNECEDOR AS CF ON
	                PS.IDCLIFOR = CF.IDCLIFOR
	    ) AS TMP2;

	-- -----------------------------------------------------------------
	-- BUSCA OS PEDIDOS ELEGÍVEIS PARA ENTRAR NO FIDC
	-- -----------------------------------------------------------------
	INSERT INTO TMP.FIDC_PEDIDO
	SELECT
	    TMP.IDPEDIDO,
	    TMP.IDGRUPOECONOMICO,
	    TMP.VALOR,
	    TMP.VALORORI,
	    RA_IDEXECUCAO AS IDEXECUCAO
	FROM
	    (
	        SELECT
	            DFL.IDPEDIDO,
	            CF.IDGRUPOECONOMICO,
	            SUM(DFL.VALFATURAMENTO) - COALESCE(FIDC.VALORFIDC, 0) AS VALOR,
	            SUM(DFL.VALFATURAMENTO) AS VALORORI,
	            COUNT(DISTINCT DFL.IDSUBPRODUTO) AS QTDPRODDIF,
	            MAX(CASE WHEN DFL.IDSUBPRODUTO = 2582 THEN 1 ELSE 0 END) TEMCISSMART
	        FROM
	            DBA.DADOS_FATURAMENTO_LOTE AS DFL
	            JOIN DBA.CLIENTE_FORNECEDOR AS CF ON
	                DFL.IDCLIFOR = CF.IDCLIFOR
	            LEFT JOIN LATERAL(
	                SELECT
	                    FPS.IDPEDIDO,
	                    FPS.IDEMPRESA,
	                    SUM(FPS.VALORFIDC) AS VALORFIDC
	                FROM
	                    DBA.FATURAMENTO_PEDIDOSISTEMA AS FPS
	                WHERE
	                    DFL.IDPEDIDO = FPS.IDPEDIDO AND
	                    DFL.IDEMPRESA = FPS.IDEMPRESA AND
	                    FPS.FLAGFIDC = 'T' AND
	                    FPS.FLAGENCERRADO = 'F'
	                GROUP BY
	                    FPS.IDPEDIDO,
	                    FPS.IDEMPRESA
	            ) AS FIDC (IDPEDIDO, IDEMPRESA, VALORFIDC) ON
	                DFL.IDPEDIDO = FIDC.IDPEDIDO AND
	                DFL.IDEMPRESA = FIDC.IDEMPRESA
	        WHERE
	            DFL.IDSITUACAO = 1 AND
	            DFL.IDEMPRESA = 1
	        GROUP BY
	            DFL.IDPEDIDO,
	            CF.IDGRUPOECONOMICO,
	            FIDC.VALORFIDC
	    ) AS TMP
	WHERE
	    TMP.TEMCISSMART = 0 OR (TMP.TEMCISSMART = 1 AND TMP.QTDPRODDIF > 1) AND
	    TMP.VALOR > 10;

	-- -----------------------------------------------------------------
	-- INSERE OS PEDIDOS SEM REPETIR
	-- -----------------------------------------------------------------
	FOR LOOPQUERY AS LQUERY CURSOR WITH HOLD FOR
	    SELECT
	        CONT.IDCONTRATO AS LI_IDCONTRATO,
	        CONT.IDGRUPOECONOMICO AS LI_IDGRUPOECONOMICO,
	        CONT.VALOR AS LDE_VALORCONTRATO,
	        CONT.IDEXECUCAO AS LI_IDEXECUCAO
	    FROM
	        TMP.FIDC_CONTRATO AS CONT
	        LEFT JOIN TMP.FIDC_CONTRATO_PEDIDO AS FCP ON
	            CONT.IDCONTRATO = FCP.IDCONTRATO AND
	            CONT.IDGRUPOECONOMICO = FCP.IDGRUPOECONOMICO AND
	            CONT.IDEXECUCAO = FCP.IDEXECUCAO
	    WHERE
	        FCP.IDCONTRATO IS NULL AND
	        CONT.IDEXECUCAO = RA_IDEXECUCAO
	    GROUP BY
	        CONT.IDCONTRATO, CONT.IDGRUPOECONOMICO, CONT.VALOR, CONT.IDEXECUCAO
	DO
	    SET LDE_VALORSALDOCONTRATO = LDE_VALORCONTRATO - COALESCE((
	        SELECT
	            SUM(CP.VALORMATCH)
	        FROM
	            TMP.FIDC_CONTRATO_PEDIDO AS CP
	        WHERE
	            CP.IDCONTRATO = LI_IDCONTRATO AND
	            CP.IDGRUPOECONOMICO = LI_IDGRUPOECONOMICO AND
	            CP.IDEXECUCAO = LI_IDEXECUCAO
	    ),0);
	
	    --TODO mudar isso aqui pra ordenar pelo maior valor
	    FOR LOOPQUERY AS LQUERY CURSOR WITH HOLD FOR
	        SELECT
	            TMP.LI_IDPEDIDO AS LI_IDPEDIDO,
	            TMP.LDE_VALORSALDOPEDIDO AS LDE_VALORSALDOPEDIDO
	        FROM
	            (
	                SELECT
	                    PED.IDPEDIDO AS LI_IDPEDIDO,
	                    PED.VALORPEDIDO - COALESCE(SUM(CP.VALORMATCH),0) AS LDE_VALORSALDOPEDIDO
	                FROM
	                    TMP.FIDC_PEDIDO AS PED
	                    LEFT JOIN TMP.FIDC_CONTRATO_PEDIDO AS CP ON
	                        PED.IDPEDIDO = CP.IDPEDIDO AND
	                        PED.IDGRUPOECONOMICO = CP.IDGRUPOECONOMICO AND
	                        PED.IDEXECUCAO = CP.IDEXECUCAO
	                WHERE
	                    PED.IDGRUPOECONOMICO = LI_IDGRUPOECONOMICO AND
	                    PED.IDEXECUCAO = LI_IDEXECUCAO
	               GROUP BY
	                   PED.IDPEDIDO, PED.VALORPEDIDO
	               HAVING
	                    LDE_VALORSALDOCONTRATO <= (PED.VALORPEDIDO - COALESCE(SUM(CP.VALORMATCH),0) + 0.05)
	            ) AS TMP
	        ORDER BY
	            TMP.LDE_VALORSALDOPEDIDO DESC
	    DO
	       IF NOT EXISTS(
	           SELECT 1 FROM TMP.FIDC_CONTRATO_PEDIDO WHERE IDCONTRATO = LI_IDCONTRATO AND IDGRUPOECONOMICO = LI_IDGRUPOECONOMICO AND IDEXECUCAO = LI_IDEXECUCAO
	       ) THEN
	           INSERT INTO TMP.FIDC_CONTRATO_PEDIDO (IDCONTRATO, IDPEDIDO, IDGRUPOECONOMICO, VALORMATCH, IDEXECUCAO) VALUES (
	                 LI_IDCONTRATO,
	                 LI_IDPEDIDO,
	                 LI_IDGRUPOECONOMICO,
	                 LDE_VALORSALDOCONTRATO,
	                 RA_IDEXECUCAO
	           );
	       END IF;
	    END FOR;
	END FOR;

	-- -----------------------------------------------------------------
	-- INSERE OS QUE VAI REPETIR
	-- -----------------------------------------------------------------
	FOR LOOPQUERY AS LQUERY CURSOR WITH HOLD FOR
	    SELECT
	        CONT.IDCONTRATO AS LI_IDCONTRATO,
	        CONT.IDGRUPOECONOMICO AS LI_IDGRUPOECONOMICO,
	        CONT.VALOR AS LDE_VALORCONTRATO,
	        CONT.IDEXECUCAO AS LI_IDEXECUCAO
	    FROM
	        TMP.FIDC_CONTRATO AS CONT
	        LEFT JOIN TMP.FIDC_CONTRATO_PEDIDO AS FCP ON
	            CONT.IDCONTRATO = FCP.IDCONTRATO AND
	            CONT.IDGRUPOECONOMICO = FCP.IDGRUPOECONOMICO AND
	            CONT.IDEXECUCAO = FCP.IDEXECUCAO
	    WHERE
	        FCP.IDCONTRATO IS NULL AND
	        CONT.IDGRUPOECONOMICO IS NOT NULL AND
	        CONT.IDEXECUCAO = RA_IDEXECUCAO
	    GROUP BY
	        CONT.IDCONTRATO, CONT.IDGRUPOECONOMICO, CONT.VALOR, CONT.IDEXECUCAO
	DO
	    FOR LOOPQUERY AS LQUERY CURSOR WITH HOLD FOR
	        SELECT
	            TMP.LI_IDPEDIDO AS LI_IDPEDIDO,
	            TMP.LDE_VALORSALDOPEDIDO AS LDE_VALORSALDOPEDIDO
	        FROM
	            (
	                SELECT
	                    PED.IDPEDIDO AS LI_IDPEDIDO,
	                    (PED.VALORPEDIDO - COALESCE(SUM(CP.VALORMATCH),0)) + 0.05 AS LDE_VALORSALDOPEDIDO
	                FROM
	                    TMP.FIDC_PEDIDO AS PED
	                    LEFT JOIN TMP.FIDC_CONTRATO_PEDIDO AS CP ON
	                        PED.IDPEDIDO = CP.IDPEDIDO AND
	                        PED.IDGRUPOECONOMICO = CP.IDGRUPOECONOMICO AND
	                        PED.IDEXECUCAO = CP.IDEXECUCAO
	                WHERE
	                    PED.IDGRUPOECONOMICO = LI_IDGRUPOECONOMICO AND
	                    PED.IDEXECUCAO = LI_IDEXECUCAO
	               GROUP BY
	                   PED.IDPEDIDO, PED.VALORPEDIDO
	               HAVING
	                    PED.VALORPEDIDO - COALESCE(SUM(CP.VALORMATCH),0) > 0
	            ) AS TMP
	        ORDER BY
	            TMP.LDE_VALORSALDOPEDIDO DESC
	    DO
	       SET LDE_VALORSALDOCONTRATO = LDE_VALORCONTRATO - COALESCE((
	            SELECT
	                SUM(CP.VALORMATCH)
	            FROM
	                TMP.FIDC_CONTRATO_PEDIDO AS CP
	            WHERE
	                CP.IDCONTRATO = LI_IDCONTRATO AND
	                CP.IDGRUPOECONOMICO = LI_IDGRUPOECONOMICO AND
	                CP.IDEXECUCAO = LI_IDEXECUCAO
	        ),0);
	
	        IF LDE_VALORSALDOCONTRATO > 0 AND LDE_VALORSALDOCONTRATO > LDE_VALORSALDOPEDIDO THEN
	            INSERT INTO TMP.FIDC_CONTRATO_PEDIDO (IDCONTRATO, IDPEDIDO, IDGRUPOECONOMICO, VALORMATCH, IDEXECUCAO) VALUES (
	                 LI_IDCONTRATO,
	                 LI_IDPEDIDO,
	                 LI_IDGRUPOECONOMICO,
	                 LDE_VALORSALDOPEDIDO,
	                 RA_IDEXECUCAO
	           );
	        ELSEIF LDE_VALORSALDOCONTRATO > 0 AND LDE_VALORSALDOCONTRATO <= LDE_VALORSALDOPEDIDO THEN
	           INSERT INTO TMP.FIDC_CONTRATO_PEDIDO (IDCONTRATO, IDPEDIDO, IDGRUPOECONOMICO, VALORMATCH, IDEXECUCAO) VALUES (
	                 LI_IDCONTRATO,
	                 LI_IDPEDIDO,
	                 LI_IDGRUPOECONOMICO,
	                 LDE_VALORSALDOCONTRATO,
	                 RA_IDEXECUCAO
	           );
	       END IF;
	    END FOR;
	
	    SET LDE_VALORSALDOCONTRATO = LDE_VALORCONTRATO - COALESCE((
	        SELECT
	            SUM(CP.VALORMATCH)
	        FROM
	            TMP.FIDC_CONTRATO_PEDIDO AS CP
	        WHERE
	            CP.IDCONTRATO = LI_IDCONTRATO AND
	            CP.IDGRUPOECONOMICO = LI_IDGRUPOECONOMICO AND
	            CP.IDEXECUCAO = LI_IDEXECUCAO
	    ),0);
	
	    IF LDE_VALORSALDOCONTRATO > 0 THEN
	        DELETE FROM TMP.FIDC_CONTRATO_PEDIDO WHERE IDCONTRATO = LI_IDCONTRATO AND IDEXECUCAO = LI_IDEXECUCAO;
	    END IF;
	END FOR;

	-- -----------------------------------------------------------------
	-- CRIA BACKUP DA TABELA QUE VAI SER ALTERADA
	-- Nome FATURAMENTO_PEDIDOSISTEMA_AAAA_MM_DD_SS, com SS
	-- sequencial de 2 dígitos — consulta o catálogo pra descobrir o
	-- próximo número disponível hoje (permite rodar >1 vez no dia).
	-- -----------------------------------------------------------------
	SET LS_PREFIXO_BACKUP = 'FATURAMENTO_PEDIDOSISTEMA_' || VARCHAR_FORMAT(CURRENT DATE, 'YYYYMMDD') || '_';

	SELECT COALESCE(MAX(INTEGER(SUBSTR(TABNAME, LENGTH(LS_PREFIXO_BACKUP) + 1))), 0) + 1
	INTO LI_PROX_SEQ
	FROM SYSCAT.TABLES
	WHERE TABSCHEMA = 'TMP' AND TABNAME LIKE LS_PREFIXO_BACKUP || '%';

	SET LS_SUFIXO_BACKUP = LS_PREFIXO_BACKUP || RIGHT('00' || TRIM(CHAR(LI_PROX_SEQ)), 2);

	SET LS_SQL_BACKUP = 'CREATE TABLE TMP.' || LS_SUFIXO_BACKUP || ' LIKE DBA.FATURAMENTO_PEDIDOSISTEMA';
	EXECUTE IMMEDIATE LS_SQL_BACKUP;

	SET LS_SQL_BACKUP = 'INSERT INTO TMP.' || LS_SUFIXO_BACKUP || ' SELECT * FROM DBA.FATURAMENTO_PEDIDOSISTEMA';
	EXECUTE IMMEDIATE LS_SQL_BACKUP;

	-- -----------------------------------------------------------------
	-- INSERE OS QUE AINDA NÃO EXISTEM NO FATURAMENTO_PEDIDOSISTEMA
	-- -----------------------------------------------------------------
	FOR LOOPQUERY AS LQUERY CURSOR WITH HOLD FOR
	    SELECT
	        FCP.IDPEDIDO AS LI_IDPEDIDO,
	        FCP.IDCONTRATO AS LI_IDCONTRATO,
	        FCP.VALORMATCH AS LDE_VALOR,
	        PED.IDEMPRESA AS LI_IDEMPRESA,
	        PED.IDPRODUTO AS LI_IDPRODUTO,
	        PED.IDSUBPRODUTO AS LI_IDSUBPRODUTO,
	        FC.NUMPARCELAS AS LI_NUMPARCELAS,
	        FCP.IDEXECUCAO AS LI_IDEXECUCAO
	    FROM
	        TMP.FIDC_CONTRATO_PEDIDO AS FCP
	        LEFT JOIN TMP.FIDC_CONTRATO AS FC ON
	            FCP.IDCONTRATO = FC.IDCONTRATO AND
	            FCP.IDGRUPOECONOMICO = FC.IDGRUPOECONOMICO AND
	            FCP.IDEXECUCAO = FC.IDEXECUCAO
	        LEFT JOIN LATERAL(
	            SELECT
	                DFL.IDPEDIDO,
	                DFL.IDPRODUTO,
	                DFL.IDSUBPRODUTO,
	                DFL.IDEMPRESA,
	                ROW_NUMBER() OVER (PARTITION BY DFL.IDPEDIDO ORDER BY DFL.VALFATURAMENTO DESC) AS LINHA
	            FROM
	                DBA.DADOS_FATURAMENTO_LOTE AS DFL
	            WHERE
	                DFL.IDPEDIDO = FCP.IDPEDIDO AND
	                DFL.IDSITUACAO = 1
	        ) AS PED ON
	            PED.IDPEDIDO = FCP.IDPEDIDO AND
	            PED.LINHA = 1
	        LEFT JOIN DBA.FATURAMENTO_PEDIDOSISTEMA AS FP ON
	            FP.IDPEDIDO = FCP.IDPEDIDO AND
	            FP.IDPEDIDOSISTEMA = FCP.IDCONTRATO AND
	            FP.IDEMPRESA = 1 AND
	            FP.IDPRODUTO = PED.IDPRODUTO AND
	            FP.IDSUBPRODUTO = PED.IDSUBPRODUTO AND
	            FP.FLAGFIDC = 'F'
	    WHERE
	        FCP.STATUSFIDC = 'PENDENTE' AND
	        FCP.IDEXECUCAO = RA_IDEXECUCAO AND
	        FP.IDPEDIDOSISTEMA IS NULL
	    ORDER BY
	        FCP.IDCONTRATO DESC
	DO
	    INSERT INTO DBA.FATURAMENTO_PEDIDOSISTEMA(IDPEDIDO, IDPEDIDOSISTEMA, IDEMPRESA, IDPRODUTO, IDSUBPRODUTO, VALOR, CLASSIFICACAO, FLAGFIDC, VALORFIDC, PRAZOFIDC, DTINICIOFIDC, IDCUSTODIANTEFIDC) VALUES (
	        LI_IDPEDIDO,
	        LI_IDCONTRATO,
	        LI_IDEMPRESA,
	        LI_IDPRODUTO,
	        LI_IDSUBPRODUTO,
	        0,
	        'A',
	        'T',
	        LDE_VALOR,
	        LI_NUMPARCELAS,
	        RA_DTINICIOFIDC,
	        2
	    );
	
	    UPDATE TMP.FIDC_CONTRATO_PEDIDO SET STATUSFIDC = 'INSERIDO' WHERE IDPEDIDO = LI_IDPEDIDO AND IDCONTRATO = LI_IDCONTRATO AND IDEXECUCAO = LI_IDEXECUCAO;
	END FOR;

	-- -----------------------------------------------------------------
	-- ATUALIZA OS QUE JÁ EXISTEM NO FATURAMENTO_PEDIDOSISTEMA
	-- -----------------------------------------------------------------
	FOR LOOPQUERY AS LQUERY CURSOR WITH HOLD FOR
	    SELECT
	        FCP.IDPEDIDO AS LI_IDPEDIDO,
	        FCP.IDCONTRATO AS LI_IDCONTRATO,
	        FCP.VALORMATCH AS LDE_VALOR,
	        PED.IDEMPRESA AS LI_IDEMPRESA,
	        PED.IDPRODUTO AS LI_IDPRODUTO,
	        PED.IDSUBPRODUTO AS LI_IDSUBPRODUTO,
	        FC.NUMPARCELAS AS LI_NUMPARCELAS,
	        FCP.IDEXECUCAO AS LI_IDEXECUCAO
	    FROM
	        TMP.FIDC_CONTRATO_PEDIDO AS FCP
	        LEFT JOIN TMP.FIDC_CONTRATO AS FC ON
	            FCP.IDCONTRATO = FC.IDCONTRATO AND
	            FCP.IDGRUPOECONOMICO = FC.IDGRUPOECONOMICO AND
	            FCP.IDEXECUCAO = FC.IDEXECUCAO
	        LEFT JOIN LATERAL(
	            SELECT
	                DFL.IDPEDIDO,
	                DFL.IDPRODUTO,
	                DFL.IDSUBPRODUTO,
	                DFL.IDEMPRESA,
	                ROW_NUMBER() OVER (PARTITION BY DFL.IDPEDIDO ORDER BY DFL.VALFATURAMENTO DESC) AS LINHA
	            FROM
	                DBA.DADOS_FATURAMENTO_LOTE AS DFL
	            WHERE
	                DFL.IDPEDIDO = FCP.IDPEDIDO AND
	                DFL.IDSITUACAO = 1
	        ) AS PED ON
	            PED.IDPEDIDO = FCP.IDPEDIDO AND
	            PED.LINHA = 1
	        JOIN DBA.FATURAMENTO_PEDIDOSISTEMA AS FP ON
	            FP.IDPEDIDO = FCP.IDPEDIDO AND
	            FP.IDPEDIDOSISTEMA = FCP.IDCONTRATO AND
	            FP.IDEMPRESA = 1 AND
	            FP.IDPRODUTO = PED.IDPRODUTO AND
	            FP.IDSUBPRODUTO = PED.IDSUBPRODUTO AND
	            FP.FLAGFIDC = 'F'
	    WHERE
	        FCP.STATUSFIDC = 'PENDENTE' AND
	        FCP.IDEXECUCAO = RA_IDEXECUCAO
	    ORDER BY
	        FCP.IDCONTRATO DESC
	DO
	    UPDATE DBA.FATURAMENTO_PEDIDOSISTEMA SET FLAGFIDC = 'T', VALORFIDC = LDE_VALOR, PRAZOFIDC = LI_NUMPARCELAS, DTINICIOFIDC = RA_DTINICIOFIDC, IDCUSTODIANTEFIDC = 2 WHERE
	        IDPEDIDO = LI_IDPEDIDO AND
	        IDPEDIDOSISTEMA = LI_IDCONTRATO AND
	        IDEMPRESA = LI_IDEMPRESA AND
	        IDPRODUTO = LI_IDPRODUTO AND
	        IDSUBPRODUTO = LI_IDSUBPRODUTO AND
	        FLAGENCERRADO = 'F'
	    ;
	
	    UPDATE TMP.FIDC_CONTRATO_PEDIDO SET STATUSFIDC = 'INSERIDO' WHERE IDPEDIDO = LI_IDPEDIDO AND IDCONTRATO = LI_IDCONTRATO AND IDEXECUCAO = LI_IDEXECUCAO;
	END FOR;

	-- Retorna o identificador gerado para a execucao atual.
	RETURN (VALUES(RA_IDEXECUCAO));
END
