CREATE OR REPLACE FUNCTION DBA.UF_ORIGEM_PRODUTO_CENARIO_FISCAL (
    RA_IDEMPRESA    INTEGER,
    RA_IDPRODUTO    INTEGER,
    RA_IDSUBPRODUTO INTEGER,
    RA_TIPOOPERACAO CHAR(1)
)
RETURNS INTEGER
LANGUAGE SQL
READS SQL DATA
NO EXTERNAL ACTION
RETURN
    COALESCE((
        SELECT
            CFPC.IDORIGEMPRODUTO
        FROM
            DBA.CENARIO_FISCAL_PADRAO_PRODUTO_EMPRESA CFPPE
        JOIN
            DBA.CENARIO_FISCAL_PADRAO_COMPOSICAO CFPC ON
                CFPC.IDCENARIOPADRAO = CFPPE.IDCENARIOPADRAO
        WHERE
            CFPPE.IDEMPRESA = RA_IDEMPRESA AND
            CFPPE.IDPRODUTO = RA_IDPRODUTO AND
            CFPPE.IDSUBPRODUTO = RA_IDSUBPRODUTO AND
            CFPC.OPERACAO = RA_TIPOOPERACAO
        FETCH FIRST 1 ROW ONLY
    ), (
        SELECT
            CFPC.IDORIGEMPRODUTO
        FROM
            DBA.PRODUTO_GRADE PG
        JOIN
            DBA.CENARIO_FISCAL_GRUPO CFG ON
                CFG.IDGRUPO = PG.IDGRUPOCENARIOFISCAL
        JOIN
            DBA.CENARIO_FISCAL_PADRAO_PRODUTO_EMPRESA CFPPE ON
                CFPPE.IDPRODUTO = CFG.IDPRODUTOMESTRE AND
                CFPPE.IDSUBPRODUTO = CFG.IDSUBPRODUTOMESTRE
        JOIN
            DBA.CENARIO_FISCAL_PADRAO_COMPOSICAO CFPC ON
                CFPC.IDCENARIOPADRAO = CFPPE.IDCENARIOPADRAO
        WHERE
            PG.IDPRODUTO = RA_IDPRODUTO AND
            PG.IDSUBPRODUTO = RA_IDSUBPRODUTO AND
            PG.IDGRUPOCENARIOFISCAL IS NOT NULL AND
            CFPPE.IDEMPRESA = RA_IDEMPRESA AND
            CFPC.OPERACAO = RA_TIPOOPERACAO
        FETCH FIRST 1 ROW ONLY
    ));
