-- CATSP - implantaÃ§Ã£o completa do levantamento para restituiÃ§Ã£o.
-- Cria as tabelas, importa os NCMs e cria a Ãºnica SP de processamento.
-- ExecuÃ§Ã£o (DB2 CLP): db2 -td@ -vf 01_deploy_catsp_restituicao.sql
-- O arquivo nÃ£o contÃ©m credenciais de conexÃ£o.
--
-- ApÃ³s a implantaÃ§Ã£o, execute:
-- CALL DBA.SP_CATSP_PROCESSA_RESTITUICAO(DATE('2026-09-30'))@

-- CATSP - processamento de produtos por NCM
-- Fonte: Relacao_NCMs_Anexos_VII_VIII_XIV_XVIII_XXI.xlsx
-- Execucao (DB2 CLP): db2 -td@ -vf 01_deploy_catsp_processamento.sql
-- O arquivo nao contem dados de conexao.

CREATE TABLE DBA.CATSP_NCM (
    ANEXO                VARCHAR(8)   NOT NULL,
    CEST                 VARCHAR(10)  NOT NULL,
    NCM                  VARCHAR(10)  NOT NULL,
    NCM_SEM_PONTUACAO    VARCHAR(8)   NOT NULL,
    DESCRICAO            VARCHAR(500) NOT NULL,
    CONSTRAINT PK_CATSP_NCM PRIMARY KEY (ANEXO, CEST, NCM)
)@

CREATE INDEX DBA.IX_CATSP_NCM_BUSCA
    ON DBA.CATSP_NCM (NCM_SEM_PONTUACAO)@

CREATE TABLE DBA.CATSP_PRODUTO (
    IDPRODUTO            INTEGER        NOT NULL,
    IDSUBPRODUTO         INTEGER        NOT NULL,
    DESCRICAO_PRODUTO    VARCHAR(60)    NOT NULL,
    NCM                  VARCHAR(8)     NOT NULL,
    CEST                 VARCHAR(7),
    UNIDADE_MEDIDA       VARCHAR(2),
    QTD_ESTOQUE          DECIMAL(18, 6) NOT NULL,
    DTMOVIMENTO          DATE           NOT NULL,
    CONSTRAINT PK_CATSP_PRODUTO PRIMARY KEY
        (IDPRODUTO, IDSUBPRODUTO, DTMOVIMENTO)
)@

CREATE INDEX DBA.IX_CATSP_PRODUTO_NCM
    ON DBA.CATSP_PRODUTO (NCM)@

-- Carga da relacao de NCMs da planilha.
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('VII', '16.001.00', '4011.10.00', '40111000', 'Pneus novos, dos tipos utilizados em automóveis de passageiros')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('VII', '16.002.00', '4011', '4011', 'Pneus novos, dos tipos utilizados em caminhões, ônibus, aviões, máquinas de terraplenagem, construção e conservação de estradas, máquinas e tratores agrícolas')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('VII', '16.003.00', '4011.40.00', '40114000', 'Pneus novos para motocicletas')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('VII', '16.005.00', '4011.50.00', '40115000', 'Pneus novos de borracha dos tipos utilizados em bicicletas')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('VII', '16.007.00', '4012.90', '401290', 'Protetores de borracha')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('VII', '16.008.00', '4013', '4013', 'Câmaras de ar de borracha')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('VII', '16.009.00', '4013.20.00', '40132000', 'Câmaras de ar de borracha dos tipos utilizados em bicicletas')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('VIII', '24.001.00', '3208', '3208', 'Tintas, vernizes')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('VIII', '24.001.00', '3209', '3209', 'Tintas, vernizes')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('VIII', '24.001.00', '3210.00', '321000', 'Tintas, vernizes')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('VIII', '24.002.00', '2821', '2821', 'Xadrez e pós assemelhados')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('VIII', '24.002.00', '3204.17.00', '32041700', 'Xadrez e pós assemelhados')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('VIII', '24.002.00', '3206', '3206', 'Xadrez e pós assemelhados')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('VIII', '24.002.00', '3206.11.10', '32061110', 'Pigmentos à base de dióxido de titânio')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('VIII', '24.002.00', '3206.11.19', '32061119', 'Pigmentos à base de dióxido de titânio')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('VIII', '24.003.00', '3204', '3204', 'Corantes para aplicação em bases, tintas e vernizes')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('VIII', '24.003.00', '3205.00.00', '32050000', 'Corantes para aplicação em bases, tintas e vernizes')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('VIII', '24.003.00', '3212', '3212', 'Corantes para aplicação em bases, tintas e vernizes')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XVIII', '08.001.00', '4016.99.90', '40169990', 'Ferramentas de borracha vulcanizada não endurecida')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XVIII', '08.002.00', '4417.00.10', '44170010', 'Ferramentas, armações e cabos de ferramentas, de madeira')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XVIII', '08.002.00', '4417.00.90', '44170090', 'Ferramentas, armações e cabos de ferramentas, de madeira')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XVIII', '08.003.00', '6804', '6804', 'Mós e artefatos semelhantes; pedras para amolar ou polir')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XVIII', '08.004.00', '8201', '8201', 'Ferramentas manuais para agricultura, horticultura ou silvicultura')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XVIII', '08.007.00', '8202', '8202', 'Serras manuais e outras folhas de serras')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XVIII', '08.008.00', '8203', '8203', 'Limas, grosas, alicates e ferramentas semelhantes')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XVIII', '08.009.00', '8204', '8204', 'Chaves de porcas, manuais')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XVIII', '08.010.00', '8205', '8205', 'Ferramentas manuais não especificadas')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XVIII', '08.011.00', '8206.00.00', '82060000', 'Ferramentas de pelo menos duas das posições 8202 a 8205')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XVIII', '08.013.00', '8207', '8207', 'Outras ferramentas intercambiáveis')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XVIII', '08.014.00', '8208', '8208', 'Facas e lâminas cortantes para máquinas ou aparelhos mecânicos')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XVIII', '08.016.00', '8209.00', '820900', 'Plaquetas, varetas, pontas e objetos semelhantes para ferramentas')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XVIII', '08.017.00', '8211', '8211', 'Facas de lâmina cortante ou serrilhada')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XVIII', '08.018.00', '8213', '8213', 'Tesouras e suas lâminas')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XVIII', '08.019.00', '8467', '8467', 'Ferramentas pneumáticas, hidráulicas ou com motor incorporado')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XVIII', '08.020.00', '9015', '9015', 'Instrumentos e aparelhos de geodesia, topografia e similares')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XVIII', '08.021.00', '9017.20.00', '90172000', 'Instrumentos de desenho, traçado ou cálculo')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XVIII', '08.021.00', '9017.30', '901730', 'Instrumentos de desenho, traçado ou cálculo')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XVIII', '08.021.00', '9017.80', '901780', 'Instrumentos de desenho, traçado ou cálculo')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XVIII', '08.021.00', '9017.90.90', '90179090', 'Partes e acessórios')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XVIII', '08.022.00', '9025.11.90', '90251190', 'Termômetros')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XVIII', '08.022.00', '9025.90.10', '90259010', 'Partes e acessórios de termômetros')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XVIII', '08.023.00', '9025.19', '902519', 'Pirômetros')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XVIII', '08.023.00', '9025.90.90', '90259090', 'Partes e acessórios de pirômetros')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XXI', '12.001.00', '8504', '8504', 'Transformadores, bobinas de reatância e de autoindução')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XXI', '12.002.00', '8516', '8516', 'Aquecedores elétricos de água, chuveiros, torneiras, resistências e partes')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XXI', '12.003.00', '8535', '8535', 'Aparelhos para interrupção, seccionamento, proteção, derivação, ligação ou conexão de circuitos elétricos para tensão superior a 1.000V')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XXI', '12.004.00', '8536', '8536', 'Aparelhos para interrupção, seccionamento, proteção, derivação, ligação ou conexão de circuitos elétricos para tensão não superior a 1.000V')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XXI', '12.005.00', '8538', '8538', 'Partes destinadas aos aparelhos das posições 8535 e 8536')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XXI', '12.006.00', '7413.00.00', '74130000', 'Cabos, tranças e semelhantes, de cobre, não isolados para usos elétricos')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XXI', '12.007.00', '8544', '8544', 'Fios, cabos e outros condutores isolados ou não para usos elétricos')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XXI', '12.007.00', '7605', '7605', 'Fios e cabos de alumínio para usos elétricos')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XXI', '12.007.00', '7614', '7614', 'Cordas, cabos, tranças e semelhantes, de alumínio')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XXI', '12.008.00', '8546', '8546', 'Isoladores de qualquer matéria, para usos elétricos')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XXI', '12.009.00', '8547', '8547', 'Peças isolantes para máquinas, aparelhos e instalações elétricas')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.001.00', '3815.12.10', '38151210', 'Catalisadores em colmeia cerâmica ou metálica')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.001.00', '3815.12.90', '38151290', 'Outros catalisadores')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.002.00', '3917', '3917', 'Tubos e acessórios de plásticos')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.003.00', '3918.10.00', '39181000', 'Protetores de caçamba')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.004.00', '3923.30.00', '39233000', 'Reservatórios de óleo')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.005.00', '3926.30.00', '39263000', 'Frisos, decalques, molduras e acabamentos')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.006.00', '4010.3', '40103', 'Correias de transmissão')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.006.00', '5910.00.00', '59100000', 'Correias de transmissão de matérias têxteis')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.007.00', '4016.93.00', '40169300', 'Juntas, gaxetas e elementos de vedação')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.007.00', '4823.90.9', '4823909', 'Juntas, gaxetas e elementos de vedação')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.008.00', '4016.10.10', '40161010', 'Partes de veículos automóveis, tratores e máquinas autopropulsadas')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.009.00', '5705.00.00', '57050000', 'Tapetes e revestimentos')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.010.00', '5903.90.00', '59039000', 'Tecidos impregnados, revestidos ou estratificados com plástico')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.011.00', '5909.00.00', '59090000', 'Mangueiras e tubos de matérias têxteis')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.012.00', '6306.1', '63061', 'Encerados e toldos')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.013.00', '6506.10.00', '65061000', 'Capacetes e artefatos de proteção')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.014.00', '6813', '6813', 'Guarnições de fricção')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.015.00', '7007.11.00', '70071100', 'Vidros para aplicação automotiva')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.015.00', '7007.21.00', '70072100', 'Vidros para aplicação automotiva')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.016.00', '7009.10.00', '70091000', 'Espelhos retrovisores')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.017.00', '7014.00.00', '70140000', 'Lentes de faróis e lanternas')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.018.00', '7311.00.00', '73110000', 'Cilindro de aço para GNV')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.020.00', '7320', '7320', 'Molas e folhas de molas')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.021.00', '7325', '7325', 'Obras moldadas de ferro fundido, ferro ou aço')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.022.00', '7806.00', '780600', 'Peso de chumbo para balanceamento de roda')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.023.00', '8007.00.90', '80070090', 'Peso para balanceamento de roda e outros utensílios de estanho')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.024.00', '8301.20', '830120', 'Fechaduras e partes de fechaduras')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.024.00', '8301.60', '830160', 'Fechaduras e partes de fechaduras')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.025.00', '8301.70', '830170', 'Chaves apresentadas isoladamente')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.026.00', '8302.10.00', '83021000', 'Dobradiças, guarnições e ferragens')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.026.00', '8302.30.00', '83023000', 'Dobradiças, guarnições e ferragens')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.027.00', '8310.00', '831000', 'Triângulo de segurança')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.028.00', '8407.3', '84073', 'Motores de pistão alternativo')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.029.00', '8408.20', '840820', 'Motores para propulsão de veículos automotores')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.030.00', '8409.9', '84099', 'Partes destinadas aos motores 8407 ou 8408')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.031.00', '8412.2', '84122', 'Motores hidráulicos')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.032.00', '8413.30', '841330', 'Bombas para combustíveis, lubrificantes ou líquidos de arrefecimento')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.033.00', '8414.10.00', '84141000', 'Bombas de vácuo')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.034.00', '8414.80.1', '8414801', 'Compressores e turbocompressores de ar')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.034.00', '8414.80.2', '8414802', 'Compressores e turbocompressores de ar')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.035.00', '8413.91.90', '84139190', 'Partes de bombas')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.035.00', '8414.90.10', '84149010', 'Partes de compressores')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.035.00', '8414.90.3', '8414903', 'Partes de compressores e turbocompressores')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.035.00', '8414.90.39', '84149039', 'Partes de compressores e turbocompressores')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.036.00', '8415.20', '841520', 'Máquinas e aparelhos de ar condicionado')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.037.00', '8421.23.00', '84212300', 'Aparelhos para filtrar óleos minerais')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.038.00', '8421.29.90', '84212990', 'Filtros a vácuo')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.039.00', '8421.9', '84219', 'Partes de aparelhos para filtrar ou depurar')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.040.00', '8424.10.00', '84241000', 'Extintores')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.041.00', '8421.31.00', '84213100', 'Filtros de entrada de ar')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.042.00', '8421.32.00', '84213200', 'Depuradores por conversão catalítica')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.042.00', '8421.39.20', '84213920', 'Depuradores por conversão catalítica')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.043.00', '8425.42.00', '84254200', 'Macacos')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.044.00', '8431.10.10', '84311010', 'Partes para macacos')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.045.00', '8431.49.2', '8431492', 'Partes destinadas a máquinas agrícolas ou rodoviárias')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.045.01', '8433.90.90', '84339090', 'Partes destinadas a máquinas agrícolas ou rodoviárias')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.046.00', '8481.10.00', '84811000', 'Válvulas redutoras de pressão')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.047.00', '8481.2', '84812', 'Válvulas para transmissão óleo-hidráulica ou pneumática')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.048.00', '8481.80.92', '84818092', 'Válvulas solenoides')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.049.00', '8482', '8482', 'Rolamentos')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.050.00', '8483', '8483', 'Árvores de transmissão, engrenagens, eixos, redutores, embreagens e similares')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.051.00', '8484', '8484', 'Juntas metaloplásticas e juntas de vedação mecânicas')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.052.00', '8505.20', '850520', 'Acoplamentos, embreagens, variadores e freios eletromagnéticos')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.053.00', '8507.10', '850710', 'Acumuladores elétricos de chumbo')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.053.01', '8507.10.10', '85071010', 'Acumuladores elétricos de chumbo')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.054.00', '8511', '8511', 'Aparelhos e dispositivos elétricos de ignição ou arranque')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.055.00', '8512.20', '851220', 'Aparelhos elétricos de iluminação ou sinalização')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.055.00', '8512.40', '851240', 'Limpadores, degeladores e desembaçadores elétricos')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.055.00', '8512.90.00', '85129000', 'Partes dos aparelhos elétricos')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.056.00', '8517.14.10', '85171410', 'Telefones móveis do tipo utilizado em veículos automóveis')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.056.00', '8517.12.13', '85171213', 'Telefones móveis do tipo utilizado em veículos automóveis')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.057.00', '8518', '8518', 'Alto-falantes, amplificadores e partes')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.058.00', '8518.50.00', '85185000', 'Aparelhos elétricos de amplificação de som')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.059.00', '8519.81', '851981', 'Aparelhos de reprodução de som')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.060.00', '8525.50.1', '8525501', 'Aparelhos transmissores')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.060.00', '8525.60.10', '85256010', 'Aparelhos transmissores')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.061.00', '8527.21.00', '85272100', 'Aparelhos receptores de radiodifusão')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.062.00', '8527.29.00', '85272900', 'Aparelhos receptores de radiodifusão')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.062.01', '8521.90.90', '85219090', 'Aparelhos videofônicos de gravação ou reprodução')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.063.00', '8529.10', '852910', 'Antenas')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.063.00', '8529.10.90', '85291090', 'Antenas')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.064.00', '8534.00', '853400', 'Circuitos impressos')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.065.00', '8535.30', '853530', 'Interruptores e seccionadores')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.065.00', '8536.50', '853650', 'Interruptores e seccionadores e comutadores')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.066.00', '8536.10.00', '85361000', 'Fusíveis e corta-circuitos')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.067.00', '8536.20.00', '85362000', 'Disjuntores')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.068.00', '8536.4', '85364', 'Relés')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.070.00', '8539.10', '853910', 'Faróis e projetores')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.071.00', '8539.2', '85392', 'Lâmpadas e tubos de incandescência')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.072.00', '8544.20.00', '85442000', 'Cabos coaxiais')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.073.00', '8544.30.00', '85443000', 'Jogos de fios para velas de ignição')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.074.00', '8707', '8707', 'Carroçarias para veículos automóveis')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.075.00', '8708', '8708', 'Partes e acessórios de veículos automóveis')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.076.00', '8714.1', '87141', 'Partes e acessórios de motocicletas')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.077.00', '8716.90.90', '87169090', 'Engates para reboques e semirreboques')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.078.00', '9026.10', '902610', 'Medidores de nível e vazão')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.079.00', '9026.20', '902620', 'Aparelhos para medida ou controle da pressão')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.080.00', '9029', '9029', 'Contadores, indicadores de velocidade e tacômetros')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.081.00', '9030.33.21', '90303321', 'Amperímetros')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.082.00', '9031.80.40', '90318040', 'Aparelhos digitais para medida e indicação de grandezas')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.083.00', '9032.89.2', '9032892', 'Controladores eletrônicos')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.084.00', '9104.00.00', '91040000', 'Relógios para painéis de instrumentos')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.085.00', '9401.20.00', '94012000', 'Assentos e partes de assentos')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.085.00', '9401.99.00', '94019900', 'Assentos e partes de assentos')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.085.00', '9401.90.90', '94019090', 'Assentos e partes de assentos')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.086.00', '9613.80.00', '96138000', 'Acendedores')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.087.00', '4009', '4009', 'Tubos de borracha vulcanizada')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.088.00', '4504.90.00', '45049000', 'Juntas de vedação de cortiça')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.088.00', '6812.99.10', '68129910', 'Juntas de vedação de amianto')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.089.00', '4823.40.00', '48234000', 'Papel-diagrama para tacógrafo')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.090.00', '3919.10', '391910', 'Fitas, tiras e adesivos de plástico')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.090.00', '3919.90', '391990', 'Fitas, tiras e adesivos de plástico')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.090.00', '8708.29.99', '87082999', 'Placas refletoras para aplicação automotiva')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.091.00', '8412.31.10', '84123110', 'Cilindros pneumáticos')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.092.00', '8413.19.00', '84131900', 'Bomba elétrica de lavador de para-brisa')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.092.00', '8413.50.90', '84135090', 'Bomba elétrica de lavador de para-brisa')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.092.00', '8413.81.00', '84138100', 'Bomba elétrica de lavador de para-brisa')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.093.00', '8413.60.19', '84136019', 'Bomba de assistência de direção hidráulica')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.093.00', '8413.70.10', '84137010', 'Bomba de assistência de direção hidráulica')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.094.00', '8414.59.10', '84145910', 'Motoventiladores')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.094.00', '8414.59.90', '84145990', 'Motoventiladores')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.095.00', '8421.39.90', '84213990', 'Filtros de pólen do ar-condicionado')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.096.00', '8501.10.19', '85011019', 'Máquina de vidro elétrico de porta')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.097.00', '8501.31.10', '85013110', 'Motor de limpador de para-brisa')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.098.00', '8504.50.00', '85045000', 'Bobinas de reatância e de autoindução')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.099.00', '8507.20', '850720', 'Baterias de chumbo e de níquel-cádmio')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.099.00', '8507.30', '850730', 'Baterias de chumbo e de níquel-cádmio')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.100.00', '8512.30.00', '85123000', 'Aparelhos de sinalização acústica')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.101.00', '9032.89.8', '9032898', 'Instrumentos para regulação de grandezas não elétricas')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.101.00', '9032.89.9', '9032899', 'Instrumentos para regulação de grandezas não elétricas')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.102.00', '9027.10.00', '90271000', 'Analisadores de gases ou fumaça')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.103.00', '4008.11.00', '40081100', 'Perfilados de borracha vulcanizada')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.104.00', '5601.22.19', '56012219', 'Artefatos de pasta de fibra de uso automotivo')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.105.00', '5703.29.00', '57032900', 'Tapetes/carpetes de náilon')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.105.00', '5703.20.00', '57032000', 'Tapetes/carpetes de náilon')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.106.00', '5703.39.00', '57033900', 'Tapetes de matérias têxteis sintéticas')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.106.00', '5703.30.00', '57033000', 'Tapetes de matérias têxteis sintéticas')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.107.00', '5911.90.00', '59119000', 'Forração interior de capacete')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.108.00', '6903.90.99', '69039099', 'Outros para-brisas')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.109.00', '7007.29.00', '70072900', 'Moldura com espelho')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.111.00', '7315.11.00', '73151100', 'Corrente de transmissão')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.113.00', '8418.99.00', '84189900', 'Condensador tubular metálico')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.114.00', '8419.50', '841950', 'Trocadores de calor')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.115.00', '8424.90.90', '84249090', 'Partes de aparelhos mecânicos de pulverizar ou dispersar')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.116.00', '8425.49.10', '84254910', 'Macacos manuais para veículos')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.117.00', '8431.41.00', '84314100', 'Caçambas, pás, ganchos e tenazes')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.118.00', '8501.61.00', '85016100', 'Geradores de corrente alternada')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.119.00', '8531.10.90', '85311090', 'Aparelhos elétricos para alarme')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.120.00', '9014.10.00', '90141000', 'Bússolas')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.121.00', '9025.19.90', '90251990', 'Indicadores de temperatura')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.123.00', '9026.90', '902690', 'Partes de aparelhos de medida ou controle')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.124.00', '9032.10.10', '90321010', 'Termostatos')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.125.00', '9032.10.90', '90321090', 'Instrumentos e aparelhos para regulação')@
INSERT INTO DBA.CATSP_NCM (ANEXO, CEST, NCM, NCM_SEM_PONTUACAO, DESCRICAO) VALUES ('XIV', '01.126.00', '9032.20.00', '90322000', 'Pressostatos')@

CREATE TABLE DBA.CATSP_CONSUMO_ENTRADA (
    DTPOSICAO                      DATE           NOT NULL,
    IDPRODUTO                      INTEGER        NOT NULL,
    IDSUBPRODUTO                   INTEGER        NOT NULL,
    IDEMPRESA                      INTEGER        NOT NULL,
    IDPLANILHA                     INTEGER        NOT NULL,
    NUMSEQUENCIA                   INTEGER        NOT NULL,
    CHAVE_ACESSO_NFE               VARCHAR(44),
    NUMNOTA                        INTEGER,
    SERIENOTA                      VARCHAR(3),
    DTEMISSAO                      DATE,
    CNPJ_FORNECEDOR                VARCHAR(14),
    CODIGO_ITEM_ENTRADA            VARCHAR(60),
    QTD_ADQUIRIDA                  DECIMAL(18, 6) NOT NULL,
    QTD_CONSIDERADA                DECIMAL(18, 6) NOT NULL,
    VALOR_UNITARIO_MERCADORIA      DECIMAL(18, 6),
    CUSTO_AQUISICAO_UNITARIO       DECIMAL(18, 6),
    BASE_ICMS_PROPRIO_UNITARIO     DECIMAL(18, 6),
    ALIQUOTA_ICMS_PROPRIO          DECIMAL(15, 6),
    VALOR_ICMS_PROPRIO_UNITARIO    DECIMAL(18, 6),
    BASE_ICMS_ST_RETIDO_UNITARIO   DECIMAL(18, 6),
    VALOR_ICMS_ST_RETIDO_UNITARIO  DECIMAL(18, 6),
    PERCENTUAL_REDUCAO_BASE        DECIMAL(15, 6),
    ALIQUOTA_ICMS_INTERNA          DECIMAL(15, 6),
    ALIQUOTA_ICMS_INTERESTADUAL    DECIMAL(15, 6),
    CONSTRAINT PK_CATSP_CONSUMO_ENTRADA PRIMARY KEY
        (DTPOSICAO, IDPRODUTO, IDSUBPRODUTO, IDEMPRESA, IDPLANILHA, NUMSEQUENCIA)
)@

CREATE INDEX DBA.IX_CATSP_CONSUMO_ENTRADA_NOTA
    ON DBA.CATSP_CONSUMO_ENTRADA (IDEMPRESA, IDPLANILHA, NUMSEQUENCIA)@

CREATE OR REPLACE PROCEDURE DBA.SP_CATSP_PROCESSA_RESTITUICAO (
    IN AI_DTPOSICAO DATE
)
LANGUAGE SQL
MODIFIES SQL DATA
BEGIN
    -- Processo 1: captura itens elegÃƒÂ­veis e consolida o estoque.
DELETE FROM DBA.CATSP_PRODUTO
    WHERE DTMOVIMENTO = AI_DTPOSICAO;

    INSERT INTO DBA.CATSP_PRODUTO (
        IDPRODUTO,
        IDSUBPRODUTO,
        DESCRICAO_PRODUTO,
        NCM,
        CEST,
        UNIDADE_MEDIDA,
        QTD_ESTOQUE,
        DTMOVIMENTO
    )
    SELECT
        PV.IDPRODUTO,
        PV.IDSUBPRODUTO,
        PV.DESCRCOMPRODUTO,
        PV.NCM,
        PV.CODCEST,
        PV.EMBALAGEMSAIDA,
        COALESCE(SUM(SE.QTDATUALESTOQUE), DECIMAL(0, 18, 6)),
        AI_DTPOSICAO
    FROM
        DBA.PRODUTOS_VIEW AS PV
        CROSS JOIN DBA.EMPRESA AS E
        CROSS JOIN TABLE(
            DBA.UF_SALDOEST_DTPOSICAO(
                E.IDEMPRESA,
                PV.IDPRODUTO,
                PV.IDSUBPRODUTO,
                AI_DTPOSICAO
            )
        ) AS SE
    WHERE
        EXISTS (
            SELECT 1
            FROM DBA.CATSP_NCM AS CN
            WHERE PV.NCM LIKE CN.NCM_SEM_PONTUACAO CONCAT '%'
        )
    GROUP BY
        PV.IDPRODUTO,
        PV.IDSUBPRODUTO,
        PV.DESCRCOMPRODUTO,
        PV.NCM,
        PV.CODCEST,
        PV.EMBALAGEMSAIDA;

    -- Processo 2: compÃƒÂµe o saldo pelas notas de compra, da mais recente
    -- para a mais antiga, atÃƒÂ© atingir a quantidade da posiÃƒÂ§ÃƒÂ£o.
DELETE FROM DBA.CATSP_CONSUMO_ENTRADA
    WHERE DTPOSICAO = AI_DTPOSICAO;

    INSERT INTO DBA.CATSP_CONSUMO_ENTRADA (
        DTPOSICAO,
        IDPRODUTO,
        IDSUBPRODUTO,
        IDEMPRESA,
        IDPLANILHA,
        NUMSEQUENCIA,
        CHAVE_ACESSO_NFE,
        NUMNOTA,
        SERIENOTA,
        DTEMISSAO,
        CNPJ_FORNECEDOR,
        CODIGO_ITEM_ENTRADA,
        QTD_ADQUIRIDA,
        QTD_CONSIDERADA,
        VALOR_UNITARIO_MERCADORIA,
        CUSTO_AQUISICAO_UNITARIO,
        BASE_ICMS_PROPRIO_UNITARIO,
        ALIQUOTA_ICMS_PROPRIO,
        VALOR_ICMS_PROPRIO_UNITARIO,
        BASE_ICMS_ST_RETIDO_UNITARIO,
        VALOR_ICMS_ST_RETIDO_UNITARIO,
        PERCENTUAL_REDUCAO_BASE,
        ALIQUOTA_ICMS_INTERNA,
        ALIQUOTA_ICMS_INTERESTADUAL
    )
    WITH MOVIMENTOS AS (
        SELECT
            CP.DTMOVIMENTO AS DTPOSICAO,
            CP.IDPRODUTO,
            CP.IDSUBPRODUTO,
            CP.QTD_ESTOQUE,
            EA.IDEMPRESA,
            EA.IDPLANILHA,
            EA.NUMSEQUENCIA,
            NFE.CHAVENFE AS CHAVE_ACESSO_NFE,
            N.NUMNOTA,
            N.SERIENOTA,
            NES.DTEMISSAO,
            NES.CNPJCPF AS CNPJ_FORNECEDOR,
            EAX.CODPRODUTO AS CODIGO_ITEM_ENTRADA,
            DECIMAL(EA.QTDPRODUTO, 18, 6) AS QTD_ADQUIRIDA,
            EA.VALUNITBRUTO AS VALOR_UNITARIO_MERCADORIA,
            EA.VALTOTLIQUIDO / NULLIF(EA.QTDPRODUTO, 0) AS CUSTO_AQUISICAO_UNITARIO,
            CASE
                WHEN COALESCE(EAST.VALBASEICMSCREDITO, 0) <> 0
                    THEN EAST.VALBASEICMSCREDITO / NULLIF(EA.QTDPRODUTO, 0)
                ELSE EA.VALBASEICM / NULLIF(EA.QTDPRODUTO, 0)
            END AS BASE_ICMS_PROPRIO_UNITARIO,
            CASE
                WHEN COALESCE(EAST.PERICMSCREDITO, 0) <> 0
                    THEN EAST.PERICMSCREDITO
                ELSE EA.PERICM
            END AS ALIQUOTA_ICMS_PROPRIO,
            CASE
                WHEN COALESCE(EAST.VALICMSCREDITO, 0) <> 0
                    THEN EAST.VALICMSCREDITO / NULLIF(EA.QTDPRODUTO, 0)
                ELSE EA.VALICMS / NULLIF(EA.QTDPRODUTO, 0)
            END AS VALOR_ICMS_PROPRIO_UNITARIO,
            CASE
                WHEN COALESCE(EAST.VALBASESTRETIDO, 0) <> 0
                    THEN EAST.VALBASESTRETIDO / NULLIF(EA.QTDPRODUTO, 0)
                ELSE EA.VALBASESUBST / NULLIF(EA.QTDPRODUTO, 0)
            END AS BASE_ICMS_ST_RETIDO_UNITARIO,
            CASE
                WHEN COALESCE(EAST.VALICMSSTRETIDO, 0) <> 0
                    THEN EAST.VALICMSSTRETIDO / NULLIF(EA.QTDPRODUTO, 0)
                ELSE EA.VALICMSUBST / NULLIF(EA.QTDPRODUTO, 0)
            END AS VALOR_ICMS_ST_RETIDO_UNITARIO,
            EA.PERREDTRIB AS PERCENTUAL_REDUCAO_BASE,
            CASE
                WHEN COALESCE(EAST.PERICMSST, 0) <> 0
                    THEN EAST.PERICMSST
                ELSE EA.PERICM
            END AS ALIQUOTA_ICMS_INTERNA,
            EAST.PERICMSCREDITO AS ALIQUOTA_ICMS_INTERESTADUAL,
            SUM(EA.QTDPRODUTO) OVER (
                PARTITION BY CP.DTMOVIMENTO, CP.IDPRODUTO, CP.IDSUBPRODUTO
                ORDER BY
                    NES.DTEMISSAO DESC,
                    EA.DTMOVIMENTO DESC,
                    EA.IDEMPRESA DESC,
                    EA.IDPLANILHA DESC,
                    EA.NUMSEQUENCIA DESC
            ) AS QTD_ACUMULADA
        FROM
            DBA.CATSP_PRODUTO AS CP
            INNER JOIN DBA.ESTOQUE_ANALITICO AS EA ON
                EA.IDPRODUTO = CP.IDPRODUTO
                AND EA.IDSUBPRODUTO = CP.IDSUBPRODUTO
            LEFT JOIN DBA.ESTOQUE_ANALITICO_ST AS EAST ON
                EAST.IDEMPRESA = EA.IDEMPRESA
                AND EAST.IDPLANILHA = EA.IDPLANILHA
                AND EAST.NUMSEQUENCIA = EA.NUMSEQUENCIA
            LEFT JOIN DBA.ESTOQUE_ANALITICO_XML AS EAX ON
                EAX.IDEMPRESA = EA.IDEMPRESA
                AND EAX.IDPLANILHA = EA.IDPLANILHA
                AND EAX.NUMSEQUENCIA = EA.NUMSEQUENCIA
            LEFT JOIN DBA.NOTA_FISCAL_ELETRONICA_TERCEIROS AS NFE ON
                NFE.IDEMPRESA = EA.IDEMPRESA
                AND NFE.IDPLANILHA = EA.IDPLANILHA
            LEFT JOIN DBA.NOTAS AS N ON
                N.IDEMPRESA = EA.IDEMPRESA
                AND N.IDPLANILHA = EA.IDPLANILHA
            LEFT JOIN DBA.NOTAS_ENTRADA_SAIDA AS NES ON
                NES.IDEMPRESA = EA.IDEMPRESA
                AND NES.IDPLANILHA = EA.IDPLANILHA
        WHERE
            CP.DTMOVIMENTO = AI_DTPOSICAO
            AND EA.IDOPERACAO < 1000
            AND EA.TIPOCATEGORIA = 'C'
            AND EA.QTDPRODUTO > 0
    )
    SELECT
        DTPOSICAO,
        IDPRODUTO,
        IDSUBPRODUTO,
        IDEMPRESA,
        IDPLANILHA,
        NUMSEQUENCIA,
        CHAVE_ACESSO_NFE,
        NUMNOTA,
        SERIENOTA,
        DTEMISSAO,
        CNPJ_FORNECEDOR,
        CODIGO_ITEM_ENTRADA,
        QTD_ADQUIRIDA,
        CASE
            WHEN QTD_ACUMULADA <= QTD_ESTOQUE THEN QTD_ADQUIRIDA
            ELSE QTD_ESTOQUE - (QTD_ACUMULADA - QTD_ADQUIRIDA)
        END AS QTD_CONSIDERADA,
        VALOR_UNITARIO_MERCADORIA,
        CUSTO_AQUISICAO_UNITARIO,
        BASE_ICMS_PROPRIO_UNITARIO,
        ALIQUOTA_ICMS_PROPRIO,
        VALOR_ICMS_PROPRIO_UNITARIO,
        BASE_ICMS_ST_RETIDO_UNITARIO,
        VALOR_ICMS_ST_RETIDO_UNITARIO,
        PERCENTUAL_REDUCAO_BASE,
        ALIQUOTA_ICMS_INTERNA,
        ALIQUOTA_ICMS_INTERESTADUAL
    FROM MOVIMENTOS
    WHERE QTD_ACUMULADA - QTD_ADQUIRIDA < QTD_ESTOQUE;
END@

-- Execucao ÃƒÂºnica:
-- CALL DBA.SP_CATSP_PROCESSA_RESTITUICAO(DATE('2026-09-30'))@
