-- CATSP - consulta final para levantamento e calculo de restituiÃ§Ã£o.
-- Altere somente a data abaixo quando necessÃ¡rio.

SELECT
    CE.DTPOSICAO AS DATA_POSICAO_ESTOQUE,
    CP.IDPRODUTO AS CODIGO_INTERNO_PRODUTO,
    CP.IDSUBPRODUTO AS CODIGO_INTERNO_SUBPRODUTO,
    CP.DESCRICAO_PRODUTO,
    CP.NCM,
    CP.CEST,
    CP.UNIDADE_MEDIDA,
    CP.QTD_ESTOQUE AS QUANTIDADE_ESTOQUE_POSICAO,
    CE.IDEMPRESA,
    CE.IDPLANILHA,
    CE.NUMSEQUENCIA AS SEQUENCIA_ITEM_NOTA,
    CE.CHAVE_ACESSO_NFE,
    CE.NUMNOTA AS NUMERO_NOTA_FISCAL,
    CE.SERIENOTA AS SERIE_NOTA_FISCAL,
    CE.DTEMISSAO AS DATA_EMISSAO,
    CE.CNPJ_FORNECEDOR,
    CE.CODIGO_ITEM_ENTRADA,
    CE.QTD_ADQUIRIDA AS QUANTIDADE_ADQUIRIDA_NOTA,
    CE.QTD_CONSIDERADA AS QUANTIDADE_UTILIZADA_CALCULO,
    CE.VALOR_UNITARIO_MERCADORIA,
    CE.CUSTO_AQUISICAO_UNITARIO,
    CE.BASE_ICMS_PROPRIO_UNITARIO,
    CE.ALIQUOTA_ICMS_PROPRIO,
    CE.VALOR_ICMS_PROPRIO_UNITARIO,
    CE.BASE_ICMS_ST_RETIDO_UNITARIO,
    CE.VALOR_ICMS_ST_RETIDO_UNITARIO,
    CE.PERCENTUAL_REDUCAO_BASE,
    CE.ALIQUOTA_ICMS_INTERNA,
    CE.ALIQUOTA_ICMS_INTERESTADUAL,
    DECIMAL(
        CE.QTD_CONSIDERADA * CE.VALOR_ICMS_PROPRIO_UNITARIO,
        18,
        6
    ) AS VALOR_ICMS_PROPRIO_CONSIDERADO,
    DECIMAL(
        CE.QTD_CONSIDERADA * CE.VALOR_ICMS_ST_RETIDO_UNITARIO,
        18,
        6
    ) AS VALOR_ICMS_ST_RETIDO_CONSIDERADO
FROM
    DBA.CATSP_CONSUMO_ENTRADA AS CE
    INNER JOIN DBA.CATSP_PRODUTO AS CP ON
        CP.DTMOVIMENTO = CE.DTPOSICAO
        AND CP.IDPRODUTO = CE.IDPRODUTO
        AND CP.IDSUBPRODUTO = CE.IDSUBPRODUTO
WHERE
    CE.DTPOSICAO = DATE('2026-09-30')
ORDER BY
    CP.NCM,
    CP.IDPRODUTO,
    CP.IDSUBPRODUTO,
    CE.DTEMISSAO DESC,
    CE.IDEMPRESA,
    CE.IDPLANILHA,
    CE.NUMSEQUENCIA;

-- Produtos com saldo na posicao, mas sem entrada de compra elegivel:
--
-- SELECT
--     CP.*
-- FROM DBA.CATSP_PRODUTO AS CP
-- WHERE
--     CP.DTMOVIMENTO = DATE('2026-09-30')
--     AND NOT EXISTS (
--         SELECT 1
--         FROM DBA.CATSP_CONSUMO_ENTRADA AS CE
--         WHERE
--             CE.DTPOSICAO = CP.DTMOVIMENTO
--             AND CE.IDPRODUTO = CP.IDPRODUTO
--             AND CE.IDSUBPRODUTO = CP.IDSUBPRODUTO
--     )
-- ORDER BY CP.NCM, CP.IDPRODUTO, CP.IDSUBPRODUTO;
