DROP INDEX DBA.IX_ADMINBANDTAXAHIS_CONSULTA
GO

ALTER TABLE DBA.ADMINISTRADORAS_BANDEIRA_TAXA_HISTORICO DROP CONSTRAINT FK_ADMINBANDTAXAHIS_BANDEIRA
GO

ALTER TABLE DBA.ADMINISTRADORAS_BANDEIRA_TAXA_HISTORICO DROP CONSTRAINT FK_ADMINBANDTAXAHIS_USUARIO
GO

ALTER TABLE DBA.ADMINISTRADORAS_BANDEIRA_TAXA_HISTORICO DROP PRIMARY KEY
GO

CREATE TABLE DBA.ADMINISTRADORAS_BANDEIRA_TAXA_HISTORICO (
    IDCONTADOR       INTEGER       NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    IDEMPRESA        INTEGER       NOT NULL,
    IDBANDEIRA       INTEGER       NOT NULL,
    IDADMINISTRADORA INTEGER       NOT NULL,
    NUMPARCELA       SMALLINT      NOT NULL DEFAULT 0,
    PERCTAXA         DECIMAL(12,6) NOT NULL,
    IDUSUARIO        INTEGER       NOT NULL,
    DTFIM            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DTALTERACAO      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
)
GO

ALTER TABLE DBA.ADMINISTRADORAS_BANDEIRA_TAXA_HISTORICO ADD CONSTRAINT PK_ADMINBANDTAXAHIS PRIMARY KEY (IDCONTADOR, IDEMPRESA, IDBANDEIRA, IDADMINISTRADORA)
GO

ALTER TABLE DBA.ADMINISTRADORAS_BANDEIRA_TAXA_HISTORICO ADD CONSTRAINT FK_ADMINBANDTAXAHIS_BANDEIRA FOREIGN KEY (IDEMPRESA, IDBANDEIRA, IDADMINISTRADORA) REFERENCES DBA.ADMINISTRADORAS_BANDEIRA (IDEMPRESA, IDBANDEIRA, IDADMINISTRADORA) ON DELETE CASCADE
GO

ALTER TABLE DBA.ADMINISTRADORAS_BANDEIRA_TAXA_HISTORICO ADD CONSTRAINT FK_ADMINBANDTAXAHIS_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES DBA.USUARIO (IDUSUARIO)
GO

CREATE INDEX DBA.IX_ADMINBANDTAXAHIS_CONSULTA
    ON DBA.ADMINISTRADORAS_BANDEIRA_TAXA_HISTORICO (IDEMPRESA, IDBANDEIRA, IDADMINISTRADORA, NUMPARCELA, DTFIM)
GO

COMMENT ON TABLE DBA.ADMINISTRADORAS_BANDEIRA_TAXA_HISTORICO IS 'Historico de taxas por parcela da administradora/bandeira com periodo de vigencia.'
GO

COMMENT ON COLUMN DBA.ADMINISTRADORAS_BANDEIRA_TAXA_HISTORICO.IDCONTADOR IS 'Contador de registro autoincremento para ser usado na PK'
GO

COMMENT ON COLUMN DBA.ADMINISTRADORAS_BANDEIRA_TAXA_HISTORICO.IDEMPRESA IS 'Codigo da empresa da administradora/bandeira.'
GO

COMMENT ON COLUMN DBA.ADMINISTRADORAS_BANDEIRA_TAXA_HISTORICO.IDBANDEIRA IS 'Codigo da bandeira vinculada a administradora.'
GO

COMMENT ON COLUMN DBA.ADMINISTRADORAS_BANDEIRA_TAXA_HISTORICO.IDADMINISTRADORA IS 'Codigo da administradora vinculada a bandeira.'
GO

COMMENT ON COLUMN DBA.ADMINISTRADORAS_BANDEIRA_TAXA_HISTORICO.NUMPARCELA IS 'Limite superior da faixa de parcelas para aplicacao da taxa.'
GO

COMMENT ON COLUMN DBA.ADMINISTRADORAS_BANDEIRA_TAXA_HISTORICO.PERCTAXA IS 'Percentual da taxa aplicada para a parcela no periodo de vigencia.'
GO

COMMENT ON COLUMN DBA.ADMINISTRADORAS_BANDEIRA_TAXA_HISTORICO.IDUSUARIO IS 'Usuario responsavel pela manutencao do registro.'
GO

COMMENT ON COLUMN DBA.ADMINISTRADORAS_BANDEIRA_TAXA_HISTORICO.DTFIM IS 'Data e hora final exclusiva de vigencia da taxa, ou seja, ate quando ela valeu'
GO

COMMENT ON COLUMN DBA.ADMINISTRADORAS_BANDEIRA_TAXA_HISTORICO.DTALTERACAO IS 'Data e horario da ultima alteracao.'
GO

CREATE OR REPLACE FUNCTION DBA.UF_ADMIN_BANDEIRA_TAXA_DATA (
    IN_IDEMPRESA        INTEGER,
    IN_IDADMINISTRADORA INTEGER,
    IN_IDBANDEIRA       INTEGER,
    IN_NUMPARCELA       SMALLINT,
    IN_DTMOVIMENTO      TIMESTAMP
)
RETURNS DECIMAL(12,6)
LANGUAGE SQL
READS SQL DATA
NO EXTERNAL ACTION
BEGIN
    DECLARE V_TAXA DECIMAL(12,6);

    SELECT
        COALESCE(
            (
                SELECT
                    H.PERCTAXA
                FROM
                    DBA.ADMINISTRADORAS_BANDEIRA_TAXA_HISTORICO H
                WHERE
                    H.IDEMPRESA = F.IDEMPRESA AND
                    H.IDADMINISTRADORA = F.IDADMINISTRADORA AND
                    H.IDBANDEIRA = F.IDBANDEIRA AND
                    H.NUMPARCELA < IN_NUMPARCELA AND
                    H.DTFIM > IN_DTMOVIMENTO
                ORDER BY
                    H.NUMPARCELA DESC,
                    H.DTFIM ASC
                FETCH FIRST 1 ROW ONLY
            ),
            F.TAXA_ATUAL
        )
    INTO
        V_TAXA
    FROM
        (
            SELECT
                AB.IDEMPRESA,
                AB.IDADMINISTRADORA,
                AB.IDBANDEIRA,
                SMALLINT(0) AS NUMPARCELA,
                AB.PERTAXAADMINISTRACAO AS TAXA_ATUAL
            FROM
                DBA.ADMINISTRADORAS_BANDEIRA AB
            WHERE
                AB.IDEMPRESA = IN_IDEMPRESA AND
                AB.IDADMINISTRADORA = IN_IDADMINISTRADORA AND
                AB.IDBANDEIRA = IN_IDBANDEIRA

            UNION ALL

            SELECT
                T.IDEMPRESA,
                T.IDADMINISTRADORA,
                T.IDBANDEIRA,
                T.NUMPARCELAS,
                T.TAXA
            FROM
                DBA.ADMINISTRADORAS_BANDEIRA_TAXAS T
            WHERE
                T.IDEMPRESA = IN_IDEMPRESA AND
                T.IDADMINISTRADORA = IN_IDADMINISTRADORA AND
                T.IDBANDEIRA = IN_IDBANDEIRA
        ) AS F
    WHERE
        F.NUMPARCELA < IN_NUMPARCELA
    ORDER BY
        F.NUMPARCELA DESC
    FETCH FIRST 1 ROW ONLY;

    RETURN COALESCE(V_TAXA, 0);
END
GO

INSERT INTO DBA.CONFIG_ENTIDADE (ENTIDADE, CHAVE1, CHAVE2, DADOS, OBSERVACAO, DTALTERACAO)
SELECT
    'HIS',
    1,
    1,
    'F',
    'Exibe historico de taxas no cadastro de bandeiras',
    CURRENT TIMESTAMP
FROM
    DBA.DUMMY
WHERE
    NOT EXISTS
        (SELECT
            1
        FROM
            DBA.CONFIG_ENTIDADE AS CE
        WHERE
            CE.ENTIDADE = 'HIS' AND
            CE.CHAVE1 = 1 AND
            CE.CHAVE2 = 1)
