CREATE OR REPLACE TRIGGER DBA.TR_INS_ADMINBANDTAXAVIG
NO CASCADE BEFORE INSERT ON DBA.ADMINISTRADORAS_BANDEIRA_TAXA_VIGENCIA
REFERENCING NEW AS N
FOR EACH ROW
BEGIN ATOMIC

    IF (
        SELECT
            COUNT(0)
        FROM
            DBA.ADMINISTRADORAS_BANDEIRA_TAXA_VIGENCIA TXV
        WHERE
            TXV.IDEMPRESA = N.IDEMPRESA AND
            TXV.IDBANDEIRA = N.IDBANDEIRA AND
            TXV.IDADMINISTRADORA = N.IDADMINISTRADORA AND
            TXV.NUMPARCELA = N.NUMPARCELA AND
            N.DTINICIO < COALESCE(TXV.DTFIM, TIMESTAMP('9999-12-31-00.00.00')) AND
            COALESCE(N.DTFIM, TIMESTAMP('9999-12-31-00.00.00')) > TXV.DTINICIO
    ) > 0 THEN
        SIGNAL SQLSTATE '75000' SET MESSAGE_TEXT='Vigencia conflitante para empresa, administradora, bandeira e limite de parcela informados';
    END IF;

END
GO

CREATE OR REPLACE TRIGGER DBA.TR_UPD_ADMINBANDTAXAVIG
NO CASCADE BEFORE UPDATE ON DBA.ADMINISTRADORAS_BANDEIRA_TAXA_VIGENCIA
REFERENCING OLD AS O NEW AS N
FOR EACH ROW
BEGIN ATOMIC

    IF (
        SELECT
            COUNT(0)
        FROM
            DBA.ADMINISTRADORAS_BANDEIRA_TAXA_VIGENCIA TXV
        WHERE
            TXV.IDEMPRESA = N.IDEMPRESA AND
            TXV.IDBANDEIRA = N.IDBANDEIRA AND
            TXV.IDADMINISTRADORA = N.IDADMINISTRADORA AND
            TXV.NUMPARCELA = N.NUMPARCELA AND
            N.DTINICIO < COALESCE(TXV.DTFIM, TIMESTAMP('9999-12-31-00.00.00')) AND
            COALESCE(N.DTFIM, TIMESTAMP('9999-12-31-00.00.00')) > TXV.DTINICIO AND
            NOT (
                TXV.IDEMPRESA = O.IDEMPRESA AND
                TXV.IDBANDEIRA = O.IDBANDEIRA AND
                TXV.IDADMINISTRADORA = O.IDADMINISTRADORA AND
                TXV.NUMPARCELA = O.NUMPARCELA AND
                TXV.DTINICIO = O.DTINICIO
            )
    ) > 0 THEN
        SIGNAL SQLSTATE '75000' SET MESSAGE_TEXT='Vigencia conflitante para empresa, administradora, bandeira e limite de parcela informados';
    END IF;

END
GO
