CREATE OR REPLACE FUNCTION DBA.UF_ADMIN_BANDEIRA_TAXA_DATA (
    IN_IDEMPRESA        INTEGER,
    IN_IDADMINISTRADORA INTEGER,
    IN_IDBANDEIRA       INTEGER,
    IN_NUMPARCELA       SMALLINT,
    IN_DTMOVIMENTO      TIMESTAMP
)
RETURNS DECIMAL(12,6)
LANGUAGE SQL
READS SQL DATA
NO EXTERNAL ACTION
RETURN
    COALESCE((
        SELECT
            TXV.PERCTAXA
        FROM
            DBA.ADMINISTRADORAS_BANDEIRA_TAXA_VIGENCIA TXV
        WHERE
            TXV.IDEMPRESA = IN_IDEMPRESA AND
            TXV.IDADMINISTRADORA = IN_IDADMINISTRADORA AND
            TXV.IDBANDEIRA = IN_IDBANDEIRA AND
            TXV.NUMPARCELA >= IN_NUMPARCELA AND
            IN_DTMOVIMENTO >= TXV.DTINICIO AND
            (
                TXV.DTFIM IS NULL OR
                IN_DTMOVIMENTO < TXV.DTFIM
            )
        ORDER BY
            TXV.NUMPARCELA,
            TXV.DTINICIO DESC
        FETCH FIRST 1 ROW ONLY
    ), 0)
