CREATE OR REPLACE PROCEDURE DBA.SP_AUDLOG (
    AS_SCHEMA VARCHAR(20),
    AS_TABNAME VARCHAR(128),
    ADT_DTINI TIMESTAMP,
    ADT_DTFIM TIMESTAMP,
    AS_FLAGINSERT CHAR(1),
    AS_FLAGUPDATE CHAR(1),
    AS_FLAGDELETE CHAR(1)
)
BEGIN
    DECLARE LS_CRLF             VARCHAR(2);
    DECLARE LS_TABNAMELOG       VARCHAR(128);
    DECLARE LS_STMT             CLOB(1M);
    DECLARE LS_CODIGO           VARCHAR(50);
    DECLARE LS_CAMPOS           CLOB(1M);
    DECLARE LS_CAMPOSOLD        CLOB(1M);
    DECLARE LI_TABEXISTS        INTEGER;
    SET LS_CRLF = CHR(13) || CHR(10);
    SET LS_TABNAMELOG = UPPER(TRIM(AS_TABNAME));
    IF  DBA.UF_APPNAME() NOT IN ( 'DB2JCC_APPLICATION', 'CISS.EXE','PODER.EXE','PB105.EXE','SQLEXEC.EXE') THEN
        SIGNAL SQLSTATE '99999' SET MESSAGE_TEXT='#181294. Operacao permitida apenas via CISSPoder.';
    END IF;
    SET LI_TABEXISTS = (SELECT COUNT(0) FROM SYSCAT.TABLES WHERE TABNAME = LS_TABNAMELOG AND TABSCHEMA = AS_SCHEMA);
    IF LI_TABEXISTS <> 0 THEN
    FOR LOOPQUERY AS
        SELECT
            TRIM(TRIGSCHEMA) AS LS_TRIGSCHEMA,
            TRIM(TRIGNAME) AS LS_TRIGNAME
        FROM
            SYSCAT.TRIGGERS AS TRG
        WHERE
            TABSCHEMA = AS_SCHEMA AND
            TABNAME = AS_TABNAME AND
            ( TRIGNAME LIKE 'TR_UPD_AUDLOG%' OR
              TRIGNAME LIKE 'TR_DEL_AUDLOG%' OR
              TRIGNAME LIKE 'TR_INS_AUDLOG%' )
        DO
            SET LS_STMT = 'DROP TRIGGER ' || LS_TRIGSCHEMA || '.' || LS_TRIGNAME;
            EXECUTE IMMEDIATE LS_STMT;
        END FOR;
    IF ADT_DTINI IS NULL AND ADT_DTFIM IS NULL THEN
        IF EXISTS(SELECT 1 FROM SYSCAT.TABLES WHERE TABSCHEMA = 'AUDLOG' AND TABNAME = AS_TABNAME) THEN
            SET LS_STMT = ' DROP TABLE AUDLOG.' || AS_TABNAME ;
            EXECUTE IMMEDIATE LS_STMT;
        END IF;
        RETURN;
    END IF;
    IF (ADT_DTINI IS NULL AND ADT_DTFIM IS NOT NULL) OR
       (ADT_DTFIM IS NULL AND ADT_DTINI IS NOT NULL) THEN
        RETURN;
    END IF;
    IF NOT EXISTS( SELECT 1 FROM SYSCAT.TABLES WHERE TABNAME = LS_TABNAMELOG AND TABSCHEMA = 'AUDLOG' ) THEN
        SET LS_STMT = 'CREATE TABLE AUDLOG.' || LS_TABNAMELOG || ' (';
        SET LS_STMT = LS_STMT || ' A_TIPODML CHAR(1) NOT NULL,';
        SET LS_STMT = LS_STMT || ' A_DATAHORA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,';
        SET LS_STMT = LS_STMT || ' A_USUARIOBD VARCHAR(32) NOT NULL,';
        SET LS_STMT = LS_STMT || ' A_APP VARCHAR(32) NOT NULL,';
        SET LS_STMT = LS_STMT || ' A_IP VARCHAR(50) NOT NULL,';
        SET LS_STMT = LS_STMT || ' A_USERCISS VARCHAR(40),';
        SET LS_STMT = LS_STMT || ' A_VERSAOCISS VARCHAR(50),';
        FOR LOOPQUERY AS
            SELECT
                COLNAME AS LS_COLNAME,
                CASE
                    WHEN TYPENAME IN ( 'VARCHAR', 'CHARACTER' ) THEN
                            TYPENAME || '(' || TRIM(CAST(LENGTH AS CHAR(10))) || ')'
                    WHEN TYPENAME IN ( 'LONG VARCHAR', 'SMALLINT', 'INTEGER', 'BIGINT', 'DATE', 'TIME', 'TIMESTAMP' ) THEN
                        TYPENAME
                    ELSE
                            TYPENAME || '(' || TRIM(CAST(LENGTH AS CHAR(10))) || ',' || TRIM(CAST(SCALE AS CHAR(10))) || ')'
                    END AS LS_TIPO
            FROM
                SYSCAT.COLUMNS AS CAT
            WHERE
                    TYPENAME IN ('DECIMAL', 'LONG VARCHAR', 'VARCHAR', 'CHARACTER', 'SMALLINT', 'INTEGER', 'BIGINT', 'DATE', 'TIME', 'TIMESTAMP') AND
                    TABSCHEMA = AS_SCHEMA AND
                    TABNAME = AS_TABNAME
            ORDER BY
                COLNO
            DO
                SET LS_STMT = LS_STMT || ' ' || LS_COLNAME || ' ' || LS_TIPO || ',';
            END FOR;
        SET LS_STMT = LEFT(LS_STMT, LENGTH( LS_STMT ) - 1 ) || ' )';
        EXECUTE IMMEDIATE LS_STMT;
        SET LS_STMT = 'CREATE INDEX AUDLOG.IX_' || LS_TABNAMELOG || '_DT ON AUDLOG.'||LS_TABNAMELOG|| '(A_DATAHORA)';
        EXECUTE IMMEDIATE LS_STMT;
        IF EXISTS ( SELECT 1 FROM SYSCAT.INDEXES WHERE TABSCHEMA = AS_SCHEMA AND TABNAME = AS_TABNAME AND UNIQUERULE = 'P' ) THEN
            SET LS_STMT = ( SELECT 'CREATE INDEX AUDLOG.IX_' || LS_TABNAMELOG || '_PK ON AUDLOG.'||LS_TABNAMELOG|| '('|| RIGHT( REPLACE( REPLACE( COLNAMES, '+', ',' ), '-', ',' ), LENGTH(COLNAMES)-1 ) || ')'
                            FROM   SYSCAT.INDEXES
                            WHERE  TABSCHEMA = AS_SCHEMA AND TABNAME = AS_TABNAME AND UNIQUERULE = 'P' );
            EXECUTE IMMEDIATE LS_STMT;
        END IF;
    ELSE
        FOR LOOPQUERY AS
            SELECT
                COLNAME AS LS_COLNAME,
                CASE
                    WHEN TYPENAME IN ( 'VARCHAR', 'CHARACTER' ) THEN
                            TYPENAME || '(' || TRIM(CAST(LENGTH AS CHAR(10))) || ')'
                    WHEN TYPENAME IN ( 'LONG VARCHAR', 'SMALLINT', 'INTEGER', 'BIGINT', 'DATE', 'TIME', 'TIMESTAMP' ) THEN
                        TYPENAME
                    ELSE
                            TYPENAME || '(' || TRIM(CAST(LENGTH AS CHAR(10))) || ',' || TRIM(CAST(SCALE AS CHAR(10))) || ')'
                    END AS LS_TIPO
            FROM
                SYSCAT.COLUMNS AS CAT
            WHERE
                    TYPENAME IN ('DECIMAL', 'LONG VARCHAR', 'VARCHAR', 'CHARACTER', 'SMALLINT', 'INTEGER', 'BIGINT', 'DATE', 'TIME', 'TIMESTAMP') AND
                    TABSCHEMA = AS_SCHEMA AND
                    TABNAME = AS_TABNAME
            EXCEPT
            SELECT
                COLNAME AS LS_COLNAME,
                CASE
                    WHEN TYPENAME IN ( 'VARCHAR', 'CHARACTER' ) THEN
                            TYPENAME || '(' || TRIM(CAST(LENGTH AS CHAR(10))) || ')'
                    WHEN TYPENAME IN ( 'LONG VARCHAR', 'SMALLINT', 'INTEGER', 'BIGINT', 'DATE', 'TIME', 'TIMESTAMP' ) THEN
                        TYPENAME
                    ELSE
                            TYPENAME || '(' || TRIM(CAST(LENGTH AS CHAR(10))) || ',' || TRIM(CAST(SCALE AS CHAR(10))) || ')'
                    END AS LS_TIPO
            FROM
                SYSCAT.COLUMNS AS CAT
            WHERE
                    TYPENAME IN ('DECIMAL', 'LONG VARCHAR', 'VARCHAR', 'CHARACTER', 'SMALLINT', 'INTEGER', 'BIGINT', 'DATE', 'TIME', 'TIMESTAMP') AND
                    TABSCHEMA = 'AUDLOG' AND
                    TABNAME = LS_TABNAMELOG
            DO
                SET LS_STMT = 'ALTER TABLE AUDLOG.' || LS_TABNAMELOG || ' ADD ' || LS_COLNAME || ' ' || LS_TIPO;
                EXECUTE IMMEDIATE LS_STMT;
            END FOR;
    END IF;
    SET LS_STMT = 'GRANT SELECT ON TABLE AUDLOG.' || LS_TABNAMELOG || ' TO USER SUPORTECISS';
    EXECUTE IMMEDIATE LS_STMT;
    SET LS_CODIGO = (
        SELECT
                TRIM(CAST(TABLEID AS CHAR(5))) || TRIM(CAST(TBSPACEID AS CHAR(5)))
        FROM
            SYSCAT.TABLES
        WHERE
                TABSCHEMA = AS_SCHEMA AND
                TABNAME = AS_TABNAME
    );
    -- VALIDA NOME DA TRIGGER CASO EXISTIR ALGUMA JÁ CRIADA DEVIDO COMBINAÇÃO DE TBSPACEID + TABLEID DUPLICAR EM TABELAS DIFERENTES
    --
    IF EXISTS ( SELECT 1 FROM SYSCAT.TRIGGERS WHERE TRIGSCHEMA = 'AUDLOG' AND (  TRIGNAME = 'TR_UPD_AUDLOG_'||LS_CODIGO OR
                                                                                 TRIGNAME = 'TR_INS_AUDLOG_'||LS_CODIGO OR
                                                                                 TRIGNAME = 'TR_DEL_AUDLOG_'||LS_CODIGO ) ) THEN
        SET LS_CODIGO = LS_CODIGO||'_'||LEFT(AS_TABNAME,20);
    END IF;
    --
    -- CRIA TRIGGER PARA UPDATE
    --
    IF AS_FLAGUPDATE = 'T' THEN
        SET LS_STMT = 'CREATE OR REPLACE TRIGGER AUDLOG.TR_UPD_AUDLOG_' || LS_CODIGO || ' AFTER UPDATE ON ' || AS_SCHEMA || '.' || AS_TABNAME || LS_CRLF;
        SET LS_STMT = LS_STMT || 'REFERENCING OLD AS O' || LS_CRLF;
        SET LS_STMT = LS_STMT || 'FOR EACH ROW WHEN ( CURRENT TIMESTAMP BETWEEN '''|| ADT_DTINI || ''' AND ''' || ADT_DTFIM || ''')' || LS_CRLF;
        SET LS_STMT = LS_STMT || 'BEGIN ATOMIC' || LS_CRLF;
        SET LS_STMT = LS_STMT || '      DECLARE LS_USER VARCHAR(40);' || LS_CRLF;
        SET LS_STMT = LS_STMT || '      DECLARE LS_VERSAO VARCHAR(50);' || LS_CRLF;
        SET LS_STMT = LS_STMT || '      DECLARE LS_APPNAME VARCHAR(32) DEFAULT '''';' || LS_CRLF;
        SET LS_STMT = LS_STMT || '      IF SESSION_USER = ''DBA'' THEN' || LS_CRLF;
        SET LS_STMT = LS_STMT || '          SET (LS_USER, LS_VERSAO) = (SELECT NOMEUSUARIO, SUBSTR(UL.RELEASECONEXAO,1,50) FROM DBA.USUARIO U, DBA.USUARIO_LOGIN UL WHERE U.IDUSUARIO = UL.IDUSUARIO AND IDCONEXAO = DBA.UF_GET_ID_CONNECTION());' || LS_CRLF;
        SET LS_STMT = LS_STMT || '      END IF;' || LS_CRLF;
        SET LS_STMT = LS_STMT || '      IF SESSION_USER <> ''SUPORTECISS'' THEN' || LS_CRLF;
        SET LS_STMT = LS_STMT || '          SET LS_APPNAME = DBA.UF_APPNAME();' || LS_CRLF;
        SET LS_STMT = LS_STMT || '      END IF;' || LS_CRLF;
        SET LS_CAMPOS     = '';
        SET LS_CAMPOSOLD  = '';
        FOR LOOPQUERY AS
            SELECT
                COLNAME AS LS_COLNAME
            FROM
                SYSCAT.COLUMNS
            WHERE
                    TABSCHEMA = AS_SCHEMA AND
                    TABNAME = AS_TABNAME AND
                    TYPENAME IN ('DECIMAL', 'LONG VARCHAR', 'VARCHAR', 'CHARACTER', 'SMALLINT', 'INTEGER', 'BIGINT', 'DATE', 'TIME', 'TIMESTAMP')
            ORDER BY
                COLNO
            DO
                SET LS_CAMPOSOLD  = LS_CAMPOSOLD || 'O.' || LS_COLNAME || ',';
                SET LS_CAMPOS     = LS_CAMPOS    ||         LS_COLNAME || ',';
            END FOR;
        IF LENGTH(LS_CAMPOS) > 0 THEN
            SET LS_CAMPOSOLD  = LEFT(LS_CAMPOSOLD, LENGTH(LS_CAMPOSOLD) - 1);
            SET LS_CAMPOS     = LEFT(LS_CAMPOS, LENGTH(LS_CAMPOS) - 1);
            -- Campos de controle
            SET LS_CAMPOSOLD  = '''U'',SESSION_USER,LS_APPNAME,DBA.UF_GET_HOSTNAME(APPLICATION_ID),LS_USER,LS_VERSAO,' || LS_CAMPOSOLD;
            SET LS_CAMPOS     = 'A_TIPODML,A_USUARIOBD,A_APP,A_IP,A_USERCISS,A_VERSAOCISS,' || LS_CAMPOS;
        ELSE
            SET LS_CAMPOSOLD  = '''U'',SESSION_USER,LS_APPNAME,DBA.UF_GET_HOSTNAME(APPLICATION_ID),LS_USER,LS_VERSAO';
            SET LS_CAMPOS     = 'A_TIPODML,A_USUARIOBD,A_APP,A_IP,A_USERCISS,A_VERSAOCISS';
        END IF;
        SET LS_STMT = LS_STMT || '      INSERT INTO AUDLOG.' || LS_TABNAMELOG || ' (' || LS_CAMPOS || ')' || LS_CRLF;
        SET LS_STMT = LS_STMT || '      VALUES (' || LS_CAMPOSOLD || ');' || LS_CRLF;
        SET LS_STMT = LS_STMT || 'END';
        EXECUTE IMMEDIATE LS_STMT;
    END IF;
    --
    -- CRIA TRIGGER PARA DELETE
    --
    IF AS_FLAGDELETE = 'T' THEN
        SET LS_STMT = 'CREATE OR REPLACE TRIGGER AUDLOG.TR_DEL_AUDLOG_' || LS_CODIGO || ' AFTER DELETE ON ' || AS_SCHEMA || '.' || AS_TABNAME || LS_CRLF;
        SET LS_STMT = LS_STMT || 'REFERENCING OLD AS O' || LS_CRLF;
        SET LS_STMT = LS_STMT || 'FOR EACH ROW WHEN ( CURRENT TIMESTAMP BETWEEN ''' || ADT_DTINI || ''' AND ''' || ADT_DTFIM || ''')' || LS_CRLF;
        SET LS_STMT = LS_STMT || 'BEGIN ATOMIC' || LS_CRLF;
        SET LS_STMT = LS_STMT || '      DECLARE LS_USER VARCHAR(40);' || LS_CRLF;
        SET LS_STMT = LS_STMT || '      DECLARE LS_VERSAO VARCHAR(50);' || LS_CRLF;
        SET LS_STMT = LS_STMT || '      DECLARE LS_APPNAME  VARCHAR(32) DEFAULT '''';' || LS_CRLF;
        SET LS_STMT = LS_STMT || '      IF SESSION_USER = ''DBA'' THEN' || LS_CRLF;
        SET LS_STMT = LS_STMT || '          SET (LS_USER, LS_VERSAO) = (SELECT NOMEUSUARIO, SUBSTR(UL.RELEASECONEXAO,1,50) FROM DBA.USUARIO U, DBA.USUARIO_LOGIN UL WHERE U.IDUSUARIO = UL.IDUSUARIO AND IDCONEXAO = DBA.UF_GET_ID_CONNECTION());' || LS_CRLF;
        SET LS_STMT = LS_STMT || '      END IF;' || LS_CRLF;
        SET LS_STMT = LS_STMT || '      IF SESSION_USER <> ''SUPORTECISS'' THEN' || LS_CRLF;
        SET LS_STMT = LS_STMT || '          SET LS_APPNAME = DBA.UF_APPNAME();' || LS_CRLF;
        SET LS_STMT = LS_STMT || '      END IF;' || LS_CRLF;
        SET LS_CAMPOS     = '';
        SET LS_CAMPOSOLD  = '';
        FOR LOOPQUERY AS
            SELECT
                COLNAME AS LS_COLNAME
            FROM
                SYSCAT.COLUMNS
            WHERE
                    TABSCHEMA = AS_SCHEMA AND
                    TABNAME = AS_TABNAME AND
                    TYPENAME IN ('DECIMAL', 'LONG VARCHAR', 'VARCHAR', 'CHARACTER', 'SMALLINT', 'INTEGER', 'BIGINT', 'DATE', 'TIME', 'TIMESTAMP')
            ORDER BY
                COLNO
            DO
                SET LS_CAMPOSOLD  = LS_CAMPOSOLD || 'O.' || LS_COLNAME || ',';
                SET LS_CAMPOS     = LS_CAMPOS    ||         LS_COLNAME || ',';
            END FOR;
        IF LENGTH(LS_CAMPOS) > 0 THEN
            SET LS_CAMPOSOLD  = LEFT(LS_CAMPOSOLD, LENGTH(LS_CAMPOSOLD) - 1);
            SET LS_CAMPOS     = LEFT(LS_CAMPOS, LENGTH(LS_CAMPOS) - 1);
            -- Campos de controle
            SET LS_CAMPOSOLD  = '''D'',SESSION_USER,LS_APPNAME,DBA.UF_GET_HOSTNAME(APPLICATION_ID),LS_USER,LS_VERSAO,' || LS_CAMPOSOLD;
            SET LS_CAMPOS     = 'A_TIPODML,A_USUARIOBD,A_APP,A_IP,A_USERCISS,A_VERSAOCISS,' || LS_CAMPOS;
        ELSE
            SET LS_CAMPOSOLD  = '''D'',SESSION_USER,LS_APPNAME,DBA.UF_GET_HOSTNAME(APPLICATION_ID),LS_USER,LS_VERSAO';
            SET LS_CAMPOS     = 'A_TIPODML,A_USUARIOBD,A_APP,A_IP,A_USERCISS,A_VERSAOCISS';
        END IF;
        SET LS_STMT = LS_STMT || '      INSERT INTO AUDLOG.' || LS_TABNAMELOG || ' (' || LS_CAMPOS || ')' || LS_CRLF;
        SET LS_STMT = LS_STMT || '      VALUES (' || LS_CAMPOSOLD || ');' || LS_CRLF;
        SET LS_STMT = LS_STMT || 'END';
        EXECUTE IMMEDIATE LS_STMT;
    END IF;
    --
    -- CRIA TRIGGER PARA INSERT
    --
    IF AS_FLAGINSERT = 'T' THEN
        SET LS_STMT = 'CREATE OR REPLACE TRIGGER AUDLOG.TR_INS_AUDLOG_' || LS_CODIGO || ' AFTER INSERT ON ' || AS_SCHEMA || '.' || AS_TABNAME || LS_CRLF;
        SET LS_STMT = LS_STMT || 'REFERENCING NEW AS N' || LS_CRLF;
        SET LS_STMT = LS_STMT || 'FOR EACH ROW WHEN ( CURRENT TIMESTAMP BETWEEN ''' || ADT_DTINI || ''' AND ''' || ADT_DTFIM || ''')' || LS_CRLF;
        SET LS_STMT = LS_STMT || 'BEGIN ATOMIC' || LS_CRLF;
        SET LS_STMT = LS_STMT || '      DECLARE LS_USER VARCHAR(40);' || LS_CRLF;
        SET LS_STMT = LS_STMT || '      DECLARE LS_VERSAO VARCHAR(50);' || LS_CRLF;
        SET LS_STMT = LS_STMT || '      DECLARE LS_APPNAME  VARCHAR(32) DEFAULT '''';' || LS_CRLF;
        SET LS_STMT = LS_STMT || '      IF SESSION_USER = ''DBA'' THEN' || LS_CRLF;
        SET LS_STMT = LS_STMT || '          SET (LS_USER, LS_VERSAO) = (SELECT NOMEUSUARIO, SUBSTR(UL.RELEASECONEXAO,1,50) FROM DBA.USUARIO U, DBA.USUARIO_LOGIN UL WHERE U.IDUSUARIO = UL.IDUSUARIO AND IDCONEXAO = DBA.UF_GET_ID_CONNECTION());' || LS_CRLF;
        SET LS_STMT = LS_STMT || '      END IF;' || LS_CRLF;
        SET LS_STMT = LS_STMT || '      IF SESSION_USER <> ''SUPORTECISS'' THEN' || LS_CRLF;
        SET LS_STMT = LS_STMT || '          SET LS_APPNAME = DBA.UF_APPNAME();' || LS_CRLF;
        SET LS_STMT = LS_STMT || '      END IF;' || LS_CRLF;
        SET LS_CAMPOS     = '';
        SET LS_CAMPOSOLD  = '';
        FOR LOOPQUERY AS
            SELECT
                COLNAME AS LS_COLNAME
            FROM
                SYSCAT.COLUMNS
            WHERE
                    TABSCHEMA = AS_SCHEMA AND
                    TABNAME = AS_TABNAME AND
                    TYPENAME IN ('DECIMAL', 'LONG VARCHAR', 'VARCHAR', 'CHARACTER', 'SMALLINT', 'INTEGER', 'BIGINT', 'DATE', 'TIME', 'TIMESTAMP')
            ORDER BY
                COLNO
            DO
                SET LS_CAMPOSOLD  = LS_CAMPOSOLD || 'N.' || LS_COLNAME || ',';
                SET LS_CAMPOS     = LS_CAMPOS    ||         LS_COLNAME || ',';
            END FOR;
        IF LENGTH(LS_CAMPOS) > 0 THEN
            SET LS_CAMPOSOLD  = LEFT(LS_CAMPOSOLD, LENGTH(LS_CAMPOSOLD) - 1);
            SET LS_CAMPOS     = LEFT(LS_CAMPOS, LENGTH(LS_CAMPOS) - 1);
            -- Campos de controle
            SET LS_CAMPOSOLD  = '''I'',SESSION_USER,LS_APPNAME,DBA.UF_GET_HOSTNAME(APPLICATION_ID),LS_USER,LS_VERSAO,' || LS_CAMPOSOLD;
            SET LS_CAMPOS     = 'A_TIPODML,A_USUARIOBD,A_APP,A_IP,A_USERCISS,A_VERSAOCISS,' || LS_CAMPOS;
        ELSE
            SET LS_CAMPOSOLD  = '''I'',SESSION_USER,LS_APPNAME,DBA.UF_GET_HOSTNAME(APPLICATION_ID),LS_USER,LS_VERSAO';
            SET LS_CAMPOS     = 'A_TIPODML,A_USUARIOBD,A_APP,A_IP,A_USERCISS,A_VERSAOCISS';
        END IF;
        SET LS_STMT = LS_STMT || '      INSERT INTO AUDLOG.' || LS_TABNAMELOG || ' (' || LS_CAMPOS || ')' || LS_CRLF;
        SET LS_STMT = LS_STMT || '      VALUES (' || LS_CAMPOSOLD || ');' || LS_CRLF;
        SET LS_STMT = LS_STMT || 'END';
        EXECUTE IMMEDIATE LS_STMT;
    END IF;
    ELSE
        SIGNAL SQLSTATE '99999' SET MESSAGE_TEXT='Tabela alvo inválida/inexistente';
    END IF;
END
