CREATE OR REPLACE TRIGGER DBA.TR_INS_CONFPED_PERSON AFTER INSERT ON DBA.CONFERE_PEDIDO
REFERENCING NEW AS N
FOR EACH ROW
WHEN (DBA.UF_CONFERE_PEDIDO_UTILIZA_WMS(N.IDEMPRESA, N.IDPEDIDO) = 'F')
BEGIN ATOMIC

    IF (SELECT COUNT(0) FROM WMS.TB_WMS_ENTRADA WHERE IDAUTORIZACAO = N.IDAUTORIZACAO AND IDPRODUTO = N.IDPRODUTO AND IDSUBPRODUTO = N.IDSUBPRODUTO) = 0 THEN
        INSERT INTO WMS.TB_WMS_ENTRADA
            (ENTRADA_ID, NRODOC, SERIE, LINHA, CODFOR, CODITEM, QTDE, QTDE_EXEC, TPDOC, STATUS, DTHR, AUTREC_ID, EMPRESA,
            IDEMPRESA, IDAUTORIZACAO, IDPRODUTO, IDSUBPRODUTO, NUMSEQUENCIA)
        VALUES
            (N.IDEMPRESA||'|'||N.IDAUTORIZACAO||'|'||N.IDPRODUTO||'|'||N.IDSUBPRODUTO||'|0|0|0', N.IDAUTORIZACAO,
            N.SERIENOTA, 1, N.IDCLIFOR, N.IDSUBPRODUTO, N.QTDPRODUTO, 0, 1, 9, SYSDATE,
            (SELECT COALESCE(MIN(AUTREC_ID),0)-1 FROM WMS.TB_WMS_ENTRADA WHERE AUTREC_ID < 0),
            N.IDEMPRESA, N.IDEMPRESA, N.IDAUTORIZACAO, N.IDPRODUTO, N.IDSUBPRODUTO, 0);
    END IF;
END
