CREATE OR REPLACE FUNCTION DBA.UF_CONFERE_PEDIDO_UTILIZA_WMS(
	IN_IDEMPRESA INTEGER,
	IN_IDPEDIDO INTEGER
)
RETURNS CHAR(1)
LANGUAGE SQL
READS SQL DATA
NO EXTERNAL ACTION
BEGIN ATOMIC
	DECLARE LC_FLAGUTILIZAWMSFULLSOFT CHAR(1) DEFAULT 'T';

	SET LC_FLAGUTILIZAWMSFULLSOFT = COALESCE((
		SELECT
			COALESCE(ECL.FLAGUTILIZAWMSFULLSOFT, 'T')
		FROM
			DBA.PEDIDO_COMPRA PC
		JOIN
			DBA.OPERACAO_INTERNA OI ON
				OI.IDOPERACAO = PC.IDOPERACAO
		LEFT JOIN
			DBA.OPERACAO_INTERNA_EMPRESA OIE ON
				OIE.IDOPERACAO = PC.IDOPERACAO AND
				OIE.IDEMPRESA = PC.IDEMPRESA
		LEFT JOIN
			DBA.ESTOQUE_CADASTRO_LOCAL ECL ON
				ECL.IDLOCALESTOQUE = COALESCE(OIE.IDLOCALESTOQUE, OI.IDLOCALESTOQUE)
		WHERE
			PC.IDEMPRESA = IN_IDEMPRESA AND
			PC.IDPEDIDO = IN_IDPEDIDO
		FETCH FIRST 1 ROW ONLY
	), 'T');

	RETURN LC_FLAGUTILIZAWMSFULLSOFT;
END
