CREATE OR REPLACE VIEW WMS.V_WMS_ENTRADA AS
--CANCELAMENTO DE NOTAS FISCAIS
SELECT
	DBA.UF_RETURNPIPE(PSE.IDEMPRESA, PSE.IDSEPARAR, PSE.IDPRODUTO, PSE.IDSUBPRODUTO, PSE.NUMSEQUENCIA, 0, 0) AS ENTRADA_ID,
	RIGHT(TRIM(CAST(CAST(PSE.IDDOCUMENTO AS CHAR(15)) AS VARCHAR(15))),10) AS NRODOC,
	NOTAS.SERIENOTA AS SERIE,
	PSE.NUMSEQUENCIA AS LINHA,
	TRIM(CAST(CAST(NOTAS.IDCLIFOR AS CHAR(30)) AS VARCHAR(30))) AS CODFOR,
	CAST(CF.NOME AS VARCHAR(50)) AS DESCFOR,
	TRIM(CAST(CAST(PSE.IDSUBPRODUTO AS CHAR(20)) AS VARCHAR(20))) AS CODITEM,
	CAST(COALESCE(PSE.QTDPRODUTO,0) AS NUMERIC(10,4)) AS QTDE,
	'2' AS TPDOC,
	'' AS PLACA,
	PSE.IDLOTE AS LOTE,
	PSE.IDEMPRESA AS EMPRESA,
	(
		SELECT
			IDEMPRESACENTRAL
		FROM
			DBA.CONFIG_COMPRAS
		WHERE
			IDCONFIGCOMPRAS = 1
	) AS CD
FROM
	DBA.PRODUTO_SEPARACAO_EXCLUSAO PSE
JOIN
	DBA.NOTAS ON
		NOTAS.IDPLANILHA = PSE.IDPLANILHAVENDA AND
		NOTAS.IDEMPRESA = PSE.IDEMPRESA
JOIN
	DBA.EMPRESA EMP ON
		EMP.IDEMPRESA = PSE.IDEMPRESABAIXAEST
LEFT OUTER JOIN
	DBA.CLIENTE_FORNECEDOR CF ON
		CF.IDCLIFOR = NOTAS.IDCLIFOR
JOIN
	DBA.LOCAL_RETIRADA LOR ON
		PSE.IDLOCALRETIRADA = LOR.IDLOCALRETIRADA
WHERE
	EMP.FLAGUTILIZAWMSFULLSOFT = 'T' AND
	LOR.FLAGUTILIZAWMSFULLSOFT = 'T' AND
	PSE.TIPODOCUMENTO <> 'P' AND
	FLAGNOTACANCEL = 'T' AND
	PSE.QTDSEPARADO > 0 AND
	PSE.DTMOVIMENTODOC > COALESCE(EMP.DTINIWMSSAIDAS,'1900-01-01') AND
	NOT EXISTS (
		SELECT
			1
		FROM
			WMS.TB_WMS_ENTRADA TWE
		WHERE
			TWE.IDEMPRESA = PSE.IDEMPRESA AND
			TWE.IDAUTORIZACAO = PSE.IDSEPARAR AND
			TWE.IDPRODUTO = PSE.IDPRODUTO AND
			TWE.IDSUBPRODUTO = PSE.IDSUBPRODUTO AND
			TWE.NUMSEQUENCIA = PSE.NUMSEQUENCIA
	)

UNION ALL

--Cancelamento de Separacao
SELECT
	DBA.UF_RETURNPIPE(PSE.IDEMPRESA, PSE.IDSEPARAR, PSE.IDPRODUTO, PSE.IDSUBPRODUTO, PSE.NUMSEQUENCIA, 0, 0) AS ENTRADA_ID,
	RIGHT(TRIM(CAST(CAST(PSE.IDDOCUMENTO AS CHAR(15)) AS VARCHAR(15))),10) AS NRODOC,
	'PRE' AS SERIE,
	PSE.NUMSEQUENCIA AS LINHA,
	TRIM(CAST(CAST(PV.IDCLIFOR AS CHAR(30)) AS VARCHAR(30))) AS CODFOR,
	CAST(CF.NOME AS VARCHAR(50)) AS DESCFOR,
	TRIM(CAST(CAST(PSE.IDSUBPRODUTO AS CHAR(20)) AS VARCHAR(20))) AS CODITEM,
	CAST(COALESCE(PSE.QTDPRODUTO,0) AS NUMERIC(10,4)) AS QTDE,
	'2' AS TPDOC,
	'' AS PLACA,
	PSE.IDLOTE AS LOTE,
	PSE.IDEMPRESA AS EMPRESA,
	(
		SELECT
			IDEMPRESACENTRAL
		FROM
			DBA.CONFIG_COMPRAS
		WHERE
			IDCONFIGCOMPRAS = 1
	) AS CD
FROM
	DBA.PRODUTO_SEPARACAO_EXCLUSAO PSE
JOIN
	DBA.PRE_VENDA PV ON
		PV.IDPREVENDA = PSE.IDDOCUMENTO AND
		PV.IDEMPRESA = PSE.IDEMPRESA AND
		PV.DTMOVIMENTO = PSE.DTMOVIMENTODOC
LEFT OUTER JOIN
	DBA.CLIENTE_FORNECEDOR CF ON
		CF.IDCLIFOR = PV.IDCLIFOR
LEFT OUTER JOIN
	DBA.EMPRESA EMP ON
		EMP.IDEMPRESA = PSE.IDEMPRESABAIXAEST
JOIN
	DBA.LOCAL_RETIRADA LOR ON
		PSE.IDLOCALRETIRADA = LOR.IDLOCALRETIRADA
WHERE
	EMP.FLAGUTILIZAWMSFULLSOFT = 'T' AND
	LOR.FLAGUTILIZAWMSFULLSOFT = 'T' AND
	PSE.TIPODOCUMENTO = 'P' AND
	PSE.QTDSEPARADO > 0 AND
	PV.DTMOVIMENTO > COALESCE(EMP.DTINIWMSENTRADAS,'1900-01-01') AND
	NOT EXISTS (
		SELECT
			1
		FROM
			WMS.TB_WMS_ENTRADA TWE
		WHERE
			TWE.IDEMPRESA = PSE.IDEMPRESA AND
			TWE.IDAUTORIZACAO = PSE.IDSEPARAR AND
			TWE.IDPRODUTO = PSE.IDPRODUTO AND
			TWE.IDSUBPRODUTO = PSE.IDSUBPRODUTO AND
			TWE.NUMSEQUENCIA = PSE.NUMSEQUENCIA
	)

UNION ALL

--Autorizacao de Recepcao
SELECT
	DBA.UF_RETURNPIPE(CP.IDEMPRESA, CP.IDAUTORIZACAO, CP.IDPRODUTO, CP.IDSUBPRODUTO, 0,/*SEQUENCIA*/ 0, 0) AS ENTRADA_ID,
	RIGHT(TRIM(CAST(CAST(CP.IDAUTORIZACAO AS CHAR(15)) AS VARCHAR(15))),10) AS NRODOC,
	CP.SERIENOTA AS SERIE,
	1 AS LINHA,
	TRIM(CAST(CAST(CP.IDCLIFOR AS CHAR(30)) AS VARCHAR(30))) AS CODFOR,
	CAST(CF.NOME AS VARCHAR(50)) AS DESCFOR,
	TRIM(CAST(CAST(CP.IDSUBPRODUTO AS CHAR(20)) AS VARCHAR(20))) AS CODITEM,
	SUM(CAST(COALESCE(CP.QTDPRODUTO,0) AS NUMERIC(10,4))) AS QTDE,
	'1' AS TPDOC,
	'' AS PLACA,
	'' AS LOTE,
	CP.IDEMPRESA AS EMPRESA,
	(
		SELECT
			IDEMPRESACENTRAL
		FROM
			DBA.CONFIG_COMPRAS
		WHERE
			IDCONFIGCOMPRAS = 1
	) AS CD
FROM
	DBA.CONFERE_PEDIDO CP
JOIN
	DBA.EMPRESA EMP ON
		EMP.IDEMPRESA = CP.IDEMPRESA
JOIN
	DBA.CONFERE_AUTORIZA CA ON
		CP.IDCLIFOR = CA.IDCLIFOR AND
		CP.IDEMPRESA = CA.IDEMPRESA AND
		CP.IDAUTORIZACAO = CA.IDAUTORIZACAO AND
		CP.NUMNOTA = CA.NUMNOTA AND
		CP.SERIENOTA = CA.SERIENOTA
JOIN
	DBA.CLIENTE_FORNECEDOR CF ON
		CF.IDCLIFOR = CP.IDCLIFOR
WHERE
	EMP.FLAGUTILIZAWMSFULLSOFT = 'T' AND
	DBA.UF_CONFERE_PEDIDO_UTILIZA_WMS(CP.IDEMPRESA, CP.IDPEDIDO) = 'T' AND
	CP.SERIENOTA <> 'PED' AND
	CP.FLAGNOTAGRAVADA = 'F' AND
	CA.DTMOVIMENTO > COALESCE(EMP.DTINIWMSENTRADAS,'1900-01-01') AND
	NOT EXISTS (
		SELECT
			0
		FROM
			DBA.CONFERE_MERCADORIA CM
		WHERE
			CM.IDPRODUTO = CP.IDPRODUTO AND
			CM.IDSUBPRODUTO = CP.IDSUBPRODUTO AND
			CM.IDAUTORIZACAO = CP.IDAUTORIZACAO
	) AND
	NOT EXISTS (
		SELECT
			1
		FROM
			WMS.TB_WMS_ENTRADA TWE
		WHERE
			TWE.IDEMPRESA = CP.IDEMPRESA AND
			TWE.IDAUTORIZACAO = CP.IDAUTORIZACAO AND
			TWE.IDPRODUTO = CP.IDPRODUTO AND
			TWE.IDSUBPRODUTO = CP.IDSUBPRODUTO
	)
GROUP BY
	CP.IDAUTORIZACAO,
	CP.SERIENOTA,
	CP.IDCLIFOR,
	CF.NOME,
	CP.IDSUBPRODUTO,
	CP.IDEMPRESA,
	CP.IDPRODUTO

UNION ALL

--Notas de entrada
SELECT
	DBA.UF_RETURNPIPE(EST.IDEMPRESA, EST.IDPLANILHA, EST.IDPRODUTO, EST.IDSUBPRODUTO, EST.NUMSEQUENCIA, 0, 0) AS ENTRADA_ID,
	RIGHT(TRIM(CAST(CAST(NOTAS.NUMNOTA AS CHAR(15)) AS VARCHAR(15))),10) AS NRODOC,
	NOTAS.SERIENOTA AS SERIE,
	EST.NUMSEQUENCIA AS LINHA,
	TRIM(CAST(CAST(NOTAS.IDCLIFOR AS CHAR(30)) AS VARCHAR(30))) AS CODFOR,
	CAST(CF.NOME AS VARCHAR(50)) AS DESCFOR,
	TRIM(CAST(CAST(EST.IDSUBPRODUTO AS CHAR(20)) AS VARCHAR(20))) AS CODITEM,
	CAST(COALESCE(EST.QTDPRODUTO,0) AS NUMERIC(10,4)) AS QTDE,
	CASE
		WHEN OPI.TIPOCATEGORIA = 'D' THEN
			'2'
		ELSE
			'1'
	END AS TPDOC,
	'' AS PLACA,
	EST.IDLOTE AS LOTE,
	CASE
		WHEN OPI.TIPOCATEGORIA = 'D' THEN
			COALESCE(ECL.IDEMPRESABAIXAEST,EST.IDEMPRESA)
		ELSE
			EST.IDEMPRESA
	END AS EMPRESA,
	CASE
		WHEN OPI.TIPOCATEGORIA = 'D' THEN
			COALESCE(ECL.IDEMPRESABAIXAEST,(
				SELECT
					IDEMPRESACENTRAL
				FROM
					DBA.CONFIG_COMPRAS
				WHERE
					IDCONFIGCOMPRAS = 1
			))
		ELSE
			(
				SELECT
					IDEMPRESACENTRAL
				FROM
					DBA.CONFIG_COMPRAS
				WHERE
					IDCONFIGCOMPRAS = 1
			)
	END AS CD
FROM
	DBA.ESTOQUE_ANALITICO EST
JOIN
	DBA.NOTAS_ENTRADA_SAIDA NES ON
		EST.IDPLANILHA = NES.IDPLANILHA AND
		EST.IDEMPRESA = NES.IDEMPRESA
JOIN
	DBA.EMPRESA EMP ON
		EMP.IDEMPRESA = COALESCE( EST.IDEMPRESAORIGEMTRANSF, EST.IDEMPRESA )
JOIN
	DBA.OPERACAO_INTERNA OPI ON
		OPI.IDOPERACAO = NES.IDOPERACAO
JOIN
	DBA.NOTAS ON
		EST.IDPLANILHA = NOTAS.IDPLANILHA AND
		EST.IDEMPRESA = NOTAS.IDEMPRESA
JOIN
	DBA.CLIENTE_FORNECEDOR CF ON
		CF.IDCLIFOR = NOTAS.IDCLIFOR
JOIN
	DBA.LOCAL_RETIRADA LOR ON
		LOR.IDLOCALRETIRADA = EST.IDLOCALRETIRADA
JOIN
	DBA.ESTOQUE_CADASTRO_LOCAL ECL ON
		LOR.IDLOCALESTOQUE = ECL.IDLOCALESTOQUE
WHERE
	EMP.FLAGUTILIZAWMSFULLSOFT = 'T' AND
	LOR.FLAGUTILIZAWMSFULLSOFT = 'T' AND
	OPI.IDOPERACAO < 1000 AND
	OPI.FLAGMOVSALDOPRO = 'T' AND
	NES.DTMOVIMENTO > COALESCE(EMP.DTINIWMSENTRADAS,'1900-01-01') AND
	LEFT(NOTAS.SERIENOTA,2) <> 'AV' AND
	CASE
		WHEN OPI.TIPOITEMCATEGORIA <> 'F1' THEN
			COALESCE((
				SELECT
					DISTINCT IDAUTORIZACAO
				FROM
					CONFERE_PEDIDO
				WHERE
					CONFERE_PEDIDO.NUMNOTA = NOTAS.NUMNOTA AND
					CONFERE_PEDIDO.SERIENOTA = NOTAS.SERIENOTA AND
					CONFERE_PEDIDO.IDEMPRESA = NOTAS.IDEMPRESA AND
					CONFERE_PEDIDO.IDCLIFOR = NOTAS.IDCLIFOR AND
					CONFERE_PEDIDO.IDAUTORIZACAO > 0
			), 0 )
		ELSE
			EST.NUMPEDIDO
	END = 0 AND
	NOT EXISTS (
		SELECT
			1
		FROM
			WMS.TB_WMS_ENTRADA TWE
		WHERE
			TWE.IDEMPRESA = EST.IDEMPRESA AND
			TWE.IDAUTORIZACAO = EST.IDPLANILHA AND
			TWE.IDPRODUTO = EST.IDPRODUTO AND
			TWE.IDSUBPRODUTO = EST.IDSUBPRODUTO AND
			TWE.NUMSEQUENCIA = EST.NUMSEQUENCIA
	)

UNION ALL

--Devolucao no logistica
SELECT
	DBA.UF_RETURNPIPE(PDL.IDEMPRESABAIXAEST, PDL.IDDEVOLUCAO, PDL.IDPRODUTO, PDL.IDSUBPRODUTO, PDL.NUMSEQUENCIA, 0, 0) AS ENTRADA_ID,
	RIGHT(TRIM(CAST(CAST(PDL.IDDEVOLUCAO AS CHAR(15)) AS VARCHAR(15))),10) AS NRODOC,
	'DEV' AS SERIE,
	PDL.NUMSEQUENCIA AS LINHA,
	TRIM(CAST(CAST(CF.IDCLIFOR AS CHAR(30)) AS VARCHAR(30))) AS CODFOR,
	CAST(CF.NOME AS VARCHAR(50)) AS DESCFOR,
	TRIM(CAST(CAST(PDL.IDSUBPRODUTO AS CHAR(20)) AS VARCHAR(20))) AS CODITEM,
	CAST(COALESCE(PDL.QTDPRODUTO,0) AS NUMERIC(10,4)) AS QTDE,
	'2' AS TPDOC,
	'' AS PLACA,
	PDL.IDLOTE AS LOTE,
	PDL.IDEMPRESABAIXAEST AS EMPRESA,
	CASE
		WHEN COALESCE(PDL.IDEMPRESABAIXAEST,0) > 0 THEN
			PDL.IDEMPRESABAIXAEST
		ELSE
			(
				SELECT
					IDEMPRESACENTRAL
				FROM
					DBA.CONFIG_COMPRAS
				WHERE
					IDCONFIGCOMPRAS = 1
			)
	END AS CD
FROM
	DBA.PRODUTO_DEVOLUCAO_LOGISTICA PDL
JOIN
	DBA.EMPRESA EMP ON
		EMP.IDEMPRESA = PDL.IDEMPRESABAIXAEST
JOIN
	DBA.CLIENTE_FORNECEDOR CF ON
		CF.IDCLIFOR = PDL.IDCLIFOR
JOIN
	DBA.LOCAL_RETIRADA LOR ON
		LOR.IDLOCALRETIRADA = PDL.IDLOCALRETIRADA
WHERE
	EMP.FLAGUTILIZAWMSFULLSOFT = 'T' AND
	LOR.FLAGUTILIZAWMSFULLSOFT = 'T' AND
	PDL.DTMOVIMENTODOC > COALESCE(EMP.DTINIWMSENTRADAS,'1900-01-01') AND
	NOT EXISTS (
		SELECT
			1
		FROM
			WMS.TB_WMS_ENTRADA TWE
		WHERE
			TWE.IDEMPRESA = PDL.IDEMPRESABAIXAEST AND
			TWE.IDAUTORIZACAO = PDL.IDDEVOLUCAO AND
			TWE.IDPRODUTO = PDL.IDPRODUTO AND
			TWE.IDSUBPRODUTO = PDL.IDSUBPRODUTO AND
			TWE.NUMSEQUENCIA = PDL.NUMSEQUENCIA
	)

UNION ALL

-- Transferencia Avulsa
SELECT
	DBA.UF_RETURNPIPE(TAT.IDEMPRESADESTINO, EST.IDPLANILHATRANSFERENCIA, EST.IDPRODUTO, EST.IDSUBPRODUTO, EST.NUMSEQUENCIA, 0, 0) AS SAIDA_ID,
	RIGHT(TRIM(CAST(CAST(EST.IDPLANILHATRANSFERENCIA AS CHAR(15)) AS VARCHAR(15))),10) AS NRODOC,
	'AVU' AS SERIE,
	EST.NUMSEQUENCIA AS LINHA,
	(
		SELECT
			TRIM(CAST(CAST(CLIORI.IDCLIFOR AS CHAR(30)) AS VARCHAR(30)))
		FROM
			DBA.CLIENTE_FORNECEDOR CLIORI
		WHERE
			CLIORI.CNPJCPF = EMPORI.CNPJ AND
			CLIORI.TIPOCADASTRO <> 'T'
	) AS CODFOR,
	CAST(EMPORI.NOMEFANTASIA AS VARCHAR(50)) AS DESCFOR,
	TRIM(CAST(CAST(EST.IDSUBPRODUTO AS CHAR(20)) AS VARCHAR(20))) AS CODITEM,
	CAST(COALESCE(EST.QTDPRODUTO,0) AS NUMERIC(10,4)) AS QTDE,
	'1' AS TPDOC,
	'' AS PLACA,
	EST.IDLOTE AS LOTE,
	TAT.IDEMPRESADESTINO AS EMPRESA,
	TAT.IDEMPRESADESTINO AS CD
FROM
	DBA.ESTOQUE_ANALITICO_TMP EST
JOIN
	DBA.TRANSFERENCIA_AVULSA_TMP TAT ON
		EST.IDPLANILHATRANSFERENCIA = TAT.IDPLANILHA
JOIN
	DBA.EMPRESA EMP ON
		TAT.IDEMPRESADESTINO = EMP.IDEMPRESA
JOIN
	DBA.EMPRESA EMPORI ON
		TAT.IDEMPRESAORIGEM = EMPORI.IDEMPRESA
JOIN
	DBA.ESTOQUE_CADASTRO_LOCAL ECL ON
		TAT.IDLOCALESTOQUEDESTINO = ECL.IDLOCALESTOQUE
JOIN
	DBA.CIDADES_IBGE CID ON
		CID.IDCIDADE = EMP.IDCIDADE
JOIN
	DBA.PRODUTO_GRADE PG ON
		PG.IDPRODUTO = EST.IDPRODUTO AND
		PG.IDSUBPRODUTO = EST.IDSUBPRODUTO
WHERE
	EST.IDPLANILHATRANSFERENCIA IS NOT NULL AND
	EST.DTMOVIMENTO >= COALESCE(EMP.DTINIWMSSAIDAS,'1900-01-01') AND
	EMP.FLAGUTILIZAWMSFULLSOFT = 'T' AND
	ECL.FLAGUTILIZAWMSFULLSOFT = 'T' AND
	NOT EXISTS (
		SELECT
			1
		FROM
			WMS.TB_WMS_ENTRADA TWS
		WHERE
			TWS.IDEMPRESA = TAT.IDEMPRESADESTINO AND
			TWS.IDAUTORIZACAO = EST.IDPLANILHATRANSFERENCIA AND
			TWS.IDPRODUTO = EST.IDPRODUTO AND
			TWS.IDSUBPRODUTO = EST.IDSUBPRODUTO AND
			TWS.NUMSEQUENCIA = EST.NUMSEQUENCIA
	)
GROUP BY
	TAT.IDEMPRESADESTINO,
	EST.IDPLANILHATRANSFERENCIA,
	EMPORI.CNPJ,
	EST.IDLOTE,
	EST.QTDPRODUTO,
	EST.IDPRODUTO,
	EST.IDSUBPRODUTO,
	EMPORI.NOMEFANTASIA,
	EST.NUMSEQUENCIA
