

WITH EA AS (
        SELECT
                EA.IDEMPRESA,
                EA.IDPLANILHA
        FROM
                ESTOQUE_ANALITICO EA
                INNER JOIN OPERACAO_INTERNA OI ON
                        EA.IDOPERACAO = OI.IDOPERACAO
                JOIN NOTAS N ON
                N.IDPLANILHA = EA.IDPLANILHA AND
                N.IDEMPRESA = EA.IDEMPRESA
        WHERE
                OI.TIPOMOVIMENTO = 'C'
                AND EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM AND
                EA.IDOPERACAO < 1000 AND
                N.FLAGMOVFISCAL = 'T'
        GROUP BY
                EA.IDEMPRESA,
                EA.IDPLANILHA
),
EAF AS (
        SELECT
        CASE
            WHEN SUM(CASE WHEN ESTOQUE_ANALITICO_FISCAL.FLAGTRIBUTACAOXML = 'T' THEN 1 ELSE 0 END) = COUNT(*) THEN 'T'
            ELSE 'F'
        END AS FLAGTRIBUTACAOXML,
                ESTOQUE_ANALITICO_FISCAL.IDEMPRESA,
                ESTOQUE_ANALITICO_FISCAL.IDPLANILHA
        FROM
                DBA.ESTOQUE_ANALITICO_FISCAL ESTOQUE_ANALITICO_FISCAL
                INNER JOIN EA ON
                        ESTOQUE_ANALITICO_FISCAL.IDEMPRESA = EA.IDEMPRESA AND
                        ESTOQUE_ANALITICO_FISCAL.IDPLANILHA = EA.IDPLANILHA
        GROUP BY
                ESTOQUE_ANALITICO_FISCAL.IDEMPRESA,
                ESTOQUE_ANALITICO_FISCAL.IDPLANILHA
)

SELECT
        COUNT(CASE WHEN FLAGTRIBUTACAOXML = 'T' THEN 1 END) AS XML,
        COUNT(CASE WHEN FLAGTRIBUTACAOXML = 'F' THEN 1 END) AS CADASTRO,
        CF.IDCLIFOR
FROM
        EAF
        INNER JOIN NOTAS N ON
                N.IDEMPRESA = EAF.IDEMPRESA AND
                N.IDPLANILHA = EAF.IDPLANILHA
        INNER JOIN CLIENTE_FORNECEDOR CF ON
                CF.IDCLIFOR = N.IDCLIFOR
GROUP BY
        CF.IDCLIFOR