SELECT
        TIPO,
        QTDNOTASTIPO,
        QTDNOTAS,
        (CAST(QTDNOTASTIPO AS DECIMAL(15,6))/CAST(QTDNOTAS AS DECIMAL(15,6))) *100 AS PERREPRESENTATIPO,
        QTDTOTAL,
        (CAST(QTDNOTASTIPO AS DECIMAL(15,6))/CAST(QTDTOTAL AS DECIMAL(15,6))) *100 AS PERREPRESENTATOTAL
FROM (
SELECT
        TIPO,
        SUM(QTDPLANILHA) OVER (PARTITION BY TIPO) AS QTDNOTASTIPO,
        SUM(QTDPLANILHA) OVER () AS QTDNOTAS,
        (SELECT
        COUNT (0)
    FROM
        DBA.NOTAS N
        JOIN DBA.NOTAS_ENTRADA_SAIDA NES ON
        NES.IDPLANILHA = N.IDPLANILHA AND
        NES.IDEMPRESA = N.IDEMPRESA
        JOIN DBA.OPERACAO_INTERNA OI ON
        OI.IDOPERACAO = NES.IDOPERACAO
    WHERE
        NES.IDOPERACAO < 1000 AND
        OI.TIPOMOVIMENTO = 'C' AND
        N.FLAGMOVFISCAL = 'T' AND
        N.DTMOVIMENTO BETWEEN DBA.DTINI (:RA_DTINI) AND DBA.DTFIM (:RA_DTFIM)
        ) AS QTDTOTAL
FROM (
    SELECT
        COUNT(DISTINCT N.IDPLANILHA) AS QTDPLANILHA,
        'ISENTO-40' AS TIPO
    FROM
        DBA.ESTOQUE_ANALITICO EA
        JOIN DBA.OPERACAO_INTERNA OI ON
        OI.IDOPERACAO = EA.IDOPERACAO
        JOIN DBA.NOTAS N ON
        N.IDPLANILHA = EA.IDPLANILHA AND
        N.IDEMPRESA = EA.IDEMPRESA
    WHERE
        EA.IDSITTRIB IN (40, 140, 240, 340, 440, 540, 640, 740, 840) AND
        EA.IDOPERACAO < 1000 AND
        OI.TIPOMOVIMENTO = 'C' AND
        N.FLAGMOVFISCAL = 'T' AND
        EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM AND
        NOT EXISTS (
            SELECT
                0
            FROM
                DBA.ESTOQUE_ANALITICO EA2
            WHERE
                EA2.IDEMPRESA = EA.IDEMPRESA AND
                EA2.IDPLANILHA = EA.IDPLANILHA AND
                EA2.IDSITTRIB NOT IN (40, 140, 240, 340, 440, 540, 640, 740, 840) AND
                EA2.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
                )
UNION ALL

    SELECT
        COUNT(DISTINCT N.IDPLANILHA) AS QTDPLANILHA,
        'TRIBUTADO-00' AS TIPO
    FROM
        DBA.ESTOQUE_ANALITICO EA
        JOIN DBA.OPERACAO_INTERNA OI ON
        OI.IDOPERACAO = EA.IDOPERACAO
        JOIN DBA.NOTAS N ON
        N.IDPLANILHA = EA.IDPLANILHA AND
        N.IDEMPRESA = EA.IDEMPRESA
    WHERE
        EA.IDSITTRIB IN (00, 100, 200, 300, 400, 500, 600, 700, 800) AND
        EA.IDOPERACAO < 1000 AND
        OI.TIPOMOVIMENTO = 'C' AND
        N.FLAGMOVFISCAL = 'T' AND
        EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM AND
        NOT EXISTS (
            SELECT
                0
            FROM
                DBA.ESTOQUE_ANALITICO EA2
            WHERE
                EA2.IDEMPRESA = EA.IDEMPRESA AND
                EA2.IDPLANILHA = EA.IDPLANILHA AND
                EA2.IDSITTRIB NOT IN (00, 100, 200, 300, 400, 500, 600, 700, 800) AND
                EA2.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
            )
UNION ALL

    SELECT
        COUNT(DISTINCT N.IDPLANILHA) AS QTDPLANILHA,
        'REDUCAO-20' AS TIPO
    FROM
        DBA.ESTOQUE_ANALITICO EA
        JOIN DBA.OPERACAO_INTERNA OI ON
        OI.IDOPERACAO = EA.IDOPERACAO
        JOIN DBA.NOTAS N ON
        N.IDPLANILHA = EA.IDPLANILHA AND
        N.IDEMPRESA = EA.IDEMPRESA
    WHERE
        EA.IDSITTRIB IN (20, 120, 220, 320, 420, 520, 620, 720, 820) AND
        EA.IDOPERACAO < 1000 AND
        OI.TIPOMOVIMENTO = 'C' AND
        N.FLAGMOVFISCAL = 'T' AND
        EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM AND
        NOT EXISTS (
            SELECT
                0
            FROM
                DBA.ESTOQUE_ANALITICO EA2
            WHERE
                EA2.IDEMPRESA = EA.IDEMPRESA AND
                EA2.IDPLANILHA = EA.IDPLANILHA AND
                EA2.IDSITTRIB NOT IN (20, 120, 220, 320, 420, 520, 620, 720, 820) AND
                EA2.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
            )
UNION ALL

    SELECT
        COUNT(DISTINCT N.IDPLANILHA) AS QTDPLANILHA,
        'SUSPENSO-50' AS TIPO
    FROM
        DBA.ESTOQUE_ANALITICO EA
        JOIN DBA.OPERACAO_INTERNA OI ON
        OI.IDOPERACAO = EA.IDOPERACAO
        JOIN DBA.NOTAS N ON
        N.IDPLANILHA = EA.IDPLANILHA AND
        N.IDEMPRESA = EA.IDEMPRESA
    WHERE
        EA.IDSITTRIB IN (50, 150, 250, 350, 450, 550, 650, 750, 850) AND
        EA.IDOPERACAO < 1000 AND
        OI.TIPOMOVIMENTO = 'C' AND
        N.FLAGMOVFISCAL = 'T' AND
        EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM AND
        NOT EXISTS (
            SELECT
                0
            FROM
                DBA.ESTOQUE_ANALITICO EA2
            WHERE
                EA2.IDEMPRESA = EA.IDEMPRESA AND
                EA2.IDPLANILHA = EA.IDPLANILHA AND
                EA2.IDSITTRIB NOT IN (50, 150, 250, 350, 450, 550, 650, 750, 850) AND
                EA2.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
            )
UNION ALL

    SELECT
        COUNT(DISTINCT N.IDPLANILHA) AS QTDPLANILHA,
        'SUSPENSO-51' AS TIPO
    FROM
        DBA.ESTOQUE_ANALITICO EA
        JOIN DBA.OPERACAO_INTERNA OI ON
        OI.IDOPERACAO = EA.IDOPERACAO
        JOIN DBA.NOTAS N ON
        N.IDPLANILHA = EA.IDPLANILHA AND
        N.IDEMPRESA = EA.IDEMPRESA
    WHERE
        EA.IDSITTRIB IN (51, 151, 251, 351, 451, 551, 651, 751, 851) AND
        EA.IDOPERACAO < 1000 AND
        OI.TIPOMOVIMENTO = 'C' AND
        N.FLAGMOVFISCAL = 'T' AND
        EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM AND
        NOT EXISTS (
            SELECT
                0
            FROM
                DBA.ESTOQUE_ANALITICO EA2
            WHERE
                EA2.IDEMPRESA = EA.IDEMPRESA AND
                EA2.IDPLANILHA = EA.IDPLANILHA AND
                EA2.IDSITTRIB NOT IN (51, 151, 251, 351, 451, 551, 651, 751, 851) AND
                EA2.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
            )
UNION ALL

    SELECT
        COUNT(DISTINCT N.IDPLANILHA) AS QTDPLANILHA,
        'NAOTRIBUTADO-41' AS TIPO
    FROM
        DBA.ESTOQUE_ANALITICO EA
        JOIN DBA.OPERACAO_INTERNA OI ON
        OI.IDOPERACAO = EA.IDOPERACAO
        JOIN DBA.NOTAS N ON
        N.IDPLANILHA = EA.IDPLANILHA AND
        N.IDEMPRESA = EA.IDEMPRESA
    WHERE
        EA.IDSITTRIB IN (41, 141, 241, 341, 441, 541, 641, 741, 841) AND
        EA.IDOPERACAO < 1000 AND
        OI.TIPOMOVIMENTO = 'C' AND
        N.FLAGMOVFISCAL = 'T' AND
        EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM AND
        NOT EXISTS (
            SELECT
                0
            FROM
                DBA.ESTOQUE_ANALITICO EA2
            WHERE
                EA2.IDEMPRESA = EA.IDEMPRESA AND
                EA2.IDPLANILHA = EA.IDPLANILHA AND
                EA2.IDSITTRIB NOT IN (41, 141, 241, 341, 441, 541, 641, 741, 841) AND
                EA2.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
            )
UNION ALL

    SELECT
        COUNT(DISTINCT N.IDPLANILHA) AS QTDPLANILHA,
        'OUTROS-90' AS TIPO
    FROM
        DBA.ESTOQUE_ANALITICO EA
        JOIN DBA.OPERACAO_INTERNA OI ON
        OI.IDOPERACAO = EA.IDOPERACAO
        JOIN DBA.NOTAS N ON
        N.IDPLANILHA = EA.IDPLANILHA AND
        N.IDEMPRESA = EA.IDEMPRESA
    WHERE
        EA.IDSITTRIB IN (90, 190, 290, 390, 490, 590, 690, 790, 890) AND
        EA.IDOPERACAO < 1000 AND
        OI.TIPOMOVIMENTO = 'C' AND
        N.FLAGMOVFISCAL = 'T' AND
        EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM AND
        NOT EXISTS (
            SELECT
                0
            FROM
                DBA.ESTOQUE_ANALITICO EA2
            WHERE
                EA2.IDEMPRESA = EA.IDEMPRESA AND
                EA2.IDPLANILHA = EA.IDPLANILHA AND
                EA2.IDSITTRIB NOT IN (90, 190, 290, 390, 490, 590, 690, 790, 890) AND
                EA2.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
            )
UNION ALL

    SELECT
        COUNT(DISTINCT N.IDPLANILHA) AS QTDPLANILHA,
        'SUBST-60' AS TIPO
    FROM
        DBA.ESTOQUE_ANALITICO EA
        JOIN DBA.OPERACAO_INTERNA OI ON
        OI.IDOPERACAO = EA.IDOPERACAO
        JOIN DBA.NOTAS N ON
        N.IDPLANILHA = EA.IDPLANILHA AND
        N.IDEMPRESA = EA.IDEMPRESA
    WHERE
        EA.IDSITTRIB IN (60, 160, 260, 360, 460, 560, 660, 760, 860) AND
        EA.IDOPERACAO < 1000 AND
        OI.TIPOMOVIMENTO = 'C' AND
        N.FLAGMOVFISCAL = 'T' AND
        EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM AND
        NOT EXISTS (
            SELECT
                0
            FROM
                DBA.ESTOQUE_ANALITICO EA2
            WHERE
                EA2.IDEMPRESA = EA.IDEMPRESA AND
                EA2.IDPLANILHA = EA.IDPLANILHA AND
                EA2.IDSITTRIB NOT IN (60, 160, 260, 360, 460, 560, 660, 760, 860) AND
                EA2.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
            )
UNION ALL

    SELECT
        COUNT(DISTINCT N.IDPLANILHA) AS QTDPLANILHA,
        'SUBST-61' AS TIPO
    FROM
        DBA.ESTOQUE_ANALITICO EA
        JOIN DBA.OPERACAO_INTERNA OI ON
        OI.IDOPERACAO = EA.IDOPERACAO
        JOIN DBA.NOTAS N ON
        N.IDPLANILHA = EA.IDPLANILHA AND
        N.IDEMPRESA = EA.IDEMPRESA
    WHERE
        EA.IDSITTRIB IN (61, 161, 261, 361, 461, 561, 661, 761, 861) AND
        EA.IDOPERACAO < 1000 AND
        OI.TIPOMOVIMENTO = 'C' AND
        N.FLAGMOVFISCAL = 'T' AND
        EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM AND
        NOT EXISTS (
            SELECT
                0
            FROM
                DBA.ESTOQUE_ANALITICO EA2
            WHERE
                EA2.IDEMPRESA = EA.IDEMPRESA AND
                EA2.IDPLANILHA = EA.IDPLANILHA AND
                EA2.IDSITTRIB NOT IN (61, 161, 261, 361, 461, 561, 661, 761, 861) AND
                EA2.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
            )
    )
)