SELECT
    RTRIM(LTRIM(CAST(STRING (PRODUTO_FORNECEDOR.IDSUBPRODUTO) AS CHAR(40)))) AS ID_SUBPRODUTOE,
    COALESCE(PRODUTO.DESCRCOMPRODUTO, '') || ' ' || COALESCE(PRODUTO_GRADE.SUBDESCRICAO, '') AS DESCRI,
    PRODUTO_FORNECEDOR.IDCLIFOR,
    PRODUTO_FORNECEDOR.IDPRODUTO,
    PRODUTO_FORNECEDOR.IDSUBPRODUTO,
    PRODUTO_FORNECEDOR.PERFRETE,
    PRODUTO_FORNECEDOR.PERADICIONAL,
    PRODUTO_FORNECEDOR.PERACESSORIOS AS PERACESSORIOS,
    PRODUTO_FORNECEDOR.PERBONIFICACAO,
    PRODUTO_FORNECEDOR.PERIPI,
    COALESCE(
        CASE
            WHEN PRODUTO_FORNECEDOR.FLAGIPIDIGITADO = 'T' OR
                PRODUTO_FORNECEDOR.FLAGVALORIPIDIGITADO = 'T' THEN PRODUTO_FORNECEDOR.PERIPI
            ELSE CASE
                WHEN PRODUTO.FLAGTRIBUTACAOGRUPO = 'T' THEN GRUPO.PERIPI
                ELSE PRODUTO.PERIPI
            END
        END,
        0
    ) AS PERIPI_FORN_GRUPO,
    PRODUTO_FORNECEDOR.PERICMSENTRADA,
    PRODUTO_FORNECEDOR.PERDESCONTO1,
    PRODUTO_FORNECEDOR.PERDESCONTO2,
    PRODUTO_FORNECEDOR.ORDEMLISTAGEM,
    PRODUTO_FORNECEDOR.PERDESCONTO3,
    PRODUTO_FORNECEDOR.PERDESCONTO4,
    PRODUTO_FORNECEDOR.VALLISTAFORNECEDOR,
    PRODUTO_FORNECEDOR.VALLISTAANTERIOR,
    PRODUTO_FORNECEDOR.DTALTERACAO,
    PRODUTO_FORNECEDOR.FLAGPRECOVENDAATUALIZADO,
    PRODUTO_GRADE.IDCODBARPROD,
    PRODUTO.IDSECAO,
    PRODUTO.IDGRUPO,
    PRODUTO.IDSUBGRUPO,
    PRODUTO.VALGRAMAENTRADA AS PROD_VALGRAMAENTRADA,
    PRODUTO.EMBALAGEMENTRADA AS PROD_EMBALAGEMENTRADA,
    PRODUTO.TIPOBAIXAMESTRE,
    PRODUTO.FABRICANTE,
    PRODUTO.MODELO,
    CAST(
        PRODUTO.VALGRAMAENTRADA * PRODUTO_FORNECEDOR.VALLISTAFORNECEDOR AS DECIMAL(15, 6)
    ) AS VALOREMBALAGEM,
    PRODUTO_FORNECEDOR.VALPEDIDOMINIMO,
    PRODUTO_FORNECEDOR.QTDPEDIDOMINIMO,
    CAST(0 AS DECIMAL(15, 6)) AS PERREDTRIBENT,
    CAST(0 AS DECIMAL(15, 6)) AS PERREDTRIBSAI,
    CAST(
        (
            SELECT
                CLIENTE_FORNECEDOR.PERDESCONTOGERAL
            FROM
                CLIENTE_FORNECEDOR
            WHERE
                CLIENTE_FORNECEDOR.IDCLIFOR = PRODUTO_FORNECEDOR.IDCLIFOR
        ) AS DECIMAL(15, 2)
    ) AS PERDESCONTOGERAL,
    POLITICA_PRECO_PRODUTO.VALCUSTOREPOS,
    POLITICA_PRECO_PRODUTO.CUSTONOTAFISCAL,
    POLITICA_PRECO_PRODUTO.VALPRECOVAREJO,
    CASE
        WHEN PROMO.VALPRECO = POLITICA_PRECO_PRODUTO.VALPRECOVAREJO THEN POLITICA_PRECO_PRODUTO.VALPROMVAREJO
        ELSE COALESCE(PROMO.VALPRECO, POLITICA_PRECO_PRODUTO.VALPROMVAREJO)
    END AS VALPROMVAREJO,
    POLITICA_PRECO_PRODUTO.VALPRECOATACADO,
    PRODUTO_GRADE.FLAGPRECOVIGIADO,
    LTRIM(RTRIM(PRODUTO_FORNECEDOR.CODIGOINTERNOFORN)) AS CODIGOINTERNOFORN,
    PRODUTO_FORNECEDOR.PERIPIFRETE,
    PRODUTO_FORNECEDOR.DTALTERACAOCENTRALCOMPRAS,
    POLITICA_PRECO_PRODUTO.PERMARGEMVAREJO,
    POLITICA_PRECO_PRODUTO.PERMARGEMATACADO,
    PRODUTO_FORNECEDOR.PERIPIADICIONAL,
    PRODUTO_FORNECEDOR.PERIPIACESSORIOS AS PERIPIACESSORIOS,
    PRODUTO_FORNECEDOR.VALICMSST,
    PRODUTO_FORNECEDOR.FLAGCALCULAST,
    PRODUTO_FORNECEDOR.VALDESCONTOICMS,
    CAST(0 AS DECIMAL(15, 6)) AS VALORLIQUIDO_MOSTRA,
    CAST(0 AS DECIMAL(15, 6)) AS VALORLIQUIDOEMB_MOSTRA,
    CAST(0 AS DECIMAL(12, 6)) AS VALFRETEDIGITADO,
    PRODUTO_FORNECEDOR.VALIPI,
    CAST(PRODUTO_FORNECEDOR.VALIPI AS DECIMAL(15, 6)) AS VALIPIDIGITADO,
    PRODUTO_FORNECEDOR.FLAGVALORIPIDIGITADO,
    PRODUTO_FORNECEDOR.FLAGIPIDIGITADO,
    PRODUTO_FORNECEDOR.FLAGVALORFRETEDIGITADO,
    CAST('T' AS CHAR(1)) AS FLAGRECALCULAIPI,
    CAST(PRODUTO_FORNECEDOR.PERINFLACAO AS DECIMAL(15, 2)) AS PERINFLACAO,
    CAST(0 AS DECIMAL(12, 6)) AS VALORMENOSDESCMAISADIC_S,
    CAST(0 AS DECIMAL(15, 6)) AS VALORICMSENTRADA_S,
    CAST(0 AS DECIMAL(15, 6)) AS VALORIPIFRETE_S,
    CAST(0 AS DECIMAL(15, 6)) AS VALORADICIONAL_S,
    CAST(0 AS DECIMAL(15, 6)) AS VALORIPIADICIONAL_S,
    CAST(0 AS DECIMAL(15, 6)) AS VALORACESSORIOS_S,
    CAST(0 AS DECIMAL(15, 6)) AS VALORIPIACESSORIOS_S,
    CAST('F' AS CHAR(1)) AS FLAGDIGITOUVALOR,
    CAST('imagens\PNG\Pesquisar_barra.png' AS CHAR(32)) AS BTN,
    PRODUTO_COMPRAS.TIPOGIRO,
    COALESCE(PRODUTO_COMPRAS.IDEMPRESA, 0) AS PRODUTO_COMPRAS_IDEMPRESA,
    CAST(0 AS DECIMAL(12, 6)) AS VALORLIQANTERIOR,
    PRODUTO_GRADE.IDCADEIAPRECO,
    CAST('' AS CHAR(1)) AS FLAGDEL,
    PRODUTO_FORNECEDOR.VALDESCONTOPISCOFINS,
    CAST('F' AS CHAR(1)) AS FLAGDIGITOUCODINTFORN,
    CAST(0 AS INTEGER) AS IDCOMPRADOR,
    CAST('A' AS CHAR(1)) AS TIPOSITTRIB,
    CAST('' AS CHAR(1)) AS FLAGCONSIDERASUBSTFRONTPEDIDO,
    PRODUTO_GRADE.FLAGCADEIACUSTO,
    CAST('F' AS CHAR(1)) AS ALTEROUCUSTOREPOS,
    CASE
        WHEN PP.QTDPEDIDOPENDENTE > 0 THEN 'T'
        ELSE 'F'
    END AS FLAGPEDIDOSPENDENTES,
    PP.QTDPEDIDOPENDENTE,
    CAST(0 AS DECIMAL(15, 2)) AS PERCUSTOADICIONAL,
    CAST('V' AS CHAR(1)) AS TIPORATEIOFRETE,
    PRODUTO.QTDETQGONDOLA,
    PRODUTO.FLAGETIQUETAPROD,
    PRODUTO_FORNECEDOR.FLAGBLOQUEADOCOMPRA,
    PRODUTO_GRADE.REFERENCIA,
    CAST(NULL AS DATE) AS DTENTREGA,
    PRODUTO_FORNECEDOR.VALBONIFICACAO AS VALBONIFICACAO,
    PRODUTO_FORNECEDOR.MULTIPLOBONIFICACAO AS MULTIPLOBONIFICACAO,
    PRODUTO_FORNECEDOR.TIPOPAGAMENTOBONIFICACAO AS TIPOPAGAMENTOBONIFICACAO,
    PRODUTO_FORNECEDOR.FLAGBONIFICAASSOCIADO AS FLAGBONIFICAASSOCIADO,
    CAST(PRODUTO_GRADE.PESOBRUTO AS DECIMAL(15, 4)) AS PESOBRUTO,
    CAST(0 AS DECIMAL(15, 6)) AS VALICMSGARANTIDOINTEGRAL,
    CAST(0 AS DECIMAL(15, 6)) AS PERICMSGARANTIDOINTEGRAL,
    CAST('F' AS CHAR(1)) AS FLAGALTEROUDESCONTOALC,
    COALESCE(PRODUTO_GRADE.IDLINHAMIXENTRADA, 0) AS IDLINHAMIXENTRADA,
    PRODUTO_FORNECEDOR.PERCOMISSAOVENDEDOR,
    PRODUTO_FORNECEDOR.PERCOMISSAOINDICADOR,
    PRODUTO_FORNECEDOR.PERCOMISSAOGERENTE,
    PRODUTO_FORNECEDOR.PERCOMISSAOLOJA,
    COALESCE(SUG.MARGEMVAREJOPRATICADA, 0) AS MARGEMVAREJOPRATICADA,
    COALESCE(SUG.QTDATUALESTOQUE, 0) AS QTDATUALESTOQUE,
    COALESCE(SUG.QTDULTIMACOMPRA, 0) AS QTDULTIMACOMPRA,
    COALESCE(DIF_DIAS (SUG.DTULTIMAVENDA, CURRENT DATE), 0) AS DIASSEMVENDA,
    COALESCE(SUG.DIASESTOQUE, 0) AS DIASESTOQUE,
    COALESCE(PRODUTO_COMPRAS.QTDESTMINIMO, 0) AS QTDESTMINIMO,
    COALESCE(PRODUTO_COMPRAS.QTDESTMAXIMO, 0) AS QTDESTMAXIMO,
    COALESCE(PRODUTO_COMPRAS.TIPOGIRO, 'B') AS TIPOGIRO,
    PRODUTO_GRADE_REDEDIA.FLAGPRODUTOTABLOIDE,
    PRODUTO_GRADE_REDEDIA.FLAGPRODUTOARMAZEMCENTRAL,
    CASE
        WHEN PRODUTO.IDSECAO = 19 THEN 'T'
        WHEN PRODUTO.IDGRUPO = 81 THEN 'T'
        WHEN PRODUTO.IDGRUPO = 185 THEN 'T'
        ELSE 'F'
    END AS FLAGPRODUTOFLUXOTENSO,
    PRODUTO_GRADE.NCM,
    CAST(0 AS DECIMAL(15, 2)) AS PERICMSENTRADACADASTRO,
    PRODUTO_FORNECEDOR.PERICMSENTRADA AS PERICMSENTRADAFORN,
    (
        SELECT
            COALESCE(PRODUTO_EMBALAGEM_CONVERSAO.GRAMATURACONVERTIDA, 0)
        FROM
            PRODUTO_EMBALAGEM_CONVERSAO
        WHERE
            PRODUTO_EMBALAGEM_CONVERSAO.IDPRODUTO = PRODUTO.IDPRODUTO AND
            PRODUTO_EMBALAGEM_CONVERSAO.EMBALAGEM = PRODUTO.EMBALAGEMENTRADA AND
            PRODUTO_EMBALAGEM_CONVERSAO.EMBALAGEMCONVERTIDA = 'BU'
    ) AS BULTOSDACOMBI,
    SUBGRUPO.IDSUBGRUPO AS IDSUBGRUPO,
    SUBGRUPO.DESCRSUBGRUPO AS DESCRSUBGRUPO,
    CAST('' AS CHAR(10)) AS EMPRESASBOLETIM,
    PRODUTO_GRADE.IDCODBARPROD,
    PRODUTO_FORNECEDOR.IDUSUARIO,
    PRODUTO_FORNECEDOR.IDOPERACAO,
    PRODUTO_FORNECEDOR.OBSOPERACAO,
    USUARIO.NOMEUSUARIO,
    CAST('F' AS CHAR(1)) AS FlagCalculaSTFornecedor,
    (
        SELECT
            CLIENTE_FORNECEDOR.FlagCalcSubStEntradaUF
        FROM
            CLIENTE_FORNECEDOR
        WHERE
            CLIENTE_FORNECEDOR.IDCLIFOR = PRODUTO_FORNECEDOR.IDCLIFOR
    ) AS FlagCalcSubStEntradaUF,
    CENARIO_FISCAL.IDTIPOOPERACAO AS IDTIPOOPERACAO,
    CAST(CENARIO_FISCAL.IDTIPOOPERACAO AS CHAR(40)) AS IDTIPOOPERACAOE,
    CAST('Imagens\PNG\Pesquisar_barra.png' AS CHAR(32)) AS B_IDTIPOOPERACAOE,
    TIPO_OPERACAO.DESCRTIPOOPERACAO AS DESCRTIPOOPERACAO,
    CENARIO_FISCAL.IDTIPOATIVIDADEORIGEM AS IDTIPOATIVIDADE,
    CENARIO_FISCAL.IDORIGEMPRODUTO AS IDORIGEMPRODUTO,
    PRODUTO_FORNECEDOR.IDCENARIOFISCAL AS IDCENARIOFISCAL,
    CAST('' AS CHAR(3)) AS HIERARQUIATIPOOPERACAO,
    PRODUTO_FORNECEDOR.EMBALAGEMENTRADA,
    PRODUTO_FORNECEDOR.VALGRAMAENTRADA,
    CAST(0 AS INTEGER) AS NUMSEQ,
    PRODUTO_FORNECEDOR.FLAGFORNECEDORPADRAO,
    PRODUTO_GRADE.FLAGPRODSOBENCOMENDA,
    COALESCE(
        (
            SELECT
                DESCRICAO
            FROM
                MARCA
            WHERE
                PRODUTO.IDMARCAFABRICANTE = MARCA.IDMARCAFABRICANTE
        ),
        ''
    ) AS DESCRICAOMARCA,
    COALESCE(PRODUTO_GRADE.MULTIPLICADORPRODUCAO, 0) AS FATORTRANSFERENCIA,
    CASE
        WHEN PRODUTO_GRADE.MULTIPLICADORPRODUCAO > 0 THEN CAST(
            ((PRODUTO_FORNECEDOR.VALLISTAFORNECEDOR / PRODUTO_GRADE.MULTIPLICADORPRODUCAO)) AS DECIMAL(15, 6)
        )
        ELSE CAST(0 AS INTEGER)
    END AS VALUNITARIOTRANSFERENCIA,
    CAST(0 AS INTEGER) AS RGB,
    CAST(0 AS DECIMAL(12, 6)) AS VALORDESCONTO1,
    PRODUTO_FORNECEDOR.QTDTOLERANCIA,
    PRODUTO_FORNECEDOR.QTDTOLERANCIAMIN,
    CAST('Imagens\PNG\Edit.png' AS CHAR(30)) AS BOTAOOBS,
    CAST('' AS VARCHAR(1000)) AS OBSERVACAOENCOMENDA,
    CAST('' AS CHAR(1)) AS FLAGINCLUIR,
    CENARIO_FISCAL.IDREGIMEESPECIALORIGEM,
    CAST('F' AS CHAR(1)) AS FLAGSELECIONAR,
    CASE
        WHEN COALESCE(PRODUTO_GRADE_COMPLEMENTAR.QTDCAMADASPALLET, 0) > 0 AND
            COALESCE(PRODUTO_GRADE_COMPLEMENTAR.QTDLASTROPALLET, 0) > 0 THEN (
            COALESCE(PRODUTO_GRADE.QTDCAPACIDADEPALLET, 0) * COALESCE(PRODUTO.VALGRAMAENTRADA, 0)
        )
        ELSE PRODUTO_GRADE.QTDCAPACIDADEPALLET
    END AS QTDCAPACIDADEPALLET,
    CAST(0 AS DECIMAL(15, 6)) AS QTDPALLET,
    CAST(
        (
            COALESCE(PRODUTO_FORNECEDOR.VALLISTAFORNECEDOR, 0) + COALESCE(PRODUTO_FORNECEDOR.VALICMSST, 0) + COALESCE(PRODUTO_FORNECEDOR.VALIPI, 0)
        ) AS DECIMAL(15, 6)
    ) VALORUNITSUBSTIPI,
    CAST(0 AS DECIMAL(12, 6)) PERICMSSUBST,
    CAST(0 AS DECIMAL(12, 6)) PERMARGEMSUBST,
    CAST(0 AS DECIMAL(12, 6)) PERREDSUBST,
    CAST(
        (
            CASE
                WHEN (COALESCE(PRODUTO_FORNECEDOR.VALGRAMAENTRADA, 0) > 0) THEN (
                    COALESCE(PRODUTO_FORNECEDOR.VALLISTAFORNECEDOR, 0) + COALESCE(PRODUTO_FORNECEDOR.VALICMSST, 0) + COALESCE(PRODUTO_FORNECEDOR.VALIPI, 0)
                ) * PRODUTO_FORNECEDOR.VALGRAMAENTRADA
                ELSE (
                    COALESCE(PRODUTO_FORNECEDOR.VALLISTAFORNECEDOR, 0) + COALESCE(PRODUTO_FORNECEDOR.VALICMSST, 0) + COALESCE(PRODUTO_FORNECEDOR.VALIPI, 0)
                ) * PRODUTO.VALGRAMAENTRADA
            END
        ) AS DECIMAL(15, 6)
    ) AS VALOREMBALAGEMSUBSTIPI,
    CAST(0 AS DECIMAL(12, 6)) VALORTOTAL,
    PRODUTO_FORNECEDOR.FLAGCONSIDERADESCPISCOFINSBCST,
    CAST(0 AS DECIMAL(15, 6)) AS VALINDICESUBST,
    CAST(0 AS DECIMAL(15, 6)) AS VALPERSUBST,
    PRODUTO_FORNECEDOR.QTDMULTIPLOCOMPRA,
    COALESCE(PRODUTO_GRADE.PERISS, 0) AS PERISS,
    PRODUTO_GRADE.FLAGPRODUTOACABADO,
    PRODUTO_GRADE.FLAGCESTABASICA,
    PRODUTO_GRADE.FLAGCOMBUSTIVEL,
    COALESCE(CFT.FLAGBASELIQUIDAIPI, 'F') AS FLAGBASELIQUIDAIPI,
    PRODUTO_FORNECEDOR.PerCreditoPresumidoICMSST,
    COALESCE(
        CAST(
            (
                SELECT
                    CLIENTE_FORNECEDOR.TIPODOCUMENTOFRETE
                FROM
                    CLIENTE_FORNECEDOR
                WHERE
                    CLIENTE_FORNECEDOR.IDCLIFOR = PRODUTO_FORNECEDOR.IDCLIFOR
            ) AS CHAR(1)
        ),
        'N'
    ) AS FLAGTIPOFRETE,
    PRODUTO_FORNECEDOR.FLAGIMPORTAXMLUNIDADETRIB,
    CAST(0 AS DECIMAL(15, 6)) AS NOVOPRECO,
    CAST('F' AS CHAR(1)) AS FlagProcessado,
    POLITICA_PRECO_PRODUTO.VALPRECOVAREJO AS VALVAREJOATUAL,
    CAST(0 AS DECIMAL(15, 6)) AS permargemabaixode,
    CAST(0 AS INTEGER) AS rgbmargemabaixode,
    CAST(0 AS DECIMAL(15, 6)) AS permargemacimade,
    CAST(0 AS INTEGER) AS rgbmargemacimade,
    CAST(0 AS DECIMAL(15, 6)) AS permargemde,
    CAST(0 AS DECIMAL(15, 6)) AS permargemate,
    CAST(0 AS INTEGER) AS rgbmargemde,
    CAST(0 AS DECIMAL(15, 6)) AS permargemabaixode2,
    CAST(0 AS INTEGER) AS rgbmargemabaixode2,
    CAST(0 AS DECIMAL(15, 6)) AS permargemacimade2,
    CAST(0 AS INTEGER) AS rgbmargemacimade2,
    CAST(0 AS DECIMAL(15, 6)) AS permargemde2,
    CAST(0 AS DECIMAL(15, 6)) AS permargemate2,
    CAST(0 AS INTEGER) AS rgbmargemde2,
    CAST(0 AS INTEGER) AS ordenacaoprodutos,
    CAST(0 AS DECIMAL(15, 6)) AS VALIPIPEDIDO,
    CAST(0 AS DECIMAL(12, 3)) AS QTDSOLICITACAO,
    PRODUTO_FORNECEDOR.VALUNITPROMOCAO,
    PRODUTO_FORNECEDOR.DTINIPROMOCAO,
    PRODUTO_FORNECEDOR.DTFIMPROMOCAO,
    PRODUTO_FORNECEDOR.VALCUSTOREPOSANTERIOR,
    PRODUTO_FORNECEDOR.FLAGPROCESSADOPROMOCAO,
    CAST(COALESCE(PRODUTO_FORNECEDOR.VALUNITPROMOCAO, 0) AS DECIMAL(15, 6)) AS VALUNITPROMOCAOATUAL,
    CAST(PRODUTO_FORNECEDOR.VALLISTAFORNECEDOR AS DECIMAL(15, 6)) AS VALUNITATUAL,
    POLITICA_PRECO_PRODUTO.DTINIPROMOCAOVAR,
    POLITICA_PRECO_PRODUTO.DTFIMPROMOCAOVAR,
    PRODUTO_FORNECEDOR.VALCUSTOREPOSPROMOCIONAL,
    PRODUTO_FORNECEDOR.VALCUSTOREPOSNOVO,
    CAST('F' AS CHAR(1)) AS FLAGALTERAPRECO,
    CAST('F' AS CHAR(1)) AS FLAGALTERACUSTO,
    PRODUTO_FORNECEDOR.DTALTERACAOPRECO AS DTALTERACAOPRECO,
    PRODUTO_FORNECEDOR.DTALTERACAOCUSTO AS DTALTERACAOCUSTO,
    CAST('imagens\PNG\Calendario.png' AS CHAR(30)) AS B_DTINIPROMOCAO,
    CAST('imagens\PNG\Calendario.png' AS CHAR(30)) AS B_DTFIMPROMOCAO,
    CAST(0 AS DECIMAL(15, 6)) AS VALORBONIFICACAO,
    PRODUTO.IDDIVISAO,
    CAST(0 AS DECIMAL(15, 6)) AS VALORUNITBONIFICACAO,
    PRODUTO_GRADE.FLAGINATIVOCOMPRA,
    CAST('F' AS CHAR(1)) AS FLAGDIGITACAORAPIDA,
    PRODUTO_FORNECEDOR.VALUNITATACADO,
    CAST('F' AS CHAR(1)) AS FLAGVALORATACADO,
    (
        SELECT
            COALESCE(RGBPRECOATACADO, 0)
        FROM
            CONFIG_COMPRAS
    ) AS RGBPRECOATACADO,
    CAST('imagens\PNG\Calculadora.png' AS CHAR(30)) AS B_CALCGRAMATURA,
    PRODUTO_FORNECEDOR.EMBALAGEMENTRADAXML,
    PRODUTO_FORNECEDOR.EMBALAGEMTRANSPORTE,
    PRODUTO_FORNECEDOR.MEDIDACONVERSAO,
    PRODUTO_FORNECEDOR.PERDESCONTOATACADO,
    CAST(0 AS DECIMAL(15, 6)) AS QTDAGUARDANDO,
    PRODUTO_FORNECEDOR.FLAGEMBALAGEMFRACIONADA,
    PRODUTO_FORNECEDOR.IDMODALIDADE AS IDMODALIDADE,
    ICMSST_MVA,
    ICMS_FCEP,
    ICMSST_ALIQUOTA,
    CASE
        WHEN COALESCE(POLITICA_PRECO_PRODUTO.PERDESPOPER, 0) = 0 THEN COALESCE(
            (
                SELECT
                    PERDESPOPER
                FROM
                    EMPRESA
                WHERE
                    IDEMPRESA = 1
            ),
            0
        )
        ELSE POLITICA_PRECO_PRODUTO.PERDESPOPER
    END AS PERDESPOPER,
    CAST('1900-01-01' AS DATE) AS DTULTIMACOMPRA,
    PRODUTO_GRADE.FLAGNEGOCIACAO,
    CAST('F' AS CHAR(1)) AS FLAGNEGOCIACAOBONIFICA,
    (
        SELECT
            CASE
                WHEN MCF.GRAMATURAXML IS NULL OR
                    MCF.QTDENTRARESTOQUE IS NULL THEN ''
                ELSE TRIM(CAST(MCF.QTDENTRARESTOQUE AS VARCHAR(20))) || '/' || TRIM(CAST(MCF.GRAMATURAXML AS VARCHAR(20)))
            END AS CALC
        FROM
            MEDIDA_CONVERSAO_FORNECEDOR MCF
        WHERE
            PRODUTO_FORNECEDOR.IDCLIFOR = MCF.IDCLIFOR AND
            PRODUTO_FORNECEDOR.IDPRODUTO = MCF.IDPRODUTO AND
            PRODUTO_FORNECEDOR.IDSUBPRODUTO = MCF.IDSUBPRODUTO
    ) AS CALCULOMEDIDACONVERSAO,
    CAST('F' AS CHAR(1)) AS FLAGEXCLUIR,
    CAST(0 AS DECIMAL(15, 2)) AS PERFDE,
    CAST(0 AS INTEGER) AS IDSITTRIBENTRADA,
    CAST(0 AS INTEGER) AS IDSITTRIBSAIDA,
    CAST(0 AS DECIMAL(15, 6)) AS QTDPEDIDOPENDENTEUNIDADE,
    CAST('T' AS CHAR(1)) AS FLAGEXISTERELACIONAMENTO,
    CAST('Imagens\PNG\Barcode.png' AS CHAR(32)) AS B_CODBAR,
    CAST(PRODUTO_GRADE.IDCODBARPROD AS VARCHAR(30)) AS IDCODBAR_STRING,
    CAST('Validades' AS CHAR(10)) AS b_validades,
    CAST('F' AS CHAR(1)) AS FLAGIMPORTADO,
    CAST(0 AS DECIMAL(15, 6)) AS QTDSALDOEMPENHO,
    CAST(0 AS DECIMAL(15, 2)) AS PERADDCUSTO,
    CAST(PRODUTO_GRADE_COMPLEMENTAR.PERADDCUSTO AS DECIMAL(15, 2)) AS PERADDCUSTOORIGINAL,
    CAST(PRODUTO_GRADE_COMPLEMENTAR.PERLIMITEADDCUSTO AS DECIMAL(15, 2)) AS PERLIMITEADDCUSTO,
    CAST(0 AS INTEGER) AS IDCOTACAO,
    CAST('Visualizar' AS CHAR(30)) AS BTNANALISEPROD,
    PRODUTO_FORNECEDOR.TIPOTROCAPRODUTO,
    PRODUTO_FORNECEDOR.DIASENTREGAPROD AS DIASENTREGA,
    (
        SELECT
            DESCRPERFIL
        FROM
            PRODUTO_PERFIL
        WHERE
            PRODUTO_PERFIL.IDPERFIL = PRODUTO_GRADE.IDPERFIL
    ) DESCRPERFIL,
    PRODUTO_FORNECEDOR.IDPOLITICAFRETE,
    COALESCE(
        TRIM(
            (
                SELECT
                    DESCRICAOPOLITICA
                FROM
                    POLITICA_FRETE
                WHERE
                    IDPOLITICA = PRODUTO_FORNECEDOR.IDPOLITICAFRETE
            )
        ),
        ''
    ) AS DESCRICAOPOLITICAFRETE,
    CAST('imagens\PNG\Pesquisar_barra.png' AS CHAR(32)) AS B_POLITICAFRETE,
    CAST(0 AS DECIMAL(15, 6)) AS VALPOLITICAFRETE,
    CAST('Configurar' AS CHAR(10)) AS btn_configoutroscustos,
    CAST(0 AS DECIMAL(15, 6)) AS VALOUTROSCUSTOS,
    CAST(0 AS DECIMAL(15, 6)) AS PEROUTROSCUSTOS,
    PRODUTO_GRADE.DTCADASTRO,
    COALESCE(PROMO.IDPROMOCAO, 0) AS IDPROMOCAO,
    COALESCE(PRODUTO.MODELO, '') AS MODELO,
    CAST('Visualizar' AS CHAR(30)) AS BOTAOSIMILARES,
    CASE
        WHEN (
            EXISTS (
                SELECT
                    1
                FROM
                    PRODUTO_SIMILARES AS PS
                WHERE
                    PS.IDPRODUTO = PRODUTO_GRADE.IDPRODUTO AND
                    PS.IDSUBPRODUTO = PRODUTO_GRADE.IDSUBPRODUTO
            )
        ) THEN 'T'
        ELSE 'F'
    END AS FLAGSIMILARES,
    CAST(0 AS INTEGER) AS IDREPRESENTANTE,
    CAST('F' AS CHAR(1)) AS FLAGCOPIAR,
    PRODUTO_FORNECEDOR.VALUNITANTERIORPROD,
    PRODUTO_FORNECEDOR.VALUNITLIQANTERIORPROD,
    PRODUTO_FORNECEDOR.VALUNITLIQATUALPROD,
    PRODUTO_FORNECEDOR.TIPOMEDIDATOLERANCIA,
    (
        PRODUTO_FORNECEDOR.VALLISTAFORNECEDOR + PRODUTO_FORNECEDOR.VALIPI + PRODUTO_FORNECEDOR.VALICMSST
    ) AS VALUNITSUBST,
    PRODUTO_FORNECEDOR.DIASENTREGAPROD
FROM
    PRODUTO
JOIN
    SUBGRUPO ON
        SUBGRUPO.IDSUBGRUPO = PRODUTO.IDSUBGRUPO
JOIN
    GRUPO ON
        GRUPO.IDGRUPO = PRODUTO.IDGRUPO
JOIN
    PRODUTO_GRADE ON
        PRODUTO.IDPRODUTO = PRODUTO_GRADE.IDPRODUTO AND
        PRODUTO_GRADE.FLAGINATIVO <> 'T'
LEFT JOIN
    PRODUTO_GRADE_COMPLEMENTAR ON
        PRODUTO_GRADE_COMPLEMENTAR.IDPRODUTO = PRODUTO_GRADE.IDPRODUTO AND
        PRODUTO_GRADE_COMPLEMENTAR.IDSUBPRODUTO = PRODUTO_GRADE.IDSUBPRODUTO
JOIN
    POLITICA_PRECO_PRODUTO ON
        PRODUTO_GRADE.IDPRODUTO = POLITICA_PRECO_PRODUTO.IDPRODUTO AND
        PRODUTO_GRADE.IDSUBPRODUTO = POLITICA_PRECO_PRODUTO.IDSUBPRODUTO
JOIN
    PRODUTO_FORNECEDOR ON
        PRODUTO_FORNECEDOR.IDPRODUTO = POLITICA_PRECO_PRODUTO.IDPRODUTO AND
        PRODUTO_FORNECEDOR.IDSUBPRODUTO = POLITICA_PRECO_PRODUTO.IDSUBPRODUTO
LEFT JOIN TABLE (
    DBA.UF_PROMOCAO_GESTAO (
        POLITICA_PRECO_PRODUTO.IDEMPRESA,
        0,
        POLITICA_PRECO_PRODUTO.IDPRODUTO,
        POLITICA_PRECO_PRODUTO.IDSUBPRODUTO,
        'V',
        CURRENT TIMESTAMP,
        CASE
            WHEN POLITICA_PRECO_PRODUTO.QTDMINPROMVAREJO > 1 THEN POLITICA_PRECO_PRODUTO.QTDMINPROMVAREJO
            ELSE CAST(999999 AS DECIMAL(12, 3))
        END
    )
) AS PROMO ON
    PROMO.VALPRECO > 0
LEFT JOIN
    CLIENTE_FORNECEDOR_TRIBUTACAO CFT ON
        CFT.IDCLIFOR = PRODUTO_FORNECEDOR.IDCLIFOR
LEFT JOIN
    USUARIO ON
        PRODUTO_FORNECEDOR.IDUSUARIO = USUARIO.IDUSUARIO
LEFT OUTER JOIN
    PRODUTO_COMPRAS ON
        PRODUTO_FORNECEDOR.IDPRODUTO = PRODUTO_COMPRAS.IDPRODUTO AND
        PRODUTO_FORNECEDOR.IDSUBPRODUTO = PRODUTO_COMPRAS.IDSUBPRODUTO AND
        (
            1 = 0 OR
            PRODUTO_COMPRAS.IDEMPRESA = 1
        )
LEFT JOIN
    DBA.ANALISE_COMPRA_DADOS_SUGESTAO_ATUAL SUG ON
        SUG.IDEMPRESA = POLITICA_PRECO_PRODUTO.IDEMPRESA AND
        SUG.IDPRODUTO = POLITICA_PRECO_PRODUTO.IDPRODUTO AND
        SUG.IDSUBPRODUTO = POLITICA_PRECO_PRODUTO.IDSUBPRODUTO
LEFT JOIN LATERAL (
    SELECT
        PEDIDO_COMPRA_PROD.IDEMPRESA,
        PEDIDO_COMPRA_PROD.IDPRODUTO,
        PEDIDO_COMPRA_PROD.IDSUBPRODUTO,
        SUM(COALESCE(PEDIDO_COMPRA_PROD.QTDSOLICITADA - PEDIDO_COMPRA_PROD.QTDATENDIDA, 0)) AS QTDPEDIDOPENDENTE
    FROM
        PEDIDO_COMPRA_PROD
    JOIN
        PEDIDO_COMPRA ON
            PEDIDO_COMPRA_PROD.IDEMPRESA = PEDIDO_COMPRA.IDEMPRESA AND
            PEDIDO_COMPRA_PROD.IDCLIFOR = PEDIDO_COMPRA.IDCLIFOR AND
            PEDIDO_COMPRA_PROD.IDPEDIDO = PEDIDO_COMPRA.IDPEDIDO
    WHERE
        POLITICA_PRECO_PRODUTO.IDEMPRESA = PEDIDO_COMPRA_PROD.IDEMPRESA AND
        POLITICA_PRECO_PRODUTO.IDPRODUTO = PEDIDO_COMPRA_PROD.IDPRODUTO AND
        POLITICA_PRECO_PRODUTO.IDSUBPRODUTO = PEDIDO_COMPRA_PROD.IDSUBPRODUTO AND
        PEDIDO_COMPRA_PROD.QTDSOLICITADA > PEDIDO_COMPRA_PROD.QTDATENDIDA AND
        UPPER(PEDIDO_COMPRA.FLAGCANCELADO) = 'F' AND
        UPPER(PEDIDO_COMPRA.FLAGPEDIDOBLOQUEADO) = 'F' AND
        (
            PEDIDO_COMPRA.TIPOCATEGORIA IS NULL OR
            UPPER(PEDIDO_COMPRA.TIPOCATEGORIA) = 'C'
        ) AND
        CURRENT DATE <= COALESCE(PEDIDO_COMPRA.DTVALIDADEPEDIDO, CURRENT DATE)
    GROUP BY
        PEDIDO_COMPRA_PROD.IDEMPRESA,
        PEDIDO_COMPRA_PROD.IDPRODUTO,
        PEDIDO_COMPRA_PROD.IDSUBPRODUTO
) AS PP ON
    1 = 1
JOIN
    PRODUTO_FORNECEDOR F2 ON
        POLITICA_PRECO_PRODUTO.IDPRODUTO = F2.IDPRODUTO AND
        POLITICA_PRECO_PRODUTO.IDSUBPRODUTO = F2.IDSUBPRODUTO AND
        F2.IDCLIFOR = 1006422
LEFT OUTER JOIN
    CENARIO_FISCAL ON
        PRODUTO_FORNECEDOR.IDCENARIOFISCAL = CENARIO_FISCAL.IDCENARIOFISCAL
LEFT OUTER JOIN
    TIPO_OPERACAO ON
        CENARIO_FISCAL.IDTIPOOPERACAO = TIPO_OPERACAO.IDTIPOOPERACAO
JOIN
    CONFIG_COMPRAS CC ON
        CC.IDCONFIGCOMPRAS = 1
LEFT JOIN LATERAL (
    SELECT
        CASE
            WHEN COALESCE(CAPATABLOIDE, 'F') = 'T' THEN 'T'
            WHEN COALESCE(TABLOIDE, 'F') = 'T' THEN 'T'
            ELSE 'F'
        END AS FLAGPRODUTOTABLOIDE,
        CASE
            WHEN COALESCE(ARMAZEM, 'FF') = 'AC' THEN 'T'
            ELSE 'F'
        END AS FLAGPRODUTOARMAZEMCENTRAL
    FROM
        PRODUTO_GRADE_REDEDIA
    WHERE
        PRODUTO_GRADE_REDEDIA.IDEMPRESA IN (1) AND
        PRODUTO_GRADE_REDEDIA.IDPRODUTO = PRODUTO_GRADE.IDPRODUTO AND
        PRODUTO_GRADE_REDEDIA.IDSUBPRODUTO = PRODUTO_GRADE.IDSUBPRODUTO
) AS PRODUTO_GRADE_REDEDIA ON
    1 = 1
WHERE
    (
        PRODUTO_GRADE.FLAGINATIVOCOMPRA <> 'T' OR
        CC.FLAGINATIVOCOMPRA = 'T'
    ) AND
    PRODUTO_FORNECEDOR.IDCLIFOR = 1006422 AND
    POLITICA_PRECO_PRODUTO.IDEMPRESA = 1 AND
    PRODUTO_GRADE.IDSUBPRODUTO NOT IN (
        162220,
        169956,
        170208,
        170282,
        170286,
        170310,
        228943,
        256407,
        256409,
        256411,
        256415,
        256417,
        258530,
        258532,
        260192,
        261953,
        263115,
        270628,
        284316,
        284318,
        284320,
        284851,
        284853,
        284855,
        285067,
        285986,
        285988,
        285990,
        286016,
        286258,
        286367,
        286442,
        297032,
        297034,
        298156,
        300393,
        300395,
        300397,
        303903,
        303905,
        303907,
        303909,
        303911,
        303915,
        303917,
        310662,
        310773,
        310971,
        317857,
        317859,
        317861,
        317863,
        319362,
        322028,
        322708,
        322710,
        322712,
        322714,
        322716,
        330400
    )
FOR READ ONLY
    ---------------------------
    OK
    ---------------------------
