CREATE OR REPLACE FUNCTION DBA.UF_VLRFINALFORNECEDOR_AGRUPAMENTO(
	IN_IDCLIFORPRINCIPAL INTEGER,
	IN_IDEMPRESA INTEGER,
	IN_IDPRODUTO INTEGER,
	IN_IDSUBPRODUTO INTEGER
)
RETURNS DECIMAL(15, 6)
LANGUAGE SQL
READS SQL DATA
NO EXTERNAL ACTION
BEGIN ATOMIC
	DECLARE LD_VLRFINALFORNECEDOR DECIMAL(15, 6);
	DECLARE LI_IDCLIFORPRECO INTEGER;

	SET LI_IDCLIFORPRECO = COALESCE((
		SELECT
			F.IDFORNECEDORCORRELACIONADO
		FROM
			TABLE(DBA.UF_GET_FORNECEDOR_CORRELACIONADO(
				IN_IDEMPRESA,
				IN_IDCLIFORPRINCIPAL
			)) F
		FETCH FIRST 1 ROW ONLY
	), IN_IDCLIFORPRINCIPAL);

	SET LD_VLRFINALFORNECEDOR = (
		SELECT
			PF.VLRFINALFORNECEDOR
		FROM
			DBA.PRODUTO_FORNECEDOR PF
		WHERE
			PF.IDCLIFOR = LI_IDCLIFORPRECO AND
			PF.IDPRODUTO = IN_IDPRODUTO AND
			PF.IDSUBPRODUTO = IN_IDSUBPRODUTO
	);

	RETURN LD_VLRFINALFORNECEDOR;
END
@
