-- Execute APOS a PREPARACAO de CONSULTAS_INDIVIDUAIS_01_A_16_POR_NOTA.sql,
-- na MESMA sessao DB2 e com o mesmo periodo.
--
-- QTDLINHAS_RESULTADO = linhas exibidas (fornecedor + tipo).
-- QTDNOTAS_DO_TIPO = soma correta de QTDNOTASTIPO.
-- Para ISENTO-40, compare o total das consultas 01, 03, 07 e 11 com o
-- TOTAL RESUMO de VALIDACAO_ISENTO_40_POR_NOTA_01_A_12.sql.

SELECT CONSULTA,
       TIPO,
       COUNT(*) AS QTDLINHAS_RESULTADO,
       SUM(QTDNOTASTIPO) AS QTDNOTAS_DO_TIPO,
       SUM(XML) AS QTDNOTAS_XML,
       SUM(CAD) AS QTDNOTAS_CAD
FROM SESSION.MAPEAMENTO_NOTA_TIPO
WHERE CONSULTA BETWEEN 1 AND 12
GROUP BY CONSULTA, TIPO
ORDER BY CONSULTA, TIPO;

-- Comparativo direto somente do ISENTO-40.
SELECT CASE CONSULTA
           WHEN 1 THEN 'CONSULTA 01'
           WHEN 3 THEN 'CONSULTA 03'
           WHEN 7 THEN 'CONSULTA 07'
           WHEN 11 THEN 'CONSULTA 11'
       END AS DESTINO,
       SUM(QTDNOTASTIPO) AS QTDNOTAS_ISENTO_40
FROM SESSION.MAPEAMENTO_NOTA_TIPO
WHERE CONSULTA IN (1, 3, 7, 11)
  AND TIPO = 'ISENTO-40'
GROUP BY CONSULTA
UNION ALL
SELECT 'TOTAL CONSULTAS 01+03+07+11',
       SUM(QTDNOTASTIPO)
FROM SESSION.MAPEAMENTO_NOTA_TIPO
WHERE CONSULTA IN (1, 3, 7, 11)
  AND TIPO = 'ISENTO-40';

-- Explica a diferenca para o resumo: estas consultas sao multítipo e, por
-- definicao, nao entram no resumo "apenas um tipo na nota toda".
SELECT CASE
           WHEN CONSULTA IN (1, 3, 7, 11) THEN 'MONOTIPO - COMPARA COM RESUMO'
           ELSE 'MULTITIPO - FORA DO RESUMO'
       END AS GRUPO,
       SUM(QTDNOTASTIPO) AS QTDNOTAS_ISENTO_40
FROM SESSION.MAPEAMENTO_NOTA_TIPO
WHERE CONSULTA BETWEEN 1 AND 12
  AND TIPO = 'ISENTO-40'
GROUP BY CASE
             WHEN CONSULTA IN (1, 3, 7, 11) THEN 'MONOTIPO - COMPARA COM RESUMO'
             ELSE 'MULTITIPO - FORA DO RESUMO'
         END;
