-- CONSULTAS INDIVIDUAIS: MAPEAMENTO DE TRIBUTACAO
-- Execute a secao PREPARACAO uma vez na mesma sessao DB2.
-- Depois execute qualquer uma das consultas 01 a 16 abaixo.
-- Parametros: :RA_DTINI e :RA_DTFIM

-- ===========================================================================
-- PREPARACAO (obrigatoria; nao retorna relatorio)
-- ===========================================================================
DECLARE GLOBAL TEMPORARY TABLE SESSION.MAPEAMENTO_FORNECEDOR (
    IDCLIFOR INTEGER,
    IDATIVIDADE INTEGER,
    ATIVIDADE VARCHAR(60),
    PRODUTOR CHAR(1),
    TIPO VARCHAR(20),
    SIMPLESNACIONAL CHAR(1),
    QTDNOTASTIPO BIGINT,
    XML BIGINT,
    CAD BIGINT,
    TEM_XML SMALLINT,
    TEM_CAD SMALLINT,
    QTDTIPOS BIGINT,
    TEM_40415090 SMALLINT,
    TEM_FORA_40415090 SMALLINT,
    TEM_00205160 SMALLINT,
    TEM_002051 SMALLINT,
    TEM_FORA_002051 SMALLINT
) ON COMMIT PRESERVE ROWS NOT LOGGED WITH REPLACE;

INSERT INTO SESSION.MAPEAMENTO_FORNECEDOR
WITH
NOTAS_MOVIMENTO AS (
    SELECT EA.IDEMPRESA, EA.IDPLANILHA, N.IDCLIFOR
    FROM DBA.ESTOQUE_ANALITICO EA
    INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
    INNER JOIN DBA.NOTAS N ON N.IDEMPRESA = EA.IDEMPRESA AND N.IDPLANILHA = EA.IDPLANILHA
    WHERE EA.IDOPERACAO < 1000
      AND OI.TIPOMOVIMENTO = 'C'
      AND OI.FLAGMOVSALDOPRO = 'T'
      AND N.FLAGMOVFISCAL = 'T'
      AND N.FLAGNOTACANCEL = 'F'
      AND EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
    GROUP BY EA.IDEMPRESA, EA.IDPLANILHA, N.IDCLIFOR
),
ITENS_TRIBUTACAO AS (
    SELECT NM.IDEMPRESA, NM.IDPLANILHA, NM.IDCLIFOR,
           CASE WHEN EAF.FLAGTRIBUTACAOXML = 'T' THEN 'XML' ELSE 'CAD' END AS FONTE,
           MOD(EA.IDSITTRIB, 100) AS CST,
           CASE
               WHEN MOD(EA.IDSITTRIB, 100) = 40 THEN 'ISENTO-40'
               WHEN MOD(EA.IDSITTRIB, 100) = 41 THEN 'NAOTRIBUTADO-41'
               WHEN MOD(EA.IDSITTRIB, 100) = 50 THEN 'SUSPENSO-50'
               WHEN MOD(EA.IDSITTRIB, 100) = 90 THEN 'OUTROS-90'
               WHEN MOD(EA.IDSITTRIB, 100) = 0 THEN 'TRIBUTADO-00'
               WHEN MOD(EA.IDSITTRIB, 100) = 20 THEN 'REDUCAO-20'
               WHEN MOD(EA.IDSITTRIB, 100) = 51 THEN 'DIFERIDO-51'
               WHEN EA.TIPOSITTRIB = 'F' AND MOD(EA.IDSITTRIB, 100) = 60 THEN 'STNORMAL-60'
               WHEN EA.TIPOSITTRIB = 'A' AND MOD(EA.IDSITTRIB, 100) = 60 THEN 'STFRONTEIRA-60'
               ELSE 'OUTRO'
           END AS TIPO_TRIBUTACAO
    FROM NOTAS_MOVIMENTO NM
    INNER JOIN DBA.ESTOQUE_ANALITICO EA ON EA.IDEMPRESA = NM.IDEMPRESA AND EA.IDPLANILHA = NM.IDPLANILHA
    INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
    LEFT JOIN DBA.ESTOQUE_ANALITICO_FISCAL EAF
        ON EAF.IDEMPRESA = EA.IDEMPRESA AND EAF.IDPLANILHA = EA.IDPLANILHA AND EAF.NUMSEQUENCIA = EA.NUMSEQUENCIA
    WHERE OI.FLAGMOVSALDOPRO = 'T'
      AND EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
),
NOTA_FONTE AS (
    SELECT IDEMPRESA, IDPLANILHA, IDCLIFOR,
           MAX(CASE WHEN FONTE = 'XML' THEN 1 ELSE 0 END) AS TEM_XML,
           MAX(CASE WHEN FONTE = 'CAD' THEN 1 ELSE 0 END) AS TEM_CAD
    FROM ITENS_TRIBUTACAO
    GROUP BY IDEMPRESA, IDPLANILHA, IDCLIFOR
),
NOTA_TIPO_FONTE AS (
    SELECT IDEMPRESA, IDPLANILHA, IDCLIFOR, TIPO_TRIBUTACAO,
           MAX(CASE WHEN FONTE = 'XML' THEN 1 ELSE 0 END) AS TEM_XML,
           MAX(CASE WHEN FONTE = 'CAD' THEN 1 ELSE 0 END) AS TEM_CAD
    FROM ITENS_TRIBUTACAO
    GROUP BY IDEMPRESA, IDPLANILHA, IDCLIFOR, TIPO_TRIBUTACAO
),
FORNECEDOR_NOTAS AS (
    SELECT IDCLIFOR, COUNT(*) AS QTDNOTASTIPO,
           SUM(TEM_XML) AS XML, SUM(TEM_CAD) AS CAD,
           MAX(TEM_XML) AS TEM_XML, MAX(TEM_CAD) AS TEM_CAD
    FROM NOTA_FONTE
    GROUP BY IDCLIFOR
),
FORNECEDOR_TIPO_NOTAS AS (
    SELECT IDCLIFOR, TIPO_TRIBUTACAO,
           COUNT(*) AS QTDNOTASTIPO,
           SUM(TEM_XML) AS XML,
           SUM(TEM_CAD) AS CAD
    FROM NOTA_TIPO_FONTE
    GROUP BY IDCLIFOR, TIPO_TRIBUTACAO
),
FORNECEDOR_TRIBUTACAO AS (
    SELECT IDCLIFOR, COUNT(DISTINCT TIPO_TRIBUTACAO) AS QTDTIPOS,
           MAX(CASE WHEN CST IN (40, 41, 50, 90) THEN 1 ELSE 0 END) AS TEM_40415090,
           MAX(CASE WHEN CST NOT IN (40, 41, 50, 90) THEN 1 ELSE 0 END) AS TEM_FORA_40415090,
           MAX(CASE WHEN CST IN (0, 20, 51, 60) THEN 1 ELSE 0 END) AS TEM_00205160,
           MAX(CASE WHEN CST IN (0, 20, 51) THEN 1 ELSE 0 END) AS TEM_002051,
           MAX(CASE WHEN CST NOT IN (0, 20, 51) THEN 1 ELSE 0 END) AS TEM_FORA_002051
    FROM ITENS_TRIBUTACAO
    GROUP BY IDCLIFOR
)
SELECT CF.IDCLIFOR, CF.IDATIVIDADE, TA.DESCRTIPOATIVIDADE,
       COALESCE(ATV.FLAGPRODUTORRURAL, 'F'),
       FTN.TIPO_TRIBUTACAO,
       CASE WHEN CF.TIPOREGIMETRIBFEDERAL = 'S' THEN 'S' ELSE 'N' END,
       FTN.QTDNOTASTIPO, FTN.XML, FTN.CAD, FN.TEM_XML, FN.TEM_CAD,
       FT.QTDTIPOS, FT.TEM_40415090, FT.TEM_FORA_40415090,
       FT.TEM_00205160, FT.TEM_002051, FT.TEM_FORA_002051
FROM FORNECEDOR_NOTAS FN
INNER JOIN FORNECEDOR_TRIBUTACAO FT ON FT.IDCLIFOR = FN.IDCLIFOR
INNER JOIN FORNECEDOR_TIPO_NOTAS FTN ON FTN.IDCLIFOR = FN.IDCLIFOR
INNER JOIN DBA.CLIENTE_FORNECEDOR CF ON CF.IDCLIFOR = FN.IDCLIFOR
LEFT JOIN DBA.ATIVIDADE ATV ON ATV.IDATIVIDADE = CF.IDATIVIDADE
LEFT JOIN DBA.ATIVIDADE_TIPO_ATIVIDADE ATA ON ATA.IDATIVIDADE = CF.IDATIVIDADE AND ATA.FLAGPADRAO = 'T'
LEFT JOIN DBA.TIPO_ATIVIDADE TA ON TA.IDTIPOATIVIDADE = ATA.IDTIPOATIVIDADE;

-- Colunas padrao de todas as consultas:
-- IDCLIFOR | IDATIVIDADE | ATIVIDADE | PRODUTOR | TIPO | QTDNOTASTIPO | XML | CAD | % XML | % CAD

-- ===========================================================================
-- CONSULTA 01: Produtor Rural / Cadastro / 1 tipo / CST 40,41,50,90
-- ===========================================================================
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR,
       TIPO,
       QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8) / NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0)) * 100, 9, 2) AS "% XML",
       DECIMAL((DECIMAL(CAD,31,8) / NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0)) * 100, 9, 2) AS "% CAD"
FROM SESSION.MAPEAMENTO_FORNECEDOR
WHERE PRODUTOR = 'T' AND TEM_CAD = 1 AND TEM_XML = 0 AND QTDTIPOS = 1 AND TEM_40415090 = 1 AND TEM_FORA_40415090 = 0
ORDER BY IDCLIFOR;

-- CONSULTA 02: Produtor Rural / Cadastro / mais de 1 tipo / CST 40,41,50,90
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR,
       TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",
       DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_FORNECEDOR
WHERE PRODUTOR = 'T' AND TEM_CAD = 1 AND TEM_XML = 0 AND QTDTIPOS > 1 AND TEM_40415090 = 1 AND TEM_FORA_40415090 = 0
ORDER BY IDCLIFOR;

-- CONSULTA 03: Nao Produtor Rural / Cadastro / 1 tipo / CST 40,41,50,90
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR,
       TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",
       DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_FORNECEDOR
WHERE PRODUTOR <> 'T' AND TEM_CAD = 1 AND TEM_XML = 0 AND QTDTIPOS = 1 AND TEM_40415090 = 1 AND TEM_FORA_40415090 = 0
ORDER BY IDCLIFOR;

-- CONSULTA 04: Nao Produtor Rural / Cadastro / mais de 1 tipo / CST 40,41,50,90
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR,
       TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",
       DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_FORNECEDOR
WHERE PRODUTOR <> 'T' AND TEM_CAD = 1 AND TEM_XML = 0 AND QTDTIPOS > 1 AND TEM_40415090 = 1 AND TEM_FORA_40415090 = 0
ORDER BY IDCLIFOR;

-- CONSULTA 05: Cadastro / 1 tipo / fora de CST 40,41,50,90
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR,
       TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",
       DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_FORNECEDOR
WHERE TEM_CAD = 1 AND TEM_XML = 0 AND QTDTIPOS = 1 AND TEM_FORA_40415090 = 1
ORDER BY IDCLIFOR;

-- CONSULTA 06: Cadastro / mais de 1 tipo / combina os dois grupos de CST
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR,
       TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",
       DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_FORNECEDOR
WHERE TEM_CAD = 1 AND TEM_XML = 0 AND QTDTIPOS > 1 AND TEM_40415090 = 1 AND TEM_00205160 = 1
ORDER BY IDCLIFOR;

-- CONSULTA 07: XML / 1 tipo / CST 40,41,50,90
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR,
       TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",
       DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_FORNECEDOR
WHERE TEM_XML = 1 AND TEM_CAD = 0 AND QTDTIPOS = 1 AND TEM_40415090 = 1 AND TEM_FORA_40415090 = 0
ORDER BY IDCLIFOR;

-- CONSULTA 08: XML / mais de 1 tipo / CST 40,41,50,90
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR,
       TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",
       DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_FORNECEDOR
WHERE TEM_XML = 1 AND TEM_CAD = 0 AND QTDTIPOS > 1 AND TEM_40415090 = 1 AND TEM_FORA_40415090 = 0
ORDER BY IDCLIFOR;

-- CONSULTA 09: XML / 1 tipo / fora de CST 40,41,50,90
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR,
       TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",
       DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_FORNECEDOR
WHERE TEM_XML = 1 AND TEM_CAD = 0 AND QTDTIPOS = 1 AND TEM_FORA_40415090 = 1
ORDER BY IDCLIFOR;

-- CONSULTA 10: XML / mais de 1 tipo / combina os dois grupos de CST
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR,
       TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",
       DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_FORNECEDOR
WHERE TEM_XML = 1 AND TEM_CAD = 0 AND QTDTIPOS > 1 AND TEM_40415090 = 1 AND TEM_00205160 = 1
ORDER BY IDCLIFOR;

-- CONSULTA 11: XML e Cadastro / 1 tipo / fora de CST 40,41,50,90
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR,
       TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",
       DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_FORNECEDOR
WHERE TEM_XML = 1 AND TEM_CAD = 1 AND QTDTIPOS = 1 AND TEM_FORA_40415090 = 1
ORDER BY IDCLIFOR;

-- CONSULTA 12: XML e Cadastro / mais de 1 tipo / combina os dois grupos de CST
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR,
       TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",
       DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_FORNECEDOR
WHERE TEM_XML = 1 AND TEM_CAD = 1 AND QTDTIPOS > 1 AND TEM_40415090 = 1 AND TEM_00205160 = 1
ORDER BY IDCLIFOR;

-- CONSULTA 13: Simples Nacional / Cadastro / 1 tipo / CST 00,20,51
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR,
       TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",
       DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_FORNECEDOR
WHERE SIMPLESNACIONAL = 'S' AND TEM_CAD = 1 AND TEM_XML = 0 AND QTDTIPOS = 1 AND TEM_002051 = 1 AND TEM_FORA_002051 = 0
ORDER BY IDCLIFOR;

-- CONSULTA 14: Simples Nacional / Cadastro / mais de 1 tipo / CST 00,20,51
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR,
       TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",
       DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_FORNECEDOR
WHERE SIMPLESNACIONAL = 'S' AND TEM_CAD = 1 AND TEM_XML = 0 AND QTDTIPOS > 1 AND TEM_002051 = 1 AND TEM_FORA_002051 = 0
ORDER BY IDCLIFOR;

-- CONSULTA 15: Nao Simples Nacional / Cadastro / 1 tipo / CST 00,20,51
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR,
       TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",
       DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_FORNECEDOR
WHERE SIMPLESNACIONAL = 'N' AND TEM_CAD = 1 AND TEM_XML = 0 AND QTDTIPOS = 1 AND TEM_002051 = 1 AND TEM_FORA_002051 = 0
ORDER BY IDCLIFOR;

-- CONSULTA 16: Nao Simples Nacional / Cadastro / mais de 1 tipo / CST 00,20,51
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR,
       TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",
       DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_FORNECEDOR
WHERE SIMPLESNACIONAL = 'N' AND TEM_CAD = 1 AND TEM_XML = 0 AND QTDTIPOS > 1 AND TEM_002051 = 1 AND TEM_FORA_002051 = 0
ORDER BY IDCLIFOR;
