-- CONSULTAS INDIVIDUAIS CORRIGIDAS: CLASSIFICACAO POR NOTA
-- Execute PREPARACAO e, na mesma sessao DB2, execute a consulta desejada.
-- Parametros: :RA_DTINI e :RA_DTFIM
--
-- A quantidade de tipos e os grupos de CST sao apurados por nota antes da
-- consolidacao por fornecedor e TIPO. Esta e a mesma granularidade do resumo.

DECLARE GLOBAL TEMPORARY TABLE SESSION.MAPEAMENTO_NOTA_TIPO (
    CONSULTA SMALLINT,
    IDCLIFOR INTEGER,
    IDATIVIDADE INTEGER,
    ATIVIDADE VARCHAR(60),
    PRODUTOR CHAR(1),
    TIPO VARCHAR(20),
    QTDNOTASTIPO BIGINT,
    XML BIGINT,
    CAD BIGINT
) ON COMMIT PRESERVE ROWS NOT LOGGED WITH REPLACE;

INSERT INTO SESSION.MAPEAMENTO_NOTA_TIPO
WITH
NOTAS_MOVIMENTO AS (
    SELECT EA.IDEMPRESA, EA.IDPLANILHA, N.IDCLIFOR
    FROM DBA.ESTOQUE_ANALITICO EA
    INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
    INNER JOIN DBA.NOTAS N ON N.IDEMPRESA = EA.IDEMPRESA AND N.IDPLANILHA = EA.IDPLANILHA
    WHERE EA.IDOPERACAO < 1000
      AND OI.TIPOMOVIMENTO = 'C'
      AND OI.FLAGMOVSALDOPRO = 'T'
      AND N.FLAGMOVFISCAL = 'T'
      AND N.FLAGNOTACANCEL = 'F'
      AND EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
    GROUP BY EA.IDEMPRESA, EA.IDPLANILHA, N.IDCLIFOR
),
ITENS AS (
    SELECT NM.IDEMPRESA, NM.IDPLANILHA, NM.IDCLIFOR,
           CASE WHEN EAF.FLAGTRIBUTACAOXML = 'T' THEN 'XML' ELSE 'CAD' END AS FONTE,
           MOD(EA.IDSITTRIB, 100) AS CST,
           CASE
               WHEN MOD(EA.IDSITTRIB, 100) = 40 THEN 'ISENTO-40'
               WHEN MOD(EA.IDSITTRIB, 100) = 41 THEN 'NAOTRIBUTADO-41'
               WHEN MOD(EA.IDSITTRIB, 100) = 50 THEN 'SUSPENSO-50'
               WHEN MOD(EA.IDSITTRIB, 100) = 90 THEN 'OUTROS-90'
               WHEN MOD(EA.IDSITTRIB, 100) = 0 THEN 'TRIBUTADO-00'
               WHEN MOD(EA.IDSITTRIB, 100) = 20 THEN 'REDUCAO-20'
               WHEN MOD(EA.IDSITTRIB, 100) = 51 THEN 'DIFERIDO-51'
               WHEN EA.TIPOSITTRIB = 'F' AND MOD(EA.IDSITTRIB, 100) = 60 THEN 'STNORMAL-60'
               WHEN EA.TIPOSITTRIB = 'A' AND MOD(EA.IDSITTRIB, 100) = 60 THEN 'STFRONTEIRA-60'
               ELSE 'OUTRO'
           END AS TIPO
    FROM NOTAS_MOVIMENTO NM
    INNER JOIN DBA.ESTOQUE_ANALITICO EA ON EA.IDEMPRESA = NM.IDEMPRESA AND EA.IDPLANILHA = NM.IDPLANILHA
    INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
    LEFT JOIN DBA.ESTOQUE_ANALITICO_FISCAL EAF
        ON EAF.IDEMPRESA = EA.IDEMPRESA AND EAF.IDPLANILHA = EA.IDPLANILHA AND EAF.NUMSEQUENCIA = EA.NUMSEQUENCIA
    WHERE OI.FLAGMOVSALDOPRO = 'T'
      AND EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
),
NOTA_RESUMO AS (
    SELECT IDEMPRESA, IDPLANILHA, IDCLIFOR,
           COUNT(DISTINCT TIPO) AS QTDTIPOS,
           MAX(CASE WHEN FONTE = 'XML' THEN 1 ELSE 0 END) AS TEM_XML,
           MAX(CASE WHEN FONTE = 'CAD' THEN 1 ELSE 0 END) AS TEM_CAD,
           MAX(CASE WHEN CST IN (40,41,50,90) THEN 1 ELSE 0 END) AS TEM_40415090,
           MAX(CASE WHEN CST NOT IN (40,41,50,90) THEN 1 ELSE 0 END) AS TEM_FORA_40415090,
           MAX(CASE WHEN CST IN (0,20,51,60) THEN 1 ELSE 0 END) AS TEM_00205160,
           MAX(CASE WHEN CST IN (0,20,51) THEN 1 ELSE 0 END) AS TEM_002051,
           MAX(CASE WHEN CST NOT IN (0,20,51) THEN 1 ELSE 0 END) AS TEM_FORA_002051
    FROM ITENS
    GROUP BY IDEMPRESA, IDPLANILHA, IDCLIFOR
),
NOTA_TIPO_FONTE AS (
    SELECT IDEMPRESA, IDPLANILHA, IDCLIFOR, TIPO,
           MAX(CASE WHEN FONTE = 'XML' THEN 1 ELSE 0 END) AS TEM_XML,
           MAX(CASE WHEN FONTE = 'CAD' THEN 1 ELSE 0 END) AS TEM_CAD
    FROM ITENS
    GROUP BY IDEMPRESA, IDPLANILHA, IDCLIFOR, TIPO
),
NOTAS_PERFIL AS (
    SELECT NR.*, CF.IDATIVIDADE, TA.DESCRTIPOATIVIDADE AS ATIVIDADE,
           COALESCE(ATV.FLAGPRODUTORRURAL, 'F') AS PRODUTOR,
           CASE WHEN CF.TIPOREGIMETRIBFEDERAL = 'S' THEN 'S' ELSE 'N' END AS SIMPLESNACIONAL
    FROM NOTA_RESUMO NR
    INNER JOIN DBA.CLIENTE_FORNECEDOR CF ON CF.IDCLIFOR = NR.IDCLIFOR
    LEFT JOIN DBA.ATIVIDADE ATV ON ATV.IDATIVIDADE = CF.IDATIVIDADE
    LEFT JOIN DBA.ATIVIDADE_TIPO_ATIVIDADE ATA ON ATA.IDATIVIDADE = CF.IDATIVIDADE AND ATA.FLAGPADRAO = 'T'
    LEFT JOIN DBA.TIPO_ATIVIDADE TA ON TA.IDTIPOATIVIDADE = ATA.IDTIPOATIVIDADE
),
NOTAS_CLASSIFICADAS AS (
    SELECT 1 AS CONSULTA, * FROM NOTAS_PERFIL WHERE PRODUTOR = 'T' AND TEM_CAD = 1 AND TEM_XML = 0 AND QTDTIPOS = 1 AND TEM_40415090 = 1 AND TEM_FORA_40415090 = 0
    UNION ALL SELECT 2, * FROM NOTAS_PERFIL WHERE PRODUTOR = 'T' AND TEM_CAD = 1 AND TEM_XML = 0 AND QTDTIPOS > 1 AND TEM_40415090 = 1 AND TEM_FORA_40415090 = 0
    UNION ALL SELECT 3, * FROM NOTAS_PERFIL WHERE PRODUTOR <> 'T' AND TEM_CAD = 1 AND TEM_XML = 0 AND QTDTIPOS = 1 AND TEM_40415090 = 1 AND TEM_FORA_40415090 = 0
    UNION ALL SELECT 4, * FROM NOTAS_PERFIL WHERE PRODUTOR <> 'T' AND TEM_CAD = 1 AND TEM_XML = 0 AND QTDTIPOS > 1 AND TEM_40415090 = 1 AND TEM_FORA_40415090 = 0
    UNION ALL SELECT 5, * FROM NOTAS_PERFIL WHERE TEM_CAD = 1 AND TEM_XML = 0 AND QTDTIPOS = 1 AND TEM_FORA_40415090 = 1
    -- Residual CAD multítipo: todas as notas que não são exclusivamente 40/41/50/90.
    UNION ALL SELECT 6, * FROM NOTAS_PERFIL WHERE TEM_CAD = 1 AND TEM_XML = 0 AND QTDTIPOS > 1 AND NOT (TEM_40415090 = 1 AND TEM_FORA_40415090 = 0)
    UNION ALL SELECT 7, * FROM NOTAS_PERFIL WHERE TEM_XML = 1 AND TEM_CAD = 0 AND QTDTIPOS = 1 AND TEM_40415090 = 1 AND TEM_FORA_40415090 = 0
    UNION ALL SELECT 8, * FROM NOTAS_PERFIL WHERE TEM_XML = 1 AND TEM_CAD = 0 AND QTDTIPOS > 1 AND TEM_40415090 = 1 AND TEM_FORA_40415090 = 0
    UNION ALL SELECT 9, * FROM NOTAS_PERFIL WHERE TEM_XML = 1 AND TEM_CAD = 0 AND QTDTIPOS = 1 AND TEM_FORA_40415090 = 1
    -- Residual XML multítipo: todas as notas que não são exclusivamente 40/41/50/90.
    UNION ALL SELECT 10, * FROM NOTAS_PERFIL WHERE TEM_XML = 1 AND TEM_CAD = 0 AND QTDTIPOS > 1 AND NOT (TEM_40415090 = 1 AND TEM_FORA_40415090 = 0)
    -- Fonte mista é residual completo: uma consulta para monotipo e outra para multítipo.
    UNION ALL SELECT 11, * FROM NOTAS_PERFIL WHERE TEM_XML = 1 AND TEM_CAD = 1 AND QTDTIPOS = 1
    UNION ALL SELECT 12, * FROM NOTAS_PERFIL WHERE TEM_XML = 1 AND TEM_CAD = 1 AND QTDTIPOS > 1
    UNION ALL SELECT 13, * FROM NOTAS_PERFIL WHERE SIMPLESNACIONAL = 'S' AND TEM_CAD = 1 AND TEM_XML = 0 AND QTDTIPOS = 1 AND TEM_002051 = 1 AND TEM_FORA_002051 = 0
    UNION ALL SELECT 14, * FROM NOTAS_PERFIL WHERE SIMPLESNACIONAL = 'S' AND TEM_CAD = 1 AND TEM_XML = 0 AND QTDTIPOS > 1 AND TEM_002051 = 1 AND TEM_FORA_002051 = 0
    UNION ALL SELECT 15, * FROM NOTAS_PERFIL WHERE SIMPLESNACIONAL = 'N' AND TEM_CAD = 1 AND TEM_XML = 0 AND QTDTIPOS = 1 AND TEM_002051 = 1 AND TEM_FORA_002051 = 0
    UNION ALL SELECT 16, * FROM NOTAS_PERFIL WHERE SIMPLESNACIONAL = 'N' AND TEM_CAD = 1 AND TEM_XML = 0 AND QTDTIPOS > 1 AND TEM_002051 = 1 AND TEM_FORA_002051 = 0
)
SELECT NC.CONSULTA, NC.IDCLIFOR, NC.IDATIVIDADE, NC.ATIVIDADE, NC.PRODUTOR,
       NTF.TIPO, COUNT(*) AS QTDNOTASTIPO, SUM(NTF.TEM_XML) AS XML, SUM(NTF.TEM_CAD) AS CAD
FROM NOTAS_CLASSIFICADAS NC
INNER JOIN NOTA_TIPO_FONTE NTF
    ON NTF.IDEMPRESA = NC.IDEMPRESA AND NTF.IDPLANILHA = NC.IDPLANILHA AND NTF.IDCLIFOR = NC.IDCLIFOR
GROUP BY NC.CONSULTA, NC.IDCLIFOR, NC.IDATIVIDADE, NC.ATIVIDADE, NC.PRODUTOR, NTF.TIPO;

-- CONSULTA 01
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR, TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML",
       DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_NOTA_TIPO WHERE CONSULTA = 1 ORDER BY IDCLIFOR, TIPO;

-- CONSULTA 02
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR, TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML", DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_NOTA_TIPO WHERE CONSULTA = 2 ORDER BY IDCLIFOR, TIPO;

-- CONSULTA 03
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR, TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML", DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_NOTA_TIPO WHERE CONSULTA = 3 ORDER BY IDCLIFOR, TIPO;

-- CONSULTA 04
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR, TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML", DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_NOTA_TIPO WHERE CONSULTA = 4 ORDER BY IDCLIFOR, TIPO;

-- CONSULTA 05
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR, TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML", DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_NOTA_TIPO WHERE CONSULTA = 5 ORDER BY IDCLIFOR, TIPO;

-- CONSULTA 06
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR, TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML", DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_NOTA_TIPO WHERE CONSULTA = 6 ORDER BY IDCLIFOR, TIPO;

-- CONSULTA 07
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR, TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML", DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_NOTA_TIPO WHERE CONSULTA = 7 ORDER BY IDCLIFOR, TIPO;

-- CONSULTA 08
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR, TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML", DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_NOTA_TIPO WHERE CONSULTA = 8 ORDER BY IDCLIFOR, TIPO;

-- CONSULTA 09
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR, TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML", DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_NOTA_TIPO WHERE CONSULTA = 9 ORDER BY IDCLIFOR, TIPO;

-- CONSULTA 10
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR, TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML", DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_NOTA_TIPO WHERE CONSULTA = 10 ORDER BY IDCLIFOR, TIPO;

-- CONSULTA 11
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR, TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML", DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_NOTA_TIPO WHERE CONSULTA = 11 ORDER BY IDCLIFOR, TIPO;

-- CONSULTA 12
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR, TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML", DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_NOTA_TIPO WHERE CONSULTA = 12 ORDER BY IDCLIFOR, TIPO;

-- CONSULTA 13
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR, TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML", DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_NOTA_TIPO WHERE CONSULTA = 13 ORDER BY IDCLIFOR, TIPO;

-- CONSULTA 14
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR, TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML", DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_NOTA_TIPO WHERE CONSULTA = 14 ORDER BY IDCLIFOR, TIPO;

-- CONSULTA 15
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR, TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML", DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_NOTA_TIPO WHERE CONSULTA = 15 ORDER BY IDCLIFOR, TIPO;

-- CONSULTA 16
SELECT IDCLIFOR, IDATIVIDADE, ATIVIDADE, PRODUTOR, TIPO, QTDNOTASTIPO, XML, CAD,
       DECIMAL((DECIMAL(XML,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% XML", DECIMAL((DECIMAL(CAD,31,8)/NULLIF(DECIMAL(QTDNOTASTIPO,31,8),0))*100,9,2) AS "% CAD"
FROM SESSION.MAPEAMENTO_NOTA_TIPO WHERE CONSULTA = 16 ORDER BY IDCLIFOR, TIPO;
