-- MAPEAMENTO DE TRIBUTACAO POR FORNECEDOR
-- Parametros esperados pelo gerador de relatorios: :RA_DTINI e :RA_DTFIM
--
-- Regra de fonte: EAF.FLAGTRIBUTACAOXML = 'T' = XML; qualquer outro valor
-- (inclusive EAF inexistente) = Cadastro.
-- QTDNOTASTIPO e a quantidade de notas distintas do fornecedor no periodo.
-- XML e CAD contam, respectivamente, notas que possuem ao menos um item de
-- cada fonte. Assim, uma nota com itens de ambas as fontes entra nas duas
-- colunas, refletindo corretamente o uso misto.

WITH
NOTAS_MOVIMENTO AS (
    SELECT EA.IDEMPRESA, EA.IDPLANILHA, N.IDCLIFOR
    FROM DBA.ESTOQUE_ANALITICO EA
    INNER JOIN DBA.OPERACAO_INTERNA OI
        ON OI.IDOPERACAO = EA.IDOPERACAO
    INNER JOIN DBA.NOTAS N
        ON N.IDEMPRESA = EA.IDEMPRESA
       AND N.IDPLANILHA = EA.IDPLANILHA
    WHERE EA.IDOPERACAO < 1000
      AND OI.TIPOMOVIMENTO = 'C'
      AND OI.FLAGMOVSALDOPRO = 'T'
      AND N.FLAGMOVFISCAL = 'T'
      AND N.FLAGNOTACANCEL = 'F'
      AND EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
    GROUP BY EA.IDEMPRESA, EA.IDPLANILHA, N.IDCLIFOR
),
ITENS_TRIBUTACAO AS (
    SELECT NM.IDEMPRESA,
           NM.IDPLANILHA,
           NM.IDCLIFOR,
           CASE WHEN EAF.FLAGTRIBUTACAOXML = 'T' THEN 'XML' ELSE 'CAD' END AS FONTE,
           MOD(EA.IDSITTRIB, 100) AS CST,
           CASE
               WHEN MOD(EA.IDSITTRIB, 100) = 40 THEN 'ISENTO-40'
               WHEN MOD(EA.IDSITTRIB, 100) = 41 THEN 'NAOTRIBUTADO-41'
               WHEN MOD(EA.IDSITTRIB, 100) = 50 THEN 'SUSPENSO-50'
               WHEN MOD(EA.IDSITTRIB, 100) = 90 THEN 'OUTROS-90'
               WHEN MOD(EA.IDSITTRIB, 100) = 0  THEN 'TRIBUTADO-00'
               WHEN MOD(EA.IDSITTRIB, 100) = 20 THEN 'REDUCAO-20'
               WHEN MOD(EA.IDSITTRIB, 100) = 51 THEN 'DIFERIDO-51'
               WHEN EA.TIPOSITTRIB = 'F' AND MOD(EA.IDSITTRIB, 100) = 60 THEN 'STNORMAL-60'
               WHEN EA.TIPOSITTRIB = 'A' AND MOD(EA.IDSITTRIB, 100) = 60 THEN 'STFRONTEIRA-60'
               ELSE 'OUTRO'
           END AS TIPO_TRIBUTACAO
    FROM NOTAS_MOVIMENTO NM
    INNER JOIN DBA.ESTOQUE_ANALITICO EA
        ON EA.IDEMPRESA = NM.IDEMPRESA
       AND EA.IDPLANILHA = NM.IDPLANILHA
    INNER JOIN DBA.OPERACAO_INTERNA OI
        ON OI.IDOPERACAO = EA.IDOPERACAO
    LEFT JOIN DBA.ESTOQUE_ANALITICO_FISCAL EAF
        ON EAF.IDEMPRESA = EA.IDEMPRESA
       AND EAF.IDPLANILHA = EA.IDPLANILHA
       AND EAF.NUMSEQUENCIA = EA.NUMSEQUENCIA
    WHERE OI.FLAGMOVSALDOPRO = 'T'
      AND EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
),
NOTA_FONTE AS (
    SELECT IDEMPRESA,
           IDPLANILHA,
           IDCLIFOR,
           MAX(CASE WHEN FONTE = 'XML' THEN 1 ELSE 0 END) AS TEM_XML,
           MAX(CASE WHEN FONTE = 'CAD' THEN 1 ELSE 0 END) AS TEM_CAD
    FROM ITENS_TRIBUTACAO
    GROUP BY IDEMPRESA, IDPLANILHA, IDCLIFOR
),
FORNECEDOR_NOTAS AS (
    SELECT IDCLIFOR,
           COUNT(*) AS QTDNOTASTIPO,
           SUM(TEM_XML) AS XML,
           SUM(TEM_CAD) AS CAD,
           MAX(TEM_XML) AS TEM_XML,
           MAX(TEM_CAD) AS TEM_CAD
    FROM NOTA_FONTE
    GROUP BY IDCLIFOR
),
FORNECEDOR_TRIBUTACAO AS (
    SELECT IDCLIFOR,
           COUNT(DISTINCT TIPO_TRIBUTACAO) AS QTDTIPOS,
           MAX(CASE WHEN CST IN (40, 41, 50, 90) THEN 1 ELSE 0 END) AS TEM_40415090,
           MAX(CASE WHEN CST NOT IN (40, 41, 50, 90) THEN 1 ELSE 0 END) AS TEM_FORA_40415090,
           MAX(CASE WHEN CST IN (0, 20, 51, 60) THEN 1 ELSE 0 END) AS TEM_00205160,
           MAX(CASE WHEN CST IN (0, 20, 51) THEN 1 ELSE 0 END) AS TEM_002051,
           MAX(CASE WHEN CST NOT IN (0, 20, 51) THEN 1 ELSE 0 END) AS TEM_FORA_002051
    FROM ITENS_TRIBUTACAO
    GROUP BY IDCLIFOR
),
FORNECEDORES AS (
    SELECT CF.IDCLIFOR,
           CF.IDATIVIDADE,
           TA.DESCRTIPOATIVIDADE AS ATIVIDADE,
           COALESCE(ATV.FLAGPRODUTORRURAL, 'F') AS PRODUTOR,
           CASE WHEN CF.TIPOREGIMETRIBFEDERAL = 'S' THEN 'S' ELSE 'N' END AS SIMPLESNACIONAL,
           FN.QTDNOTASTIPO,
           FN.XML,
           FN.CAD,
           FN.TEM_XML,
           FN.TEM_CAD,
           FT.QTDTIPOS,
           FT.TEM_40415090,
           FT.TEM_FORA_40415090,
           FT.TEM_00205160,
           FT.TEM_002051,
           FT.TEM_FORA_002051
    FROM FORNECEDOR_NOTAS FN
    INNER JOIN FORNECEDOR_TRIBUTACAO FT ON FT.IDCLIFOR = FN.IDCLIFOR
    INNER JOIN DBA.CLIENTE_FORNECEDOR CF ON CF.IDCLIFOR = FN.IDCLIFOR
    LEFT JOIN DBA.ATIVIDADE ATV ON ATV.IDATIVIDADE = CF.IDATIVIDADE
    LEFT JOIN DBA.ATIVIDADE_TIPO_ATIVIDADE ATA
        ON ATA.IDATIVIDADE = CF.IDATIVIDADE
       AND ATA.FLAGPADRAO = 'T'
    LEFT JOIN DBA.TIPO_ATIVIDADE TA ON TA.IDTIPOATIVIDADE = ATA.IDTIPOATIVIDADE
),
RESULTADO AS (
    SELECT '01 - PRODUTOR / CAD / 1 TIPO / CST 40,41,50,90' AS TIPO, F.* FROM FORNECEDORES F
     WHERE PRODUTOR = 'T' AND TEM_CAD = 1 AND TEM_XML = 0 AND QTDTIPOS = 1 AND TEM_40415090 = 1 AND TEM_FORA_40415090 = 0
    UNION ALL
    SELECT '02 - PRODUTOR / CAD / >1 TIPO / CST 40,41,50,90', F.* FROM FORNECEDORES F
     WHERE PRODUTOR = 'T' AND TEM_CAD = 1 AND TEM_XML = 0 AND QTDTIPOS > 1 AND TEM_40415090 = 1 AND TEM_FORA_40415090 = 0
    UNION ALL
    SELECT '03 - NAO PRODUTOR / CAD / 1 TIPO / CST 40,41,50,90', F.* FROM FORNECEDORES F
     WHERE PRODUTOR <> 'T' AND TEM_CAD = 1 AND TEM_XML = 0 AND QTDTIPOS = 1 AND TEM_40415090 = 1 AND TEM_FORA_40415090 = 0
    UNION ALL
    SELECT '04 - NAO PRODUTOR / CAD / >1 TIPO / CST 40,41,50,90', F.* FROM FORNECEDORES F
     WHERE PRODUTOR <> 'T' AND TEM_CAD = 1 AND TEM_XML = 0 AND QTDTIPOS > 1 AND TEM_40415090 = 1 AND TEM_FORA_40415090 = 0
    UNION ALL
    SELECT '05 - CAD / 1 TIPO / FORA CST 40,41,50,90', F.* FROM FORNECEDORES F
     WHERE TEM_CAD = 1 AND TEM_XML = 0 AND QTDTIPOS = 1 AND TEM_FORA_40415090 = 1
    UNION ALL
    SELECT '06 - CAD / >1 TIPO / COMBINA 40,41,50,90 COM 00,20,51,60', F.* FROM FORNECEDORES F
     WHERE TEM_CAD = 1 AND TEM_XML = 0 AND QTDTIPOS > 1 AND TEM_40415090 = 1 AND TEM_00205160 = 1
    UNION ALL
    SELECT '07 - XML / 1 TIPO / CST 40,41,50,90', F.* FROM FORNECEDORES F
     WHERE TEM_XML = 1 AND TEM_CAD = 0 AND QTDTIPOS = 1 AND TEM_40415090 = 1 AND TEM_FORA_40415090 = 0
    UNION ALL
    SELECT '08 - XML / >1 TIPO / CST 40,41,50,90', F.* FROM FORNECEDORES F
     WHERE TEM_XML = 1 AND TEM_CAD = 0 AND QTDTIPOS > 1 AND TEM_40415090 = 1 AND TEM_FORA_40415090 = 0
    UNION ALL
    SELECT '09 - XML / 1 TIPO / FORA CST 40,41,50,90', F.* FROM FORNECEDORES F
     WHERE TEM_XML = 1 AND TEM_CAD = 0 AND QTDTIPOS = 1 AND TEM_FORA_40415090 = 1
    UNION ALL
    SELECT '10 - XML / >1 TIPO / COMBINA 40,41,50,90 COM 00,20,51,60', F.* FROM FORNECEDORES F
     WHERE TEM_XML = 1 AND TEM_CAD = 0 AND QTDTIPOS > 1 AND TEM_40415090 = 1 AND TEM_00205160 = 1
    UNION ALL
    SELECT '11 - XML E CAD / 1 TIPO / FORA CST 40,41,50,90', F.* FROM FORNECEDORES F
     WHERE TEM_XML = 1 AND TEM_CAD = 1 AND QTDTIPOS = 1 AND TEM_FORA_40415090 = 1
    UNION ALL
    SELECT '12 - XML E CAD / >1 TIPO / COMBINA 40,41,50,90 COM 00,20,51,60', F.* FROM FORNECEDORES F
     WHERE TEM_XML = 1 AND TEM_CAD = 1 AND QTDTIPOS > 1 AND TEM_40415090 = 1 AND TEM_00205160 = 1
    UNION ALL
    SELECT '13 - SIMPLES / CAD / 1 TIPO / CST 00,20,51', F.* FROM FORNECEDORES F
     WHERE SIMPLESNACIONAL = 'S' AND TEM_CAD = 1 AND TEM_XML = 0 AND QTDTIPOS = 1 AND TEM_002051 = 1 AND TEM_FORA_002051 = 0
    UNION ALL
    SELECT '14 - SIMPLES / CAD / >1 TIPO / CST 00,20,51', F.* FROM FORNECEDORES F
     WHERE SIMPLESNACIONAL = 'S' AND TEM_CAD = 1 AND TEM_XML = 0 AND QTDTIPOS > 1 AND TEM_002051 = 1 AND TEM_FORA_002051 = 0
    UNION ALL
    SELECT '15 - NAO SIMPLES / CAD / 1 TIPO / CST 00,20,51', F.* FROM FORNECEDORES F
     WHERE SIMPLESNACIONAL = 'N' AND TEM_CAD = 1 AND TEM_XML = 0 AND QTDTIPOS = 1 AND TEM_002051 = 1 AND TEM_FORA_002051 = 0
    UNION ALL
    SELECT '16 - NAO SIMPLES / CAD / >1 TIPO / CST 00,20,51', F.* FROM FORNECEDORES F
     WHERE SIMPLESNACIONAL = 'N' AND TEM_CAD = 1 AND TEM_XML = 0 AND QTDTIPOS > 1 AND TEM_002051 = 1 AND TEM_FORA_002051 = 0
),
TOTAIS_16 AS (
    SELECT COALESCE(SUM(QTDNOTASTIPO), 0) AS QTDNOTAS_CLASSIFICADAS
    FROM RESULTADO
),
TOTAL_BASE AS (
    SELECT COUNT(*) AS QTDNOTAS_BASE
    FROM NOTAS_MOVIMENTO
)
SELECT R.IDCLIFOR,
       R.IDATIVIDADE,
       R.ATIVIDADE,
       R.PRODUTOR,
       R.TIPO,
       R.QTDNOTASTIPO,
       R.XML,
       R.CAD,
       DECIMAL((DECIMAL(R.XML, 31, 8) / NULLIF(DECIMAL(R.QTDNOTASTIPO, 31, 8), 0)) * 100, 9, 2) AS "% XML",
       DECIMAL((DECIMAL(R.CAD, 31, 8) / NULLIF(DECIMAL(R.QTDNOTASTIPO, 31, 8), 0)) * 100, 9, 2) AS "% CAD",
       T16.QTDNOTAS_CLASSIFICADAS,
       TB.QTDNOTAS_BASE,
       TB.QTDNOTAS_BASE - T16.QTDNOTAS_CLASSIFICADAS AS DIFERENCA_PARA_BASE
FROM RESULTADO R
CROSS JOIN TOTAIS_16 T16
CROSS JOIN TOTAL_BASE TB
ORDER BY R.TIPO, R.IDCLIFOR;

-- O comparativo e exibido nas tres ultimas colunas. DIFERENCA_PARA_BASE = 0
-- indica que as 16 classificacoes cobriram todas as notas da consulta-base.
