-- VALIDACAO: ISENTO-40 das consultas 01 a 16 x resumo-base
-- Parametros: :RA_DTINI e :RA_DTFIM
--
-- Observacao: o resumo-base conta notas cujo conjunto inteiro de itens possui
-- somente ISENTO-40. As consultas 01-16 classificam o fornecedor no periodo e
-- depois totalizam cada tipo. A coluna DIFERENCA demonstra essa eventual
-- diferenca de granularidade.

WITH
NOTAS_MOVIMENTO AS (
    SELECT EA.IDEMPRESA, EA.IDPLANILHA, N.IDCLIFOR
    FROM DBA.ESTOQUE_ANALITICO EA
    INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
    INNER JOIN DBA.NOTAS N ON N.IDEMPRESA = EA.IDEMPRESA AND N.IDPLANILHA = EA.IDPLANILHA
    WHERE EA.IDOPERACAO < 1000
      AND OI.TIPOMOVIMENTO = 'C'
      AND OI.FLAGMOVSALDOPRO = 'T'
      AND N.FLAGMOVFISCAL = 'T'
      AND N.FLAGNOTACANCEL = 'F'
      AND EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
    GROUP BY EA.IDEMPRESA, EA.IDPLANILHA, N.IDCLIFOR
),
ITENS AS (
    SELECT NM.IDEMPRESA, NM.IDPLANILHA, NM.IDCLIFOR,
           CASE WHEN EAF.FLAGTRIBUTACAOXML = 'T' THEN 'XML' ELSE 'CAD' END AS FONTE,
           MOD(EA.IDSITTRIB, 100) AS CST,
           CASE
               WHEN MOD(EA.IDSITTRIB, 100) = 40 THEN 'ISENTO-40'
               WHEN MOD(EA.IDSITTRIB, 100) = 41 THEN 'NAOTRIBUTADO-41'
               WHEN MOD(EA.IDSITTRIB, 100) = 50 THEN 'SUSPENSO-50'
               WHEN MOD(EA.IDSITTRIB, 100) = 90 THEN 'OUTROS-90'
               WHEN MOD(EA.IDSITTRIB, 100) = 0 THEN 'TRIBUTADO-00'
               WHEN MOD(EA.IDSITTRIB, 100) = 20 THEN 'REDUCAO-20'
               WHEN MOD(EA.IDSITTRIB, 100) = 51 THEN 'DIFERIDO-51'
               WHEN EA.TIPOSITTRIB = 'F' AND MOD(EA.IDSITTRIB, 100) = 60 THEN 'STNORMAL-60'
               WHEN EA.TIPOSITTRIB = 'A' AND MOD(EA.IDSITTRIB, 100) = 60 THEN 'STFRONTEIRA-60'
               ELSE 'OUTRO'
           END AS TIPO
    FROM NOTAS_MOVIMENTO NM
    INNER JOIN DBA.ESTOQUE_ANALITICO EA ON EA.IDEMPRESA = NM.IDEMPRESA AND EA.IDPLANILHA = NM.IDPLANILHA
    INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
    LEFT JOIN DBA.ESTOQUE_ANALITICO_FISCAL EAF
        ON EAF.IDEMPRESA = EA.IDEMPRESA AND EAF.IDPLANILHA = EA.IDPLANILHA AND EAF.NUMSEQUENCIA = EA.NUMSEQUENCIA
    WHERE OI.FLAGMOVSALDOPRO = 'T'
      AND EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
),
NOTA_FONTE AS (
    SELECT IDEMPRESA, IDPLANILHA, IDCLIFOR,
           MAX(CASE WHEN FONTE = 'XML' THEN 1 ELSE 0 END) AS TEM_XML,
           MAX(CASE WHEN FONTE = 'CAD' THEN 1 ELSE 0 END) AS TEM_CAD
    FROM ITENS
    GROUP BY IDEMPRESA, IDPLANILHA, IDCLIFOR
),
NOTA_TIPO AS (
    SELECT IDEMPRESA, IDPLANILHA, IDCLIFOR, TIPO,
           MAX(CASE WHEN FONTE = 'XML' THEN 1 ELSE 0 END) AS TEM_XML,
           MAX(CASE WHEN FONTE = 'CAD' THEN 1 ELSE 0 END) AS TEM_CAD
    FROM ITENS
    GROUP BY IDEMPRESA, IDPLANILHA, IDCLIFOR, TIPO
),
FORNECEDOR_NOTAS AS (
    SELECT IDCLIFOR, MAX(TEM_XML) AS TEM_XML, MAX(TEM_CAD) AS TEM_CAD
    FROM NOTA_FONTE
    GROUP BY IDCLIFOR
),
FORNECEDOR_TRIBUTACAO AS (
    SELECT IDCLIFOR,
           COUNT(DISTINCT TIPO) AS QTDTIPOS,
           MAX(CASE WHEN CST IN (40,41,50,90) THEN 1 ELSE 0 END) AS TEM_40415090,
           MAX(CASE WHEN CST NOT IN (40,41,50,90) THEN 1 ELSE 0 END) AS TEM_FORA_40415090,
           MAX(CASE WHEN CST IN (0,20,51,60) THEN 1 ELSE 0 END) AS TEM_00205160
    FROM ITENS
    GROUP BY IDCLIFOR
),
FORNECEDORES AS (
    SELECT FN.IDCLIFOR,
           COALESCE(ATV.FLAGPRODUTORRURAL, 'F') AS PRODUTOR,
           FN.TEM_XML, FN.TEM_CAD,
           FT.QTDTIPOS, FT.TEM_40415090, FT.TEM_FORA_40415090, FT.TEM_00205160
    FROM FORNECEDOR_NOTAS FN
    INNER JOIN FORNECEDOR_TRIBUTACAO FT ON FT.IDCLIFOR = FN.IDCLIFOR
    INNER JOIN DBA.CLIENTE_FORNECEDOR CF ON CF.IDCLIFOR = FN.IDCLIFOR
    LEFT JOIN DBA.ATIVIDADE ATV ON ATV.IDATIVIDADE = CF.IDATIVIDADE
),
ISENTO_40_CONSULTAS AS (
    SELECT COUNT(*) AS QTDNOTAS
    FROM NOTA_TIPO NT
    INNER JOIN FORNECEDORES F ON F.IDCLIFOR = NT.IDCLIFOR
    WHERE NT.TIPO = 'ISENTO-40'
      AND (
           (F.PRODUTOR = 'T'  AND F.TEM_CAD = 1 AND F.TEM_XML = 0 AND F.QTDTIPOS = 1 AND F.TEM_40415090 = 1 AND F.TEM_FORA_40415090 = 0)
        OR (F.PRODUTOR = 'T'  AND F.TEM_CAD = 1 AND F.TEM_XML = 0 AND F.QTDTIPOS > 1 AND F.TEM_40415090 = 1 AND F.TEM_FORA_40415090 = 0)
        OR (F.PRODUTOR <> 'T' AND F.TEM_CAD = 1 AND F.TEM_XML = 0 AND F.QTDTIPOS = 1 AND F.TEM_40415090 = 1 AND F.TEM_FORA_40415090 = 0)
        OR (F.PRODUTOR <> 'T' AND F.TEM_CAD = 1 AND F.TEM_XML = 0 AND F.QTDTIPOS > 1 AND F.TEM_40415090 = 1 AND F.TEM_FORA_40415090 = 0)
        OR (F.TEM_CAD = 1 AND F.TEM_XML = 0 AND F.QTDTIPOS > 1 AND F.TEM_40415090 = 1 AND F.TEM_00205160 = 1)
        OR (F.TEM_XML = 1 AND F.TEM_CAD = 0 AND F.QTDTIPOS = 1 AND F.TEM_40415090 = 1 AND F.TEM_FORA_40415090 = 0)
        OR (F.TEM_XML = 1 AND F.TEM_CAD = 0 AND F.QTDTIPOS > 1 AND F.TEM_40415090 = 1 AND F.TEM_FORA_40415090 = 0)
        OR (F.TEM_XML = 1 AND F.TEM_CAD = 0 AND F.QTDTIPOS > 1 AND F.TEM_40415090 = 1 AND F.TEM_00205160 = 1)
        OR (F.TEM_XML = 1 AND F.TEM_CAD = 1 AND F.QTDTIPOS > 1 AND F.TEM_40415090 = 1 AND F.TEM_00205160 = 1)
      )
),
ISENTO_40_RESUMO AS (
    SELECT COUNT(*) AS QTDNOTAS
    FROM (
        SELECT IDEMPRESA, IDPLANILHA
        FROM ITENS
        GROUP BY IDEMPRESA, IDPLANILHA
        HAVING COUNT(DISTINCT TIPO) = 1
           AND MAX(TIPO) = 'ISENTO-40'
    ) X
)
SELECT 'ISENTO-40' AS TIPO,
       C.QTDNOTAS AS QTDNOTAS_CONSULTAS_01_A_16,
       R.QTDNOTAS AS QTDNOTAS_RESUMO,
       C.QTDNOTAS - R.QTDNOTAS AS DIFERENCA,
       CASE WHEN C.QTDNOTAS = R.QTDNOTAS THEN 'BATE' ELSE 'NAO BATE' END AS VALIDACAO
FROM ISENTO_40_CONSULTAS C
CROSS JOIN ISENTO_40_RESUMO R;
