-- VALIDACAO ESPECIFICA DO ISENTO-40: RESUMO x CONSULTAS 01/03/07/11.
-- Parametros: :RA_DTINI e :RA_DTFIM
-- Execute na mesma referencia de periodo do resumo.

WITH
NOTAS_MOVIMENTO AS (
    SELECT EA.IDEMPRESA, EA.IDPLANILHA, N.IDCLIFOR
    FROM DBA.ESTOQUE_ANALITICO EA
    INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
    INNER JOIN DBA.NOTAS N ON N.IDEMPRESA = EA.IDEMPRESA AND N.IDPLANILHA = EA.IDPLANILHA
    WHERE EA.IDOPERACAO < 1000 AND OI.TIPOMOVIMENTO = 'C'
      AND OI.FLAGMOVSALDOPRO = 'T' AND N.FLAGMOVFISCAL = 'T' AND N.FLAGNOTACANCEL = 'F'
      AND EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
    GROUP BY EA.IDEMPRESA, EA.IDPLANILHA, N.IDCLIFOR
),
ITENS_TIPO AS (
    SELECT NM.IDEMPRESA, NM.IDPLANILHA, NM.IDCLIFOR,
           CASE
               WHEN MOD(EA.IDSITTRIB, 100) = 40 THEN 'ISENTO-40'
               WHEN MOD(EA.IDSITTRIB, 100) = 41 THEN 'NAOTRIBUTADO-41'
               WHEN MOD(EA.IDSITTRIB, 100) = 50 THEN 'SUSPENSO-50'
               WHEN MOD(EA.IDSITTRIB, 100) = 90 THEN 'OUTROS-90'
               WHEN MOD(EA.IDSITTRIB, 100) = 0 THEN 'TRIBUTADO-00'
               WHEN MOD(EA.IDSITTRIB, 100) = 20 THEN 'REDUCAO-20'
               WHEN MOD(EA.IDSITTRIB, 100) = 51 THEN 'DIFERIDO-51'
               WHEN EA.TIPOSITTRIB = 'F' AND MOD(EA.IDSITTRIB, 100) = 60 THEN 'STNORMAL-60'
               WHEN EA.TIPOSITTRIB = 'A' AND MOD(EA.IDSITTRIB, 100) = 60 THEN 'STFRONTEIRA-60'
               ELSE 'OUTRO'
           END AS TIPO
    FROM NOTAS_MOVIMENTO NM
    INNER JOIN DBA.ESTOQUE_ANALITICO EA ON EA.IDEMPRESA = NM.IDEMPRESA AND EA.IDPLANILHA = NM.IDPLANILHA
    INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
    WHERE OI.FLAGMOVSALDOPRO = 'T' AND EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
),
RESUMO_ISENTO AS (
    SELECT IDEMPRESA, IDPLANILHA, IDCLIFOR
    FROM ITENS_TIPO
    GROUP BY IDEMPRESA, IDPLANILHA, IDCLIFOR
    HAVING COUNT(DISTINCT TIPO) = 1 AND MAX(TIPO) = 'ISENTO-40'
),
FONTE_NOTA AS (
    SELECT RI.IDEMPRESA, RI.IDPLANILHA,
           MAX(CASE WHEN EAF.FLAGTRIBUTACAOXML = 'T' THEN 1 ELSE 0 END) AS TEM_XML,
           MAX(CASE WHEN EAF.FLAGTRIBUTACAOXML = 'T' THEN 0 ELSE 1 END) AS TEM_CAD
    FROM RESUMO_ISENTO RI
    INNER JOIN DBA.ESTOQUE_ANALITICO EA ON EA.IDEMPRESA = RI.IDEMPRESA AND EA.IDPLANILHA = RI.IDPLANILHA
    INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
    LEFT JOIN DBA.ESTOQUE_ANALITICO_FISCAL EAF
        ON EAF.IDEMPRESA = EA.IDEMPRESA AND EAF.IDPLANILHA = EA.IDPLANILHA AND EAF.NUMSEQUENCIA = EA.NUMSEQUENCIA
    WHERE OI.FLAGMOVSALDOPRO = 'T' AND EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
    GROUP BY RI.IDEMPRESA, RI.IDPLANILHA
),
DISTRIBUICAO AS (
    SELECT CASE
               WHEN FN.TEM_CAD = 1 AND FN.TEM_XML = 0 AND COALESCE(ATV.FLAGPRODUTORRURAL, 'F') = 'T' THEN 'CONSULTA 01'
               WHEN FN.TEM_CAD = 1 AND FN.TEM_XML = 0 THEN 'CONSULTA 03'
               WHEN FN.TEM_XML = 1 AND FN.TEM_CAD = 0 THEN 'CONSULTA 07'
               WHEN FN.TEM_XML = 1 AND FN.TEM_CAD = 1 THEN 'CONSULTA 11'
               ELSE 'SEM CLASSIFICACAO'
           END AS DESTINO
    FROM RESUMO_ISENTO RI
    INNER JOIN FONTE_NOTA FN ON FN.IDEMPRESA = RI.IDEMPRESA AND FN.IDPLANILHA = RI.IDPLANILHA
    INNER JOIN DBA.CLIENTE_FORNECEDOR CF ON CF.IDCLIFOR = RI.IDCLIFOR
    LEFT JOIN DBA.ATIVIDADE ATV ON ATV.IDATIVIDADE = CF.IDATIVIDADE
),
TOTAIS AS (
    SELECT DESTINO, COUNT(*) AS QTDNOTAS FROM DISTRIBUICAO GROUP BY DESTINO
    UNION ALL SELECT 'TOTAL RESUMO', COUNT(*) FROM RESUMO_ISENTO
)
SELECT DESTINO, QTDNOTAS
FROM TOTAIS
ORDER BY CASE DESTINO
             WHEN 'CONSULTA 01' THEN 1 WHEN 'CONSULTA 03' THEN 2
             WHEN 'CONSULTA 07' THEN 3 WHEN 'CONSULTA 11' THEN 4
             WHEN 'SEM CLASSIFICACAO' THEN 5 ELSE 6
         END;
