-- VALIDA O FECHAMENTO DAS CONSULTAS 01 A 12 CONTRA O UNIVERSO DO RESUMO.
-- Parametros: :RA_DTINI e :RA_DTFIM
-- A comparacao usa notas unicas, e nao a soma de QTDNOTASTIPO: uma nota
-- multítipo aparece em mais de uma linha de tipo no relatorio detalhado.

WITH
NOTAS_MOVIMENTO AS (
    SELECT EA.IDEMPRESA, EA.IDPLANILHA, N.IDCLIFOR
    FROM DBA.ESTOQUE_ANALITICO EA
    INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
    INNER JOIN DBA.NOTAS N ON N.IDEMPRESA = EA.IDEMPRESA AND N.IDPLANILHA = EA.IDPLANILHA
    WHERE EA.IDOPERACAO < 1000 AND OI.TIPOMOVIMENTO = 'C'
      AND OI.FLAGMOVSALDOPRO = 'T' AND N.FLAGMOVFISCAL = 'T' AND N.FLAGNOTACANCEL = 'F'
      AND EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
    GROUP BY EA.IDEMPRESA, EA.IDPLANILHA, N.IDCLIFOR
),
ITENS AS (
    SELECT NM.IDEMPRESA, NM.IDPLANILHA, NM.IDCLIFOR,
           CASE WHEN EAF.FLAGTRIBUTACAOXML = 'T' THEN 'XML' ELSE 'CAD' END AS FONTE,
           MOD(EA.IDSITTRIB, 100) AS CST,
           CASE
               WHEN MOD(EA.IDSITTRIB, 100) = 40 THEN 'ISENTO-40'
               WHEN MOD(EA.IDSITTRIB, 100) = 41 THEN 'NAOTRIBUTADO-41'
               WHEN MOD(EA.IDSITTRIB, 100) = 50 THEN 'SUSPENSO-50'
               WHEN MOD(EA.IDSITTRIB, 100) = 90 THEN 'OUTROS-90'
               WHEN MOD(EA.IDSITTRIB, 100) = 0 THEN 'TRIBUTADO-00'
               WHEN MOD(EA.IDSITTRIB, 100) = 20 THEN 'REDUCAO-20'
               WHEN MOD(EA.IDSITTRIB, 100) = 51 THEN 'DIFERIDO-51'
               WHEN EA.TIPOSITTRIB = 'F' AND MOD(EA.IDSITTRIB, 100) = 60 THEN 'STNORMAL-60'
               WHEN EA.TIPOSITTRIB = 'A' AND MOD(EA.IDSITTRIB, 100) = 60 THEN 'STFRONTEIRA-60'
               ELSE 'OUTRO'
           END AS TIPO
    FROM NOTAS_MOVIMENTO NM
    INNER JOIN DBA.ESTOQUE_ANALITICO EA ON EA.IDEMPRESA = NM.IDEMPRESA AND EA.IDPLANILHA = NM.IDPLANILHA
    INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
    LEFT JOIN DBA.ESTOQUE_ANALITICO_FISCAL EAF ON EAF.IDEMPRESA = EA.IDEMPRESA AND EAF.IDPLANILHA = EA.IDPLANILHA AND EAF.NUMSEQUENCIA = EA.NUMSEQUENCIA
    WHERE OI.FLAGMOVSALDOPRO = 'T' AND EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
),
NOTA_RESUMO AS (
    SELECT IDEMPRESA, IDPLANILHA, IDCLIFOR, COUNT(DISTINCT TIPO) AS QTDTIPOS,
           MAX(CASE WHEN FONTE = 'XML' THEN 1 ELSE 0 END) AS TEM_XML,
           MAX(CASE WHEN FONTE = 'CAD' THEN 1 ELSE 0 END) AS TEM_CAD,
           MAX(CASE WHEN CST IN (40,41,50,90) THEN 1 ELSE 0 END) AS TEM_40415090,
           MAX(CASE WHEN CST NOT IN (40,41,50,90) THEN 1 ELSE 0 END) AS TEM_FORA_40415090
    FROM ITENS
    GROUP BY IDEMPRESA, IDPLANILHA, IDCLIFOR
),
NOTAS_PERFIL AS (
    SELECT NR.*, COALESCE(ATV.FLAGPRODUTORRURAL, 'F') AS PRODUTOR
    FROM NOTA_RESUMO NR
    INNER JOIN DBA.CLIENTE_FORNECEDOR CF ON CF.IDCLIFOR = NR.IDCLIFOR
    LEFT JOIN DBA.ATIVIDADE ATV ON ATV.IDATIVIDADE = CF.IDATIVIDADE
),
CLASSIFICADAS AS (
    SELECT 1 AS CONSULTA, IDEMPRESA, IDPLANILHA FROM NOTAS_PERFIL WHERE PRODUTOR = 'T' AND TEM_CAD=1 AND TEM_XML=0 AND QTDTIPOS=1 AND TEM_40415090=1 AND TEM_FORA_40415090=0
    UNION ALL SELECT 2, IDEMPRESA, IDPLANILHA FROM NOTAS_PERFIL WHERE PRODUTOR = 'T' AND TEM_CAD=1 AND TEM_XML=0 AND QTDTIPOS>1 AND TEM_40415090=1 AND TEM_FORA_40415090=0
    UNION ALL SELECT 3, IDEMPRESA, IDPLANILHA FROM NOTAS_PERFIL WHERE PRODUTOR <> 'T' AND TEM_CAD=1 AND TEM_XML=0 AND QTDTIPOS=1 AND TEM_40415090=1 AND TEM_FORA_40415090=0
    UNION ALL SELECT 4, IDEMPRESA, IDPLANILHA FROM NOTAS_PERFIL WHERE PRODUTOR <> 'T' AND TEM_CAD=1 AND TEM_XML=0 AND QTDTIPOS>1 AND TEM_40415090=1 AND TEM_FORA_40415090=0
    UNION ALL SELECT 5, IDEMPRESA, IDPLANILHA FROM NOTAS_PERFIL WHERE TEM_CAD=1 AND TEM_XML=0 AND QTDTIPOS=1 AND TEM_FORA_40415090=1
    UNION ALL SELECT 6, IDEMPRESA, IDPLANILHA FROM NOTAS_PERFIL WHERE TEM_CAD=1 AND TEM_XML=0 AND QTDTIPOS>1 AND NOT (TEM_40415090=1 AND TEM_FORA_40415090=0)
    UNION ALL SELECT 7, IDEMPRESA, IDPLANILHA FROM NOTAS_PERFIL WHERE TEM_XML=1 AND TEM_CAD=0 AND QTDTIPOS=1 AND TEM_40415090=1 AND TEM_FORA_40415090=0
    UNION ALL SELECT 8, IDEMPRESA, IDPLANILHA FROM NOTAS_PERFIL WHERE TEM_XML=1 AND TEM_CAD=0 AND QTDTIPOS>1 AND TEM_40415090=1 AND TEM_FORA_40415090=0
    UNION ALL SELECT 9, IDEMPRESA, IDPLANILHA FROM NOTAS_PERFIL WHERE TEM_XML=1 AND TEM_CAD=0 AND QTDTIPOS=1 AND TEM_FORA_40415090=1
    UNION ALL SELECT 10, IDEMPRESA, IDPLANILHA FROM NOTAS_PERFIL WHERE TEM_XML=1 AND TEM_CAD=0 AND QTDTIPOS>1 AND NOT (TEM_40415090=1 AND TEM_FORA_40415090=0)
    UNION ALL SELECT 11, IDEMPRESA, IDPLANILHA FROM NOTAS_PERFIL WHERE TEM_XML=1 AND TEM_CAD=1 AND QTDTIPOS=1
    UNION ALL SELECT 12, IDEMPRESA, IDPLANILHA FROM NOTAS_PERFIL WHERE TEM_XML=1 AND TEM_CAD=1 AND QTDTIPOS>1
),
TOTAIS AS (
    SELECT COUNT(*) AS QTDNOTAS_CLASSIFICADAS,
           COUNT(DISTINCT IDEMPRESA || ':' || IDPLANILHA) AS QTDNOTAS_DISTINTAS,
           COUNT(*) - COUNT(DISTINCT IDEMPRESA || ':' || IDPLANILHA) AS DUPLICIDADES
    FROM CLASSIFICADAS
),
BASE AS (
    SELECT COUNT(*) AS QTDNOTAS_BASE FROM NOTAS_MOVIMENTO
)
SELECT B.QTDNOTAS_BASE,
       T.QTDNOTAS_CLASSIFICADAS,
       T.QTDNOTAS_DISTINTAS,
       T.DUPLICIDADES,
       B.QTDNOTAS_BASE - T.QTDNOTAS_DISTINTAS AS DIFERENCA_PARA_BASE,
       CASE WHEN B.QTDNOTAS_BASE = T.QTDNOTAS_DISTINTAS AND T.DUPLICIDADES = 0 THEN 'BATE' ELSE 'NAO BATE' END AS VALIDACAO
FROM BASE B CROSS JOIN TOTAIS T;
