-- Objetos propostos para cache de cenario fiscal do Monitor CissFront.
-- A procedure usa a regra atual como fonte de verdade e materializa o resultado
-- para a consulta SelectProdutosComCenarioFiscal_v3_cache.txt.

CREATE TABLE DBA.PRODUTO_GRADE_CENARIO_FISCAL (
    IDEMPRESA INTEGER NOT NULL,
    IDPRODUTO INTEGER NOT NULL,
    IDSUBPRODUTO INTEGER NOT NULL,
    IDCENARIOFISCAL INTEGER NOT NULL,
    PERICMSAI DECIMAL(16, 4) NOT NULL DEFAULT 0,
    TIPO_ANTECIPACAO INTEGER NOT NULL DEFAULT 0,
    IDSITTRIBSAI INTEGER NOT NULL DEFAULT 0,
    PERREDTRIBSAI DECIMAL(16, 4) NOT NULL DEFAULT 0,
    PERICMECF DECIMAL(16, 4) NOT NULL DEFAULT 0,
    UFORIGEM CHAR(2) NOT NULL DEFAULT '',
    CENFISDTALTERACAO TIMESTAMP NOT NULL DEFAULT '1900-01-01-00.00.00.000000',
    FLAGEVIDENCIAC CHAR(1) NOT NULL DEFAULT 'F',
    ICMS_FCEP DECIMAL(16, 4) NOT NULL DEFAULT 0,
    DTALTERACAO_ORIGEM TIMESTAMP NOT NULL DEFAULT '1900-01-01-00.00.00.000000',
    DTPROCESSAMENTO TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    FLAGVALIDO CHAR(1) NOT NULL DEFAULT 'T',
    CONSTRAINT PK_PROD_GRD_CENFIS PRIMARY KEY (IDEMPRESA, IDPRODUTO, IDSUBPRODUTO)
);

CREATE INDEX DBA.IX_PROD_GRD_CENFIS_01
    ON DBA.PRODUTO_GRADE_CENARIO_FISCAL (IDEMPRESA, IDCENARIOFISCAL);

CREATE INDEX DBA.IX_PROD_GRD_CENFIS_02
    ON DBA.PRODUTO_GRADE_CENARIO_FISCAL (DTALTERACAO_ORIGEM);

CREATE TABLE DBA.MONITORFRONT_CENFIS_PENDENTE (
    IDEMPRESA INTEGER,
    IDPRODUTO INTEGER,
    IDSUBPRODUTO INTEGER,
    DTREFERENCIA TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    ORIGEM VARCHAR(60) NOT NULL,
    DTPROCESSAMENTO TIMESTAMP,
    FLAGPROCESSADO CHAR(1) NOT NULL DEFAULT 'F'
);

CREATE INDEX DBA.IX_MONFRONT_CENFIS_PEND_01
    ON DBA.MONITORFRONT_CENFIS_PENDENTE (FLAGPROCESSADO, DTREFERENCIA);

CREATE PROCEDURE DBA.SP_MONITORFRONT_ATUALIZA_CENFIS (
    IN PI_IDEMPRESA INTEGER,
    IN PI_IDPRODUTO INTEGER,
    IN PI_IDSUBPRODUTO INTEGER,
    IN PI_DTALTERACAO TIMESTAMP
)
LANGUAGE SQL
BEGIN
    MERGE INTO DBA.PRODUTO_GRADE_CENARIO_FISCAL AS DESTINO
    USING (
        WITH BASE AS (
        SELECT
            EMPRESA.IDEMPRESA,
            PG.IDPRODUTO,
            PG.IDSUBPRODUTO,
            PTCV.IDCENARIOFISCAL,
            COALESCE(PTCV.PERICMSAI, 0) AS PERICMSAI,
            COALESCE(PTCV.TIPO_ANTECIPACAO, 0) AS TIPO_ANTECIPACAO,
            COALESCE(PTCV.IDSITTRIBSAI, 0) AS IDSITTRIBSAI,
            COALESCE(PTCV.PERREDTRIBSAI, 0) AS PERREDTRIBSAI,
            COALESCE(PTCV.PERICMECF, 0) AS PERICMECF,
            COALESCE(PTCV.UFORIGEM, '') AS UFORIGEM,
            COALESCE(PTCV.CENFISDTALTERACAO, CAST('1900-01-01 00:00:00' AS TIMESTAMP)) AS CENFISDTALTERACAO,
            COALESCE(PTCV.FLAGEVIDENCIA, 'F') AS FLAGEVIDENCIAC,
            COALESCE(PTCV.PERFCEP, 0) AS ICMS_FCEP,
            COALESCE(
                MAX_COLUMN_TIMESTAMP(
                    MAX_COLUMN_TIMESTAMP(PTCV.CENFISDTALTERACAO, PG.DTALTERACAO),
                    P.DTALTERACAO
                ),
                CAST('1900-01-01 00:00:00' AS TIMESTAMP)
            ) AS DTALTERACAO_ORIGEM,
            ROW_NUMBER() OVER (
                PARTITION BY EMPRESA.IDEMPRESA, PG.IDPRODUTO, PG.IDSUBPRODUTO
                ORDER BY
                    CASE WHEN PTCV.UFORIGEM = EMPRESA.UF THEN 0 ELSE 1 END,
                    COALESCE(PTCV.CENFISDTALTERACAO, CAST('1900-01-01 00:00:00' AS TIMESTAMP)) DESC,
                    PTCV.IDCENARIOFISCAL DESC
            ) AS RN
        FROM
            DBA.EMPRESA EMPRESA
            JOIN DBA.ATIVIDADE_TIPO_ATIVIDADE ATIVIDADE_TIPO_ATIVIDADE ON (
                ATIVIDADE_TIPO_ATIVIDADE.IDATIVIDADE = EMPRESA.IDATIVIDADE AND
                ATIVIDADE_TIPO_ATIVIDADE.FLAGPADRAO = 'T'
            )
            JOIN DBA.CENARIO_FISCAL_PADRAO_PRODUTO_VW CENARIO_FISCAL_PADRAO_PRODUTO_VW ON (
                CENARIO_FISCAL_PADRAO_PRODUTO_VW.IDEMPRESA = EMPRESA.IDEMPRESA AND
                CENARIO_FISCAL_PADRAO_PRODUTO_VW.OPERACAO = 'S' AND
                CENARIO_FISCAL_PADRAO_PRODUTO_VW.IDTIPOOPERACAO = 96 AND
                CENARIO_FISCAL_PADRAO_PRODUTO_VW.UF = EMPRESA.UF
            )
            JOIN DBA.PRODUTO_TRIBUTACAO_CENARIO_VIEW PTCV ON (
                (PTCV.UFORIGEM = EMPRESA.UF OR PTCV.UFORIGEM = '') AND
                PTCV.IDTIPOATIVIDADEORIGEM = ATIVIDADE_TIPO_ATIVIDADE.IDTIPOATIVIDADE AND
                PTCV.IDREGIMEESPECIALORIGEM = EMPRESA.IDREGIMEESPECIAL AND
                PTCV.UFDESTINO = EMPRESA.UF AND
                PTCV.TIPOREGIMETRIBFEDERALORIGEM = EMPRESA.TIPOREGIMETRIBFEDERAL AND
                PTCV.IDORIGEMPRODUTO = CENARIO_FISCAL_PADRAO_PRODUTO_VW.IDORIGEMPRODUTO AND
                PTCV.IDPRODUTO = CENARIO_FISCAL_PADRAO_PRODUTO_VW.IDPRODUTO AND
                PTCV.IDSUBPRODUTO = CENARIO_FISCAL_PADRAO_PRODUTO_VW.IDSUBPRODUTO
            )
            JOIN DBA.PRODUTO_GRADE PG ON (
                PG.IDPRODUTO = PTCV.IDPRODUTO AND
                PG.IDSUBPRODUTO = PTCV.IDSUBPRODUTO
            )
            JOIN DBA.PRODUTO P ON (
                P.IDPRODUTO = PG.IDPRODUTO
            )
        WHERE
            P.TIPOBAIXAMESTRE <> 'C' AND
            (PI_IDEMPRESA IS NULL OR EMPRESA.IDEMPRESA = PI_IDEMPRESA) AND
            (PI_IDPRODUTO IS NULL OR PG.IDPRODUTO = PI_IDPRODUTO) AND
            (PI_IDSUBPRODUTO IS NULL OR PG.IDSUBPRODUTO = PI_IDSUBPRODUTO) AND
            (
                PI_DTALTERACAO IS NULL OR
                PG.DTALTERACAO >= PI_DTALTERACAO OR
                P.DTALTERACAO >= PI_DTALTERACAO OR
                PTCV.CENFISDTALTERACAO >= PI_DTALTERACAO
            )
        )
        SELECT
            IDEMPRESA,
            IDPRODUTO,
            IDSUBPRODUTO,
            IDCENARIOFISCAL,
            PERICMSAI,
            TIPO_ANTECIPACAO,
            IDSITTRIBSAI,
            PERREDTRIBSAI,
            PERICMECF,
            UFORIGEM,
            CENFISDTALTERACAO,
            FLAGEVIDENCIAC,
            ICMS_FCEP,
            DTALTERACAO_ORIGEM
        FROM
            BASE
        WHERE
            RN = 1
    ) AS ORIGEM
    ON (
        DESTINO.IDEMPRESA = ORIGEM.IDEMPRESA AND
        DESTINO.IDPRODUTO = ORIGEM.IDPRODUTO AND
        DESTINO.IDSUBPRODUTO = ORIGEM.IDSUBPRODUTO
    )
    WHEN MATCHED THEN UPDATE SET
        IDCENARIOFISCAL = ORIGEM.IDCENARIOFISCAL,
        PERICMSAI = ORIGEM.PERICMSAI,
        TIPO_ANTECIPACAO = ORIGEM.TIPO_ANTECIPACAO,
        IDSITTRIBSAI = ORIGEM.IDSITTRIBSAI,
        PERREDTRIBSAI = ORIGEM.PERREDTRIBSAI,
        PERICMECF = ORIGEM.PERICMECF,
        UFORIGEM = ORIGEM.UFORIGEM,
        CENFISDTALTERACAO = ORIGEM.CENFISDTALTERACAO,
        FLAGEVIDENCIAC = ORIGEM.FLAGEVIDENCIAC,
        ICMS_FCEP = ORIGEM.ICMS_FCEP,
        DTALTERACAO_ORIGEM = ORIGEM.DTALTERACAO_ORIGEM,
        DTPROCESSAMENTO = CURRENT TIMESTAMP,
        FLAGVALIDO = 'T'
    WHEN NOT MATCHED THEN INSERT (
        IDEMPRESA,
        IDPRODUTO,
        IDSUBPRODUTO,
        IDCENARIOFISCAL,
        PERICMSAI,
        TIPO_ANTECIPACAO,
        IDSITTRIBSAI,
        PERREDTRIBSAI,
        PERICMECF,
        UFORIGEM,
        CENFISDTALTERACAO,
        FLAGEVIDENCIAC,
        ICMS_FCEP,
        DTALTERACAO_ORIGEM,
        DTPROCESSAMENTO,
        FLAGVALIDO
    ) VALUES (
        ORIGEM.IDEMPRESA,
        ORIGEM.IDPRODUTO,
        ORIGEM.IDSUBPRODUTO,
        ORIGEM.IDCENARIOFISCAL,
        ORIGEM.PERICMSAI,
        ORIGEM.TIPO_ANTECIPACAO,
        ORIGEM.IDSITTRIBSAI,
        ORIGEM.PERREDTRIBSAI,
        ORIGEM.PERICMECF,
        ORIGEM.UFORIGEM,
        ORIGEM.CENFISDTALTERACAO,
        ORIGEM.FLAGEVIDENCIAC,
        ORIGEM.ICMS_FCEP,
        ORIGEM.DTALTERACAO_ORIGEM,
        CURRENT TIMESTAMP,
        'T'
    );
END;

-- Para invalidacao automatica, registre pendencias em MONITORFRONT_CENFIS_PENDENTE
-- quando houver alteracao em produto, grade, empresa ou nas tabelas base dos cenarios.
-- A rotina agendada deve ler a fila e chamar SP_MONITORFRONT_ATUALIZA_CENFIS
-- passando chaves especificas sempre que possivel.
