SELECT 
	TMP.CONT,
	TMP.IDCTACONTABIL,
	TMP.IDPLANILHA,
	TMP.TIPONATUREZALCTO,
	TMP.VALCREDITO+TMP.VALDEBITO AS VALCONTABIL,
	TMP.ORIGEMMOVIMENTO,
	TMP.DTPAGAMENTO,
	TMP.IDEMPRESA,
	TMP.TIPONATUREZACTA,
	TMP.COMPLEMENTO,
	TMP.FLAGAGRUPADO,
	TMP.IDUSUARIO,
	TMP.IDCAIXA,
	TMP.IDRECEBIMENTO,
	TMP.IDABERTURA,
	EST.IDDREGRUPO
FROM (
	SELECT
	    DISTINCT
	    1 AS CONT,
	    CP.IDCTACONTABILCONTRAPARTIDA AS IDCTACONTABIL,
	    CPB.IDPLANILHA,
	    CP.IDPLANILHA AS IDPLANILHA2,
	    'D' TIPONATUREZALCTO,
	    0 AS VALCREDITO,
	    CPB.VALPAGAMENTOTITULO+CPB.VALDESCCONCEDIDOTITULO AS VALDEBITO,
	    CPB.ORIGEMMOVIMENTO,
	    CPB.DTPAGAMENTO AS DTPAGAMENTO,
	    CPB.IDEMPRESABAIXA AS IDEMPRESA,
	    CPN.TIPONATUREZA AS TIPONATUREZACTA,
	    CAST(COALESCE((  SELECT
	                COMPLEMENTO
	            FROM
	                CONTABIL_MOVIMENTO CM
	            WHERE
	                CM.IDCTACONTABIL = CP.IDCTACONTABIL AND
	                CM.IDPLANILHA = CP.IDPLANILHA AND
	                CM.IDEMPRESA = CP.IDEMPRESA
	            FETCH FIRST 1 ROW ONLY),CP.OBSTITULO) AS VARCHAR(32000)) AS COMPLEMENTO,
	    U.NOMEUSUARIO,
	    CPC.DESCRCTACONTABIL,
	    CP.FLAGAGRUPADO,
	    U.IDUSUARIO,
	    0 AS IDCAIXA,
	    CP.IDPAGAMENTO AS IDRECEBIMENTO,
	    0 AS IDABERTURA,
	    CPB.IDTITULO,
	    CPB.DIGITOTITULO,
	    CP.IDCTACONTABIL AS IDCTACONTABIL1,
	    CONTABIL.DTALTERACAO
	FROM
	    CONTAS_PAGAR_BAIXAS CPB
	JOIN 
		CONTAS_PAGAR CP ON
	        CP.IDEMPRESA = CPB.IDEMPRESA AND
	        CP.IDCLIFOR = CPB.IDCLIFOR AND
	        CP.IDTITULO = CPB.IDTITULO AND
	        CP.DIGITOTITULO = CPB.DIGITOTITULO AND
	        CP.SERIENOTA = CPB.SERIENOTA
	JOIN 
		CONTABIL_PLANO_CONTAS CPN ON
	        CP.IDCTACONTABIL = CPN.IDCTACONTABIL
	JOIN 
		CONTABIL_PLANO_CONTAS CPC ON
	        CP.IDCTACONTABILCONTRAPARTIDA = CPC.IDCTACONTABIL
	JOIN 
		USUARIO U ON 
			CP.IDUSUARIO = U.IDUSUARIO
	LEFT JOIN 
		NOTAS_ENTRADA_SAIDA NES ON
	        NES.IDPLANILHA = CP.IDPLANILHA AND
	        NES.IDEMPRESA = CP.IDEMPRESA
	LEFT JOIN LATERAL (
        SELECT
                COMPLEMENTO,
                TIPONATUREZALCTO,
                IDPLANILHA,
                CM.DTHORAULTIMAALTERACAO AS DTALTERACAO
            FROM
                CONTABIL_MOVIMENTO CM
            WHERE
                CM.IDCTACONTABIL = CP.IDCTACONTABIL AND
                CM.IDPLANILHA = CPB.IDPLANILHA AND
                CM.IDEMPRESA = CP.IDEMPRESA
            ORDER BY
            	CM.DTHORAULTIMAALTERACAO DESC
            FETCH FIRST 1 ROW ONLY
	    ) AS CONTABIL ON 
	    	1 = 1
	WHERE
	    CPB.DTPAGAMENTO BETWEEN :RA_DTINI AND :RA_DTFIM AND
	    CPB.IDEMPRESABAIXA IN (:RA_IDEMPRESA) AND
	    --NOT CP.IDCTACONTABILCONTRAPARTIDA  IS NULL AND
	    (CPB.IDPLANILHA IN (:RA_IDPLANILHAS) OR (:RA_IDPLANILHAS) IN (0)) AND
	    (EXISTS (
	    	SELECT 
	    		1 
	    	FROM 
	    		CONTABIL_MOVIMENTO CM2 
	    	WHERE 
	    		CM2.IDEMPRESA = CPB.IDEMPRESABAIXA AND 
	    		CM2.IDPLANILHA = CPB.IDPLANILHA  AND 
	    		EXISTS (
	    			SELECT 
	    				0 
	    			FROM 
	    				DRE_CAIXA_CONTAS_BASE DCCB 
	    			WHERE 
	    				DCCB.IDCTACONTABIL = CM2.IDCTACONTABIL  
	    			)
	    	) OR
	    EXISTS (
	    	SELECT 
	    		0 
	    	FROM 
	    		CONTAS_RECEBER_BAIXAS CRB 
	    	WHERE 
	    		CRB.IDPLANILHA = CPB.IDPLANILHA
	    	) OR
	    EXISTS (
	    	SELECT 
	    		0 
	    	FROM 
	    		ADIANTAMENTO_BAIXA AB 
	    	WHERE 
	    		AB.IDPLANILHA = CPB.IDPLANILHA
	    	) OR
	    (EXISTS (
			SELECT
				0
			FROM
				DBA.CONTAS_PAGAR_BAIXAS CPBX
			WHERE
				CPBX.IDPLANILHA = CPB.IDPLANILHA) AND 
		EXISTS (
			SELECT
				0
			FROM
				DBA.CHEQUES_MOVIMENTO CHE
			WHERE
				CHE.IDPLANILHA = CPB.IDPLANILHA))
	   	) AND
	    NOT EXISTS (
	    	SELECT 
	    		0 
	    	FROM 
	    		CONTAS_PAGAR AGR 
	    	WHERE 
	    		AGR.IDPLANILHA = CPB.IDPLANILHA
	    	)
	
	UNION ALL
	
	SELECT
	    /*DISTINCT*/
	    2 AS CONT,
	    CP.IDCTACONTABILCONTRAPARTIDA AS IDCTACONTABIL,
	    CPB.IDPLANILHA,
	    CP.IDPLANILHA AS IDPLANILHA2,
	    'C' TIPONATUREZALCTO,
	    ROUND(COALESCE(CPBDET.VALRECEBIMENTO, CPB.VALPAGAMENTOTITULO)+
	    CASE 
		    WHEN COALESCE(CPBDET.VALRECEBIMENTO,0) = 0 THEN 
		    	CPB.VALDESCCONCEDIDOTITULO 
		    ELSE 
		    	CASE 
					WHEN CPB.ORIGEMMOVIMENTO = 'CAI' OR (CPB.ORIGEMMOVIMENTO = 'FRE' AND CPB.SERIENOTA = 'PDV') THEN 
						(CPBDET.VALRECEBIMENTO*(CPB.VALDESCCONCEDIDOTITULO/(CPB.VALPAGAMENTOTITULO)))
					ELSE
						0
				END
		END -
		CASE
			WHEN (SELECT COUNT(0) FROM CONTAS_RECEBER_BAIXAS_DETALHES CRBD WHERE CRBD.IDEMPRESA = CPB.IDEMPRESA AND CRBD.IDPLANILHA = CPB.IDPLANILHA) > 1 THEN
				(CPBDET.VALRECEBIMENTO*(CPB.VALJUROSCOBRADO/(CPB.VALPAGAMENTOTITULO)))
			ELSE
				0
		END,2)  AS VALCREDITO,
	    0 AS VALDEBITO,
	    CPB.ORIGEMMOVIMENTO,
	    CPB.DTPAGAMENTO AS DTPAGAMENTO,
	    CPB.IDEMPRESABAIXA AS IDEMPRESA,
	    CPN.TIPONATUREZA AS TIPONATUREZACTA,
	    CAST(COALESCE((  SELECT
	                COMPLEMENTO
	            FROM
	                CONTABIL_MOVIMENTO CM
	            WHERE
	                CM.IDCTACONTABIL = CP.IDCTACONTABIL AND
	                CM.IDPLANILHA = CP.IDPLANILHA AND
	                CM.IDEMPRESA = CP.IDEMPRESA
	            FETCH FIRST 1 ROW ONLY),CP.OBSTITULO) AS VARCHAR(32000)) AS COMPLEMENTO,
	    U.NOMEUSUARIO,
	    CPC.DESCRCTACONTABIL,
	    CP.FLAGAGRUPADO,
	    U.IDUSUARIO,
	    0 AS IDCAIXA,
	    CP.IDRECEBIMENTO AS IDRECEBIMENTO,
	    0 AS IDABERTURA,
	    CPB.IDTITULO,
	    CPB.DIGITOTITULO,
	    CP.IDCTACONTABIL AS IDCTACONTABIL1,
	    CONTABIL.DTALTERACAO
	FROM	
	    CONTAS_RECEBER_BAIXAS CPB
    LEFT 
    	JOIN CONTAS_RECEBER_BAIXAS_DETALHES CPBDET ON
	        CPBDET.IDEMPRESA = CPB.IDEMPRESA AND
	        CPBDET.IDCLIFOR = CPB.IDCLIFOR AND
	        CPBDET.IDTITULO = CPB.IDTITULO AND
	        CPBDET.DIGITOTITULO = CPB.DIGITOTITULO AND
	        CPBDET.SERIENOTA = CPB.SERIENOTA AND
	        CPBDET.IDPLANILHA = CPB.IDPLANILHA
    JOIN 
    	CONTAS_RECEBER CP ON
	        CP.IDEMPRESA = CPB.IDEMPRESA AND
	        CP.IDCLIFOR = CPB.IDCLIFOR AND
	        CP.IDTITULO = CPB.IDTITULO AND
	        CP.DIGITOTITULO = CPB.DIGITOTITULO AND
	        CP.SERIENOTA = CPB.SERIENOTA
    JOIN 
    	CONTABIL_PLANO_CONTAS CPN ON
        	CP.IDCTACONTABIL = CPN.IDCTACONTABIL
    JOIN 
    	CONTABIL_PLANO_CONTAS CPC ON
        	CP.IDCTACONTABILCONTRAPARTIDA = CPC.IDCTACONTABIL
    JOIN 
    	USUARIO U ON 
    		CP.IDUSUARIO = U.IDUSUARIO
    LEFT JOIN 
    	NOTAS_ENTRADA_SAIDA NES ON
	        NES.IDPLANILHA = CP.IDPLANILHA AND
	        NES.IDEMPRESA = CP.IDEMPRESA
	LEFT JOIN
		CONFIG_SAIDA CS ON
			CS.IDEMPRESA = CPB.IDEMPRESA
    LEFT JOIN LATERAL
    (
        SELECT
            COMPLEMENTO,
            TIPONATUREZALCTO,
            IDPLANILHA,
            CM.DTHORAULTIMAALTERACAO AS DTALTERACAO
        FROM
            CONTABIL_MOVIMENTO CM
        WHERE
            CM.IDCTACONTABIL = CP.IDCTACONTABIL AND
            CM.IDPLANILHA = CPB.IDPLANILHA AND
            CM.IDEMPRESA = CP.IDEMPRESA
        ORDER BY 
        	CM.DTHORAULTIMAALTERACAO DESC
        FETCH FIRST 1 ROW ONLY
    ) AS CONTABIL ON 1 = 1
	WHERE
	    CPB.DTPAGAMENTO BETWEEN :RA_DTINI AND :RA_DTFIM AND
	    (CPB.IDEMPRESABAIXA IN (:RA_IDEMPRESA) OR
	    EXISTS (
	    	SELECT 
	    		1 
	    	FROM 
	    		CONTABIL_MOVIMENTO CM2 
	    	WHERE 
	    		CM2.IDEMPRESA IN (:RA_IDEMPRESA) AND 
	    		CM2.IDPLANILHA = CPB.IDPLANILHA AND 
	    		EXISTS (
	    			SELECT 
	    				0 
	    			FROM 
	    				DRE_CAIXA_CONTAS_BASE dccb 
	    			WHERE
	    				DCCB.IDCTACONTABIL = CM2.IDCTACONTABIL
	    			)
	    	) 
	    ) AND
	    CP.IDCTACONTABILCONTRAPARTIDA IS NOT NULL AND
	    (CPB.IDPLANILHA IN (:RA_IDPLANILHAS) OR (:RA_IDPLANILHAS) IN (0)) AND
	    (EXISTS (
	    	SELECT 
	    		1 
	    	FROM 
	    		CONTABIL_MOVIMENTO CM3 
	    	WHERE 
	    		CM3.IDEMPRESA = CPB.IDEMPRESABAIXA AND 
	    		CM3.IDPLANILHA = CPB.IDPLANILHA AND 
	    		EXISTS (
	    			SELECT 
	    				0
	    			FROM 
	    				DRE_CAIXA_CONTAS_BASE dccb 
	    			WHERE
	    				DCCB.IDCTACONTABIL = CM3.IDCTACONTABIL
	    			)
	    	) OR
	    EXISTS (
	    	SELECT 
	    		0 
	    	FROM 
	    		CONTAS_PAGAR_BAIXAS CRB 
	    	WHERE 
	    		CRB.IDPLANILHA = CPB.IDPLANILHA
	    	) OR
	    EXISTS (
	    	SELECT 
	    		0 
	    	FROM 
	    		ADIANTAMENTO_BAIXA AB 
	    	WHERE 
	    		AB.IDPLANILHA = CPB.IDPLANILHA
	    	) OR
	    EXISTS (
	    	SELECT 
	    		1 
	    	FROM 
	    		CONTABIL_MOVIMENTO CM4 
	    	WHERE 
	    		CM4.IDEMPRESA IN (:RA_IDEMPRESA) AND 
	    		CM4.IDPLANILHA = CPB.IDPLANILHA AND 
	    		EXISTS (
	    			SELECT 
	    				0 
	    			FROM 
	    				DRE_CAIXA_CONTAS_BASE dccb 
	    			WHERE
	    				DCCB.IDCTACONTABIL = CM4.IDCTACONTABIL
	    			)
	    	)
	    ) AND
	    NOT EXISTS (
	    	SELECT
	    		0
	    	FROM
	    		CONTAS_RECEBER CR 
	    	WHERE 
	    		CR.IDEMPRESA = CPBDET.IDEMPRESA AND
	    		CR.IDPLANILHA = CPBDET.IDPLANILHA AND 
	    		(CR.VALTITULO = CPBDET.VALRECEBIMENTO OR
	    		CR.IDRECEBIMENTO = CPBDET.IDRECEBIMENTO) AND
	    		CR.IDTITULO <> CPBDET.IDTITULO
	    	) AND
	    NOT EXISTS (
	    	SELECT
	    		0
	    	FROM
	    		DBA.CHEQUES_MOVIMENTO CHE 
	    	JOIN
	    		DBA.FORMA_PAGREC FP ON
	    			FP.IDRECEBIMENTO = CPBDET.IDRECEBIMENTO
	    	WHERE 
	    		CHE.IDEMPRESA = CPBDET.IDEMPRESA AND
	    		CHE.IDPLANILHA = CPBDET.IDPLANILHA AND 
	    		FP.FLAGCHEQUE = 'T'
	    	) AND
	    NOT EXISTS (
	    	SELECT
	    		0
	    	FROM
	    		DBA.CONTAS_RECEBER CRCHE
	    	JOIN
	    		DBA.FORMA_PAGREC FP ON
	    			FP.IDRECEBIMENTO = CP.IDRECEBIMENTO
	    	WHERE 
	    		CRCHE.IDEMPRESA = CPB.IDEMPRESA AND
	    		CRCHE.IDPLANILHA = CPB.IDPLANILHA AND 
	    		FP.FLAGCHEQUE = 'T'
	    	)
	
	UNION ALL
	/*juros e desconto*/
	SELECT
	    DISTINCT
	    3 AS CONT,
	    CM.IDCTACONTABIL AS IDCTACONTABIL,
	    CM.IDPLANILHA,
	    CM.IDPLANILHA AS IDPLANILHA2,
	    CM.TIPONATUREZALCTO AS TIPONATUREZALCTO,
	    CASE WHEN CM.TIPONATUREZALCTO = 'C' THEN CASE WHEN CTAVALIDA.IDCTAVALIDA IS NOT NULL AND COALESCE(TMPFATORJURO.FATOR,0) <> 0 THEN ROUND(CM.VALLANCAMENTO*COALESCE(TMPFATORJURO.FATOR,0),2)-COALESCE(CHE.VALCHEQUE,0) ELSE CM.VALLANCAMENTO-COALESCE(CHE.VALCHEQUE,0) END ELSE 0 END AS VALCREDITO,
	    CASE WHEN CM.TIPONATUREZALCTO = 'D' THEN CASE WHEN CTAVALIDA.IDCTAVALIDA IS NOT NULL AND COALESCE(TMPFATORJURO.FATOR,0) <> 0 THEN ROUND(CM.VALLANCAMENTO*COALESCE(TMPFATORJURO.FATOR,0),2)-COALESCE(CHE.VALCHEQUE,0) ELSE CM.VALLANCAMENTO-COALESCE(CHE.VALCHEQUE,0) END ELSE 0 END AS VALDEBITO,
	    CM.ORIGEMMOVIMENTO,
	    CM.DTMOVIMENTO AS DTPAGAMENTO,
	    CM.IDEMPRESA AS IDEMPRESA,
	    CM.TIPONATUREZACTA AS TIPONATUREZACTA,
	    CAST(CM.COMPLEMENTO AS VARCHAR(32000)) AS COMPLEMENTO,
	    U.NOMEUSUARIO,
	    CPN.DESCRCTACONTABIL,
	    'F' AS FLAGAGRUPADO,
	    U.IDUSUARIO,
	    0 AS IDCAIXA,
	    NULL AS IDRECEBIMENTO,
	    0 AS IDABERTURA,
	    NULL AS IDTITULO,
	    NULL AS DIGITOTITULO,
	    CM.IDCTACONTABIL AS IDCTACONTABIL1,
	    CM.DTHORAULTIMAALTERACAO AS DTALTERACAO
	FROM
	    CONTABIL_MOVIMENTO CM
	JOIN
		USUARIO U ON
			U.IDUSUARIO = CM.IDUSUARIO
	JOIN
		CONTABIL_PLANO_CONTAS CPN ON
	        CPN.IDCTACONTABIL = CM.IDCTACONTABIL
	LEFT JOIN  (
		SELECT
        	IDEMPRESA,
         	IDCTAJUROSCOB AS IDCTAVALIDA
        FROM
			DBA.CONFIG_CAIXA
        UNION ALL
        SELECT
			IDEMPRESA,
            IDCTADESCCONCEDIDOS AS IDCTAVALIDA
        FROM
            DBA.CONFIG_CAIXA
        UNION ALL
        SELECT
            IDEMPRESA,
            IDCTAJUROSPAGOS AS IDCTAVALIDA
        FROM
            DBA.CONFIG_CAIXA
        UNION ALL
        SELECT
            IDEMPRESA,
            IDCTADESCOBTIDOS AS IDCTAVALIDA
        FROM
            DBA.CONFIG_CAIXA
        ) CTAVALIDA (IDEMPRESA, IDCTAVALIDA) ON
            CTAVALIDA.IDEMPRESA = CM.IDEMPRESA AND
            CTAVALIDA.IDCTAVALIDA = CM.IDCTACONTABIL
    LEFT JOIN (
		SELECT 
    		DISTINCT 
    		IDCTACONTABILDESPESA 
    	FROM 
    		ADMINISTRADORAS_BANDEIRA 
    	WHERE 
    		IDCTACONTABILDESPESA IS NOT NULL
    	UNION ALL
    	SELECT 
    		DISTINCT 
    		IDCTATAXAADM 
    	FROM 
    		CLW_PRODUTOS_BANDEIRA 
    	WHERE 
    		IDCTATAXAADM IS NOT NULL
    	) AS TAXAADM (IDCTATAXAADM) ON 
    		TAXAADM.IDCTATAXAADM = CM.IDCTACONTABIL
    LEFT JOIN (
    	SELECT 
    		IDCTACONTABIL 
    	FROM 
    		CONTABIL_PLANO_CONTAS
    	WHERE 
    		TIPONATUREZA = 'D' AND 
    		CODIGONATUREZA = '04' AND 
    		TIPOCTACONTABIL = 'A'
    	) AS DESPESA (IDCTADESPESA) ON 
			DESPESA.IDCTADESPESA = CM.IDCTACONTABIL
	LEFT JOIN LATERAL (
		SELECT
			IDPLANILHA,
			SUM(VALOR) AS VALCHEQUE
		FROM
			CHEQUES_MOVIMENTO CHE
		WHERE
			CHE.IDPLANILHA = CM.IDPLANILHA AND
			CHE.TIPOSITUACAO = 'L'
		GROUP BY 
			CHE.IDPLANILHA
		) CHE ON
			CHE.IDPLANILHA = CM.IDPLANILHA AND
			CM.TIPOABAMOVIMENTO = 2		
	LEFT JOIN LATERAL (
		SELECT
			IDEMPRESA,
			IDPLANILHA,
			CAST(VALORDETALHE AS NUMERIC(15,6))/CAST(TOTALDETALHE AS NUMERIC(15,6)) FATOR
		FROM LATERAL (	
			SELECT
				CPB.IDEMPRESA, 
				CPB.IDPLANILHA,
				SUM(CPBDET.VALRECEBIMENTO) VALORDETALHE,
				(SELECT 
					SUM(VALRECEBIMENTO)
				FROM
					DBA.CONTAS_RECEBER_BAIXAS_DETALHES DET
				WHERE
					DET.IDEMPRESA = CPB.IDEMPRESA AND
					DET.IDPLANILHA = CPB.IDPLANILHA
				) TOTALDETALHE
			FROM
			    CONTAS_RECEBER_BAIXAS CPB
		    LEFT 
		    	JOIN CONTAS_RECEBER_BAIXAS_DETALHES CPBDET ON
			        CPBDET.IDEMPRESA = CPB.IDEMPRESA AND
			        CPBDET.IDCLIFOR = CPB.IDCLIFOR AND
			        CPBDET.IDTITULO = CPB.IDTITULO AND
			        CPBDET.DIGITOTITULO = CPB.DIGITOTITULO AND
			        CPBDET.SERIENOTA = CPB.SERIENOTA AND
			        CPBDET.IDPLANILHA = CPB.IDPLANILHA
		    JOIN 
		    	FORMA_PAGREC FP ON
			        FP.IDRECEBIMENTO = CPBDET.IDRECEBIMENTO AND
			        FP.FLAGCARTAOCREDITO = 'F' AND FP.FLAGCHEQUE = 'F'
			WHERE
				CPB.IDPLANILHA = CM.IDPLANILHA
			GROUP BY 
				CPB.IDEMPRESA,
				CPB.IDPLANILHA
			)
		) TMPFATORJURO (IDEMPRESA, IDPLANILHA, FATOR) ON
			TMPFATORJURO.IDEMPRESA = CM.IDEMPRESA AND
			TMPFATORJURO.IDPLANILHA = CM.IDPLANILHA
	WHERE
	    CM.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM AND
	    CM.IDEMPRESA IN (:RA_IDEMPRESA) AND
	    (CM.IDPLANILHA IN (:RA_IDPLANILHAS) OR (:RA_IDPLANILHAS) IN (0)) AND
	    (CTAVALIDA.IDCTAVALIDA IS NOT NULL OR TAXAADM.IDCTATAXAADM IS NOT NULL OR 
	    (DESPESA.IDCTADESPESA IS NOT NULL AND
	    NOT EXISTS (
	    	SELECT
				0
			FROM
				DBA.CONTAS_PAGAR_BAIXAS CPBX2
			WHERE
				CPBX2.IDPLANILHA = CM.IDPLANILHA))) AND
	    (EXISTS (
	    	SELECT 
	    		1 
	    	FROM 
	    		CONTABIL_MOVIMENTO CM2 
	    	WHERE 
	    		CM2.IDEMPRESA = CM.IDEMPRESA AND 
	    		CM2.IDPLANILHA = CM.IDPLANILHA AND 
	    		IDCTACONTABIL IN (SELECT IDCTACONTABIL FROM DRE_CAIXA_CONTAS_BASE dccb )) OR
	    EXISTS (
	    	SELECT 
	    		1 
	    	FROM 
	    		CONTABIL_MOVIMENTO CM5 
	    	WHERE 
	    		CM5.IDEMPRESA <> CM.IDEMPRESA AND 
	    		CM5.IDPLANILHA = CM.IDPLANILHA AND 
	    		IDCTACONTABIL IN (SELECT IDCTACONTABIL FROM DRE_CAIXA_CONTAS_BASE dccb )
	    	) OR
	    EXISTS (
	    	SELECT 
	    		1 
	    	FROM 
	    		CONTABIL_MOVIMENTO CM6
	    	JOIN
	    		CONTABIL_INTEGRACAO CI ON 
	    			CI.IDEMPRESA <> CM6.IDEMPRESA AND
	    			CI.IDPLANILHA = CM6.IDPLANILHA AND
	    			CI.IDEMPRESADESTINO = CM.IDEMPRESA AND
	    			CI.IDPLANILHADESTINO = CM.IDPLANILHA AND
	    			CI.IDCTACONTABIL = CM.IDCTACONTABIL
	    	) OR
	    EXISTS (
	    	SELECT 
	    		1 
	    	FROM 
	    		CONTABIL_MOVIMENTO CM3 
	    	JOIN 
	    		CONTABIL_INTEGRACAO CI ON 
	    			CI.IDCTACONTABIL = CM3.IDCTACONTABIL AND 
	    			CI.IDEMPRESADESTINO = CM3.IDEMPRESA AND 
	    			CI.IDPLANILHADESTINO = CM3.IDPLANILHA AND 
	    			CI.TIPONATUREZALCTO = CM3.TIPONATUREZALCTO 
	    	JOIN
	    		CONTABIL_MOVIMENTO CM4 ON
	    			CM4.IDPLANILHA = CI.IDPLANILHA
	    	WHERE 
	    		CM3.IDEMPRESA = CM.IDEMPRESA AND 
	    		CM3.IDPLANILHA = CM.IDPLANILHA AND 
	    		CM4.IDCTACONTABIL IN (SELECT IDCTACONTABIL FROM DRE_CAIXA_CONTAS_BASE dccb )) OR
		(EXISTS (
			SELECT
				0
			FROM
				DBA.CONTAS_RECEBER_BAIXAS CRBX
			WHERE
				CRBX.IDPLANILHA = CM.IDPLANILHA) AND 
		EXISTS (
			SELECT
				0
			FROM
				DBA.CONTAS_PAGAR_BAIXAS CPBX
			WHERE
				CPBX.IDPLANILHA = CM.IDPLANILHA)) OR
		(EXISTS (
			SELECT
				0
			FROM
				DBA.CONTAS_RECEBER_BAIXAS CRBX
			WHERE
				CRBX.IDPLANILHA = CM.IDPLANILHA) AND 
		EXISTS (
			SELECT
				0
			FROM
				DBA.ADIANTAMENTO_BAIXA AB
			WHERE
				AB.IDPLANILHA = CM.IDPLANILHA)) OR
		(EXISTS (
			SELECT
				0
			FROM
				DBA.CONTAS_PAGAR_BAIXAS CPBX
			WHERE
				CPBX.IDPLANILHA = CM.IDPLANILHA) AND 
		EXISTS (
			SELECT
				0
			FROM
				DBA.ADIANTAMENTO_BAIXA AB
			WHERE
				AB.IDPLANILHA = CM.IDPLANILHA)) OR
		(EXISTS (
			SELECT
				0
			FROM
				DBA.CONTAS_PAGAR_BAIXAS CPBX
			WHERE
				CPBX.IDPLANILHA = CM.IDPLANILHA) AND 
		EXISTS (
			SELECT
				0
			FROM
				DBA.CHEQUES_MOVIMENTO CHE
			WHERE
				CHE.IDPLANILHA = CM.IDPLANILHA)))
	
	UNION ALL
	
	SELECT
	    DISTINCT
	    4 AS CONT,
	    CM.IDCTACONTABIL AS IDCTACONTABIL,
	    CM.IDPLANILHA,
	    CM.IDPLANILHA AS IDPLANILHA2,
	    CM.TIPONATUREZALCTO AS TIPONATUREZALCTO,
	    CASE WHEN CM.TIPONATUREZALCTO = 'C' THEN CM.VALLANCAMENTO ELSE 0 END AS VALCREDITO,
	    CASE WHEN CM.TIPONATUREZALCTO = 'D' THEN CM.VALLANCAMENTO ELSE 0 END AS VALDEBITO,
	    CM.ORIGEMMOVIMENTO,
	    CM.DTMOVIMENTO AS DTPAGAMENTO,
	    CM.IDEMPRESA AS IDEMPRESA,
	    CM.TIPONATUREZACTA AS TIPONATUREZACTA,
	    CAST(CM.COMPLEMENTO AS VARCHAR(32000)) AS COMPLEMENTO,
	    U.NOMEUSUARIO,
	    CPN.DESCRCTACONTABIL,
	    'F' AS FLAGAGRUPADO,
	    U.IDUSUARIO,
	    0 AS IDCAIXA,
	    NULL AS IDRECEBIMENTO,
	    0 AS IDABERTURA,
	    NULL AS IDTITULO,
	    NULL AS DIGITOTITULO,
	    CM.IDCTACONTABIL AS IDCTACONTABIL1,
	   	CM.DTHORAULTIMAALTERACAO AS DTALTERACAO
	FROM
	    CONTABIL_MOVIMENTO CM
	JOIN
        USUARIO U ON
            U.IDUSUARIO = CM.IDUSUARIO
	JOIN
        CONTABIL_PLANO_CONTAS CPN ON
        	CPN.IDCTACONTABIL = CM.IDCTACONTABIL
	LEFT JOIN  (
        SELECT
            IDEMPRESA,
            IDCTAJUROSCOB AS IDCTAVALIDA
        FROM
            DBA.CONFIG_CAIXA
        UNION ALL
        SELECT
            IDEMPRESA,
            IDCTADESCCONCEDIDOS AS IDCTAVALIDA
        FROM
            DBA.CONFIG_CAIXA
        UNION ALL
        SELECT
            IDEMPRESA,
            IDCTAJUROSPAGOS AS IDCTAVALIDA
        FROM
            DBA.CONFIG_CAIXA
        UNION ALL
        SELECT
            IDEMPRESA,
            IDCTADESCOBTIDOS AS IDCTAVALIDA
        FROM
            DBA.CONFIG_CAIXA
        ) CTAVALIDA (IDEMPRESA, IDCTAVALIDA) ON
            CTAVALIDA.IDEMPRESA = CM.IDEMPRESA AND
            CTAVALIDA.IDCTAVALIDA = CM.IDCTACONTABIL
    LEFT JOIN (
    	SELECT 
    		IDCTACREDITO 
    	FROM 
    		CONFIG_INTEGRACAO_CONTABIL
    	UNION ALL
    	SELECT 
    		IDCTADEBITO 
    	FROM 
    		CONFIG_INTEGRACAO_CONTABIL
    	) AS NUMERARIOS (IDCTANUMERARIOS) ON
			NUMERARIOS.IDCTANUMERARIOS = CM.IDCTACONTABIL
    LEFT JOIN (
    	SELECT 
    		DISTINCT 
    		IDCTACONTABILDESPESA 
    	FROM 
    		ADMINISTRADORAS_BANDEIRA 
    	WHERE 
    		IDCTACONTABILDESPESA IS NOT NULL
		UNION ALL
    	SELECT 
    		DISTINCT 
    		IDCTATAXAADM 
    	FROM 
    		CLW_PRODUTOS_BANDEIRA 
    	WHERE 
    		IDCTATAXAADM IS NOT NULL
    	) AS TAXAADM (IDCTATAXAADM) ON 
    		TAXAADM.IDCTATAXAADM = CM.IDCTACONTABIL
    LEFT JOIN (
    	SELECT 
    		IDCTACONTABIL 
    	FROM 
    		CONTABIL_PLANO_CONTAS
    	WHERE 
    		TIPONATUREZA = 'D' AND 
    		CODIGONATUREZA = '04' AND 
    		TIPOCTACONTABIL = 'A'
    	) AS DESPESA (IDCTADESPESA) ON 
    		DESPESA.IDCTADESPESA = CM.IDCTACONTABIL
	WHERE
	    CM.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM AND
	    CM.IDEMPRESA IN (:RA_IDEMPRESA) AND
        (CM.IDPLANILHA IN (:RA_IDPLANILHAS) OR (:RA_IDPLANILHAS) IN (0)) AND
        CTAVALIDA.IDCTAVALIDA IS NULL AND
        NUMERARIOS.IDCTANUMERARIOS IS NULL AND TAXAADM.IDCTATAXAADM IS NULL AND DESPESA.IDCTADESPESA IS NULL AND
	    (EXISTS (
	    	SELECT 
	    		1 
	    	FROM 
	    		CONTABIL_MOVIMENTO CM2 
	    	WHERE 
	    		CM2.IDEMPRESA = CM.IDEMPRESA AND 
	    		CM2.IDPLANILHA = CM.IDPLANILHA AND 
	    		EXISTS (
	    			SELECT 
	    				0 
	    			FROM 
	    				DRE_CAIXA_CONTAS_BASE dccb 
	    			WHERE 
	    				DCCB.IDCTACONTABIL = CM2.IDCTACONTABIL
	    			)
	    	) OR 
	    EXISTS (
	    	SELECT 
	    		1 
	    	FROM 
	    		CONTABIL_MOVIMENTO CM5 
	    	WHERE 
	    		CM5.IDEMPRESA <> CM.IDEMPRESA AND 
	    		CM5.IDPLANILHA = CM.IDPLANILHA AND 
	    		IDCTACONTABIL IN (SELECT IDCTACONTABIL FROM DRE_CAIXA_CONTAS_BASE dccb ) AND
	    		EXISTS (SELECT 0 FROM CLW_AJUSTES_CONTABIL_MOVIMENTO CLW WHERE CLW.IDPLANILHA = CM5.IDPLANILHA)
	    	)) AND
	    NOT EXISTS (
	    	SELECT 
	    		0 
	    	FROM 
	    		DRE_CAIXA_CONTAS_BASE dccb 
	    	WHERE 
	    		DCCB.IDCTACONTABIL = CM.IDCTACONTABIL
	    	) AND
	    NOT EXISTS (
	    	SELECT 
	    		0 
	    	FROM 
	    		CONTAS_RECEBER_BAIXAS CRB 
	    	WHERE 
	    		CRB.IDEMPRESABAIXA = CM.IDEMPRESA AND 
	    		CRB.IDPLANILHA = CM.IDPLANILHA
	    	) AND
	    NOT EXISTS (
	    	SELECT 
	    		0 
	    	FROM 
	    		CONTAS_PAGAR_BAIXAS CPB 
	    	WHERE 
	    		CPB.IDEMPRESABAIXA = CM.IDEMPRESA AND 
	    		CPB.IDPLANILHA = CM.IDPLANILHA
	    	) AND
	    NOT EXISTS (
	    	SELECT
	    		0
	    	FROM
	    		DBA.NOTAS NF
	    	WHERE
	    		NF.IDEMPRESA = CM.IDEMPRESA AND
	    		NF.IDPLANILHA = CM.IDPLANILHA AND
	    		NF.TIPOORIGEMEXTERNA = 'FBX' AND 
	    		NF.NUMNOTA = TRIM(TRIM(TO_CHAR(YEAR(DTMOVIMENTO),'0000'))||TRIM(TO_CHAR(MONTH(DTMOVIMENTO),'00'))||TRIM(TO_CHAR(DAY(DTMOVIMENTO),'00')))
	    		
	    	)
	    	
	UNION ALL

	SELECT 
		5 AS CONT,
	    FRE.IDCTACREDITO AS IDCTACONTABIL,
	    FRE.IDPLANILHA,
	    FRE.IDPLANILHA AS IDPLANILHA2,
	    'C' AS TIPONATUREZALCTO,
	    SUM(FRE.VLRDEBITO) AS VALCREDITO,
	    0 AS VALDEBITO,
	    'FRE' AS ORIGEMMOVIMENTO,
	    FRE.DTMOVIMENTO AS DTPAGAMENTO,
	    FRE.IDEMPRESA,
	    'C' AS TIPONATUREZACTA,
	    FRE.DESCRRECEBIMENTO AS COMPLEMENTO,
	    U.NOMEUSUARIO,
	    CPC.DESCRCTACONTABIL,
	    'F' AS FLAGAGRUPADO,
	    FRE.IDUSUARIO,
	    FRE.IDCAIXA,
	    0 AS IDRECEBIMENTO,
	    1 AS IDABERTURA,
	    NULL AS IDTITULO,
	    NULL AS DIGITOTITULO,
	    FRE.IDCTACREDITO AS IDCTACONTABIL1,
	   	FRE.DTALTERACAO AS DTALTERACAO
	FROM (
		SELECT
		    FRE.IDEMPRESA,
		    FRE.DTMOVIMENTO,
		    FRE.IDUSUARIO,
		    ' [CONFORME MOVIMENTO DO CAIXA ' || N.IDCAIXA ||
	        ' DO DIA ' || VARCHAR_FORMAT(FRE.DTMOVIMENTO, 'DD/MM/YYYY') || ']' AS DESCRRECEBIMENTO,
		    CASE
			    WHEN FRE.IDCTADEBITO <> 0 THEN FRE.IDCTADEBITO 
			    WHEN FRE.IDCTADEBITO = 0 AND FRE.IDCTATROCO <> 0 THEN FRE.IDCTATROCO END AS IDCTADEBITO,
		    (SELECT FRE2.IDCTACREDITO FROM TABLE(UF_REPROCESSADOR_CONTABIL_FRONT_V2 (FRE.IDEMPRESA, N.IDCAIXA, FRE.DTMOVIMENTO, FRE.DTMOVIMENTO)) FRE2 WHERE FRE2.IDPLANILHA = FRE.IDPLANILHA AND FRE2.DESCRRECEBIMENTO = FRE.DESCRRECEBIMENTO AND FRE2.IDCTACREDITO <> 0) AS IDCTACREDITO,
		    SUM(CASE 
		    		WHEN FRE.IDCTADEBITO <> 0 THEN COALESCE(CAST(FRE.VLRDEBITO AS DECIMAL(15,2)),0)
		    		WHEN FRE.IDCTADEBITO = 0 AND FRE.IDCTATROCO <> 0 THEN COALESCE(CAST(FRE.VLRTROCO AS DECIMAL(15,2)),0)*-1 END ) AS VLRDEBITO,
		    SUM(COALESCE(CAST(FRE.VLRCREDITO AS DECIMAL(15,2)),0)) AS VLRCREDITO,
		    FRE.IDPLANILHA,
		    N.IDCAIXA,
		    N.DTALTERACAO
		FROM
		    (SELECT
		        N.IDEMPRESA,
		        N.IDCAIXA,
		        DATE(N.DTMOVIMENTO) AS DTMOVIMENTO,
		        CONTABIL.DTALTERACAO
		    FROM
		        NOTAS N
		    JOIN LATERAL (
		        SELECT
		            COMPLEMENTO,
		            TIPONATUREZALCTO,
		            IDPLANILHA,
		            CM.DTHORAULTIMAALTERACAO AS DTALTERACAO
		        FROM
		            CONTABIL_MOVIMENTO CM
		        WHERE
		            CM.IDPLANILHA = N.IDPLANILHA AND
		            CM.IDEMPRESA = N.IDEMPRESA
		        ORDER BY 
		        	CM.DTHORAULTIMAALTERACAO DESC
		        FETCH FIRST 1 ROW ONLY
	    		) AS CONTABIL ON 1 = 1
		    WHERE
		        N.IDEMPRESA IN (:RA_IDEMPRESA) AND
		        (N.IDPLANILHA IN (:RA_IDPLANILHAS) OR (:RA_IDPLANILHAS) IN (0)) AND
		        N.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
		    GROUP BY
		        N.IDEMPRESA,
		        N.IDCAIXA,
		        DATE(N.DTMOVIMENTO),
		        CONTABIL.DTALTERACAO
		   ) AS N
		    JOIN TABLE(UF_REPROCESSADOR_CONTABIL_FRONT_V2(N.IDEMPRESA, N.IDCAIXA, N.DTMOVIMENTO, N.DTMOVIMENTO)) AS FRE
		         ON 1=1
		WHERE 
			EXISTS (
				SELECT 
					0 
				FROM 
					DRE_CAIXA_CONTAS_BASE DCCB 
				WHERE 
					DCCB.IDCTACONTABIL = FRE.IDCTADEBITO OR
					DCCB.IDCTACONTABIL = FRE.IDCTATROCO
				) AND
		    NOT EXISTS (
			    SELECT 
					0 
				FROM 
					TABLE(UF_REPROCESSADOR_CONTABIL_FRONT_V2(N.IDEMPRESA, N.IDCAIXA, N.DTMOVIMENTO, N.DTMOVIMENTO)) TMP
				JOIN
					DBA.CONFIG_SAIDA CS ON
						CS.IDEMPRESA = TMP.IDEMPRESA
				JOIN
					DBA.FORMA_PAGREC FP ON 
						FP.IDRECEBIMENTO = CS.IDAPROPRIACAOCREDITOVENDA AND
						FP.IDCTADEBITO = TMP.IDCTADEBITO
				WHERE
					TMP.IDPLANILHA = FRE.IDPLANILHA)
		GROUP BY
	        FRE.IDEMPRESA,
	        FRE.DTMOVIMENTO,
	        FRE.IDUSUARIO,
	        N.IDCAIXA,
	        FRE.IDPLANILHA,
	        N.DTALTERACAO,
	        FRE.IDCTADEBITO,
	        FRE.IDCTATROCO,
	        FRE.IDCTACREDITO,
	        FRE.DESCRRECEBIMENTO
		) FRE
		JOIN USUARIO U ON
	        FRE.IDUSUARIO = U.IDUSUARIO
	    JOIN CONTABIL_PLANO_CONTAS CPC ON
	        FRE.IDCTACREDITO = CPC.IDCTACONTABIL
	    JOIN CONFIG_SAIDA CS ON
	        CS.IDEMPRESA = FRE.IDEMPRESA
	WHERE
		EXISTS (
			SELECT 
	    		0 
	    	FROM 
	    		DRE_CAIXA_CONTAS_BASE dccb 
	    	WHERE 
	    		DCCB.IDCTACONTABIL = FRE.IDCTADEBITO)
	GROUP BY
		5,
	    FRE.IDCTACREDITO,
	    FRE.IDPLANILHA,
	    FRE.IDPLANILHA,
	    'C',
	    0,
	    'FRE',
	    FRE.DTMOVIMENTO,
	    FRE.IDEMPRESA,
	    'C',
	    FRE.DESCRRECEBIMENTO,
	    U.NOMEUSUARIO,
	    CPC.DESCRCTACONTABIL,
	    'F',
	    FRE.IDUSUARIO,
	    FRE.IDCAIXA,
	    0,
	    1,
	    NULL,
	    NULL,
	    FRE.IDCTACREDITO,
	   	FRE.DTALTERACAO,
	   	IDCTADEBITO
	
	UNION ALL
	
	SELECT
	    DISTINCT
	    6 AS CONT,
	    AD.IDCTACONTABIL AS IDCTACONTABIL,
	    AB.IDPLANILHA,
	    AB.IDPLANILHA AS IDPLANILHA2,
	    CASE 
	    	WHEN AB.TIPOADIANTAMENTO IN ('F','U') THEN 'C' 
	    	WHEN AB.TIPOADIANTAMENTO = 'C' THEN 'D' END AS TIPONATUREZALCTO,
	    CASE WHEN AB.TIPOADIANTAMENTO IN ('F','U') THEN AB.VALBAIXAADIANT ELSE 0 END AS VALCREDITO,
	    CASE WHEN AB.TIPOADIANTAMENTO = 'C' THEN AB.VALBAIXAADIANT ELSE 0 END AS VALDEBITO,
	    'ADT' AS ORIGEMMOVIMENTO,
	    AB.DTMOVIMENTO AS DTPAGAMENTO,
	    AB.IDEMPRESABAIXA AS IDEMPRESA,
	    CPN.TIPONATUREZA AS TIPONATUREZACTA,
	    CONTABIL.COMPLEMENTO AS COMPLEMENTO,
	    U.NOMEUSUARIO,
	    CPN.DESCRCTACONTABIL,
	    'F' AS FLAGAGRUPADO,
	    U.IDUSUARIO,
	    0 AS IDCAIXA,
	    0 AS IDRECEBIMENTO,
	    0 AS IDABERTURA,
	    AB.IDADIANTAMENTO AS IDTITULO,
	    '01' AS DIGITOTITULO,
	    AD.IDCTACONTABIL AS IDCTACONTABIL1,
	    CONTABIL.DTALTERACAO
	FROM
	    ADIANTAMENTO_BAIXA AB
	JOIN 
		ADIANTAMENTO AD ON
	        AD.IDADIANTAMENTO = AB.IDADIANTAMENTO
	JOIN 
		CONTABIL_PLANO_CONTAS CPN ON
	        CPN.IDCTACONTABIL = AD.IDCTACONTABIL 
	JOIN 
		USUARIO U ON 
			U.IDUSUARIO = AB.IDUSUARIO
	LEFT JOIN LATERAL (
        SELECT
                CAST(SUBSTR(COMPLEMENTO,1,900) AS VARCHAR(1000)) AS COMPLEMENTO,
                TIPONATUREZALCTO,
                IDPLANILHA,
                CM.DTHORAULTIMAALTERACAO AS DTALTERACAO
            FROM
                CONTABIL_MOVIMENTO CM
            WHERE
                CM.IDCTACONTABIL = AD.IDCTACONTABIL AND
                CM.IDPLANILHA = AB.IDPLANILHA AND
                CM.IDEMPRESA = AB.IDEMPRESA
            ORDER BY
            	CM.DTHORAULTIMAALTERACAO DESC
            FETCH FIRST 1 ROW ONLY
	    ) AS CONTABIL ON 
	    	1 = 1
	WHERE
	    AB.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM AND
	    AB.IDEMPRESABAIXA IN (:RA_IDEMPRESA) AND
	    (AB.IDPLANILHA IN (:RA_IDPLANILHAS) OR (:RA_IDPLANILHAS) IN (0)) AND
	    (
	    EXISTS (
	    	SELECT 
	    		0 
	    	FROM 
	    		CONTAS_RECEBER_BAIXAS CRB 
	    	WHERE 
	    		CRB.IDPLANILHA = AB.IDPLANILHA
	    	) OR
	    EXISTS (
	    	SELECT 
	    		0 
	    	FROM 
	    		CONTAS_PAGAR_BAIXAS AGR 
	    	WHERE 
	    		AGR.IDPLANILHA = AB.IDPLANILHA
	    	)
	   	) 
	    
	UNION ALL

	SELECT
	    DISTINCT
	    7 AS CONT,
	    CHE.IDCTACONTABIL AS IDCTACONTABIL,
	    CHE.IDPLANILHA,
	    CHE.IDPLANILHA AS IDPLANILHA2,
	    'C' TIPONATUREZALCTO,
	    CHE.VALOR AS VALCREDITO,
	    0 AS VALDEBITO,
	    'CHE' AS ORIGEMMOVIMENTO,
	    DATE(CHE.DTMOVIMENTO) AS DTPAGAMENTO,
	    CHE.IDEMPRESADESTINO AS IDEMPRESA,
	    CPN.TIPONATUREZA AS TIPONATUREZACTA,
	    CAST(COALESCE((  SELECT
	                COMPLEMENTO
	            FROM
	                CONTABIL_MOVIMENTO CM
	            WHERE
	                CM.IDCTACONTABIL = CHE.IDCTACONTABIL AND
	                CM.IDPLANILHA = CHE.IDPLANILHA AND
	                CM.IDEMPRESA = CHE.IDEMPRESA
	            FETCH FIRST 1 ROW ONLY),CHE.OBSGERAL) AS VARCHAR(32000)) AS COMPLEMENTO,
	    U.NOMEUSUARIO,
	    CPN.DESCRCTACONTABIL,
	    'F' AS FLAGAGRUPADO,
	    U.IDUSUARIO,
	    0 AS IDCAIXA,
	    0 AS IDRECEBIMENTO,
	    0 AS IDABERTURA,
	    CHE.IDNUMCHEQUE AS IDTITULO,
	    '01' AS DIGITOTITULO,
	    CHE.IDCTACONTABIL AS IDCTACONTABIL1,
	    CONTABIL.DTALTERACAO
	FROM
	    CHEQUES_MOVIMENTO CHE
    JOIN 
    	CONTABIL_PLANO_CONTAS CPN ON
        	CPN.IDCTACONTABIL = CHE.IDCTACONTABIL
    JOIN 
    	USUARIO U ON 
    		U.IDUSUARIO = CHE.IDUSUARIO
    LEFT JOIN LATERAL
    (
        SELECT
            COMPLEMENTO,
            TIPONATUREZALCTO,
            IDPLANILHA,
            CM.DTHORAULTIMAALTERACAO AS DTALTERACAO
        FROM
            CONTABIL_MOVIMENTO CM
        WHERE
            CM.IDCTACONTABIL = CHE.IDCTACONTABIL AND
            CM.IDPLANILHA = CHE.IDPLANILHA AND
            CM.IDEMPRESA = CHE.IDEMPRESA
        ORDER BY 
        	CM.DTHORAULTIMAALTERACAO DESC
        FETCH FIRST 1 ROW ONLY
    ) AS CONTABIL ON 1 = 1
	WHERE
	    CHE.DTMOVIMENTO BETWEEN DTINI( :RA_DTINI ) AND DTFIM( :RA_DTFIM ) AND
	    (CHE.IDEMPRESADESTINO IN (:RA_IDEMPRESA)) AND
	    (CHE.IDPLANILHA IN (:RA_IDPLANILHAS) OR (:RA_IDPLANILHAS) IN (0)) AND
	    EXISTS (
	    	SELECT 
	    		0 
	    	FROM 
	    		CONTAS_PAGAR_BAIXAS CRB 
	    	WHERE 
	    		CRB.IDPLANILHA = CHE.IDPLANILHA
	    	)	    	
	
) TMP
LEFT JOIN
	DRE_ESTRUTURA_COMPOSICAO DREEST ON
		DREEST.IDCTACONTABIL IS NOT NULL AND
		TMP.IDCTACONTABIL LIKE (DREEST.IDCTACONTABIL||'%')
LEFT JOIN
	DRE_ESTRUTURA EST ON
		EST.IDESTRUTURA = DREEST.IDESTRUTURA AND
		EST.TIPONATUREZA = TMP.TIPONATUREZALCTO
WHERE
	(TMP.IDCTACONTABIL IN (:RA_IDCTACONTABIL) OR (:RA_IDCTACONTABIL) IN (0)) AND
	EST.IDDREGRUPO IS NOT NULL OR
	NOT EXISTS (
		SELECT
			0
		FROM
			DRE_ESTRUTURA_COMPOSICAO DREEST 
		WHERE
			DREEST.IDCTACONTABIL IS NOT NULL AND
			TMP.IDCTACONTABIL LIKE (DREEST.IDCTACONTABIL||'%')
		)		
