-- RESUMO - TOTAIS POR TIPO CONFORME AGRUPAMENTOS POR FORNECEDOR
-- Este resumo usa as mesmas regras das consultas 01 a 16.
-- Como alguns agrupamentos podem ser analiticamente sobrepostos, o total deve ser conferido por AGRUPAMENTO.
WITH NOTAS_MOVIMENTO AS (
        SELECT EA.IDEMPRESA, EA.IDPLANILHA, N.IDCLIFOR
        FROM DBA.ESTOQUE_ANALITICO EA
        INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
        INNER JOIN DBA.NOTAS N ON N.IDEMPRESA = EA.IDEMPRESA AND N.IDPLANILHA = EA.IDPLANILHA
        WHERE EA.IDOPERACAO < 1000
                AND OI.TIPOMOVIMENTO = 'C'
                AND OI.FLAGMOVSALDOPRO = 'T'
                AND N.FLAGMOVFISCAL = 'T'
                AND N.FLAGNOTACANCEL = 'F'
                AND EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
        GROUP BY EA.IDEMPRESA, EA.IDPLANILHA, N.IDCLIFOR
),
ITENS_TRIBUTACAO AS (
        SELECT NM.IDEMPRESA, NM.IDPLANILHA, NM.IDCLIFOR,
                CASE
                        WHEN EA.IDSITTRIB IN (40,140,240,340,440,540,640,740,840) THEN 'ISENTO-40'
                        WHEN EA.IDSITTRIB IN (41,141,241,341,441,541,641,741,841) THEN 'NAOTRIBUTADO-41'
                        WHEN EA.IDSITTRIB IN (50,150,250,350,450,550,650,750,850) THEN 'SUSPENSO-50'
                        WHEN EA.IDSITTRIB IN (90,190,290,390,490,590,690,790,890) THEN 'OUTROS-90'
                        WHEN EA.IDSITTRIB IN (0,100,200,300,400,500,600,700,800) THEN 'TRIBUTADO-00'
                        WHEN EA.IDSITTRIB IN (20,120,220,320,420,520,620,720,820) THEN 'REDUCAO-20'
                        WHEN EA.IDSITTRIB IN (51,151,251,351,451,551,651,751,851) THEN 'DIFERIDO-51'
                        WHEN EA.TIPOSITTRIB = 'F' AND EA.IDSITTRIB IN (60,160,260,360,460,560,660,760,860) THEN 'STNORMAL-60'
                        WHEN EA.TIPOSITTRIB = 'A' AND EA.IDSITTRIB IN (60,160,260,360,460,560,660,760,860) THEN 'STFRONTEIRA-60'
                END AS TIPO
        FROM NOTAS_MOVIMENTO NM
        INNER JOIN DBA.ESTOQUE_ANALITICO EA ON EA.IDEMPRESA = NM.IDEMPRESA AND EA.IDPLANILHA = NM.IDPLANILHA
        INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
        WHERE OI.FLAGMOVSALDOPRO = 'T'
                AND EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
),
TIPO_NOTA AS (
        SELECT IDEMPRESA, IDPLANILHA, IDCLIFOR, MAX(TIPO) AS TIPO
        FROM ITENS_TRIBUTACAO
        GROUP BY IDEMPRESA, IDPLANILHA, IDCLIFOR
        HAVING COUNT(DISTINCT COALESCE(TIPO, 'OUTRO')) = 1
                AND MAX(TIPO) IS NOT NULL
),
TRIBUTACAO_XML AS (
        SELECT EAF.IDEMPRESA, EAF.IDPLANILHA,
                CASE WHEN SUM(CASE WHEN EAF.FLAGTRIBUTACAOXML = 'T' THEN 1 ELSE 0 END) = COUNT(*) THEN 'T' ELSE 'F' END AS FLAGTRIBUTACAOXML
        FROM DBA.ESTOQUE_ANALITICO_FISCAL EAF
        INNER JOIN NOTAS_MOVIMENTO NM ON NM.IDEMPRESA = EAF.IDEMPRESA AND NM.IDPLANILHA = EAF.IDPLANILHA
        GROUP BY EAF.IDEMPRESA, EAF.IDPLANILHA
),
DADOS_FORNECEDOR AS (
        SELECT CF.IDCLIFOR, CF.IDATIVIDADE, TA.DESCRTIPOATIVIDADE AS ATIVIDADE,
                ATV.FLAGPRODUTORRURAL AS PRODUTOR,
                CASE WHEN CF.TIPOREGIMETRIBFEDERAL = 'S' THEN 'S' ELSE 'N' END AS SIMPLESNACIONAL
        FROM DBA.CLIENTE_FORNECEDOR CF
        LEFT JOIN DBA.ATIVIDADE ATV ON ATV.IDATIVIDADE = CF.IDATIVIDADE
        LEFT JOIN DBA.ATIVIDADE_TIPO_ATIVIDADE ATA ON ATA.IDATIVIDADE = CF.IDATIVIDADE AND ATA.FLAGPADRAO = 'T'
        LEFT JOIN DBA.TIPO_ATIVIDADE TA ON TA.IDTIPOATIVIDADE = ATA.IDTIPOATIVIDADE
),
APURACAO AS (
        SELECT TN.IDCLIFOR, DF.IDATIVIDADE, DF.ATIVIDADE, DF.PRODUTOR, DF.SIMPLESNACIONAL, TN.TIPO,
                COUNT(*) AS QTDNOTASTIPO,
                SUM(CASE WHEN COALESCE(TX.FLAGTRIBUTACAOXML, 'F') = 'T' THEN 1 ELSE 0 END) AS XML,
                SUM(CASE WHEN COALESCE(TX.FLAGTRIBUTACAOXML, 'F') = 'F' THEN 1 ELSE 0 END) AS CAD
        FROM TIPO_NOTA TN
        LEFT JOIN TRIBUTACAO_XML TX ON TX.IDEMPRESA = TN.IDEMPRESA AND TX.IDPLANILHA = TN.IDPLANILHA
        LEFT JOIN DADOS_FORNECEDOR DF ON DF.IDCLIFOR = TN.IDCLIFOR
        GROUP BY TN.IDCLIFOR, DF.IDATIVIDADE, DF.ATIVIDADE, DF.PRODUTOR, DF.SIMPLESNACIONAL, TN.TIPO
),
FORNECEDOR_TOTAL AS (
        SELECT IDCLIFOR, COUNT(*) AS QTDNOTAS_TOTAL
        FROM NOTAS_MOVIMENTO
        GROUP BY IDCLIFOR
),
FORNECEDOR AS (
        SELECT A.IDCLIFOR, SUM(A.QTDNOTASTIPO) AS QTDNOTAS, SUM(A.XML) AS XML_TOTAL, SUM(A.CAD) AS CAD_TOTAL,
                COUNT(DISTINCT A.TIPO) AS QTDTIPOS,
                SUM(CASE WHEN A.TIPO IN ('ISENTO-40','NAOTRIBUTADO-41','SUSPENSO-50','OUTROS-90') THEN 1 ELSE 0 END) AS QTDTIPOS_405090,
                SUM(CASE WHEN A.TIPO NOT IN ('ISENTO-40','NAOTRIBUTADO-41','SUSPENSO-50','OUTROS-90') THEN 1 ELSE 0 END) AS QTDTIPOS_OUTRAS_405090,
                SUM(CASE WHEN A.TIPO IN ('TRIBUTADO-00','REDUCAO-20','DIFERIDO-51') THEN 1 ELSE 0 END) AS QTDTIPOS_002051,
                SUM(CASE WHEN A.TIPO NOT IN ('TRIBUTADO-00','REDUCAO-20','DIFERIDO-51') THEN 1 ELSE 0 END) AS QTDTIPOS_OUTRAS_002051,
                SUM(CASE WHEN A.TIPO IN ('TRIBUTADO-00','REDUCAO-20','DIFERIDO-51','STNORMAL-60','STFRONTEIRA-60') THEN 1 ELSE 0 END) AS QTDTIPOS_00205160,
                SUM(CASE WHEN A.TIPO NOT IN ('ISENTO-40','NAOTRIBUTADO-41','SUSPENSO-50','OUTROS-90','TRIBUTADO-00','REDUCAO-20','DIFERIDO-51','STNORMAL-60','STFRONTEIRA-60') THEN 1 ELSE 0 END) AS QTDTIPOS_FORA_COMBINACAO
        FROM APURACAO A
        GROUP BY A.IDCLIFOR
),
BASE AS (
        SELECT A.*, F.QTDNOTAS, F.XML_TOTAL, F.CAD_TOTAL, F.QTDTIPOS, F.QTDTIPOS_405090,
                F.QTDTIPOS_OUTRAS_405090, F.QTDTIPOS_002051, F.QTDTIPOS_OUTRAS_002051,
                F.QTDTIPOS_00205160, F.QTDTIPOS_FORA_COMBINACAO, FT.QTDNOTAS_TOTAL
        FROM APURACAO A
        INNER JOIN FORNECEDOR F ON F.IDCLIFOR = A.IDCLIFOR
        INNER JOIN FORNECEDOR_TOTAL FT ON FT.IDCLIFOR = A.IDCLIFOR
),
AGRUPAMENTOS AS (
        SELECT '01 - PRODUTORES 100 CADASTRO 40 41 50 90 UMA TRIBUTACAO' AS AGRUPAMENTO, TIPO, QTDNOTASTIPO
        FROM BASE
        WHERE PRODUTOR = 'T' AND XML_TOTAL = 0 AND CAD_TOTAL = QTDNOTAS AND QTDNOTAS = QTDNOTAS_TOTAL AND QTDTIPOS = 1 AND QTDTIPOS_OUTRAS_405090 = 0 AND TIPO IN ('ISENTO-40','NAOTRIBUTADO-41','SUSPENSO-50','OUTROS-90')
        UNION ALL
        SELECT '02 - PRODUTORES 100 CADASTRO 40 41 50 90 MULTI TRIBUTACOES', TIPO, QTDNOTASTIPO
        FROM BASE
        WHERE PRODUTOR = 'T' AND XML_TOTAL = 0 AND CAD_TOTAL = QTDNOTAS AND QTDNOTAS = QTDNOTAS_TOTAL AND QTDTIPOS > 1 AND QTDTIPOS_OUTRAS_405090 = 0 AND TIPO IN ('ISENTO-40','NAOTRIBUTADO-41','SUSPENSO-50','OUTROS-90')
        UNION ALL
        SELECT '03 - NAO PRODUTORES 100 CADASTRO 40 41 50 90 UMA TRIBUTACAO', TIPO, QTDNOTASTIPO
        FROM BASE
        WHERE PRODUTOR = 'F' AND XML_TOTAL = 0 AND CAD_TOTAL = QTDNOTAS AND QTDNOTAS = QTDNOTAS_TOTAL AND QTDTIPOS = 1 AND QTDTIPOS_OUTRAS_405090 = 0 AND TIPO IN ('ISENTO-40','NAOTRIBUTADO-41','SUSPENSO-50','OUTROS-90')
        UNION ALL
        SELECT '04 - NAO PRODUTORES 100 CADASTRO 40 41 50 90 MULTI TRIBUTACOES', TIPO, QTDNOTASTIPO
        FROM BASE
        WHERE PRODUTOR = 'F' AND XML_TOTAL = 0 AND CAD_TOTAL = QTDNOTAS AND QTDNOTAS = QTDNOTAS_TOTAL AND QTDTIPOS > 1 AND QTDTIPOS_OUTRAS_405090 = 0 AND TIPO IN ('ISENTO-40','NAOTRIBUTADO-41','SUSPENSO-50','OUTROS-90')
        UNION ALL
        SELECT '05 - FORNECEDORES 100 CADASTRO OUTRAS UMA TRIBUTACAO', TIPO, QTDNOTASTIPO
        FROM BASE
        WHERE XML_TOTAL = 0 AND CAD_TOTAL = QTDNOTAS AND QTDNOTAS = QTDNOTAS_TOTAL AND QTDTIPOS = 1 AND QTDTIPOS_405090 = 0 AND TIPO NOT IN ('ISENTO-40','NAOTRIBUTADO-41','SUSPENSO-50','OUTROS-90')
        UNION ALL
        SELECT '06 - FORNECEDORES 100 CADASTRO COMBINANDO 40 41 50 90 COM 00 20 51 60', TIPO, QTDNOTASTIPO
        FROM BASE
        WHERE XML_TOTAL = 0 AND CAD_TOTAL = QTDNOTAS AND QTDNOTAS = QTDNOTAS_TOTAL AND QTDTIPOS > 1 AND QTDTIPOS_405090 > 0 AND QTDTIPOS_00205160 > 0 AND QTDTIPOS_FORA_COMBINACAO = 0
        UNION ALL
        SELECT '07 - FORNECEDORES 100 XML 40 41 50 90 UMA TRIBUTACAO', TIPO, QTDNOTASTIPO
        FROM BASE
        WHERE XML_TOTAL = QTDNOTAS AND CAD_TOTAL = 0 AND QTDNOTAS = QTDNOTAS_TOTAL AND QTDTIPOS = 1 AND QTDTIPOS_OUTRAS_405090 = 0 AND TIPO IN ('ISENTO-40','NAOTRIBUTADO-41','SUSPENSO-50','OUTROS-90')
        UNION ALL
        SELECT '08 - FORNECEDORES 100 XML 40 41 50 90 MULTI TRIBUTACOES', TIPO, QTDNOTASTIPO
        FROM BASE
        WHERE XML_TOTAL = QTDNOTAS AND CAD_TOTAL = 0 AND QTDNOTAS = QTDNOTAS_TOTAL AND QTDTIPOS > 1 AND QTDTIPOS_OUTRAS_405090 = 0 AND TIPO IN ('ISENTO-40','NAOTRIBUTADO-41','SUSPENSO-50','OUTROS-90')
        UNION ALL
        SELECT '09 - FORNECEDORES 100 XML OUTRAS UMA TRIBUTACAO', TIPO, QTDNOTASTIPO
        FROM BASE
        WHERE XML_TOTAL = QTDNOTAS AND CAD_TOTAL = 0 AND QTDNOTAS = QTDNOTAS_TOTAL AND QTDTIPOS = 1 AND QTDTIPOS_405090 = 0 AND TIPO NOT IN ('ISENTO-40','NAOTRIBUTADO-41','SUSPENSO-50','OUTROS-90')
        UNION ALL
        SELECT '10 - FORNECEDORES 100 XML COMBINANDO 40 41 50 90 COM 00 20 51 60', TIPO, QTDNOTASTIPO
        FROM BASE
        WHERE XML_TOTAL = QTDNOTAS AND CAD_TOTAL = 0 AND QTDNOTAS = QTDNOTAS_TOTAL AND QTDTIPOS > 1 AND QTDTIPOS_405090 > 0 AND QTDTIPOS_00205160 > 0 AND QTDTIPOS_FORA_COMBINACAO = 0
        UNION ALL
        SELECT '11 - FORNECEDORES MISTO OUTRAS UMA TRIBUTACAO', TIPO, QTDNOTASTIPO
        FROM BASE
        WHERE XML_TOTAL > 0 AND CAD_TOTAL > 0 AND QTDNOTAS = QTDNOTAS_TOTAL AND QTDTIPOS = 1 AND QTDTIPOS_405090 = 0 AND TIPO NOT IN ('ISENTO-40','NAOTRIBUTADO-41','SUSPENSO-50','OUTROS-90')
        UNION ALL
        SELECT '12 - FORNECEDORES MISTO COMBINANDO 40 41 50 90 COM 00 20 51 60', TIPO, QTDNOTASTIPO
        FROM BASE
        WHERE XML_TOTAL > 0 AND CAD_TOTAL > 0 AND QTDNOTAS = QTDNOTAS_TOTAL AND QTDTIPOS > 1 AND QTDTIPOS_405090 > 0 AND QTDTIPOS_00205160 > 0 AND QTDTIPOS_FORA_COMBINACAO = 0
        UNION ALL
        SELECT '13 - SIMPLES NACIONAL 100 CADASTRO 00 20 51 UMA TRIBUTACAO', TIPO, QTDNOTASTIPO
        FROM BASE
        WHERE SIMPLESNACIONAL = 'S' AND XML_TOTAL = 0 AND CAD_TOTAL = QTDNOTAS AND QTDNOTAS = QTDNOTAS_TOTAL AND QTDTIPOS = 1 AND QTDTIPOS_OUTRAS_002051 = 0 AND TIPO IN ('TRIBUTADO-00','REDUCAO-20','DIFERIDO-51')
        UNION ALL
        SELECT '14 - SIMPLES NACIONAL 100 CADASTRO 00 20 51 MULTI TRIBUTACOES', TIPO, QTDNOTASTIPO
        FROM BASE
        WHERE SIMPLESNACIONAL = 'S' AND XML_TOTAL = 0 AND CAD_TOTAL = QTDNOTAS AND QTDNOTAS = QTDNOTAS_TOTAL AND QTDTIPOS > 1 AND QTDTIPOS_OUTRAS_002051 = 0 AND TIPO IN ('TRIBUTADO-00','REDUCAO-20','DIFERIDO-51')
        UNION ALL
        SELECT '15 - NAO SIMPLES NACIONAL 100 CADASTRO 00 20 51 UMA TRIBUTACAO', TIPO, QTDNOTASTIPO
        FROM BASE
        WHERE SIMPLESNACIONAL = 'N' AND XML_TOTAL = 0 AND CAD_TOTAL = QTDNOTAS AND QTDNOTAS = QTDNOTAS_TOTAL AND QTDTIPOS = 1 AND QTDTIPOS_OUTRAS_002051 = 0 AND TIPO IN ('TRIBUTADO-00','REDUCAO-20','DIFERIDO-51')
        UNION ALL
        SELECT '16 - NAO SIMPLES NACIONAL 100 CADASTRO 00 20 51 MULTI TRIBUTACOES', TIPO, QTDNOTASTIPO
        FROM BASE
        WHERE SIMPLESNACIONAL = 'N' AND XML_TOTAL = 0 AND CAD_TOTAL = QTDNOTAS AND QTDNOTAS = QTDNOTAS_TOTAL AND QTDTIPOS > 1 AND QTDTIPOS_OUTRAS_002051 = 0 AND TIPO IN ('TRIBUTADO-00','REDUCAO-20','DIFERIDO-51')
),
TOTAL_TIPO_AGRUPAMENTO AS (
        SELECT AGRUPAMENTO, TIPO, SUM(QTDNOTASTIPO) AS QTDNOTAS
        FROM AGRUPAMENTOS
        GROUP BY AGRUPAMENTO, TIPO
),
TOTAL_TIPO AS (
        SELECT TIPO, SUM(QTDNOTAS) AS QTDNOTAS
        FROM TOTAL_TIPO_AGRUPAMENTO
        GROUP BY TIPO
),
TOTAL_GERAL AS (
        SELECT SUM(QTDNOTAS) AS QTDTOTALAGRUPAMENTOS
        FROM TOTAL_TIPO
)
SELECT
        TT.TIPO,
        TT.QTDNOTAS,
        TG.QTDTOTALAGRUPAMENTOS,
        DECIMAL(COALESCE((CAST(TT.QTDNOTAS AS DECIMAL(15,6)) / NULLIF(CAST(TG.QTDTOTALAGRUPAMENTOS AS DECIMAL(15,6)), 0)) * 100, 0), 15, 2) AS "% TOTAL AGRUPAMENTOS"
FROM TOTAL_TIPO TT
CROSS JOIN TOTAL_GERAL TG
ORDER BY
        CASE TT.TIPO
                WHEN 'ISENTO-40' THEN 1
                WHEN 'NAOTRIBUTADO-41' THEN 2
                WHEN 'OUTROS-90' THEN 3
                WHEN 'REDUCAO-20' THEN 4
                WHEN 'STNORMAL-60' THEN 5
                WHEN 'STFRONTEIRA-60' THEN 6
                WHEN 'SUSPENSO-50' THEN 7
                WHEN 'DIFERIDO-51' THEN 8
                WHEN 'TRIBUTADO-00' THEN 9
        END;
