ALTER TABLE DBA.CUSTO_MEDIO_COMPRA_PROCESSAMENTO DROP PRIMARY KEY
GO
CREATE TABLE DBA.CUSTO_MEDIO_COMPRA_PROCESSAMENTO (
    IDMOVIMENTO     INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    IDEMPRESA       INTEGER,
    IDPLANILHA      INTEGER,
    IDPRODUTO       INTEGER,
    IDSUBPRODUTO    INTEGER,
    NUMSEQUENCIA    INTEGER,
    DTMOVIMENTO     TIMESTAMP,
    CMCATUAL        DECIMAL(15,6),
    STATUS          CHAR(1),
    DTINCLUSAO      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
GO
ALTER TABLE DBA.CUSTO_MEDIO_COMPRA_PROCESSAMENTO ADD CONSTRAINT PK_CMCPROCESSAMENTO PRIMARY KEY (IDMOVIMENTO)
GO
CREATE INDEX IDX_CMCPROC_CM ON CUSTO_MEDIO_COMPRA_PROCESSAMENTO (IDEMPRESA, IDPLANILHA, IDPRODUTO, IDSUBPRODUTO, NUMSEQUENCIA)
GO
CREATE INDEX IDX_CMCPROC_DT ON CUSTO_MEDIO_COMPRA_PROCESSAMENTO (DTMOVIMENTO)
GO
CREATE INDEX IDX_CMCPROC_ST ON CUSTO_MEDIO_COMPRA_PROCESSAMENTO (STATUS)
GO
ALTER TABLE DBA.CUSTO_MEDIO_COMPRA_PROCESSAMENTO ADD CONSTRAINT CKT_CMCPROC_STATUS CHECK ( STATUS IN ('C','P') )
GO
COMMENT ON COLUMN DBA.CUSTO_MEDIO_COMPRA_PROCESSAMENTO.STATUS IS 'Status do registro da fila P-Pendente, C-Concluido'
GO
ALTER TABLE DBA.CUSTO_MEDIO_COMPRA_PROCHIST DROP PRIMARY KEY
GO
CREATE TABLE DBA.CUSTO_MEDIO_COMPRA_PROCHIST (
    IDHISTPROCCMC   INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    IDEMPRESA       INTEGER,
    IDPLANILHA      INTEGER,
    IDPRODUTO       INTEGER,
    IDSUBPRODUTO    INTEGER,
    NUMSEQUENCIA    INTEGER,
    DTMOVIMENTO     TIMESTAMP,
    CMCOLD          DECIMAL(15,6),
    CMCNEW          DECIMAL(15,6),
    QTDOLD          DECIMAL(15,6),
    QTDNEW          DECIMAL(15,6),
    DTALTERACAO     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IDPLANILHAORI   INTEGER
)
GO
ALTER TABLE DBA.CUSTO_MEDIO_COMPRA_PROCHIST ADD CONSTRAINT PK_CMCPROCHIST PRIMARY KEY (IDHISTPROCCMC)
GO
CREATE INDEX IDX_CMCPROCHIST_CM ON CUSTO_MEDIO_COMPRA_PROCHIST (IDEMPRESA, IDPLANILHA, IDPRODUTO, IDSUBPRODUTO, NUMSEQUENCIA)
GO
CREATE INDEX IDX_CMCPROCHIST_DT ON CUSTO_MEDIO_COMPRA_PROCHIST (DTMOVIMENTO)
GO
ALTER TABLE DBA.CUSTO_MEDIO_COMPRA_CTRLTRIGGER DROP PRIMARY KEY
GO
CREATE TABLE DBA.CUSTO_MEDIO_COMPRA_CTRLTRIGGER (
    IDSESSIONPROC   INTEGER NOT NULL
)
GO
ALTER TABLE DBA.CUSTO_MEDIO_COMPRA_CTRLTRIGGER ADD CONSTRAINT PK_CMCCTRLTRIGGER PRIMARY KEY (IDSESSIONPROC)
GO
CREATE OR REPLACE FUNCTION DBA.UF_CALCULADORA_CMC(
    IN_IDEMPRESA        INTEGER,
    IN_IDPLANILHA       INTEGER,
    IN_IDPRODUTO        INTEGER,
    IN_IDSUBPRODUTO     INTEGER,
    IN_NUMSEQUENCIA     INTEGER,
    IN_DTMOVIMENTO      TIMESTAMP
)
RETURNS TABLE (
    CMCCALCULADO DECIMAL(15,6),
    QTDESTCPCALCULADO DECIMAL(15,6),
    MEMORIA VARCHAR(500)
)
LANGUAGE SQL
READS SQL DATA
DETERMINISTIC
BEGIN ATOMIC

    DECLARE ANT_CUSTOULTCP, ANT_MEDIOCOMPRA, ANTDIA_QUANTIDADEPRO, ATU_CUSTOCOMPRA, ATU_SALDOINIATUAL, ATU_SALDOINIATUAL_HIST, ATU_QTDPRODREGATUAL, LD_CMCCALCULADO, LD_QTDESTCPCALCULADO DECIMAL(15,6);
    DECLARE LS_MEMORIA VARCHAR(500);

    SET (ANT_CUSTOULTCP, ANT_MEDIOCOMPRA, ANTDIA_QUANTIDADEPRO, ATU_CUSTOCOMPRA, ATU_SALDOINIATUAL, ATU_QTDPRODREGATUAL) =
        (SELECT
            COALESCE(ANTERIOR.CUSTOULTCP, 0)            AS ANTCUSTOULTCP,
            COALESCE(ANTERIOR.MEDIOCOMPRA, 0)           AS ANTMEDIOCOMPRA,
            COALESCE(ANTERIORDIA.QTDPRODANT,0)          AS ANTDIAQUANTIDADEPRO,
            COALESCE(CUSTOESTATUAL.CUSTOCPATUAL,0)      AS ATUCUSTOCOMPRA,
            COALESCE(CUSTOESTATUAL.SALDOINICIALATUAL,0) AS ATUSALDOINICIAL,
            COALESCE(CUSTOESTATUAL.QTDPRODREGATUAL,0)   AS QTDPRODREGATUAL
        FROM
            DBA.DUMMY
        LEFT JOIN (
            SELECT
                COALESCE(TEMP.CUSTOULTIMACOMPRA, 0)     AS CUSTOULTCP,
                COALESCE(TEMP.VALCUSTOMEDIOCOMPRA, 0)   AS MEDIOCOMPRA
            FROM (
                SELECT
                    PC.IDEMPRESA,
                    PC.IDPRODUTO,
                    PC.IDSUBPRODUTO,
                    PC.DTMOVIMENTO,
                    PC.CUSTOULTIMACOMPRA,
                    MC.VALCUSTOMEDIOCOMPRA,
                    ROW_NUMBER() OVER (
                        PARTITION BY PC.IDEMPRESA, PC.IDPRODUTO, PC.IDSUBPRODUTO
                        ORDER BY PC.DTMOVIMENTO DESC
                    ) AS LINHA
                FROM
                    DBA.PRODUTO_CUSTO AS PC
                JOIN
                    DBA.MOVIMENTO_CUSTO  MC ON
                        MC.IDEMPRESA        = PC.IDEMPRESA AND
                        MC.IDPLANILHA       = PC.IDPLANILHA AND
                        MC.IDPRODUTO        = PC.IDPRODUTO AND
                        MC.IDSUBPRODUTO     = PC.IDSUBPRODUTO AND
                        MC.NUMSEQUENCIA     = PC.NUMSEQUENCIA
                WHERE
                    PC.IDEMPRESA        = IN_IDEMPRESA AND
                    PC.IDPRODUTO        = IN_IDPRODUTO AND
                    PC.IDSUBPRODUTO     = IN_IDSUBPRODUTO AND
                    PC.DTMOVIMENTO      < IN_DTMOVIMENTO AND
                    MC.FLAGALTEROUCUSTO = 'T' AND
                    MC.ORIGEMMOVIMENTO  = 'NFE'
            ) TEMP
            WHERE
                LINHA = 1
        ) AS ANTERIOR ON
            0 = 0
        LEFT JOIN (
            SELECT
                COALESCE(SUM(QTDPRODUTO),0) AS QTDPRODANT
            FROM
                DBA.MOVIMENTO_CUSTO MC2
            WHERE
                MC2.IDEMPRESA           = IN_IDEMPRESA AND
                MC2.IDPRODUTO           = IN_IDPRODUTO AND
                MC2.IDSUBPRODUTO        = IN_IDSUBPRODUTO AND
                MC2.DTMOVIMENTO         > DBA.DTINI(IN_DTMOVIMENTO) AND
                MC2.DTMOVIMENTO         < IN_DTMOVIMENTO AND
                MC2.FLAGALTEROUCUSTO    = 'T' AND
                MC2.ORIGEMMOVIMENTO     = 'NFE'
        ) ANTERIORDIA (QTDPRODANT) ON
            0 = 0
        LEFT JOIN (
            SELECT
                COALESCE(MC3.CUSTOULTIMACOMPRA,0)   AS CUSTOCPATUAL,
                COALESCE(SLDEST.QTDATUALESTOQUE,0)  AS SALDOINICIALATUAL,
                COALESCE(MC3.QTDPRODUTO,0)   AS QTDPRODREGATUAL
            FROM
                DBA.PRODUTO_CUSTO MC3
            LEFT JOIN TABLE (
                DBA.UF_SALDOEST_DTPOSICAO(MC3.IDEMPRESA, MC3.IDPRODUTO, MC3.IDSUBPRODUTO, DATE(MC3.DTMOVIMENTO) - 1 DAY)
            ) SLDEST ON
                    SLDEST.IDEMPRESA    = MC3.IDEMPRESA AND
                    SLDEST.IDPRODUTO    = MC3.IDPRODUTO AND
                    SLDEST.IDSUBPRODUTO = MC3.IDSUBPRODUTO
            WHERE
                MC3.IDEMPRESA       = IN_IDEMPRESA AND
                MC3.IDPLANILHA      = IN_IDPLANILHA AND
                MC3.IDPRODUTO       = IN_IDPRODUTO AND
                MC3.IDSUBPRODUTO    = IN_IDSUBPRODUTO AND
                MC3.NUMSEQUENCIA    = IN_NUMSEQUENCIA
        ) CUSTOESTATUAL (CUSTOCPATUAL, SALDOINICIALATUAL, QTDPRODREGATUAL) ON
            0 = 0
    );

    SET LS_MEMORIA =    'ANTCMC: '||CAST(ANT_MEDIOCOMPRA AS VARCHAR(20))||'-'||
                        'SLDINI: '||CAST(ATU_SALDOINIATUAL AS VARCHAR(20))||'-'||
                        'QTDDIA: '||CAST(ANTDIA_QUANTIDADEPRO AS VARCHAR(20))||'-'||
                        'CUSCOM: '||CAST(ATU_CUSTOCOMPRA AS VARCHAR(20))||'-'||
                        'QTDREG: '||CAST(ATU_QTDPRODREGATUAL AS VARCHAR(20));

    SET ATU_SALDOINIATUAL_HIST = ATU_SALDOINIATUAL;

    IF ATU_SALDOINIATUAL < 0 THEN
        SET ATU_SALDOINIATUAL = 0;
    END IF;

    IF ANT_MEDIOCOMPRA <= 0 THEN
        SET LD_CMCCALCULADO = (
            (COALESCE(ATU_CUSTOCOMPRA,0)*COALESCE((COALESCE(ATU_SALDOINIATUAL,0)+COALESCE(ANTDIA_QUANTIDADEPRO,0)),0))
            + (COALESCE(ATU_CUSTOCOMPRA,0)*COALESCE(ATU_QTDPRODREGATUAL,0))
            ) / (
            COALESCE((COALESCE(ATU_SALDOINIATUAL,0)+COALESCE(ANTDIA_QUANTIDADEPRO,0)),0)
            + COALESCE(ATU_QTDPRODREGATUAL,0)
            );
    ELSE
        SET LD_CMCCALCULADO = (
            (COALESCE(ANT_MEDIOCOMPRA,0)*COALESCE((COALESCE(ATU_SALDOINIATUAL,0)+COALESCE(ANTDIA_QUANTIDADEPRO,0)),0))
            + (COALESCE(ATU_CUSTOCOMPRA,0)*COALESCE(ATU_QTDPRODREGATUAL,0))
            ) / (
            COALESCE((
            COALESCE(ATU_SALDOINIATUAL,0)+COALESCE(ANTDIA_QUANTIDADEPRO,0)),0)
            + COALESCE(ATU_QTDPRODREGATUAL,0)
            );
    END IF;

    SET LD_QTDESTCPCALCULADO = COALESCE((COALESCE(ATU_SALDOINIATUAL_HIST,0)+COALESCE(ANTDIA_QUANTIDADEPRO,0)),0);

    RETURN (VALUES(LD_CMCCALCULADO, LD_QTDESTCPCALCULADO, LS_MEMORIA));

END
GO
CREATE OR REPLACE PROCEDURE DBA.SP_PROCESSA_CUSTO_MEDIO_COMPRA_CMC()  /* ATUALIZADA COM ORIGEMMOVIMENTO PRD*/
LANGUAGE SQL
MODIFIES SQL DATA
BEGIN

    DECLARE LS_COMMIT CHAR(6) DEFAULT 'COMMIT';
    DECLARE LD_CMCCALCULADO, LD_QTDESTCPCALCULADO DECIMAL(15,6);
    DECLARE LI_SESSIONID INTEGER;

    SET LI_SESSIONID = ( SELECT
                            AGENT_ID
                        FROM
                            SYSIBMADM.APPLICATIONS
                        WHERE
                            APPL_ID = DBA.UF_APPLICATION_ID());

    INSERT INTO DBA.CUSTO_MEDIO_COMPRA_CTRLTRIGGER (IDSESSIONPROC) VALUES (LI_SESSIONID);

    -- Loop da fila
    FOR ROW_FILA AS CURSOR_FILA CURSOR WITH HOLD FOR
        SELECT
            IDMOVIMENTO     AS I_IDMOV,
            IDEMPRESA       AS I_EMP,
            IDPLANILHA      AS I_PLA,
            IDPRODUTO       AS I_PRO,
            IDSUBPRODUTO    AS I_SUB,
            NUMSEQUENCIA    AS I_SEQ,
            DTMOVIMENTO     AS I_DTM,
            CMCATUAL        AS I_CMC
        FROM
            DBA.CUSTO_MEDIO_COMPRA_PROCESSAMENTO
        WHERE
            STATUS = 'P'
        ORDER BY
            DTINCLUSAO
    DO

        -- Loop dos movimentos posteriores
        FOR ROW_MOV AS CURSOR_MOV CURSOR WITH HOLD FOR
            SELECT
                MC.IDEMPRESA             AS I_IDEMPRESA,
                MC.IDPLANILHA            AS I_IDPLANILHA,
                MC.IDPRODUTO             AS I_IDPRODUTO,
                MC.IDSUBPRODUTO          AS I_IDSUBPRODUTO,
                MC.NUMSEQUENCIA          AS I_NUMSEQUENCIA,
                MC.DTMOVIMENTO           AS I_DTMOVIMENTO,
                MC.VALCUSTOMEDIOCOMPRA   AS I_CMCOLD,
                MC.QTDESTOQUECOMPRA      AS I_QTDOLD
            FROM
                DBA.MOVIMENTO_CUSTO MC
            WHERE
                MC.IDEMPRESA        = ROW_FILA.I_EMP AND
                MC.IDPRODUTO        = ROW_FILA.I_PRO AND
                MC.IDSUBPRODUTO     = ROW_FILA.I_SUB AND
                MC.DTMOVIMENTO      >= ROW_FILA.I_DTM AND
                MC.FLAGALTEROUCUSTO = 'T' AND
                MC.ORIGEMMOVIMENTO  IN ('NFE', 'PRD')
            ORDER BY
                MC.DTMOVIMENTO,
                MC.NUMSEQUENCIA
        DO
            SET (LD_CMCCALCULADO, LD_QTDESTCPCALCULADO) = (SELECT CMCCALCULADO, QTDESTCPCALCULADO FROM TABLE (DBA.UF_CALCULADORA_CMC ( ROW_MOV.I_IDEMPRESA, ROW_MOV.I_IDPLANILHA, ROW_MOV.I_IDPRODUTO, ROW_MOV.I_IDSUBPRODUTO, ROW_MOV.I_NUMSEQUENCIA, ROW_MOV.I_DTMOVIMENTO)));

            UPDATE
                DBA.MOVIMENTO_CUSTO
            SET
                VALCUSTOMEDIOCOMPRA = COALESCE(LD_CMCCALCULADO,0),
                QTDESTOQUECOMPRA    = COALESCE(LD_QTDESTCPCALCULADO,0)
            WHERE
                IDEMPRESA    = ROW_MOV.I_IDEMPRESA AND
                IDPLANILHA   = ROW_MOV.I_IDPLANILHA AND
                IDPRODUTO    = ROW_MOV.I_IDPRODUTO AND
                IDSUBPRODUTO = ROW_MOV.I_IDSUBPRODUTO AND
                NUMSEQUENCIA = ROW_MOV.I_NUMSEQUENCIA;

            UPDATE
                DBA.MOVIMENTO_CUSTO
            SET
                VALCUSTOMEDIOCOMPRA = COALESCE(LD_CMCCALCULADO,0),
                QTDESTOQUECOMPRA    = COALESCE(LD_QTDESTCPCALCULADO,0)
            WHERE
                ORIGEMMOVIMENTO = 'MCC' AND
                IDEMPRESA    = ROW_MOV.I_IDEMPRESA AND
                IDPLANILHA   = ROW_MOV.I_IDPLANILHA AND
                /*IDPRODUTO    = ROW_MOV.I_IDPRODUTO AND
                IDSUBPRODUTO = ROW_MOV.I_IDSUBPRODUTO AND*/
                NUMSEQUENCIA = ROW_MOV.I_NUMSEQUENCIA;

            INSERT INTO DBA.CUSTO_MEDIO_COMPRA_PROCHIST (IDEMPRESA, IDPLANILHA, IDPRODUTO, IDSUBPRODUTO, NUMSEQUENCIA, DTMOVIMENTO, CMCOLD, CMCNEW, QTDOLD, QTDNEW, DTALTERACAO, IDPLANILHAORI)
            VALUES (ROW_MOV.I_IDEMPRESA, ROW_MOV.I_IDPLANILHA, ROW_MOV.I_IDPRODUTO, ROW_MOV.I_IDSUBPRODUTO, ROW_MOV.I_NUMSEQUENCIA, ROW_MOV.I_DTMOVIMENTO, ROW_MOV.I_CMCOLD, LD_CMCCALCULADO, ROW_MOV.I_QTDOLD, LD_QTDESTCPCALCULADO, SYSDATE, ROW_FILA.I_PLA);

            EXECUTE IMMEDIATE LS_COMMIT;

        END FOR;

        UPDATE
            DBA.CUSTO_MEDIO_COMPRA_PROCESSAMENTO
        SET
            STATUS = 'C'
        WHERE
            IDMOVIMENTO = I_IDMOV;

        EXECUTE IMMEDIATE LS_COMMIT;

    END FOR;

    DELETE FROM DBA.CUSTO_MEDIO_COMPRA_CTRLTRIGGER WHERE IDSESSIONPROC = LI_SESSIONID;

END
GO
CREATE OR REPLACE TRIGGER DBA.TR_ATCMC_FILA_AD AFTER DELETE ON DBA.MOVIMENTO_CUSTO
REFERENCING OLD AS O
FOR EACH ROW
BEGIN

    DECLARE LI_SESSIONID INTEGER;

    SET LI_SESSIONID = DBA.UF_GET_ID_CONNECTION();

    IF (SELECT COUNT(0) FROM DBA.CUSTO_MEDIO_COMPRA_CTRLTRIGGER WHERE IDSESSIONPROC = LI_SESSIONID) = 0 THEN
        INSERT INTO DBA.CUSTO_MEDIO_COMPRA_PROCESSAMENTO (IDEMPRESA, IDPLANILHA, IDPRODUTO, IDSUBPRODUTO, NUMSEQUENCIA, DTMOVIMENTO, CMCATUAL, STATUS)
        VALUES (O.IDEMPRESA, O.IDPLANILHA, O.IDPRODUTO, O.IDSUBPRODUTO, O.NUMSEQUENCIA, O.DTMOVIMENTO-2 MINUTES, O.VALCUSTOMEDIOCOMPRA, 'P'/*Pendente*/);
    END IF;

END
GO
CREATE OR REPLACE TRIGGER DBA.TR_ATCMC_FILA_AI AFTER INSERT ON DBA.MOVIMENTO_CUSTO
REFERENCING NEW AS N
FOR EACH ROW
WHEN (DATE(N.DTMOVIMENTO) < CURRENT_DATE )
BEGIN

    DECLARE LI_COUNT INTEGER;
    DECLARE LI_SESSIONID INTEGER;

    SET LI_SESSIONID = DBA.UF_GET_ID_CONNECTION();
    SET LI_COUNT = (SELECT COUNT(0) FROM DBA.MOVIMENTO_CUSTO MC WHERE MC.IDEMPRESA = N.IDEMPRESA AND MC.IDPRODUTO = N.IDPRODUTO AND MC.IDSUBPRODUTO = N.IDSUBPRODUTO AND MC.DTMOVIMENTO > N.DTMOVIMENTO);

    IF LI_COUNT > 0 AND (SELECT COUNT(0) FROM DBA.CUSTO_MEDIO_COMPRA_CTRLTRIGGER WHERE IDSESSIONPROC = LI_SESSIONID) = 0 THEN
        INSERT INTO DBA.CUSTO_MEDIO_COMPRA_PROCESSAMENTO (IDEMPRESA, IDPLANILHA, IDPRODUTO, IDSUBPRODUTO, NUMSEQUENCIA, DTMOVIMENTO, CMCATUAL, STATUS)
        VALUES (N.IDEMPRESA, N.IDPLANILHA, N.IDPRODUTO, N.IDSUBPRODUTO, N.NUMSEQUENCIA, N.DTMOVIMENTO-2 MINUTES, N.VALCUSTOMEDIOCOMPRA, 'P'/*Pendente*/);
    END IF;

END
GO
CREATE OR REPLACE TRIGGER DBA.TR_ATCMC_FILA_AU AFTER UPDATE ON DBA.MOVIMENTO_CUSTO
REFERENCING NEW AS N OLD AS O
FOR EACH ROW
BEGIN

    DECLARE LI_COUNT INTEGER;
    DECLARE LD_DTCTRL TIMESTAMP;
    DECLARE LI_SESSIONID INTEGER;

    SET LI_SESSIONID = DBA.UF_GET_ID_CONNECTION();

    IF N.DTMOVIMENTO > O.DTMOVIMENTO THEN
        SET LD_DTCTRL = O.DTMOVIMENTO-2 MINUTES;
    ELSE
        SET LD_DTCTRL = N.DTMOVIMENTO-2 MINUTES;
    END IF;

    SET LI_COUNT = (SELECT COUNT(0) FROM DBA.MOVIMENTO_CUSTO MC WHERE MC.IDEMPRESA = N.IDEMPRESA AND MC.IDPRODUTO = N.IDPRODUTO AND MC.IDSUBPRODUTO = N.IDSUBPRODUTO AND MC.DTMOVIMENTO > N.DTMOVIMENTO);

    IF LI_COUNT > 0 AND (SELECT COUNT(0) FROM DBA.CUSTO_MEDIO_COMPRA_CTRLTRIGGER WHERE IDSESSIONPROC = LI_SESSIONID) = 0 THEN
        INSERT INTO DBA.CUSTO_MEDIO_COMPRA_PROCESSAMENTO (IDEMPRESA, IDPLANILHA, IDPRODUTO, IDSUBPRODUTO, NUMSEQUENCIA, DTMOVIMENTO, CMCATUAL, STATUS)
        VALUES (N.IDEMPRESA, N.IDPLANILHA, N.IDPRODUTO, N.IDSUBPRODUTO, N.NUMSEQUENCIA, LD_DTCTRL, N.VALCUSTOMEDIOCOMPRA, 'P'/*Pendente*/);
    END IF;

END