-- 03 - ANALITICA NAO PRODUTORES, 100% CADASTRO, 40/41/50/90, UMA TRIBUTACAO
WITH NOTAS_MOVIMENTO AS (
        SELECT EA.IDEMPRESA, EA.IDPLANILHA, N.IDCLIFOR
        FROM DBA.ESTOQUE_ANALITICO EA
        INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
        INNER JOIN DBA.NOTAS N ON N.IDEMPRESA = EA.IDEMPRESA AND N.IDPLANILHA = EA.IDPLANILHA
        WHERE EA.IDOPERACAO < 1000
                AND OI.TIPOMOVIMENTO = 'C'
                AND OI.FLAGMOVSALDOPRO = 'T'
                AND N.FLAGMOVFISCAL = 'T'
                AND N.FLAGNOTACANCEL = 'F'
                AND EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
        GROUP BY EA.IDEMPRESA, EA.IDPLANILHA, N.IDCLIFOR
),
ITENS_TRIBUTACAO AS (
        SELECT NM.IDEMPRESA, NM.IDPLANILHA, NM.IDCLIFOR,
                CASE
                        WHEN EA.IDSITTRIB IN (40,140,240,340,440,540,640,740,840) THEN 'ISENTO-40'
                        WHEN EA.IDSITTRIB IN (41,141,241,341,441,541,641,741,841) THEN 'NAOTRIBUTADO-41'
                        WHEN EA.IDSITTRIB IN (50,150,250,350,450,550,650,750,850) THEN 'SUSPENSO-50'
                        WHEN EA.IDSITTRIB IN (90,190,290,390,490,590,690,790,890) THEN 'OUTROS-90'
                        WHEN EA.IDSITTRIB IN (0,100,200,300,400,500,600,700,800) THEN 'TRIBUTADO-00'
                        WHEN EA.IDSITTRIB IN (20,120,220,320,420,520,620,720,820) THEN 'REDUCAO-20'
                        WHEN EA.IDSITTRIB IN (51,151,251,351,451,551,651,751,851) THEN 'DIFERIDO-51'
                        WHEN EA.TIPOSITTRIB = 'F' AND EA.IDSITTRIB IN (60,160,260,360,460,560,660,760,860) THEN 'STNORMAL-60'
                        WHEN EA.TIPOSITTRIB = 'A' AND EA.IDSITTRIB IN (60,160,260,360,460,560,660,760,860) THEN 'STFRONTEIRA-60'
                END AS TIPO
        FROM NOTAS_MOVIMENTO NM
        INNER JOIN DBA.ESTOQUE_ANALITICO EA ON EA.IDEMPRESA = NM.IDEMPRESA AND EA.IDPLANILHA = NM.IDPLANILHA
        INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
        WHERE OI.FLAGMOVSALDOPRO = 'T'
                AND EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
),
TIPO_NOTA AS (
        SELECT IDEMPRESA, IDPLANILHA, IDCLIFOR, MAX(TIPO) AS TIPO
        FROM ITENS_TRIBUTACAO
        GROUP BY IDEMPRESA, IDPLANILHA, IDCLIFOR
        HAVING COUNT(DISTINCT COALESCE(TIPO, 'OUTRO')) = 1
                AND MAX(TIPO) IS NOT NULL
),
TRIBUTACAO_XML AS (
        SELECT EAF.IDEMPRESA, EAF.IDPLANILHA,
                CASE WHEN SUM(CASE WHEN EAF.FLAGTRIBUTACAOXML = 'T' THEN 1 ELSE 0 END) = COUNT(*) THEN 'T' ELSE 'F' END AS FLAGTRIBUTACAOXML
        FROM DBA.ESTOQUE_ANALITICO_FISCAL EAF
        INNER JOIN NOTAS_MOVIMENTO NM ON NM.IDEMPRESA = EAF.IDEMPRESA AND NM.IDPLANILHA = EAF.IDPLANILHA
        GROUP BY EAF.IDEMPRESA, EAF.IDPLANILHA
),
DADOS_FORNECEDOR AS (
        SELECT CF.IDCLIFOR, CF.IDATIVIDADE, TA.DESCRTIPOATIVIDADE AS ATIVIDADE,
                ATV.FLAGPRODUTORRURAL AS PRODUTOR,
                CASE WHEN CF.TIPOREGIMETRIBFEDERAL = 'S' THEN 'S' ELSE 'N' END AS SIMPLESNACIONAL
        FROM DBA.CLIENTE_FORNECEDOR CF
        LEFT JOIN DBA.ATIVIDADE ATV ON ATV.IDATIVIDADE = CF.IDATIVIDADE
        LEFT JOIN DBA.ATIVIDADE_TIPO_ATIVIDADE ATA ON ATA.IDATIVIDADE = CF.IDATIVIDADE AND ATA.FLAGPADRAO = 'T'
        LEFT JOIN DBA.TIPO_ATIVIDADE TA ON TA.IDTIPOATIVIDADE = ATA.IDTIPOATIVIDADE
),
APURACAO AS (
        SELECT TN.IDCLIFOR, DF.IDATIVIDADE, DF.ATIVIDADE, DF.PRODUTOR, DF.SIMPLESNACIONAL, TN.TIPO,
                COUNT(*) AS QTDNOTASTIPO,
                SUM(CASE WHEN COALESCE(TX.FLAGTRIBUTACAOXML, 'F') = 'T' THEN 1 ELSE 0 END) AS XML,
                SUM(CASE WHEN COALESCE(TX.FLAGTRIBUTACAOXML, 'F') = 'F' THEN 1 ELSE 0 END) AS CAD
        FROM TIPO_NOTA TN
        LEFT JOIN TRIBUTACAO_XML TX ON TX.IDEMPRESA = TN.IDEMPRESA AND TX.IDPLANILHA = TN.IDPLANILHA
        LEFT JOIN DADOS_FORNECEDOR DF ON DF.IDCLIFOR = TN.IDCLIFOR
        GROUP BY TN.IDCLIFOR, DF.IDATIVIDADE, DF.ATIVIDADE, DF.PRODUTOR, DF.SIMPLESNACIONAL, TN.TIPO
),
FORNECEDOR_TOTAL AS (
        SELECT IDCLIFOR, COUNT(*) AS QTDNOTAS_TOTAL
        FROM NOTAS_MOVIMENTO
        GROUP BY IDCLIFOR
),
FORNECEDOR AS (
        SELECT A.IDCLIFOR, SUM(A.QTDNOTASTIPO) AS QTDNOTAS, SUM(A.XML) AS XML_TOTAL, SUM(A.CAD) AS CAD_TOTAL,
                COUNT(DISTINCT A.TIPO) AS QTDTIPOS,
                SUM(CASE WHEN A.TIPO IN ('ISENTO-40','NAOTRIBUTADO-41','SUSPENSO-50','OUTROS-90') THEN 1 ELSE 0 END) AS QTDTIPOS_405090,
                SUM(CASE WHEN A.TIPO NOT IN ('ISENTO-40','NAOTRIBUTADO-41','SUSPENSO-50','OUTROS-90') THEN 1 ELSE 0 END) AS QTDTIPOS_OUTRAS_405090,
                SUM(CASE WHEN A.TIPO IN ('TRIBUTADO-00','REDUCAO-20','DIFERIDO-51') THEN 1 ELSE 0 END) AS QTDTIPOS_002051,
                SUM(CASE WHEN A.TIPO NOT IN ('TRIBUTADO-00','REDUCAO-20','DIFERIDO-51') THEN 1 ELSE 0 END) AS QTDTIPOS_OUTRAS_002051
        FROM APURACAO A
        GROUP BY A.IDCLIFOR
),
VALORES_NOTA AS (
        SELECT
                N.IDEMPRESA,
                N.IDPLANILHA,
                N.IDCLIFOR,
                DATE(N.DTMOVIMENTO) AS DATA,
                N.NUMNOTA,
                N.SERIENOTA,
                LISTAGG(DISTINCT VARCHAR(EA.IDCSTPISCOFINS), ', ') WITHIN GROUP (ORDER BY VARCHAR(EA.IDCSTPISCOFINS)) AS IDCSTPISCOFINS,
                SUM(COALESCE(EA.VALIPI, 0)) AS VALIPI,
                SUM(COALESCE(EA.VALIPIFRETE, 0)) AS VALIPIFRETE,
                SUM(COALESCE(EA.VALIPIACESSORIOS, 0)) AS VALIPIACESSORIOS,
                SUM(COALESCE(EA.VALIPIEMBALAGEM, 0)) AS VALIPIEMBALAGEM,
                SUM(COALESCE(EA.VALADICIONAIS, 0)) AS VALADICIONAIS,
                SUM(COALESCE(EA.VALFRETE, 0)) AS VALFRETE,
                SUM(COALESCE(EA.VALACESSORIOS, 0)) AS VALACESSORIOS,
                SUM(COALESCE(EA.VALDESCONTOPRO, 0)) AS VALDESCONTOPRO,
                SUM(COALESCE(EA.VALDESCONTOFINANCEIRO, 0)) AS VALDESCONTOFINANCEIRO,
                SUM(COALESCE(EA.VALACRESCIMOFINANCEIRO, 0)) AS VALACRESCIMOFINANCEIRO,
                SUM(COALESCE(EA.VALACRESCIMOPRO, 0)) AS VALACRESCIMOPRO
        FROM NOTAS_MOVIMENTO NM
        INNER JOIN DBA.NOTAS N ON N.IDEMPRESA = NM.IDEMPRESA AND N.IDPLANILHA = NM.IDPLANILHA
        INNER JOIN DBA.ESTOQUE_ANALITICO EA ON EA.IDEMPRESA = NM.IDEMPRESA AND EA.IDPLANILHA = NM.IDPLANILHA
        INNER JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
        WHERE OI.FLAGMOVSALDOPRO = 'T'
                AND EA.DTMOVIMENTO BETWEEN :RA_DTINI AND :RA_DTFIM
        GROUP BY N.IDEMPRESA, N.IDPLANILHA, N.IDCLIFOR, DATE(N.DTMOVIMENTO), N.NUMNOTA, N.SERIENOTA
        HAVING SUM(ABS(COALESCE(EA.VALIPI, 0))) <> 0
                OR SUM(ABS(COALESCE(EA.VALIPIFRETE, 0))) <> 0
                OR SUM(ABS(COALESCE(EA.VALIPIACESSORIOS, 0))) <> 0
                OR SUM(ABS(COALESCE(EA.VALIPIEMBALAGEM, 0))) <> 0
                OR SUM(ABS(COALESCE(EA.VALADICIONAIS, 0))) <> 0
                OR SUM(ABS(COALESCE(EA.VALFRETE, 0))) <> 0
                OR SUM(ABS(COALESCE(EA.VALACESSORIOS, 0))) <> 0
                OR SUM(ABS(COALESCE(EA.VALDESCONTOPRO, 0))) <> 0
                OR SUM(ABS(COALESCE(EA.VALDESCONTOFINANCEIRO, 0))) <> 0
                OR SUM(ABS(COALESCE(EA.VALACRESCIMOFINANCEIRO, 0))) <> 0
                OR SUM(ABS(COALESCE(EA.VALACRESCIMOPRO, 0))) <> 0
),
VALORES_XML AS (
        SELECT
                NFET.IDEMPRESA,
                NFET.IDPLANILHA,
                SUM(COALESCE(XP.VDESC, 0)) AS XML_VDESC,
                SUM(COALESCE(XP.VFRETE, 0)) AS XML_VFRETE,
                SUM(COALESCE(XP.VSEG, 0)) AS XML_VSEG,
                SUM(COALESCE(XP.VOUTRO, 0)) AS XML_VOUTRO,
                SUM(COALESCE(XPI.VIPI, 0)) AS XML_VIPI,
                SUM(COALESCE(XICMS.VICMSST, 0)) AS XML_VICMSST,
                LISTAGG(DISTINCT VARCHAR(XICMS.PMVAST), ', ') WITHIN GROUP (ORDER BY VARCHAR(XICMS.PMVAST)) AS PMVAST
        FROM NOTAS_MOVIMENTO NM
        INNER JOIN DBA.NOTA_FISCAL_ELETRONICA_TERCEIROS NFET ON NFET.IDEMPRESA = NM.IDEMPRESA AND NFET.IDPLANILHA = NM.IDPLANILHA
        INNER JOIN NFE.XML_IDENTIFICACAO XI ON XI.CHNFE = NFET.CHAVENFE
        LEFT JOIN NFE.XML_PRODUTO XP ON XP.IDNFE = XI.IDNFE
        LEFT JOIN NFE.XML_PRODUTO_IPI XPI ON XPI.IDPRODUTONFE = XP.IDPRODUTONFE
        LEFT JOIN NFE.XML_PRODUTO_ICMS XICMS ON XICMS.IDPRODUTONFE = XP.IDPRODUTONFE
        GROUP BY NFET.IDEMPRESA, NFET.IDPLANILHA
),
FILTRO AS (
        SELECT A.*
        FROM APURACAO A
        INNER JOIN FORNECEDOR F ON F.IDCLIFOR = A.IDCLIFOR
        INNER JOIN FORNECEDOR_TOTAL FT ON FT.IDCLIFOR = A.IDCLIFOR
        WHERE A.PRODUTOR = 'F' AND F.XML_TOTAL = 0 AND F.CAD_TOTAL = F.QTDNOTAS AND F.QTDNOTAS = FT.QTDNOTAS_TOTAL AND F.QTDTIPOS = 1 AND F.QTDTIPOS_OUTRAS_405090 = 0 AND A.TIPO IN ('ISENTO-40','NAOTRIBUTADO-41','SUSPENSO-50','OUTROS-90')
)
SELECT
        VN.DATA,
        VN.IDEMPRESA,
        VN.IDPLANILHA,
        VN.IDCLIFOR,
        VN.NUMNOTA,
        VN.SERIENOTA,
        VN.IDCSTPISCOFINS,
        F.IDATIVIDADE,
        F.ATIVIDADE,
        F.PRODUTOR,
        F.SIMPLESNACIONAL,
        F.TIPO,
        VN.VALIPI,
        VN.VALIPIFRETE,
        VN.VALIPIACESSORIOS,
        VN.VALIPIEMBALAGEM,
        VN.VALADICIONAIS,
        VN.VALFRETE,
        VN.VALACESSORIOS,
        VN.VALDESCONTOPRO,
        VN.VALDESCONTOFINANCEIRO,
        VN.VALACRESCIMOFINANCEIRO,
        VN.VALACRESCIMOPRO,
        COALESCE(VX.XML_VDESC, 0) AS XML_VDESC,
        COALESCE(VX.XML_VFRETE, 0) AS XML_VFRETE,
        COALESCE(VX.XML_VSEG, 0) AS XML_VSEG,
        COALESCE(VX.XML_VOUTRO, 0) AS XML_VOUTRO,
        COALESCE(VX.XML_VIPI, 0) AS XML_VIPI,
        COALESCE(VX.XML_VICMSST, 0) AS XML_VICMSST,
        COALESCE(VX.PMVAST, '') AS PMVAST
FROM FILTRO F
INNER JOIN VALORES_NOTA VN ON VN.IDCLIFOR = F.IDCLIFOR
LEFT JOIN VALORES_XML VX ON VX.IDEMPRESA = VN.IDEMPRESA AND VX.IDPLANILHA = VN.IDPLANILHA
INNER JOIN TIPO_NOTA TN ON TN.IDEMPRESA = VN.IDEMPRESA AND TN.IDPLANILHA = VN.IDPLANILHA AND TN.IDCLIFOR = VN.IDCLIFOR AND TN.TIPO = F.TIPO
ORDER BY VN.DATA, VN.IDEMPRESA, VN.IDPLANILHA, VN.IDCLIFOR, F.TIPO;